src/objects/Arbol_Decision__c.object
<CustomObject>
    <fields>
        <fullName>ADC_LKP_Producto_CIA__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Producto</label>
        <referenceTo>Producto_CIA__c</referenceTo>
        <relationshipName>Arbol_de_Decisi_n_Cabecera</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Árbol de Decisión</label>
    <nameField>
        <displayFormat>ADC{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Árboles de Decisión</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Arbol_Decision_Lineas__c.object
<CustomObject>
    <fields>
        <fullName>ADL_LKP_Arbol_Decision__c</fullName>
        <label>Árbol de Decisión</label>
        <referenceTo>Arbol_Decision__c</referenceTo>
        <relationshipName>Arbol_de_Decision_Lineas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Árbol de Decisión: Línea</label>
    <nameField>
        <displayFormat>ADL{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Árbol de Decisión: Líneas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <fields>
        <fullName>TPR_LKP_Compania__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Compañía a la que pertenece el tipo de producto. Representa la FK al objeto Account para la compañía. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External Id (Account.CUE_TXT_Identificador__c):Código de compañía HomeServe</description>
        <label>Compañía</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Compañía</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Compañía: Tipos de Producto</relationshipLabel>
        <relationshipName>Tipos_de_Producto_CIA</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_TRG_Handler_Arbol_Decision_Lineas.cls
@isTest
public class Test_TRG_Handler_Arbol_Decision_Lineas {
	@isTest static void test1(){

		Account compania=Util_Tests.crearCuentaCompania('Name','12345','X1234567X');
		insert compania;

		Tipo_Producto_CIA__c tpc=new Tipo_Producto_CIA__c();
		tpc.TPR_LKP_Compania__c=compania.Id;
		tpc.TPR_LKP_Compania__r=compania;
		insert tpc;

		Producto_CIA__c pc=Util_Tests.crearProductoCIA('nombre','12345',tpc.id);
		insert pc;

		Arbol_Decision__c ad=new Arbol_Decision__c();
		ad.ADC_LKP_Producto_CIA__r=pc;
		ad.ADC_LKP_Producto_CIA__c=pc.id;
		insert ad;

		Arbol_Decision_Lineas__c adl=new Arbol_Decision_Lineas__c();
		adl.ADL_LKP_Arbol_Decision__r=ad;
		adl.ADL_LKP_Arbol_Decision__c=ad.Id;

		insert adl;

		update adl;
	}
}