src/objects/Ayuda__c.object
<CustomObject>
    <fields>
        <fullName>AYU_SEL_Tipo__c</fullName>
        <description>Tipos de ayudas que se muestran en las páginas VF de la aplicación</description>
        <label>Tipo</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipo_de_ayuda</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AYU_TXT_Descripcion__c</fullName>
        <description>Texto de la ayuda</description>
        <label>Texto</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Ayuda</label>
    <nameField>
        <displayFormat>AYU-{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ayudas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Tipo_de_ayuda.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ayuda árbol: Grupo de causa</fullName>
    </customValue>
    <customValue>
        <fullName>Ayuda árbol: Tipo de avería</fullName>
    </customValue>
    <customValue>
        <fullName>Ayuda árbol: Detalle de la avería</fullName>
    </customValue>
    <customValue>
        <fullName>Ayuda árbol: Causa de la avería</fullName>
    </customValue>
    <customValue>
        <fullName>Ayuda árbol: Daños propios</fullName>
    </customValue>
    <customValue>
        <fullName>Ayuda árbol: Daños a Perjudicados</fullName>
    </customValue>
    <customValue>
        <fullName>Ayuda árbol: Argumentario rechazo</fullName>
    </customValue>
    <customValue>
        <fullName>Ayuda árbol: Indemnizable</fullName>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Póliza Pertenece a Multiasistencias</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Póliza Pertenece</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <label>No existen resultados</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Póliza de Baja</label>
    </customValue>
    <description>Tipos de ayudas que se muestran en las páginas VF de la aplicación</description>
    <masterLabel>Tipos de ayuda</masterLabel>
</GlobalValueSet>

src/classes/Visor_Ayuda.cls
public without sharing class Visor_Ayuda {
	public Ayuda__c ayuda {get;set;}

	public Visor_Ayuda(ApexPages.standardController stdCtr){
		PageReference paginaActual = ApexPages.currentPage();
		if(paginaActual.getParameters().containsKey('id')){
			List<String> fields = new List<String>{'Id','AYU_TXT_Descripcion__c','AYU_SEL_Tipo__c'};
			stdCtr.addFields(fields);
			ayuda = (Ayuda__c) stdCtr.getRecord();
		}
	}
}