src/objects/Baremo__c.object
<CustomObject>
    <fields>
        <fullName>BAR_LKP_Compania__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Compañía</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Baremos</relationshipLabel>
        <relationshipName>Baremos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BAR_TXT_Identificador_Unico__c</fullName>
        <description>Identificador único que concatena el Gremio_Identificador</description>
        <externalId>true</externalId>
        <label>Identificador Único</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Baremo</label>
    <nameField>
        <label>Nombre de Baremo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Baremos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Util_Baremos.cls
/**
 * Clase de funciones auxiliares relativas a los Baremos.
 * 
 * @author EVERIS
 *
 */
public without sharing class Util_Baremos{

	/**
	 * Devuelve los Baremos filtrados por Compañías y códigos de baremo.
	 *
	 * @param setCompania: conjunto de IDs de compañías
	 * @param setCodBaremo: conjunto de códigos de baremo
	 *
	 * @return mapa que contiene los Baremos encontrados
	 */
	public static Map<Id,Baremo__c> getBaremoByCompaniaAndCodigoBaremo(Set<Id> setCompania, Set<String> setCodBaremo){
		Map<Id,Baremo__c> mapa = new Map<Id,Baremo__c>();
		if(setCompania != null && !setCompania.isEmpty() && setCodBaremo != null && !setCodBaremo.isEmpty()){
			for(List<Baremo__c> lista:[SELECT Id,BAR_TXT_Identificador_Unico__c,BAR_LKP_Compania__c
										FROM Baremo__c
										WHERE BAR_TXT_Identificador_Unico__c IN :setCodBaremo
										AND BAR_LKP_Compania__c IN :setCompania]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}
}