src/objects/BigMachines__Configuration_Record__c.object
<CustomObject>
    <description>A set of parameters used for integrating a Oracle CPQ Cloud site to this Salesforce org.</description>
    <fields>
        <fullName>BigMachines__Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BigMachines__action_id_copy__c</fullName>
        <inlineHelpText>action_id_copy</inlineHelpText>
        <label>Copy Action ID</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BigMachines__action_id_open__c</fullName>
        <inlineHelpText>action_id_open</inlineHelpText>
        <label>Open Action ID</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BigMachines__bm_site__c</fullName>
        <inlineHelpText>site URL</inlineHelpText>
        <label>Site Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BigMachines__document_id__c</fullName>
        <inlineHelpText>document_id</inlineHelpText>
        <label>Document ID</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BigMachines__process__c</fullName>
        <inlineHelpText>process</inlineHelpText>
        <label>Process Variable Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BigMachines__process_id__c</fullName>
        <inlineHelpText>process_id</inlineHelpText>
        <label>Process ID</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BigMachines__version_id__c</fullName>
        <inlineHelpText>version_id</inlineHelpText>
        <label>Version ID</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Oracle CPQ Cloud Site</label>
    <nameField>
        <displayFormat>SITE-{000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oracle CPQ Cloud Site Setup</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BigMachines__Quote__c.object
<CustomObject>
    <description>An Oracle CPQ Cloud quote object storing the proposal(s) and line items.</description>
    <fields>
        <fullName>BigMachines__Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BigMachines__Transaction_Id__c</fullName>
        <externalId>true</externalId>
        <label>Transaction Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OQU_LKP_Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Oracle Quotes and Orders</relationshipLabel>
        <relationshipName>Oracle_Quotes_and_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Oracle Quote</label>
    <nameField>
        <label>Quote Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oracle Quotes and Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Util_CPQ.cls
/**
 * Clase de funciones auxiliares relativas a las Compañías.
 * 
 * @author EVERIS
 */
public without sharing class Util_CPQ {
	/**
	 * Devuelve los Registros de configuración BigMachines filtradas por BigMachines__bm_site__c
	 *
	 * @param setDominio: conjunto de nombres del site del registro
	 *
	 * @return mapa que contiene los Registros de configuración BigMachines
	 */
	public static Map<Id,BigMachines__Configuration_Record__c> getBigMachRecBySite(Set<String> setDominio){
		Map<Id,BigMachines__Configuration_Record__c> mapa = new Map<Id,BigMachines__Configuration_Record__c>();
		if(setDominio != null && !setDominio.isEmpty()){
			for(List<BigMachines__Configuration_Record__c> lista:[SELECT Id,
																		BigMachines__bm_site__c,
																		BigMachines__process_id__c,
																		BigMachines__version_id__c,
																		BigMachines__action_id_open__c,
																		BigMachines__document_id__c,
																		BigMachines__process__c,
																		BigMachines__action_id_copy__c
																	FROM BigMachines__Configuration_Record__c 
																	WHERE BigMachines__bm_site__c IN :setDominio]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}
	
	/**
	 * Devuelve los Registros de BigMachine_quote filtradas por su lkp a Workorder
	 *
	 * @param setWoId: conjunto de Ids de las Wo
	 *
	 * @return mapa que contiene los Registros de BigMachine_quote
	 */
	public static Map<Id,BigMachines__Quote__c> getBigMachQuoByWo(Set<Id> setWoId){
		Map<Id,BigMachines__Quote__c> mapa = new Map<Id,BigMachines__Quote__c>();
		if(setWoId != null && !setWoId.isEmpty()){
			for(List<BigMachines__Quote__c> lista:[SELECT BigMachines__Transaction_Id__c,
														OQU_LKP_Work_Order__c,
														BigMachines__Is_Primary__c 
													FROM BigMachines__Quote__c
													WHERE OQU_LKP_Work_Order__c IN :setWoId]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}
}