src/objects/Buzon_CIA__c.object
<CustomObject>
    <description>Almacena las direcciones de correo electrónico configuradas mediante Email2Case para cada Compañía.</description>
    <fields>
        <fullName>BUZ_EMA_Direccion__c</fullName>
        <description>Dirección de correo electrónico de HomeServe configurada como email2Case para la CIA.</description>
        <label>Dirección de Correo Electrónico</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>BUZ_LKP_Cuenta__c</fullName>
        <description>Compañía asociada al Buzón.</description>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buzones</relationshipLabel>
        <relationshipName>Buzones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BUZ_SEL_Tipo_Programa__c</fullName>
        <description>Lista de selección que refleja los tipos de programa que provocan una comunicación vía fax o email a un contacto de una cuenta Compañía</description>
        <label>Tipo de Programa</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipo_Programa</valueSetName>
        </valueSet>
    </fields>
    <label>Buzón</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buzones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Linea_Presupuesto__c.object
<CustomObject>
    <fields>
        <fullName>PREL_DIV_Facturacion_Total_AI__c</fullName>
        <description>Importe a facturar a la compañía/cliente sin impuestos</description>
        <label>Facturación Total antes de impuestos</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PREL_DIV_Facturacion_Total_DI__c</fullName>
        <description>Importe a facturar a la compañía/cliente con impuestos</description>
        <label>Facturación Total después de impuestos</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PREL_LKP_Presupuesto__c</fullName>
        <label>Presupuesto</label>
        <referenceTo>Presupuesto__c</referenceTo>
        <relationshipLabel>Líneas de Presupuesto</relationshipLabel>
        <relationshipName>Lineas_de_Presupuesto</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PREL_POR_Impuesto_Cliente__c</fullName>
        <description>Porcentaje impuesto cliente/compañía</description>
        <label>Porcentaje impuesto cliente/compañía</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PREL_TXT_Descripcion__c</fullName>
        <label>Descripción</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Línea de Presupuesto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Presupuesto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Presupuesto__c.object
<CustomObject>
    <description>Representa cada uno de los presupuestos generados para un caso.</description>
    <fields>
        <fullName>PRE_LKP_Caso__c</fullName>
        <description>Caso al que se vincula el Comentario. Representa la FK al objeto Case. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto Case (Case.CAS_TXT_Identificador__c).</description>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Presupuestos</relationshipLabel>
        <relationshipName>Presupuestos_Valoraciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PRE_NUM_Version__c</fullName>
        <description>Versión.</description>
        <label>Versión</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Presupuesto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nº de Presupuesto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Presupuestos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Procedencia__c.object
<CustomObject>
    <description>Representa cada una de las procedencias de una Compañía/Cliente B2B.</description>
    <fields>
        <fullName>PROC_SEL_Motivos_rechazo_presupuesto__c</fullName>
        <label>Motivos rechazo presupuesto</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Motivo_rechazo_presupuesto</valueSetName>
        </valueSet>
    </fields>
    <label>Procedencia</label>
    <nameField>
        <label>Código de Procedencia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Tipo_Programa.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Albarán</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Aviso a Compañía</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Comprobante Servicio</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Coordinador de Cuenta</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <label>Informes Periciales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Notificación No-Reply</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Presupuesto</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Perito</label>
    </customValue>
    <customValue>
        <fullName>CAMBIOSTRO</fullName>
        <isActive>false</isActive>
        <label>CAMBIOSTRO</label>
    </customValue>
    <customValue>
        <fullName>INDEMNIZABLES</fullName>
        <isActive>false</isActive>
        <label>INDEMNIZABLES</label>
    </customValue>
    <customValue>
        <fullName>REAPERTURA</fullName>
        <isActive>false</isActive>
        <label>REAPERTURA</label>
    </customValue>
    <customValue>
        <fullName>NUEVOTEL</fullName>
        <isActive>false</isActive>
        <label>NUEVOTEL</label>
    </customValue>
    <customValue>
        <fullName>RECHAZOAPERTURA</fullName>
        <isActive>false</isActive>
        <label>RECHAZOAPERTURA</label>
    </customValue>
    <customValue>
        <fullName>RECHAZOCONFIR</fullName>
        <isActive>false</isActive>
        <label>RECHAZOCONFIR</label>
    </customValue>
    <customValue>
        <fullName>INCIPOL</fullName>
        <isActive>false</isActive>
        <label>INCIPOL</label>
    </customValue>
    <description>Lista de selección que refleja los tipos de programa que provocan una comunicación vía fax o email a un contacto de una cuenta Compañía.</description>
    <masterLabel>Tipos de Programa</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Motivo_rechazo_presupuesto.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Rechazo por precio alto</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>No disponible gremio</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Otros</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Avería de un tercero</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>No hay averia</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Atencion al cliente</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Seguimiento de asistencia</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Telefono erroneo</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Error en tramitacion</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>No se puede reparar</label>
    </customValue>
    <masterLabel>Motivo rechazo presupuesto</masterLabel>
</GlobalValueSet>

src/classes/Test_GenerarPresupuestoController.cls
/**
 * Clase de Test de la Clase GenerarPresupuestoController 
 * 
 */
@isTest
public without sharing class Test_GenerarPresupuestoController {  

	/**
	 * Este metodo se encarga de realizar la carga de datos de static resources
	 * 
	 */
	public static Account compania;
	public static Account cuenta;
	public static Tipo_Producto_CIA__c tipoProducto;
	public static Producto_CIA__c producto;
	public static ServiceContract sv;
	public static Case caso;
	public static Procedencia__c procedencia;
	public static WorkOrder wo;
	public static WorkType wt;
	public static Buzon_CIA__c buzon;
	public static Presupuesto__c pre;
	public static Linea_Presupuesto__c lineaPre;
	public static WorkOrderLineItem woLI;
	
	private static void inicializaVariables(){
		Baipas.establecerVariableControl(); 
		
		compania = Util_Tests.crearCuentaCompania('compania', '1018','X1234567X');
		insert compania;
		
		cuenta = Util_Tests.crearCuentaB2BPpal('cuenta', '1458','X1134567X');
		insert cuenta;
		
		tipoProducto = Util_Tests.crearTipoProductoCIA('tipo', '01', compania.Id);
		insert tipoProducto;
		
		producto = Util_Tests.crearProductoCIA('producto', '292', tipoProducto.Id);
		insert producto;
		
		sv = Util_Tests.crearPolizaContrato('Alberto', cuenta.Id, compania.Id, producto.Id);
		insert sv;
		procedencia = Util_Tests.crearProcedencia(0.0, 0.0, 0.0, 0.0, 0.0, cuenta.Id, '545687', 'CAS_Solicitud_de_Servicio_B2B_B2B2C;CAS_Servicio_B2B_B2B2C');
		procedencia.PROC_SEL_Motivos_rechazo_presupuesto__c = '09;07;02;08;06;21;03;01';
		insert procedencia;

		buzon = new Buzon_CIA__c();
		buzon.BUZ_LKP_Cuenta__r = compania;
		buzon.BUZ_LKP_Cuenta__c = compania.Id;
		buzon.BUZ_SEL_Tipo_Programa__c = '02;03;'+Label.CON_TIPO_PROGRAMA_AUTORIZA_PRESUPUESTO;
		buzon.BUZ_EMA_Direccion__c = 'ser@ser.com';
		buzon.Name = 'buzon';
		insert buzon;
		
		caso = Util_Tests.crearCasoB2B(sv.Id, cuenta.Id, compania.Id);
		caso.CAS_SEL_Encuestador__c = 'Servitelco';
		caso.CAS_LKP_Compania__r = compania;
		caso.CAS_LKP_Compania__c = compania.Id;
		caso.CAS_EMA_Solicitud_Email__c = 'sera@sera.com';		
		caso.CAS_LKP_Procedencia__c = procedencia.Id;
		insert caso;
		
		wt = Util_Tests.crearTipoTrabajo('Rotura de bajante/tubería empotrada', '01', 120.0);
		insert wt;
		
		wo = Util_Tests.crearOrdenTrabajo('0000000545','01',wt.Id,caso.Id);
		insert wo;
		
		woLI = Util_Tests.crearNuevaPartidaTrabajo(wo.Id);
		woLI.Status = Label.PAR_ESTADO_ACEPTADA;
		insert woLI;
		pre = new Presupuesto__c();
		pre.PRE_LKP_Caso__c = caso.Id;
		pre.PRE_NUM_Version__c = 1.0;
		
		insert pre;
		
		lineaPre = new Linea_Presupuesto__c();
		lineaPre.PREL_LKP_Presupuesto__c = pre.Id;
		lineaPre.PREL_TXT_Descripcion__c = 'lineaPre prueba';
		lineaPre.PREL_DIV_Facturacion_Total_AI__c = 100.2;
		lineaPre.PREL_DIV_Facturacion_Total_DI__c = 111;
		lineaPre.PREL_POR_Impuesto_Cliente__c = 1;
		
		insert lineaPre;
	}
    
    @isTest static void success1(){
        test_GenerarPresupuestoController();
    }
    
    @isTest static void success2(){
        test_GenerarPresupuestoController1(false);
    }
    
    @isTest static void fail(){
        test_GenerarPresupuestoController1(true);
    }
    
	private static void test_GenerarPresupuestoController(){
		inicializaVariables();
		Test.startTest();
		PageReference pageRef = Page.AltaModificacionCliente;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('fase','Y');
		ApexPages.currentPage().getParameters().put('solicitudExistente','Y');
		ApexPages.currentPage().getParameters().put('VDN','1018');
		ApexPages.currentPage().getParameters().put('idTabBusqClientes','01r9E0000000');
		ApexPages.currentPage().getParameters().put('retorno','Y');
		ApexPages.currentPage().getParameters().put('id',caso.Id);
		ApexPages.currentPage().getParameters().put('nuevoPresupuesto','Y');
		//Account asegurado = Util_Tests.getAccountByName('Asegurado');
		ApexPages.StandardController sc = new ApexPages.StandardController(caso);
		GenerarPresupuestoController presupuesto = new GenerarPresupuestoController(sc);
		presupuesto.aceptarPresupuesto();
		presupuesto.pensarPresupuesto();
		presupuesto.generarPDF();
		presupuesto.rechazarPresupuesto();
		presupuesto.rechazarPresupuestoParcial();
		presupuesto.motivoSeleccionado();
		presupuesto.volver();
		presupuesto.actualizarPartidas();
	   
		Test.stopTest();
	}
	
	private static void test_GenerarPresupuestoController1(boolean willTestFail){
		Test.startTest();
		inicializaVariables();
		PageReference pageRef = Page.AltaModificacionCliente;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('fase','Y');
		ApexPages.currentPage().getParameters().put('solicitudExistente','Y');
		ApexPages.currentPage().getParameters().put('VDN','1018');
		ApexPages.currentPage().getParameters().put('idTabBusqClientes','01r9E0000000');
		ApexPages.currentPage().getParameters().put('retorno','Y');
		ApexPages.currentPage().getParameters().put('id',caso.Id);
        system.debug('a');
		//Account asegurado = Util_Tests.getAccountByName('Asegurado');
		ApexPages.StandardController sc = new ApexPages.StandardController(caso);
		GenerarPresupuestoController presupuesto = new GenerarPresupuestoController(sc);
        if(willTestFail)
        //presupuesto.presupuesto.PRE_NUM_Version__c=null;
		presupuesto.guardarPresupuesto();
		presupuesto.aceptarPresupuesto();
		presupuesto.pensarPresupuesto();
		presupuesto.generarPDF();
		presupuesto.rechazarPresupuesto();
		presupuesto.rechazarPresupuestoParcial();
		presupuesto.motivoSeleccionado();
		presupuesto.volver();
		presupuesto.actualizarPartidas();
		Test.stopTest();
	}
}