src/objects/Buzon_CIA__c.object
<CustomObject>
    <description>Almacena las direcciones de correo electrónico configuradas mediante Email2Case para cada Compañía.</description>
    <fields>
        <fullName>BUZ_EMA_Direccion__c</fullName>
        <description>Dirección de correo electrónico de HomeServe configurada como email2Case para la CIA.</description>
        <label>Dirección de Correo Electrónico</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>BUZ_LKP_Cuenta__c</fullName>
        <description>Compañía asociada al Buzón.</description>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buzones</relationshipLabel>
        <relationshipName>Buzones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BUZ_SEL_Tipo_Programa__c</fullName>
        <description>Lista de selección que refleja los tipos de programa que provocan una comunicación vía fax o email a un contacto de una cuenta Compañía</description>
        <label>Tipo de Programa</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipo_Programa</valueSetName>
        </valueSet>
    </fields>
    <label>Buzón</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buzones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Procedencia__c.object
<CustomObject>
    <description>Representa cada una de las procedencias de una Compañía/Cliente B2B.</description>
    <fields>
        <fullName>PROC_SEL_Motivos_rechazo_presupuesto__c</fullName>
        <label>Motivos rechazo presupuesto</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Motivo_rechazo_presupuesto</valueSetName>
        </valueSet>
    </fields>
    <label>Procedencia</label>
    <nameField>
        <label>Código de Procedencia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_DAT_Fecha_Primera_Cita__c</fullName>
        <description>Fecha de la primera visita del profesional a la situación de riesgo del asegurado.</description>
        <label>Fecha de Primera Cita</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OTR_SEL_Rango_Primera_Cita__c</fullName>
        <label>Hora de Primera Cita</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Rango_2_Horas</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Rango_2_Horas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>00:00 - 02:00</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02:00 - 04:00</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>04:00 - 06:00</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>06:00 - 08:00</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>08:00 - 10:00</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>10:00 - 12:00</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>12:00 - 14:00</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>14:00 - 16:00</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>16:00 - 18:00</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>18:00 - 20:00</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>20:00 - 22:00</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>22:00 - 00:00</label>
    </customValue>
    <description>Intervalos de 2 horas pares.</description>
    <masterLabel>Rango 2 Horas</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Tipo_Programa.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>03</fullName>
        <label>Albarán</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Aviso a Compañía</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Comprobante Servicio</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Coordinador de Cuenta</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <label>Informes Periciales</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Notificación No-Reply</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Presupuesto</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Perito</label>
    </customValue>
    <customValue>
        <fullName>CAMBIOSTRO</fullName>
        <isActive>false</isActive>
        <label>CAMBIOSTRO</label>
    </customValue>
    <customValue>
        <fullName>INDEMNIZABLES</fullName>
        <isActive>false</isActive>
        <label>INDEMNIZABLES</label>
    </customValue>
    <customValue>
        <fullName>REAPERTURA</fullName>
        <isActive>false</isActive>
        <label>REAPERTURA</label>
    </customValue>
    <customValue>
        <fullName>NUEVOTEL</fullName>
        <isActive>false</isActive>
        <label>NUEVOTEL</label>
    </customValue>
    <customValue>
        <fullName>RECHAZOAPERTURA</fullName>
        <isActive>false</isActive>
        <label>RECHAZOAPERTURA</label>
    </customValue>
    <customValue>
        <fullName>RECHAZOCONFIR</fullName>
        <isActive>false</isActive>
        <label>RECHAZOCONFIR</label>
    </customValue>
    <customValue>
        <fullName>INCIPOL</fullName>
        <isActive>false</isActive>
        <label>INCIPOL</label>
    </customValue>
    <description>Lista de selección que refleja los tipos de programa que provocan una comunicación vía fax o email a un contacto de una cuenta Compañía.</description>
    <masterLabel>Tipos de Programa</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Motivo_rechazo_presupuesto.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Rechazo por precio alto</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>No disponible gremio</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Otros</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Avería de un tercero</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>No hay averia</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Atencion al cliente</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Seguimiento de asistencia</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Telefono erroneo</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Error en tramitacion</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>No se puede reparar</label>
    </customValue>
    <masterLabel>Motivo rechazo presupuesto</masterLabel>
</GlobalValueSet>

src/classes/Test_TRG_Handler_Tarea.cls
@isTest
public without sharing class Test_TRG_Handler_Tarea {

    private static Account compania;
    private static Account cuenta;
    private static Tipo_Producto_CIA__c tipoProducto;
    private static Producto_CIA__c producto;
    private static ServiceContract sv;
    private static Case caso;
    private static Procedencia__c procedencia;
    private static WorkOrder wo;
    private static WorkType tipoTrabajo;
    
    static testMethod void Handler_Tarea(){
        Datetime posibleFechaReserva = Datetime.now().addDays(Util_Cita_Servicio.sumarDias(Datetime.now()));
        compania = Util_Tests.crearCuentaCompania('compania', '1018','X1234567X');
        compania.Type='01';
        insert compania;
        
        cuenta = Util_Tests.crearCuentaB2BPpal('cuenta', '1458','X1134567X');
        cuenta.cue_lkp_cuenta_principal__c = compania.id;
        cuenta.Cue_LKP_Cliente_contable__c = compania.id;
        cuenta.Type='01';
        insert cuenta;
        
        tipoProducto = Util_Tests.crearTipoProductoCIA('tipo', '01', compania.Id);
        insert tipoProducto;
        
        producto = Util_Tests.crearProductoCIA('producto', '292', tipoProducto.Id);
        insert producto;
        
        sv = Util_Tests.crearPolizaContrato('poliza', compania.Id, cuenta.Id, producto.Id);
        
        procedencia = Util_Tests.crearProcedencia(0.0, 0.0, 0.0, 0.0, 0.0, cuenta.Id, '545687', 'CAS_Solicitud_de_Servicio_B2B_B2B2C;CAS_Servicio_B2B_B2B2C');
        procedencia.PROC_SEL_Motivos_rechazo_presupuesto__c = '09;07;02;08;06;21;03;01';
        insert procedencia;
        
        system.debug('<<<<<<<<<<<<<<<<procedencia>>>>>>>' + procedencia.Id);
        
        Buzon_CIA__c buzon = new Buzon_CIA__c();
        buzon.BUZ_LKP_Cuenta__c = compania.Id;
        buzon.BUZ_SEL_Tipo_Programa__c = '02;03';
        buzon.BUZ_EMA_Direccion__c = 'ser@ser.com';
        buzon.Name = 'buzon';
        insert buzon;
        
        User newUser = new User();
        newUser.FirstName = 'Manolo';
        newUser.LastName = 'tena';
        newUser.Email = 'manolo@manolo.com';
        newUser.Alias = 'Manolo';
        newUser.ProfileId = system.UserInfo.getProfileId();
        newUser.Username = ' john784poi@acme7.com';
        newUser.CommunityNickname = 'pepe';
        newUser.TimeZoneSidKey = 'Europe/Paris';
        newUser.LocaleSidKey = system.UserInfo.getLocale();
        newUser.EmailEncodingKey = 'ISO-8859-1';
        newUser.LanguageLocaleKey = 'es';
        newUser.USR_TXT_Identificador__c = '0000';

        insert newUser;
        
        Task tarea = new Task();
        
        system.runAs(newUser){
            
            caso = Util_Tests.crearCasoB2B(sv.Id, cuenta.Id, compania.Id);
            caso.CAS_SEL_Encuestador__c = 'Servitelco';
            caso.CAS_EMA_Solicitud_Email__c = 'sera@sera.com';        
            caso.CAS_LKP_Procedencia__c = procedencia.Id;
            caso.OwnerId = newUser.Id;
            caso.Status = '993';
            insert caso;
            
            caso.Status = '001';
            update caso;
            
            tipoTrabajo = Util_Tests.crearTipoTrabajo('Tipo de Trabajo por Defecto', '01', 120.0);
            insert tipoTrabajo;
            
            wo = Util_Tests.crearOrdenTrabajo('0000000545','01',tipoTrabajo.Id,caso.Id);
            wo.OTR_DAT_Fecha_Primera_Cita__c = posibleFechaReserva.date();
            wo.OTR_SEL_Rango_Primera_Cita__c = '07';
            insert wo;
            
            tarea.CallDisposition = '{root=100}';
            tarea.CallDurationInSeconds = 248;
            tarea.CallObject = '12709';
            tarea.CallType = 'Inbound';
            tarea.TAR_DAT_Inicio_Llamada__c = posibleFechaReserva.addDays(-1);
            tarea.TAR_DAT_Fin_Llamada__c = posibleFechaReserva.addDays(1);
            tarea.OwnerId = newUser.Id;
            tarea.Subject = 'RE:' + Label.TAR_ASUNTO_RECORDATORIO_ID;
            tarea.Description = Label.EMAIL_TO_SALESFORCE;
            tarea.WhatId = caso.Id;
            
        Test.startTest();
            insert tarea;
            
            Task tarea1 = new Task();
            
            tarea1.CallDisposition = '{root=100}';
            tarea1.CallDurationInSeconds = 248;
            tarea1.CallObject = '12709';
            tarea1.CallType = 'Inbound';
            tarea1.TAR_DAT_Inicio_Llamada__c = posibleFechaReserva.addDays(-1);
            tarea1.TAR_DAT_Fin_Llamada__c = posibleFechaReserva.addDays(1);
            tarea1.OwnerId = newUser.Id;
            tarea1.Subject = Label.TAR_ASUNTO_RECORDATORIO_MINUTA;
            tarea1.Description = Label.EMAIL_TO_SALESFORCE;
            tarea1.WhatId = caso.Id;
            
            insert tarea1;
            tarea1.Subject = Label.TAR_ASUNTO_RECORDATORIO_MINUTA;
            update tarea1;
            
            Test.stopTest();
        }
    }
}