src/objects/Causa_de_la_reclamacion__mdt.object
<CustomObject>
    <fields>
        <fullName>MTD_CAUSA_TXT_Causa_de_la_reclamacion__c</fullName>
        <label>Causa de la reclamación</label>
        <type>TextArea</type>
    </fields>
    <label>Causa de la reclamación</label>
    <pluralLabel>Causas de las reclamaciones</pluralLabel>
</CustomObject>

src/objects/Comentario_caso__c.object
<CustomObject>
    <description>Representa cada uno de los comentarios asociados a un caso</description>
    <label>Comentario Intervención</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comentarios Intervención</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Propuesta_de_Abono__c.object
<CustomObject>
    <fields>
        <fullName>AB_LKP_Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Orden_de_Trabajo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Número Servicio</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_SEL_Estado__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>En Curso</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Aprobado</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Rechazado</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Propuesta de Abono</label>
    <nameField>
        <displayFormat>AB-{0000000}</displayFormat>
        <label>Abono</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propuestas de Abonos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Propuesta_de_Evento__c.object
<CustomObject>
    <description>Objeto utilizado para modelar el proceso de liquidación y/o facturación a profesionales, clientes y compañías aseguradoras</description>
    <fields>
        <fullName>EV_AB_LKP_Abono__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Abono padre</label>
        <referenceTo>Propuesta_de_Abono__c</referenceTo>
        <relationshipLabel>Propuestas de Eventos</relationshipLabel>
        <relationshipName>Propuestas_de_Eventos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_AB_LKP_Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Caso relacionado al Evento/Abono</description>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Propuestas de Eventos</relationshipLabel>
        <relationshipName>EV_AB_REL_Caso</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_AB_LKP_Orden_de_Trabajo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Orden de Trabajo relacionada al Evento/Abono</description>
        <label>Número Servicio</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipName>EV_AB_REL_Orden_de_Trabajo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_AB_LKP_Propuesta_de_Evento_Economico__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evento padre</label>
        <referenceTo>Propuesta_de_Evento__c</referenceTo>
        <relationshipLabel>Propuestas de Eventos</relationshipLabel>
        <relationshipName>Propuestas_de_Eventos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_AB_SEL_Estado__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>02</fullName>
                    <label>Aprobado</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Rechazado</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>Anulado</label>
                </value>
                <value>
                    <fullName>01</fullName>
                    <isActive>false</isActive>
                    <label>En Curso</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Propuesta de Evento Económico</label>
    <nameField>
        <displayFormat>EV-{0000000}</displayFormat>
        <label>Evento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propuestas de Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>PAR_DIV_Importe_a_Imputar_gestor1__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_DIV_Importe_a_Imputar_gestor2__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_DIV_Importe_a_Imputar_gestor3__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_DIV_Importe_a_Imputar_prof1__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_DIV_Importe_a_Imputar_prof2__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_DIV_Importe_a_Imputar_prof3__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_LKP_Imputar_a_gestor1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partidas_de_rdenes_de_trabajo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAR_LKP_Imputar_a_gestor2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partidas_de_rdenes_de_trabajo1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAR_LKP_Imputar_a_gestor3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partidas_de_rdenes_de_trabajo2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAR_LKP_Imputar_a_prof1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a</label>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Partidas de órdenes de trabajo</relationshipLabel>
        <relationshipName>Partidas_de_rdenes_de_trabajo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAR_LKP_Imputar_a_prof2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a</label>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Partidas de órdenes de trabajo (Imputar a)</relationshipLabel>
        <relationshipName>Partidas_de_rdenes_de_trabajo1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAR_LKP_Imputar_a_prof3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a</label>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Partidas de órdenes de trabajo (Imputar a)</relationshipLabel>
        <relationshipName>Partidas_de_rdenes_de_trabajo2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CierreReclamaciones.cls
/**
 * Clase controladora de la Visualforce "CierreReclamaciones" encargada de gestionar la creación de reclamaciones
 * 
 * @author EVERIS
 */
public without sharing class CierreReclamaciones {
	
	public Case reclamacion;
	public Case reclCampos;
	public ApexPages.standardController controlador;
	
	public Boolean todoCorrecto {get;set;}
	public String comentario {get;set;}
	
	/**
    * 
 	* Constructor de la clase
 	* 
 	*/  
	public CierreReclamaciones(ApexPages.standardController stdCtr){

		todoCorrecto = true;
		PageReference paginaActual = ApexPages.currentPage();
		if (!paginaActual.getParameters().containsKey('id')){
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'No hay objeto asociado'));
			todoCorrecto = false;
		} else {

			Id idReclamacion = stdCtr.getRecord().Id;

			List<Case> recAux = Util_Caso.getCaseById(new Set<Id>{idReclamacion}).values();
			//List<Case> recAux = Util_Caso.getMapaCasos(new Set<Id>{idReclamacion}).values();
			//List<Case> recAux = [Select id, Status, CAS_SEL_Padre_reclamacion__c, CAS_SEL_Reclamacion__c, CAS_SEL_Naturaleza__c,CAS_SEL_Motivo_de_Cierre__c,CAS_SEL_Comunicador_Recl__c from Case where Id = :idReclamacion];
			
			if(!recAux.isEmpty()){
				reclCampos = recAux.get(0);
				reclamacion = (Case)stdCtr.getRecord();
					
			} else {
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'No hay objeto asociado'));
				todoCorrecto = false;
			}
			
			controlador = stdCtr;
		}

	}
	
	public List<SelectOption> getOpcionesEstado(){
		List<SelectOption> options = new List<SelectOption>();
		
		Set<String> validos = new Set<String>{Label.CAS_ESTADO_CERRADO_PDTE_LIQUIDAR,Label.CAS_ESTADO_CERRADO_FACTURADO};
		
		Schema.DescribeFieldResult fieldResult = Case.Status.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();	
		for(Schema.PicklistEntry f : ple){
			if(validos.contains(f.getValue())){
				options.add(new SelectOption(f.getValue(),f.getLabel()));
			}
		}
		
		return options;
	}
	
	public List<SelectOption> getOpcionesCierre(){
		List<SelectOption> options = new List<SelectOption>();
		
		options.add(new SelectOption('','--Ninguno--'));
		
		if(reclCampos == null)
			return options;
			
		system.debug('-----------IN');
		
		//TODO: Coger los metadatos cuando estén
		//TODO: Cambiar los valores quien comunica para añadir el valor de analizado no procedente
		
		String tipologia = reclCampos.CAS_SEL_Padre_reclamacion__c;
		String fundada = reclCampos.CAS_SEL_Reclamacion__c;
		String naturaleza = reclCampos.CAS_SEL_Naturaleza__c;
		
		String clave = tipologia+fundada+naturaleza;
		
		
		system.debug('-------clave: '+ clave);
		
		List<Causa_de_la_reclamacion__mdt> opciones = Util_Metadatos.mapaCausaReclClave.get(clave);
		
		if(opciones != null && !opciones.isEmpty()){
			
			Set<String> validos = new Set<String>();
			
			for(Causa_de_la_reclamacion__mdt causa: opciones){
				validos.add(causa.MTD_CAUSA_TXT_Causa_de_la_reclamacion__c);
			}
				
			Schema.DescribeFieldResult fieldResult = Case.CAS_SEL_Motivo_de_Cierre__c.getDescribe();
			List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

			for(Schema.PicklistEntry f : ple){
				if(validos.contains(f.getValue())){
					options.add(new SelectOption(f.getValue(),f.getLabel()));
				}
			}
			
		}
		
		
		if(reclCampos.CAS_SEL_Comunicador_Recl__c == '002' || reclCampos.CAS_SEL_Comunicador_Recl__c == '003'){
			options.add(new SelectOption(Label.CAS_MOTIVO_DE_CIERRE_RECLAMACION3,'Analizado no procedente, sin imputar'));
		}
		
		return options;
	}
	
	public PageReference guardar(){
		
		system.debug('------status: '+reclamacion.Status);
		system.debug('------Label.CAS_ESTADO_CERRADO_FACTURADO: '+Label.CAS_ESTADO_CERRADO_FACTURADO);
		system.debug('------CAS_SEL_Motivo_de_Cierre__c: '+reclamacion.CAS_SEL_Motivo_de_Cierre__c);
		
		if(reclamacion.Status == Label.CAS_ESTADO_CERRADO_FACTURADO && String.isBlank(reclamacion.CAS_SEL_Motivo_de_Cierre__c)){
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Se debe rellenar la causa de la reclamación'));
			return null;	
		}
		
		List<WorkorderLineItem> partidas = Util_caso.getListaPartidasCaso(reclamacion.Id);
		Boolean partidasImputadas = true;
        system.debug(partidas + 'partidaaaaaaas');
		system.debug(reclamacion + ' reclamacion de clase antes de guardar1');
		if(!partidas.isEmpty()){
			for(WorkOrderLineItem woli : partidas){
				if((woli.PAR_DIV_Importe_a_Imputar_prof1__c == null || woli.PAR_DIV_Importe_a_Imputar_prof1__c == 0)
					&& (woli.PAR_DIV_Importe_a_Imputar_prof2__c == null || woli.PAR_DIV_Importe_a_Imputar_prof2__c == 0)
					&& (woli.PAR_DIV_Importe_a_Imputar_prof3__c == null || woli.PAR_DIV_Importe_a_Imputar_prof3__c == 0)
					&& (woli.PAR_DIV_Importe_a_Imputar_gestor1__c == null || woli.PAR_DIV_Importe_a_Imputar_gestor1__c == 0)
					&& (woli.PAR_DIV_Importe_a_Imputar_gestor2__c == null || woli.PAR_DIV_Importe_a_Imputar_gestor2__c == 0)
					&& (woli.PAR_DIV_Importe_a_Imputar_gestor3__c == null || woli.PAR_DIV_Importe_a_Imputar_gestor3__c == 0)
					&& woli.PAR_LKP_Imputar_a_prof1__c == null
					&& woli.PAR_LKP_Imputar_a_prof2__c == null
					&& woli.PAR_LKP_Imputar_a_prof3__c == null
					&& woli.PAR_LKP_Imputar_a_gestor1__c == null
					&& woli.PAR_LKP_Imputar_a_gestor2__c == null
					&& woli.PAR_LKP_Imputar_a_gestor3__c == null){
						
					partidasImputadas = false;
					break;
				}
			}
		} else {
			if(reclCampos.CAS_LKP_Responsable_Reclamacion__c == null && reclCampos.CAS_SEL_Reclamacion__c == Label.CAS_RECLAMACION_FUNDADA){
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'No se ha seleccionado ningún responsable de la reclamación'));
				return null;
			}
		}
		
		
		if(!partidasImputadas){
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Existen partidas para las que no se ha realizado imputación'));
			return null;
		}
		
		//PREV
		/*
		List<Propuesta_de_evento__c> eventos = [Select Id from Propuesta_de_evento__c where (EV_AB_LKP_Caso__c = :reclamacion.Id or EV_AB_LKP_Orden_de_Trabajo__r.CaseId = :reclamacion.Id) and EV_AB_LKP_Propuesta_de_Evento_Economico__c = null and EV_AB_LKP_Abono__c = null and EV_AB_SEL_Estado__c != :Label.EV_AB_ESTADO_APROBADO and EV_AB_SEL_Estado__c != :Label.EV_AB_ESTADO_RECHAZADO];
		List<Propuesta_de_abono__c> abonos = [Select id from Propuesta_de_abono__c where (AB_LKP_Caso__c = :reclamacion.Id or AB_LKP_Orden_de_Trabajo__r.CaseId = :reclamacion.Id) and AB_SEL_Estado__c != :Label.EV_AB_ESTADO_APROBADO and AB_SEL_Estado__c != :Label.EV_AB_ESTADO_RECHAZADO];
		*/
		//NEW
		Set<Id> setIdsReclamacion = new Set <Id>{reclamacion.Id};
		List<Propuesta_de_evento__c> eventos = Util_Propuesta_de_evento.queryMap_Propuesta_de_EventoBy_EV_AB_LKP_Caso_Or_Orden_de_Trabajo_r_CaseId_And_PropEvEconomico_null_And_LKPAbono_null_And_EstadoNoAprobado_And_EstadoNoRechazado(setIdsReclamacion).values();
		List<Propuesta_de_abono__c> abonos = Util_Propuesta_de_abono.queryMap_Propuesta_de_AbonoBy_EV_AB_LKP_Caso_Or_Orden_de_Trabajo_r_CaseId_And_PropEvEconomico_null_And_LKPAbono_null_And_EstadoNoAprobado_And_EstadoNoRechazado(setIdsReclamacion).values();
		//END_NEW
		
		
		Boolean enProceso = true;
		
		if(!eventos.isEmpty()){
			Map<Id,Boolean> eventosLocked = Approval.isLocked(eventos);
			
			for(Boolean isLocked: eventosLocked.values()){
				enProceso = enProceso && isLocked;
			}
		}
		
		if(!abonos.isEmpty()){
			Map<Id,Boolean> abonosLocked = Approval.isLocked(abonos);
			
			for(Boolean isLocked: abonosLocked.values()){
				enProceso = enProceso && isLocked;
			}
		}
		
		if(!enProceso){
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Existen eventos o abonos para los que no se ha lanzado el proceso de aprobación'));
			return null;
		}
		system.debug(reclCampos.CAS_LKP_Compania__r.CUE_TXT_Identificador__c + ' reclamacion de casos');
		if(String.isBlank(reclCampos.CAS_SEL_Conformidad_del_Cliente__c) 
		|| (reclCampos.CAS_SEL_Conformidad_del_Cliente__c == 'NO LOCALIZADO' 
		&& (String.isBlank(reclCampos.CAS_SEL_Conformidad_del_Cliente_2__c) || (reclCampos.CAS_SEL_Conformidad_del_Cliente_2__c == 'NO LOCALIZADO' && reclCampos.CAS_LKP_Compania__r.CUE_TXT_Identificador__c != Label.IDE_MEMBERSHIP))
		&& String.isBlank(reclCampos.CAS_SEL_Conformidad_del_Cliente_3__c))){
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'No se puede cerrar la reclamación, no se ha confirmado con el cliente'));
			return null;
		} 
		
		if(String.isBlank(reclCampos.CAS_TXT_Gestor_Cierra_Reclamacion__c))
			reclamacion.CAS_TXT_Gestor_Cierra_Reclamacion__c = UserInfo.getName();
			
		PageReference paginaRedireccion = controlador.save();
		if(!String.isBlank(comentario)){
			Comentario_caso__c comentarioCasoInsertar = Util_Caso.crearComentarioCaso(reclamacion.Id, comentario);
			insert comentarioCasoInsertar;
		}
		
		return paginaRedireccion;
	}
    
}