src/objects/Comentario_caso__c.object
<CustomObject>
    <description>Representa cada uno de los comentarios asociados a un caso</description>
    <label>Comentario Intervención</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comentarios Intervención</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contacto_telefonico__c.object
<CustomObject>
    <description>Representa los contactos que están vinculados a un Siniestro o a una Póliza</description>
    <label>Contacto Telefónico</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contactos Telefónicos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Garantia__c.object
<CustomObject>
    <label>Garantía</label>
    <nameField>
        <displayFormat>GAR-{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantías</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Garantia_Siniestro__c.object
<CustomObject>
    <label>Garantía Siniestro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantías Siniestro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/INT_Config_Fichero_CIA__c.object
<CustomObject>
    <description>Representa la configuración de cada uno de los ficheros enviados a las Compañías Aseguradoras.</description>
    <fields>
        <fullName>FIC_LKP_Compania__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Compañía</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Compañía</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Integraciones: Configuración Fichero CIA</relationshipLabel>
        <relationshipName>Integraciones_Configuraci_n_Fichero_CIA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FIC_TXT_Query__c</fullName>
        <label>Sentencia Query</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Integraciones: Configuración Fichero CIA</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integraciones: Configuración Fichero CIA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/INT_Envio_Programado__c.object
<CustomObject>
    <description>Representa la tabla de parametrización correspondiente a los diferentes eventos/movimientos de siniestros/asistencias/reclamaciones que se deben informar a cada una de las aseguradoras.</description>
    <fields>
        <fullName>ENV_CAS_Activo__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ENV_DAT_Fecha_Inicio__c</fullName>
        <label>Fecha Inicio</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ENV_LKP_Fichero__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Id Fichero</label>
        <referenceTo>INT_Config_Fichero_CIA__c</referenceTo>
        <relationshipName>Integraciones_Envios_Programados_CIA</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ENV_NUM_Contador_Lote__c</fullName>
        <description>Campo para almacenar el Nº de lote del siguiente envío</description>
        <label>Contador Lote</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ENV_SEL_Dias_Semana__c</fullName>
        <label>Días de la Semana</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Dias_Semana</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ENV_SEL_Hora__c</fullName>
        <label>Hora</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Horas</valueSetName>
        </valueSet>
    </fields>
    <label>Integraciones: Envío Programado CIA</label>
    <nameField>
        <displayFormat>ENV{000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones: Envío Programado CIA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/INT_Movimiento_CIA__c.object
<CustomObject>
    <description>Representa el conjunto de eventos susceptibles de ser informados a las diferentes aseguradoras.
En función de la parametrización, Salesforce guardará una imagen del siniestro en el momento en el cuál se disparó el evento.</description>
    <fields>
        <fullName>MOV_LKP_Bitacora__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bitácora</label>
        <referenceTo>INT_Bitacora__c</referenceTo>
        <relationshipName>MOV_REL_Integraciones_Movimientos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MOV_LKP_Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Integraciones: Movimiento CIA</relationshipLabel>
        <relationshipName>MOV_REL_Integraciones_Movimientos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MOV_LKP_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>MOV_REL_Integraciones_Movimientos2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MOV_TXT_Tipo_Movimiento__c</fullName>
        <label>Tipo de Movimiento</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>Integraciones: Movimiento CIA</label>
    <nameField>
        <displayFormat>MOV{000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones: Movimiento CIA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Perjudicado_Siniestro__c.object
<CustomObject>
    <description>Representa las personas que están afectadas por un Siniestro.</description>
    <label>Perjudicado Siniestro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Perjudicados Siniestro</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Procedencia__c.object
<CustomObject>
    <description>Representa cada una de las procedencias de una Compañía/Cliente B2B.</description>
    <label>Procedencia</label>
    <nameField>
        <label>Código de Procedencia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Dias_Semana.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Lunes</fullName>
    </customValue>
    <customValue>
        <fullName>Martes</fullName>
    </customValue>
    <customValue>
        <fullName>Miércoles</fullName>
    </customValue>
    <customValue>
        <fullName>Jueves</fullName>
    </customValue>
    <customValue>
        <fullName>Viernes</fullName>
    </customValue>
    <customValue>
        <fullName>Sábado</fullName>
    </customValue>
    <customValue>
        <fullName>Domingo</fullName>
    </customValue>
    <masterLabel>Dias de la Semana</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Horas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>09:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>15:00</fullName>
    </customValue>
    <customValue>
        <fullName>16:00</fullName>
    </customValue>
    <customValue>
        <fullName>17:00</fullName>
    </customValue>
    <customValue>
        <fullName>18:00</fullName>
    </customValue>
    <customValue>
        <fullName>19:00</fullName>
    </customValue>
    <customValue>
        <fullName>20:00</fullName>
    </customValue>
    <customValue>
        <fullName>21:00</fullName>
    </customValue>
    <customValue>
        <fullName>22:00</fullName>
    </customValue>
    <customValue>
        <fullName>23:00</fullName>
    </customValue>
    <masterLabel>Horas</masterLabel>
</GlobalValueSet>

src/classes/Test_Batch_Envio_Mov.cls
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Author:             everis
Company:        everis España
Description:    <Clase de testeo para Batch_Envio_Mov>

History:  <DESCRIPCIÓN DEL CAMBIO, REQUISITO, INCIDENCIA, CORRECTIVO O MEJORA QUE HIZO ACTUALIZAR/CREAR LA CLASE>

<27/11/2017>                      everis                       <Inicio de clase>
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
@isTest
global without sharing class Test_Batch_Envio_Mov {
	private static String CRON_EXP = '0 0 0 15 3 ? 2032';
	private static Account compania;
	private static Account cuenta;
	private static Tipo_Producto_CIA__c tipoProducto;
	private static Producto_CIA__c producto;
	private static ServiceContract sv;
	private static Procedencia__c procedencia;
	private static Case caso;
	private static Contact contacto;
	private static Contacto_telefonico__c contactoT;
	private static WorkType tipoTrabajo;
	private static WorkOrder ordenTrabajo;
	private static Perjudicado_Siniestro__c perjudicado;
	private static Garantia__c garantia;
	private static Garantia_Siniestro__c garantiaSini;
	private static INT_Movimiento_CIA__c mov;
	private static List<Comentario_caso__c> comentarios;
	private static List<INT_Envio_Programado__c> envioProg;
	private static List<INT_Config_Fichero_CIA__c> fichConfig;
	private static List<INT_Movimiento_CIA__c> movList;
	private static List<Account> listCuentas;
	private static List<Case> listCasos;
	

	static void setup() {

		envioProg = new List<INT_Envio_Programado__c>();
		fichConfig = new List<INT_Config_Fichero_CIA__c>();
		movList = new List<INT_Movimiento_CIA__c>();
		listCuentas = new List<Account>();
		listCasos = new List<Case>();
		

		//Genero días malos y buenos e idem con las horas
		Date hoyDate = Date.today();
		String[] diasSemana = new String[]{'Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'};
		Integer intDiaSemana = hoyDate.ToStartOfWeek().DaysBetween(hoyDate);
		String diaSemanaBueno = diasSemana[intDiaSemana];
		String diaSemanaMalo = diasSemana[intDiaSemana + 1];
		String horaBuena;
		if(Datetime.now().time().minute()<29){
			horaBuena = String.valueOf(Datetime.now().time().hour());
		} else{
			horaBuena = String.valueOf(Datetime.now().time().addHours(1).hour());
		}
		if(horaBuena.length() < 2){
			horaBuena = '0' + horaBuena;
		}
		horaBuena = horaBuena + ':00';
		String horaMala = Datetime.now().time().addHours(2).hour() + ':00';

        compania = Util_Tests.crearCuentaCompania('Name', '1234', 'X1234566X');
		compania.Type = '01';
        insert compania;
		
		cuenta = Util_Tests.crearCuentaB2BPpal('Name','12345', 'X1234567X');
		cuenta.CUE_LKP_CUENTA_PRINCIPAL__c = compania.id;
		cuenta.CUE_LKP_Cliente_contable__c = compania.id;
		cuenta.Type = '01';
        insert cuenta;

        tipoProducto = Util_Tests.crearTipoProductoCIA('nombre','01', compania.Id);
        insert tipoProducto;

        producto = Util_Tests.crearProductoCIA('nombre','1234',tipoProducto.Id);
        insert producto;

        sv = Util_Tests.crearPolizaContrato('nombre', compania.Id, cuenta.Id,producto.Id);
        insert sv;
        
        listCasos.add(caso = Util_Tests.crearCasoB2B(sv.Id,cuenta.Id,compania.Id) );
        listCasos.add(caso = Util_Tests.crearCasoB2B(sv.Id,cuenta.Id,compania.Id) );
        insert listCasos;

	    //Creo un par de cuentas
	    listCuentas.add(compania = Util_Tests.crearCuentaCompania('compania1', '1042','X1234567X'));
	    listCuentas.add(compania = Util_Tests.crearCuentaCompania('compania2', '1043','Y1234567Y'));
	    insert listCuentas;

		// inserto varios INT_Config_Fichero_CIA__c
		fichConfig.add(new INT_Config_Fichero_CIA__c( FIC_TXT_Query__c = 'SELECT Name FROM INT_Movimiento_CIA__c WHERE MOV_TXT_Tipo_Movimiento__c = \'1\' AND MOV_LKP_Bitacora__c != null', FIC_LKP_Compania__c = listCuentas.get(0).Id));
		fichConfig.add(new INT_Config_Fichero_CIA__c(FIC_TXT_Query__c = 'SELECT Name FROM INT_Movimiento_CIA__c WHERE MOV_TXT_Tipo_Movimiento__c != \'2\' AND MOV_LKP_Bitacora__c != null', FIC_LKP_Compania__c = listCuentas.get(1).Id));
		insert fichConfig;

        //system.debug(fichConfig.get(0) + ' aaaaaaaaaaa1');
        //system.debug(fichConfig + ' aaaaaaaa');
		// inserto varios INT_Envio_Programado__c
		envioProg.add(new INT_Envio_Programado__c(ENV_CAS_Activo__c = true, 
				ENV_SEL_Hora__c = horaBuena, ENV_LKP_Fichero__c=fichConfig.get(0).id, ENV_SEL_Dias_Semana__c = diaSemanaBueno,ENV_NUM_Contador_Lote__c=1));

		envioProg.add(new INT_Envio_Programado__c(ENV_CAS_Activo__c = true, 
				ENV_SEL_Hora__c = horaBuena, ENV_LKP_Fichero__c=fichConfig.get(1).id, ENV_SEL_Dias_Semana__c = diaSemanaBueno, ENV_DAT_Fecha_Inicio__c = Datetime.now().date().addMonths(-1),ENV_NUM_Contador_Lote__c=1));

        
		envioProg.add(new INT_Envio_Programado__c(ENV_CAS_Activo__c = true, 
				ENV_SEL_Hora__c = horaBuena, ENV_LKP_Fichero__c=fichConfig.get(1).Id, ENV_SEL_Dias_Semana__c = diaSemanaBueno, ENV_DAT_Fecha_Inicio__c = Datetime.now().date().addMonths(-1),ENV_NUM_Contador_Lote__c=1));
		insert envioProg;

		//Inserto algunos movimientos
		movList.add(new INT_Movimiento_CIA__c(MOV_TXT_Tipo_Movimiento__c = '1' ,MOV_LKP_Cliente__c=listCuentas.get(0).Id,MOV_LKP_Caso__c = listCasos.get(0).Id));
		movList.add(new INT_Movimiento_CIA__c(MOV_TXT_Tipo_Movimiento__c = '2',MOV_LKP_Cliente__c=listCuentas.get(1).Id,MOV_LKP_Caso__c = listCasos.get(1).Id));
		insert movList;
	}

	static testmethod void test() {
        setup();
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
		String jobId = System.schedule('ScheduledApexTest', CRON_EXP, new Batch_Envio_Mov_Desencadenador());

		Test.stopTest();
	}

	global class TestHttpCalloutMock implements HttpCalloutMock {
		// Implement this interface method
		global HTTPResponse respond(HTTPRequest request) {
			// Create a fake response
			HttpResponse response = new HttpResponse();
			response.setHeader('Content-Type', 'application/json');
			response.setBody('{"code":"INT-001","identificadorDestino":"123456", "message" : "peligroo" }');

			response.setStatusCode(200);
			return response; 
		}
	}
}