src/objects/Confirmacion__c.object
<CustomObject>
    <description>Copia del objeto Caso, que va a almacenar información de la Apertura y de las diferentes Confirmaciones.</description>
    <fields>
        <fullName>CNF_LKP_ParentId__c</fullName>
        <label>Siniestro</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Datos Apertura/Confirmaciones</relationshipLabel>
        <relationshipName>Confirmacion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CNF_SEL_Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Reparable</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Mixto</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Indemnizable</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Rechazo en apertura</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Reparable, mixto e indemnizable. Cubre todo</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>No Abierto en Llamada</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>Cobertura Adicional</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <label>Rechazo en confirmación parcial</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>Rechazo en confirmación total</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>Asistencia con Cobertura</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>Llamadas</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>Manitas</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>Servicio Especial Reparable</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>Servicio Especial Indemnizable</label>
                </value>
                <value>
                    <fullName>98</fullName>
                    <label>Preventivo</label>
                </value>
                <value>
                    <fullName>99</fullName>
                    <label>Correctivo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Datos Apertura/Confirmaciones</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Datos Apertura/Confirmaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Garantia_Siniestro__c.object
<CustomObject>
    <label>Garantía Siniestro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantías Siniestro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRG_Handler_Confirmacion.cls
public class TRG_Handler_Confirmacion {
	//private static Map<Id,Case> mapaCaso;
	private static Map<Id,List<WorkOrder>> mapaWOPorIdCaso;
	private static Map<Id,List<Garantia_Siniestro__c>> mapaGarantSiniPorIdConfirm;
	public static void tratamientoBefore(Map<Id, Confirmacion__c> triggerNewMap, List<Confirmacion__c> triggerNew, Map<Id, Confirmacion__c> triggerOldMap, List<Confirmacion__c> triggerOld) {  
		if(Trigger.IsDelete){
			if(mapaGarantSiniPorIdConfirm!=null){
				mapaGarantSiniPorIdConfirm=Util_Siniestro.queryIdCasoGarantiasExistentes(triggerNewMap.keySet());
			}
			List<Garantia_Siniestro__c> garantiasBorrar = new List<Garantia_Siniestro__c>();
			for(List<Garantia_Siniestro__c> listaGarant : mapaGarantSiniPorIdConfirm.values()){
				garantiasBorrar.addAll(listaGarant);
			}
			delete garantiasBorrar;
		}
	}

	public static void tratamientoAfter(Map<Id, Confirmacion__c> triggerNewMap, List<Confirmacion__c> triggerNew, Map<Id, Confirmacion__c> triggerOldMap, List<Confirmacion__c> triggerOld) {
		List<WorkOrder> listWOc2c = new List<WorkOrder>();
		if(Trigger.IsUpdate){
			if(mapaWOPorIdCaso==null){
				inicializaVariables(triggerNew,triggerNewMap);
			}
			for (Confirmacion__c confirm : triggerNew){
				//Comprobamos si el profesional
				if(Util_Perfiles_Usuario.esProfesional(UserInfo.getProfileId())){
					//Comprobamos si le ha salido un rechazo
					if(confirm.CNF_SEL_Tipo__c == Label.CAS_TIPO_RECHAZO_EN_CONFIRMACION_PARCIAL 
							|| confirm.CNF_SEL_Tipo__c == Label.CAS_TIPO_RECHAZO_EN_CONFIRMACION_TOTAL){
						listWOc2c.addAll(mapaWOPorIdCaso.get(confirm.CNF_LKP_ParentId__c));
					}
				}
			}
		}
	}
    /**
     * Método para inicializar las variables necesarias para el funcionamiento del trigger
     * @param triggerNew: List<Confirmacion__c> del triggerNew
	 * @param triggerNewMap: Map<Id,Confirmacion__c> del triggerNew
     */
	private static void inicializaVariables(List<Confirmacion__c> triggerNew, Map<Id,Confirmacion__c> triggerNewMap){
		Set<Id> setIdCaso = new Set<Id>();
		for(Confirmacion__c c:triggerNew){
			setIdCaso.add(c.CNF_LKP_ParentId__c);
		}
		//mapaCaso = Util_Caso.getCaseById(setIdCaso);
		//mapaCaso = Util_Caso.getMapaCasos(setIdCaso);
		mapaWOPorIdCaso = Util_Orden_Trabajo.queryMapIdCaseOTByCase(setIdCaso);
		//mapaWOPorIdCaso = Util_Orden_Trabajo.queryOTBySet(null,mapaCaso.keySet(),null);
	}
}