src/objects/Contacto_telefonico__c.object
<CustomObject>
    <description>Representa los contactos que están vinculados a un Siniestro o a una Póliza</description>
    <fields>
        <fullName>CTF_LKP_Contacto__c</fullName>
        <description>Contacto vinculado a un caso.</description>
        <label>Contacto</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contactos Telefónicos</relationshipLabel>
        <relationshipName>CCA_REL_Casos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CTF_LKP_Poliza_Contrato__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Póliza/Contrato</description>
        <label>Póliza/Contrato</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Contactos Telefónicos</relationshipLabel>
        <relationshipName>CTF_REL_Poliza_Contrato</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CTF_SEL_Hora_desde__c</fullName>
        <description>Hora desde la que está disponible</description>
        <label>Hora desde</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Horas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CTF_SEL_Hora_hasta__c</fullName>
        <description>Hora hasta la que está disponible</description>
        <label>Hora hasta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Horas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CTF_SEL_Tipo_Relacion__c</fullName>
        <label>Tipo/Relación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipos_Relacion</valueSetName>
        </valueSet>
    </fields>
    <label>Contacto Telefónico</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contactos Telefónicos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>POL_LKP_Compania__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Compañía asociada a la póliza</description>
        <label>Compañía</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>POL_REL_Compania</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POL_LKP_Producto_Cia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Producto asociado a la póliza</description>
        <label>Producto</label>
        <referenceTo>Producto_CIA__c</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>POL_REL_Producto</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POL_LKP_Version_Actual__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versión Actual</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Version_ContratoServicio__c.POLV_LKP_PolizaContrato__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Version_ContratoServicio__c</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>Contratos_de_servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Version_ContratoServicio__c.object
<CustomObject>
    <description>Representa cada una de las versiones de una Póliza o Contrato.</description>
    <fields>
        <fullName>POLV_DAT_FechaFin__c</fullName>
        <description>Fecha de finalización</description>
        <label>Fecha de finalización</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POLV_DAT_FechaInicio__c</fullName>
        <description>Fecha de inicio</description>
        <label>Fecha de inicio</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POLV_LKP_PolizaContrato__c</fullName>
        <label>Póliza/Contrato</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Versiones Póliza/Contrato</relationshipLabel>
        <relationshipName>Versiones_Poliza_Contrato</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>POLV_SEL_Idioma__c</fullName>
        <description>Idioma</description>
        <label>Idioma</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Idiomas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>POLV_SEL_Pais__c</fullName>
        <description>País</description>
        <label>País</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Paises</valueSetName>
        </valueSet>
    </fields>
    <label>Versión Póliza/Contrato</label>
    <nameField>
        <label>Versión Póliza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versiones Póliza/Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Horas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>09:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>15:00</fullName>
    </customValue>
    <customValue>
        <fullName>16:00</fullName>
    </customValue>
    <customValue>
        <fullName>17:00</fullName>
    </customValue>
    <customValue>
        <fullName>18:00</fullName>
    </customValue>
    <customValue>
        <fullName>19:00</fullName>
    </customValue>
    <customValue>
        <fullName>20:00</fullName>
    </customValue>
    <customValue>
        <fullName>21:00</fullName>
    </customValue>
    <customValue>
        <fullName>22:00</fullName>
    </customValue>
    <customValue>
        <fullName>23:00</fullName>
    </customValue>
    <masterLabel>Horas</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Idiomas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <default>true</default>
        <label>Castellano</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Catalán</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Desconocido</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Euskera</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Gallego</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Francés</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Alemán</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Italiano</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Resto</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Portugués</label>
    </customValue>
    <masterLabel>Idiomas</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Paises.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ES</fullName>
        <default>true</default>
        <label>España</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
        <label>Bélgica</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croacia</label>
    </customValue>
    <customValue>
        <fullName>CY</fullName>
        <label>Chipre</label>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
        <label>República Checa</label>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
        <label>Dinamarca</label>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
        <label>Estonia</label>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
        <label>Finlandia</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>Francia</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Alemania</label>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
        <label>Grecia</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungría</label>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
        <label>Irlanda</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italia</label>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
        <label>Letonia</label>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
        <label>Lituania</label>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
        <label>Luxemburgo</label>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
        <label>Malta</label>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
        <label>Países Bajos</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Polonia</label>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
        <label>Portugal</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Rumanía</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Eslovaquia</label>
    </customValue>
    <customValue>
        <fullName>SI</fullName>
        <label>Eslovenia</label>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
        <label>Suecia</label>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
        <label>Reino Unido</label>
    </customValue>
    <description>Listados de países de Europa</description>
    <masterLabel>Países</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Tipos_Relacion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Asegurado</fullName>
    </customValue>
    <customValue>
        <fullName>Hijo/a de asegurado</fullName>
    </customValue>
    <customValue>
        <fullName>Inquilino</fullName>
    </customValue>
    <customValue>
        <fullName>Marido de asegurado</fullName>
    </customValue>
    <customValue>
        <fullName>Mujer de asegurado</fullName>
    </customValue>
    <masterLabel>Tipos de Relación</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/Test_AltaConfirmacionClienteController.cls
@isTest 
public without sharing class Test_AltaConfirmacionClienteController{

    private static Account compania;
    private static Account cuenta;
    private static Tipo_Producto_CIA__c tipoProducto;
    private static Producto_CIA__c producto;
    private static ServiceContract sv;
    private static Case caso;
    private static AltaConfirmacionClienteController accc;
    private static Contact contacto;
    private static Contacto_telefonico__c contactoTelefonico;
    private static Version_ContratoServicio__c  NuevaVersion;

    static void InicializarVariables(){
    	cuenta = Util_Tests.crearCuentaB2BPpal('Name','12345', 'X1234567X');
        insert cuenta;
        
      	compania = Util_Tests.crearCuentaCompania('Miguel','1018','H79023677');
		insert compania;
        
        Account asegurado = Util_Tests.crearCuentaAsegurado('Miguel','2018', 'miguel@gmail.es', '73661110E','Miguel', 'Sagrado', 'Velasco');
		asegurado.CUE_LKP_Cuenta_principal__c = compania.id;
		insert asegurado;
 

        tipoProducto = Util_Tests.crearTipoProductoCIA('nombre','01', compania.Id);
        insert tipoProducto;

        producto = Util_Tests.crearProductoCIA('nombre','1234',tipoProducto.Id);
        insert producto;
        
        
        sv=new ServiceContract();
        sv.Name='10';
        sv.POL_LKP_Compania__c = compania.Id;
        sv.AccountId = cuenta.Id;
        sv.POL_LKP_Producto_Cia__c = producto.Id;
        insert sv;

        
        
      	NuevaVersion = new  Version_ContratoServicio__c();
       	NuevaVersion.Name = '10';
        NuevaVersion.POLV_LKP_PolizaContrato__c = sv.Id;
        NuevaVersion.POLV_SEL_Pais__c = 'ES';
        NuevaVersion.POLV_SEL_Idioma__c = '2';
        Date myDate = Date.newInstance(2018, 5, 6);
        Date newDate = mydate.addDays(2);
        NuevaVersion.POLV_DAT_FechaFin__c = newDate;
        NuevaVersion.POLV_DAT_FechaInicio__c = myDate;
        
        Insert NuevaVersion;

        caso = Util_Tests.crearCasoB2B(sv.Id,asegurado.Id,compania.id);
        insert caso;
        
        sv.POL_LKP_Version_Actual__c= NuevaVersion.Id; 
        update sv;

        contacto = new Contact();
        contacto.FirstName = 'Laura';
        contacto.LastName = 'Hdez';
        contacto.Phone = '666999888';
        insert contacto;

        contactoTelefonico = new Contacto_telefonico__c();
        contactoTelefonico.CTF_SEL_Tipo_Relacion__c = 'Asegurado';
        contactoTelefonico.CTF_SEL_Hora_desde__c = '16:00';
        contactoTelefonico.CTF_SEL_Hora_hasta__c = '18:00';
        contactoTelefonico.CTF_LKP_Poliza_Contrato__c = sv.id;
        contactoTelefonico.CTF_LKP_Contacto__c = contacto.id;
        insert contactoTelefonico;
    }

    @isTest 
	public static void noEsCliente(){
        Test.startTest();

		PageReference pageRef = Page.AltaConfirmacionCliente;
        Test.setCurrentPage(pageRef);

		accc = pruebaPage();
        AltaConfirmacionClienteController.ContactoTelefonicoPoliza accc2 = new AltaConfirmacionClienteController.ContactoTelefonicoPoliza(contacto,contactoTelefonico);     

        accc.addContactoDePoliza();
        accc.cargarUbicacion();

        Test.stopTest();

	}

	@isTest
	public static void sinClienteLlamada(){
		InicializarVariables();

		Test.startTest();

		PageReference pageRef = Page.AltaConfirmacionCliente;
        Test.setCurrentPage(pageRef);

        ApexPages.currentPage().getParameters().put('idPoliza',sv.id);
        ApexPages.currentPage().getParameters().put('idCompania',compania.id);
        ApexPages.currentPage().getParameters().put('numeroDocumento','X1234446X');

		accc = pruebaPage();
        AltaConfirmacionClienteController.ContactoTelefonicoPoliza accc2 = new AltaConfirmacionClienteController.ContactoTelefonicoPoliza(contacto,contactoTelefonico);     

		Test.stopTest();
	}

	@isTest 
	public static void noEsPolizaNueva(){        
		InicializarVariables();

        Test.startTest();

		PageReference pageRef = Page.AltaConfirmacionCliente;
        Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('id',cuenta.id);
        ApexPages.currentPage().getParameters().put('idPoliza',sv.id);
        ApexPages.currentPage().getParameters().put('idCompania',compania.id);
        ApexPages.currentPage().getParameters().put('idCaso',caso.id);
        ApexPages.currentPage().getParameters().put('numeroDocumento','X1234446X');
        ApexPages.currentPage().getParameters().put('telefono1','697381155');
        ApexPages.currentPage().getParameters().put('telefono2','697381156');
        ApexPages.currentPage().getParameters().put('telefono3','697381157');
        ApexPages.currentPage().getParameters().put('telefono4','697381158');
        ApexPages.currentPage().getParameters().put('nombreCliente','Laura');
        ApexPages.currentPage().getParameters().put('nuevaPoliza','viejaPoliza');
        
		accc = pruebaPage();
        AltaConfirmacionClienteController.ContactoTelefonicoPoliza accc2 = new AltaConfirmacionClienteController.ContactoTelefonicoPoliza(contacto,contactoTelefonico);

        accc.addContactoDePoliza();
        Boolean emailValidarEliminar = accc.validaEliminarContacto(1);
        accc.nuevoContacto();
        accc.cancelarContacto();
        accc.volverBusquedaPoliza();
        //accc.navegarDetallePoliza();
        accc.navegarSiniTipoInterlocutor();
        //accc.navegarB2BGremios();
        accc.cargarUbicacion();

        Test.stopTest();

	}

	@isTest 
	public static void esPolizaNueva(){
		InicializarVariables();

        Test.startTest();

		PageReference pageRef = Page.AltaConfirmacionCliente;
        Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('id',cuenta.id);
        ApexPages.currentPage().getParameters().put('idPoliza',sv.id);
        ApexPages.currentPage().getParameters().put('idCompania',compania.id);
        ApexPages.currentPage().getParameters().put('idCaso',caso.id);
        ApexPages.currentPage().getParameters().put('numeroDocumento','X1234446X');
        ApexPages.currentPage().getParameters().put('telefono1','697381155');
        ApexPages.currentPage().getParameters().put('telefono2','697381156');
        ApexPages.currentPage().getParameters().put('telefono3','697381157');
        ApexPages.currentPage().getParameters().put('telefono4','697381158');
        ApexPages.currentPage().getParameters().put('nombreCliente','Laura');
        ApexPages.currentPage().getParameters().put('apellido1','Hdez');
        ApexPages.currentPage().getParameters().put('apellido2','zor');
        ApexPages.currentPage().getParameters().put('nuevaPoliza','true');

		accc = pruebaPage();
        AltaConfirmacionClienteController.ContactoTelefonicoPoliza accc2 = new AltaConfirmacionClienteController.ContactoTelefonicoPoliza(contacto,contactoTelefonico);     

        accc.addContactoDePoliza();
        accc.mostrarAyudaTelefonoCompania();
        Boolean emailValidarEliminar = accc.validaEliminarContacto(1);
        accc.nuevoContacto();
        accc.cancelarContacto();
        accc.volverBusquedaPoliza();
        //accc.navegarDetallePoliza();
        accc.navegarSiniTipoInterlocutor();
        //accc.navegarB2BGremios();
        accc.cargarUbicacion();

        Test.stopTest();

	}

	@isTest
	static void mostrarAyudaTelefonica(){
		InicializarVariables();

		Test.startTest();
		PageReference pageRef = Page.AltaConfirmacionCliente;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('indiceResultado','0');
        ApexPages.currentPage().getParameters().put('id',cuenta.id);
        ApexPages.currentPage().getParameters().put('idPoliza',sv.id);
        ApexPages.currentPage().getParameters().put('idCompania',compania.id);
        ApexPages.currentPage().getParameters().put('idCaso',caso.id);
        ApexPages.currentPage().getParameters().put('numeroDocumento','X1234446X');
        ApexPages.currentPage().getParameters().put('telefono1','697381155');
        ApexPages.currentPage().getParameters().put('telefono2','697381156');
        ApexPages.currentPage().getParameters().put('telefono3','697381157');
        ApexPages.currentPage().getParameters().put('telefono4','697381158');
        ApexPages.currentPage().getParameters().put('nombreCliente','Laura');
        ApexPages.currentPage().getParameters().put('apellido1','Hdez');
        ApexPages.currentPage().getParameters().put('apellido2','zor');
        ApexPages.currentPage().getParameters().put('nuevaPoliza','true');
		accc = pruebaPage();
        AltaConfirmacionClienteController.ContactoTelefonicoPoliza accc2 = new AltaConfirmacionClienteController.ContactoTelefonicoPoliza(contacto,contactoTelefonico);     

		accc.telefonoSeleccionado = compania.id;
		
        accc.addContactoDePoliza();
        accc.seleccionarResultado();
        accc.addContactoDePoliza();
 
		Test.stopTest();
	}

    @isTest
    static void eleminarContacto(){
        InicializarVariables();

        Test.startTest();
        PageReference pageRef = Page.AltaConfirmacionCliente;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('indiceResultado','1');
        ApexPages.currentPage().getParameters().put('id',cuenta.id);
        ApexPages.currentPage().getParameters().put('idPoliza',sv.id);
        ApexPages.currentPage().getParameters().put('idCompania',compania.id);
        ApexPages.currentPage().getParameters().put('idCaso',caso.id);
        ApexPages.currentPage().getParameters().put('numeroDocumento','X1234446X');
        ApexPages.currentPage().getParameters().put('telefono1','697381155');
        ApexPages.currentPage().getParameters().put('telefono2','697381156');
        ApexPages.currentPage().getParameters().put('telefono3','697381157');
        ApexPages.currentPage().getParameters().put('telefono4','697381158');
        ApexPages.currentPage().getParameters().put('nombreCliente','Laura');
        ApexPages.currentPage().getParameters().put('apellido1','Hdez');
        ApexPages.currentPage().getParameters().put('apellido2','zor');
        ApexPages.currentPage().getParameters().put('nuevaPoliza','true');

        accc = pruebaPage();
        AltaConfirmacionClienteController.ContactoTelefonicoPoliza accc2 = new AltaConfirmacionClienteController.ContactoTelefonicoPoliza(contacto,contactoTelefonico);     
        
        Account cliente = accc.cliente;
        cliente.CUE_SEL_Tipo_Documento__c = 'C';
        accc.cliente = cliente;
        accc.poblacion = 'Murcia';

        accc.guardar();
        accc.eliminarContacto();
    }

    @isTest
    static void eleminarContactoConError(){
        InicializarVariables();

        Test.startTest();
        PageReference pageRef = Page.AltaConfirmacionCliente;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('indiceResultado','1');
        ApexPages.currentPage().getParameters().put('id',cuenta.id);
        ApexPages.currentPage().getParameters().put('idPoliza',sv.id);
        ApexPages.currentPage().getParameters().put('idCompania',compania.id);
        ApexPages.currentPage().getParameters().put('idCaso',caso.id);
        ApexPages.currentPage().getParameters().put('numeroDocumento','SSSDDSSSD');
        ApexPages.currentPage().getParameters().put('telefono1','697381155');
        ApexPages.currentPage().getParameters().put('telefono2','697381156');
        ApexPages.currentPage().getParameters().put('telefono3','697381157');
        ApexPages.currentPage().getParameters().put('telefono4','697381158');
        ApexPages.currentPage().getParameters().put('nombreCliente','Laura');
        ApexPages.currentPage().getParameters().put('apellido1','Hdez');
        ApexPages.currentPage().getParameters().put('apellido2','zor');
        ApexPages.currentPage().getParameters().put('nuevaPoliza','true');

        accc = pruebaPage();
        AltaConfirmacionClienteController.ContactoTelefonicoPoliza accc2 = new AltaConfirmacionClienteController.ContactoTelefonicoPoliza(contacto,contactoTelefonico);     
        
        Account cliente = accc.cliente;
        cliente.CUE_SEL_Tipo_Documento__c = 'C';
        accc.cliente = cliente;
        accc.poblacion = 'Murcia';

        accc.guardar();
        accc.eliminarContacto();
    }

	static AltaConfirmacionClienteController pruebaPage(){
        Account a = Util_Tests.crearCuentaB2BPpal('Name2','12355', 'X1234667X');
        insert a;

        ApexPages.StandardController sc = new ApexPages.StandardController(a);
        accc = new AltaConfirmacionClienteController(sc);

		return accc;
    }

}