src/objects/Contacto_telefonico__c.object
<CustomObject>
    <description>Representa los contactos que están vinculados a un Siniestro o a una Póliza</description>
    <fields>
        <fullName>CTF_FOR_Telefono__c</fullName>
        <formula>CTF_LKP_Contacto__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Teléfono</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTF_LKP_Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Caso vinculado a un contacto.</description>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contactos Telefónicos</relationshipLabel>
        <relationshipName>CCA_REL_Contactos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contacto Telefónico</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contactos Telefónicos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/INT_Bitacora__c.object
<CustomObject>
    <description>Representa el registro histórico de integraciones entre Salesforce y otros sistemas de forma que se puedan monitorizar los estados de los envíos y los errores obtenidos.</description>
    <fields>
        <fullName>BIT_LKP_Id_Registro_caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Registro de caso que falla en una integración</description>
        <label>Registro no integrado caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Integraciones: Bitácora</relationshipLabel>
        <relationshipName>Integraciones_Bitacora</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BIT_NUM_Orden_RGA__c</fullName>
        <description>Orden de integración de llamadas a RGA. Debido a la casuística concreta de este sistema que no está operativo las 24 horas de la semana, es necesario indicar el orden de las llamadas.</description>
        <label>Orden RGA</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BIT_SEL_Estado__c</fullName>
        <description>Indica el estado del movimiento</description>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Estados_Bitacora</valueSetName>
        </valueSet>
    </fields>
    <label>Integraciones: Bitácora</label>
    <nameField>
        <displayFormat>BIT{000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones: Bitácora</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Perjudicado_Siniestro__c.object
<CustomObject>
    <description>Representa las personas que están afectadas por un Siniestro.</description>
    <fields>
        <fullName>PRJ_LKP_Siniestro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Siniestro al que se vincula el Perjudicado. Representa la FK al objeto Case. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto Case (Case.CAS_TXT_Identificador__c) para Siniestros: &quot;[Código de CIA]_[Nº de Siniestro HomeServe]&quot;</description>
        <label>Siniestro</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Perjudicados Siniestro</relationshipLabel>
        <relationshipName>PER_REL_Siniestro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRJ_TFN_Telefono_1__c</fullName>
        <description>Teléfono 1 del perjudicado del siniestro</description>
        <label>Teléfono</label>
        <type>Phone</type>
    </fields>
    <label>Perjudicado Siniestro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Perjudicados Siniestro</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Estados_Bitacora.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <default>true</default>
        <label>No Enviado</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Enviado</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Error</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Recibido</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>En espera</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Resuelto</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Recibiendo</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>En espera de apertura</label>
    </customValue>
    <masterLabel>Estados Bitacora</masterLabel>
</GlobalValueSet>

src/classes/Util_RGA.cls
/*
 * Clase encargada del setteo de los datos de los Callouts de RGA;
 *
 * @author EVERIS
 */
public without sharing class Util_RGA {
	
	/*
	 * Método que obtiene todos los parametros para construir el body, y desde este método se hace la llamada a Callout_RGA_Siniestro
	 *
	 * @param datos: recibe los datos necesarios para componer la request al endpoint externo
	 * 
	 */
	public static String construirPeticionPratus(Id idCaso, Integer tipoAccion){
		/*Pendiente: realizar las queries para obtener las listas, saber qué Listas recibo desde los triggers,
		pendiente lógica de CRM*/
		
		Case caso = [select CreatedDate, CAS_TXT_texto_observaciones_RGA__c, CAS_SEL_Perito_de_RGA__c, CAS_CAS_Tercero_Causante__c, CAS_SEL_Grupo_Causa__c, toLabel(CAS_SEL_Grupo_Causa__c) etiquetaCausa, CAS_CAS_Danos_Perjudicado__c  from Case where id=:idCaso];
		
		Perjudicado_Siniestro__c perjudicado = new Perjudicado_Siniestro__c();
		if(caso.CAS_CAS_Danos_Perjudicado__c) 
			perjudicado= [SELECT Id, Name, PRJ_TFN_Telefono_1__c FROM Perjudicado_Siniestro__c WHERE PRJ_LKP_Siniestro__c = :idCaso LIMIT 1];
		
		Contacto_telefonico__c contactoTLF = [SELECT id, CTF_FOR_Telefono__c FROM Contacto_telefonico__c where CTF_LKP_Caso__c=:idCaso LIMIT 1];
		
		Callout_RGAPratusAsistenciaApertura_RQ peticion = new Callout_RGAPratusAsistenciaApertura_RQ();
		
		List<WorkOrder> listOrdenesTrabajo = Util_Orden_Trabajo.queryMapOTByCase(new Set<Id>{caso.Id}).values();
		//List<WorkOrder> listOrdenesTrabajo = Util_Orden_Trabajo.queryOT(null, caso.Id, null);
		
		DateTime ahora = System.now();
		
		peticion.refSiniestroAsis = Integer.valueof(caso.CAS_TXT_Num_Caso_HS__c); 
		peticion.fechaRegistroAsis = caso.CreatedDate.format('dd-MM-yyyy');
	    peticion.horaRegistroAsis = caso.CreatedDate.format('kk:mm:ss');
		peticion.tipoAccion = tipoAccion;
		peticion.fechaAccion = system.now().format('dd-MM-yyyy');
		//peticion.nombreReparador = '';   ????
		peticion.textoObservaciones = caso.CAS_TXT_texto_observaciones_RGA__c;
		//peticion.origenObservacion = '';
		//peticion.codigoSeguimientoAsis = '';
		peticion.identificadorPerito = Integer.valueOf(caso.CAS_SEL_Perito_de_RGA__c);
		//peticion.codigoMotivoRechazo = '';
		//peticion.indicadorGestora = '';
		peticion.causanteAveria = Integer.valueOf(caso.CAS_SEL_Perito_de_RGA__c);
		//peticion.codigoOperadoraAsis = '';
		peticion.codigoCausaAsis = Integer.valueOf(caso.CAS_SEL_Grupo_Causa__c);
		//peticion.descrCausaAsis = caso.etiquetaCausa;
		if(caso.CAS_CAS_Danos_Perjudicado__c) peticion.indicadorPerjudicado = 'S';
		else peticion.indicadorPerjudicado = 'N';				
		peticion.nombrePerjudicado = perjudicado.Name;
		peticion.telefonoPerjudicado = perjudicado.PRJ_TFN_Telefono_1__c;
		peticion.telefonoAsegurado = contactoTLF.CTF_FOR_Telefono__c;
		
		String body = JSON.serialize(peticion);
		
		return body;
	}
	
	/**
	* Se buscan las bitácoras que no se hayan podido recibir por estar Pratus apagado (Bitácoras en estado 'en espera' con ese idCaso)
	*
	*
	*/
	private void recogeBitacora(Id idCaso, Integer tipoAccion, String body, Id idContacto){
		List<INT_Bitacora__c> listaBitacoras = new List<INT_Bitacora__c>([SELECT Id, BIT_NUM_Orden_RGA__c FROM INT_Bitacora__c WHERE BIT_SEL_Estado__c =: Label.BIT_ESTADO_EN_ESPERA AND BIT_LKP_Id_Registro_caso__c =: idCaso order by BIT_NUM_Orden_RGA__c desc]);
		Integer orden;
		String cuerpo = construirPeticionPratus(idCaso,tipoAccion);
		if(listaBitacoras.isEmpty()){
			orden=0;
		}else{
			orden=listaBitacoras[0].BIT_NUM_Orden_RGA__c.intValue() + 1;
		}
		
		Util_Llamada_Externa.insertarBitacora('RGA Pratus','','01','02','SRV-PSV-095',body,'homeserve/rga/asistenciaApertura',
						idCaso,idContacto,'','','','',orden,'',0,Label.Callout_PUT);
	}
}