src/objects/Direcciones_B2B_B2B2C_Lineas_de_Contrato__c.object
<CustomObject>
    <fields>
        <fullName>DLC_LKP_Linea_de_Contrato__c</fullName>
        <label>Línea de Contrato</label>
        <referenceTo>Linea_Contrato__c</referenceTo>
        <relationshipLabel>Direcciones/Clientes Finales</relationshipLabel>
        <relationshipName>Direcciones_B2B_B2B2C_L_neas_de_Contrato</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Dirección B2B/B2B2C-Línea de Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones B2B/B2B2C-Líneas de Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Linea_Contrato__c.object
<CustomObject>
    <description>Objeto personalizado utilizado para albergar el conjunto de tareas pertenecientes a un contrato de mantenimiento B2B-B2B2C que tienen la misma periodicidad.</description>
    <fields>
        <fullName>LDC_LKP_Tipo_Trabajo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Campo lookup para relacionar las líneas de contrato con los tipos de trabajo que posteriormente se relacionará con cada Orden de Trabajo</description>
        <label>Tipo de Trabajo</label>
        <referenceTo>WorkType</referenceTo>
        <relationshipLabel>Líneas de Contrato</relationshipLabel>
        <relationshipName>Lineas_de_Contrato</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Línea de Contrato</label>
    <nameField>
        <displayFormat>L.C-{00000000}</displayFormat>
        <label>Nº de Línea</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Procedencia__c.object
<CustomObject>
    <description>Representa cada una de las procedencias de una Compañía/Cliente B2B.</description>
    <fields>
        <fullName>PROC_LKP_Cuenta__c</fullName>
        <description>Identificador único de la compañia</description>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Procedencias</relationshipLabel>
        <relationshipName>Procedencias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Procedencia</label>
    <nameField>
        <label>Código de Procedencia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_CAS_Orden_Trabajo_Facturada__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check que indica si la Work Order ha sido facturada</description>
        <label>Servicio Facturado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OTR_LKP_Recurso_Servicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Profesional (Perfil Técnico) vinculado a la Orden de Trabajo. Representa la FK al objeto ServiceResource. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto ServiceResource (ServiceResources.RSE_TXT_Codigo_Recurso__c): Código único del Profesional</description>
        <label>Profesional</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>ServiceResource.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Status</field>
                <operation>equals</operation>
                <value>Anulado, Anulado desde Inactivo, Cerrado, Cerrado Albarán Recibido, Cerrado Pdte. Albarán, Revisado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Órdenes de trabajo</relationshipLabel>
        <relationshipName>OTR_REL_Recurso_Servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>PAR_DIV_Cargar_Cliente_AI__c</fullName>
        <description>Importe a facturar al Cliente</description>
        <label>Facturación a Cliente antes de impuestos</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_DIV_Cargar_Comp_AI__c</fullName>
        <description>Importe que se factura a la compañía del importe de la partida.</description>
        <label>Facturación a CIA antes de impuesto</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_DIV_Importe_a_Imputar_gestor1__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_DIV_Importe_a_Imputar_gestor2__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_DIV_Importe_a_Imputar_gestor3__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_DIV_Importe_a_Imputar_prof1__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_DIV_Importe_a_Imputar_prof2__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_DIV_Importe_a_Imputar_prof3__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAR_LKP_Imputar_a_gestor1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partidas_de_rdenes_de_trabajo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAR_LKP_Imputar_a_gestor2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partidas_de_rdenes_de_trabajo1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAR_LKP_Imputar_a_gestor3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partidas_de_rdenes_de_trabajo2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAR_LKP_Imputar_a_prof1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a</label>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Partidas de órdenes de trabajo</relationshipLabel>
        <relationshipName>Partidas_de_rdenes_de_trabajo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAR_LKP_Imputar_a_prof2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a</label>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Partidas de órdenes de trabajo (Imputar a)</relationshipLabel>
        <relationshipName>Partidas_de_rdenes_de_trabajo1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAR_LKP_Imputar_a_prof3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a</label>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Partidas de órdenes de trabajo (Imputar a)</relationshipLabel>
        <relationshipName>Partidas_de_rdenes_de_trabajo2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAR_POR_Porcentaje_Imp_Cia_Cliente__c</fullName>
        <description>Porcentaje impuesto cliente/compañía</description>
        <label>Porcentaje Impuestos Cliente/CIA</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_TRG_Handler_Partidas_OT.cls
@isTest
public without sharing class Test_TRG_Handler_Partidas_OT{

	private static Account cuentaCompania {get; set;}
	private static Account cuentaAsegurado {get; set;}
	private static Account cuentaB2BSec {get; set;}
	private static Account cuentaB2BPrincipal {get; set;}
	private static Account profesional {get; set;}
	private static Tipo_Producto_CIA__c tipoProductoCIA {get; set;}
	private static Producto_CIA__c productoCIA {get; set;}
	private static ServiceContract poliza {get; set;}
	private static Procedencia__c procedencia {get; set;}
	private static Case caso {get; set;}
	private static WorkType tipoTrabajo {get; set;}
	private static Contract contrato {get; set;}
	private static Linea_Contrato__c lineaContrato {get; set;}
	private static Direcciones_B2B_B2B2C_Lineas_de_Contrato__c direccionBB_lineas {get; set;}
	private static ServiceResource recursoServ {get; set;}
	private static WorkOrder ordenTrabajo {get; set;}
	private static User user {get; set;}
	private static Account cuentaPrincipalProf {get;set;}
	private static Case siniestro {get; set;}

	private static void inicializarVariables(){
		Baipas.establecerVariableControl();
		cuentaB2BPrincipal = Util_Tests.crearCuentaB2BPpal('B2BPrincipal','1018','X1234567X');
		//insert cuentaB2BPrincipal;
		cuentaCompania = Util_Tests.crearCuentaCompania('SegurCaixa','1019','X1134567X');
		cuentaAsegurado = Util_Tests.crearCuentaAsegurado('Asegurado','1021','email@gmail.es','41847655Y','nombre','apellido1','apellido2');
		cuentaB2BSec = Util_Tests.crearCuentaB2BSec('SegurCaixa2','1020',cuentaB2BPrincipal.Id,'X1114567X');
		cuentaPrincipalProf = Util_Tests.crearCuentaB2BPpal('B2BPrincipal','2002','X1134567X');
		insert cuentaPrincipalProf;
		profesional = Util_Tests.crearCuentaProfesionalContrato('SegurCaixa2','1020','X1114567X',cuentaPrincipalProf.Id);
		profesional.CUE_SEL_Estado__c = '01';
		profesional.CUE_SEL_Tipo_de_Profesional__c = '01';
        profesional.Name='PR123456';
		insert profesional;
		profesional.CUE_SEL_Estado__c = '02';
		update profesional;
		insert cuentaCompania;
		cuentaAsegurado.CUE_LKP_Cuenta_Principal__c = cuentaCompania.Id;
		insert cuentaAsegurado;
		//insert cuentaB2BSec;
		tipoProductoCIA = Util_Tests.crearTipoProductoCIA('SegurCaixa - HOGAR','01',cuentaCompania.id);
		insert tipoProductoCIA;
		productoCIA = Util_Tests.crearProductoCIA('KIT 107','12345678',tipoProductoCIA.Id);
		insert productoCIA;
		poliza = Util_Tests.crearPolizaContrato('9729187',cuentaCompania.Id,cuentaAsegurado.Id,productoCIA.Id);
		insert poliza;
		procedencia = Util_Tests.crearProcedencia(0,0,0,0,0,profesional.Id,'101801','CAS_Siniestro');
		procedencia.Name = Label.IDE_PROCEDENCIA_HOMESERVE;
		procedencia.PROC_LKP_Cuenta__c = cuentaAsegurado.Id;
		insert procedencia;
		tipoTrabajo = Util_Tests.crearTipoTrabajo('Tipo de Trabajo por Defecto','21', 2);
		insert tipoTrabajo;
		contrato = Util_Tests.crearContrato(cuentaAsegurado.Id,'b2b_p_1');
		insert contrato;
		lineaContrato = Util_Tests.crearLineaContrato(contrato.Id,3,'21',Label.RT_LIN_CON_CORRECTIVO);
		lineaContrato.LDC_LKP_Tipo_Trabajo__c = tipoTrabajo.Id;
		insert lineaContrato;
		caso = Util_Tests.crearCasoReclamacion(poliza.Id,profesional.Id,cuentaCompania.Id);
		caso.CAS_LKP_Linea_de_Contrato__c = lineaContrato.Id;
		caso.CAS_LKP_Procedencia__c = procedencia.Id;
		insert caso;
		direccionBB_lineas = Util_Tests.crearDireccionesB2B_B2B2CLineasContrato(profesional.Id,lineaContrato.Id,3);
		direccionBB_lineas.DLC_LKP_Linea_de_Contrato__c = lineaContrato.Id;
		//insert direccionBB_lineas;
		user = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        Account prof = [SELECT Id, Name, CUE_TXT_Identificador__c FROM Account WHERE id=:profesional.Id];
		recursoServ = Util_Tests.crearRecursoServicio('Recurso de Servicio', '000000', profesional.Id , user);
        recursoServ.Name = prof.CUE_TXT_Identificador__c + '_01_1';
		insert recursoServ;
		ordenTrabajo = Util_Tests.crearOrdenTrabajo('18210.0','21',tipoTrabajo.Id,caso.Id);
		ordenTrabajo.Status = Label.OTR_ESTADO_REVISADO;
		ordenTrabajo.OTR_LKP_Recurso_Servicio__c = recursoServ.Id;
		ordenTrabajo.OTR_CAS_Orden_Trabajo_Facturada__c = false;
		insert ordenTrabajo;
		
		siniestro = Util_Tests.crearCasoSini(poliza.Id, cuentaPrincipalProf.Id, cuentaPrincipalProf.Id);
		insert siniestro;
		Baipas.deshabilitarVariableControl();
	}
	
	@isTest static void testPartidasOT() {
		Test.startTest();
		inicializarVariables();
		WorkOrderLineItem partidaOT = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
		partidaOT.Status = Label.PAR_ESTADO_EN_CURSO_PROF;
		partidaOT.PAR_LKP_Imputar_a_prof1__c = recursoServ.Id;
		partidaOT.PAR_DIV_Importe_a_Imputar_prof1__c = 0;
		partidaOT.PAR_LKP_Imputar_a_prof2__c = recursoServ.Id;
		partidaOT.PAR_DIV_Importe_a_Imputar_prof2__c = 0;
		partidaOT.PAR_LKP_Imputar_a_prof3__c = recursoServ.Id;
		partidaOT.PAR_DIV_Importe_a_Imputar_prof3__c = 0;
		partidaOT.PAR_LKP_Imputar_a_gestor1__c = user.Id;
		partidaOT.PAR_DIV_Importe_a_Imputar_gestor1__c = 0;
		partidaOT.PAR_LKP_Imputar_a_gestor2__c = user.Id;
		partidaOT.PAR_DIV_Importe_a_Imputar_gestor2__c = 0;
		partidaOT.PAR_LKP_Imputar_a_gestor3__c = user.Id;
		partidaOT.PAR_DIV_Importe_a_Imputar_gestor3__c = 0;
        /*partidaOT.PAR_POR_Porcentaje_Imp_Cia_Cliente__c = 20;
        partidaOT.PAR_DIV_Cargar_Comp_AI__c = 240;*/
		insert partidaOT;
		partidaOT.Status = label.PAR_ESTADO_ACEPTADA_POR_PERITO_CIA;
		Baipas.establecerVariableControl();
		upsert partidaOT;
		Baipas.deshabilitarVariableControl();
		//delete partidaOT;
		Test.stopTest();
	}
	
	//Método test para probar el fragmento de Facturador;
	@isTest static void ActualizaImportesPartidasOT(){
		Test.startTest();
		inicializarVariables();
		Baipas.establecerVariableControl();
		ordenTrabajo.CaseId = siniestro.Id;
		update ordenTrabajo;
		Baipas.deshabilitarVariableControl();
		WorkOrderLineItem partidaOT = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
		partidaOT.Status = Label.PAR_ESTADO_EN_CURSO_PROF;
		partidaOT.PAR_DIV_Cargar_Cliente_AI__c = 11.65;
		insert partidaOT;
		partidaOT.PAR_DIV_Cargar_Cliente_AI__c = 13.25;
		update partidaOT;
		Test.stopTest();
	}
	
}