src/objects/Direcciones_B2B_B2B2C_Lineas_de_Contrato__c.object
<CustomObject>
    <fields>
        <fullName>DLC_DAT_Activacion_primer_servicio__c</fullName>
        <label>Activación primer servicio</label>
        <type>Date</type>
    </fields>
    <label>Dirección B2B/B2B2C-Línea de Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones B2B/B2B2C-Líneas de Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Linea_Contrato__c.object
<CustomObject>
    <description>Objeto personalizado utilizado para albergar el conjunto de tareas pertenecientes a un contrato de mantenimiento B2B-B2B2C que tienen la misma periodicidad.</description>
    <fields>
        <fullName>LDC_LKP_Tipo_Trabajo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Campo lookup para relacionar las líneas de contrato con los tipos de trabajo que posteriormente se relacionará con cada Orden de Trabajo</description>
        <label>Tipo de Trabajo</label>
        <referenceTo>WorkType</referenceTo>
        <relationshipLabel>Líneas de Contrato</relationshipLabel>
        <relationshipName>Lineas_de_Contrato</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_NUM_Preaviso_dias__c</fullName>
        <label>Días de preaviso</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Línea de Contrato</label>
    <nameField>
        <displayFormat>L.C-{00000000}</displayFormat>
        <label>Nº de Línea</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tarea_Linea_Contrato__c.object
<CustomObject>
    <description>Objeto personalizado que representa el detalle de todas las tareas que están dentro de una línea de trabajo</description>
    <label>Tarea de Línea de Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nº de Tarea</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tareas de Línea de Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tareas_Tipo_Trabajo__c.object
<CustomObject>
    <description>Objeto personalizado que representa el detalle de todas las tareas que están dentro de un tipo de trabajo</description>
    <label>Tarea de Tipo de Trabajo</label>
    <nameField>
        <label>Tarea de Tipo de Trabajo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tareas de Tipo de Trabajo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_TRG_Handler_Direcciones_B2B_Lineas.cls
@isTest
public without sharing class Test_TRG_Handler_Direcciones_B2B_Lineas extends TestSetup{
	
	private static void InicializarVariables(){
		
		Baipas.establecerVariableControl();
		Account compania = Util_Tests.crearCuentaB2BPpal('Holiday Gym','2000','X1234567X');
		insert compania;		
		Account cuenta = Util_Tests.crearCuentaB2BSec('Holiday Gym2','1000',compania.Id,'X1134567X');
		insert cuenta;
		//Creo e inserto Contratos
		Contract contrato = Util_Tests.crearContrato(cuenta.Id,'b2b_p_1');
		insert contrato;
		//Creo e inserto linea de contrato
		WorkType tipoTrabajo = Util_Tests.crearTipoTrabajo('Tipo de Trabajo por Defecto', '21', 2);
		insert tipoTrabajo;
		Linea_Contrato__c lineaContrato = Util_Tests.crearLineaContrato(contrato.Id,3,'21',Label.RT_LIN_CON_PREVENTIVO);
		lineaContrato.LDC_LKP_Tipo_Trabajo__c = tipoTrabajo.Id;
		lineaContrato.LDC_NUM_Preaviso_dias__c = 5;
		insert lineaContrato;
		Tareas_Tipo_Trabajo__c tareaTipoTrabajo = Util_Tests.crearTareaTipoTrabajo('Tarea para un tipo de trabajo', tipoTrabajo.Id);
		insert tareaTipoTrabajo;
		Tarea_Linea_Contrato__c tareaLineaContrato = Util_Tests.crearTareaLineaContrato(lineaContrato.Id, tareaTipoTrabajo.Id);
		insert tareaLineaContrato;
		Baipas.deshabilitarVariableControl();
		//Creo e inserto dirección dec linea de contrato
		Direcciones_B2B_B2B2C_Lineas_de_Contrato__c direccion = Util_Tests.crearDireccionesB2B_B2B2CLineasContrato(cuenta.Id, lineaContrato.Id, 8);
		direccion.DLC_DAT_Activacion_primer_servicio__c = DateTime.Now().Date();
		insert direccion;
	}	
	
	static testMethod void EliminarVariables(){		
		
		Test.startTest();
		InicializarVariables();
		List<Direcciones_B2B_B2B2C_Lineas_de_Contrato__c> direccion = new List<Direcciones_B2B_B2B2C_Lineas_de_Contrato__c>([SELECT id from Direcciones_B2B_B2B2C_Lineas_de_Contrato__c]);
		delete direccion;
		Test.stopTest();
	}

}