src/objects/Direcciones_B2B_B2B2C_Lineas_de_Contrato__c.object
<CustomObject>
    <fields>
        <fullName>DLC_TXT_Identificador__c</fullName>
        <description>Concatenación de los IDs de la Cuenta y de la Línea de Contrato.</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Dirección B2B/B2B2C-Línea de Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones B2B/B2B2C-Líneas de Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FSL__Scheduling_Policy__c.object
<CustomObject>
    <label>Scheduling Policy</label>
    <nameField>
        <label>Scheduling Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduling Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Linea_Contrato__c.object
<CustomObject>
    <description>Objeto personalizado utilizado para albergar el conjunto de tareas pertenecientes a un contrato de mantenimiento B2B-B2B2C que tienen la misma periodicidad.</description>
    <label>Línea de Contrato</label>
    <nameField>
        <displayFormat>L.C-{00000000}</displayFormat>
        <label>Nº de Línea</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Poblacion__c.object
<CustomObject>
    <description>Municipios de España.</description>
    <label>Población</label>
    <nameField>
        <label>Población</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poblaciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Procedencia__c.object
<CustomObject>
    <description>Representa cada una de las procedencias de una Compañía/Cliente B2B.</description>
    <label>Procedencia</label>
    <nameField>
        <label>Código de Procedencia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceResource.object
<CustomObject>
    <fields>
        <fullName>RSE_LKP_Cuenta__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Cuenta del Profesional Contrato</description>
        <label>Cuenta de Profesional</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Profesional Contrato</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recursos de servicios</relationshipLabel>
        <relationshipName>Recursos_de_servicios</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSE_SEL_Gremio__c</fullName>
        <description>Gremio al que pertenece el profesional</description>
        <label>Gremio</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Gremios</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_CAS_Orden_Trabajo_Facturada__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check que indica si la Work Order ha sido facturada</description>
        <label>Servicio Facturado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OTR_LKP_Linea_Contrato__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Línea de Contrato</label>
        <referenceTo>Linea_Contrato__c</referenceTo>
        <relationshipLabel>Órdenes de trabajo</relationshipLabel>
        <relationshipName>OTR_REL_Linea_Contrato</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OTR_LKP_Primera_Cita__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primera Cita de Servicio vinculada a la Orden de Trabajo. Representa la FK al objeto ServiceAppoinment. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto ServiceAppoinment</description>
        <label>Primera Cita de Servicio</label>
        <referenceTo>ServiceAppointment</referenceTo>
        <relationshipLabel>Órdenes de trabajo</relationshipLabel>
        <relationshipName>Ordenes_de_trabajo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OTR_SEL_Gremio__c</fullName>
        <description>Gremio vinculado a la orden de trabajo.</description>
        <label>Gremio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Gremios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OTR_SEL_Rango_Primera_Cita__c</fullName>
        <label>Hora de Primera Cita</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Rango_2_Horas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OTR_TXT_Identificador_DLC__c</fullName>
        <description>Concatenación de la Línea de Contrato y de la Cuenta B2B secundaria para identificar de forma única el registro de la tabla intermedia.</description>
        <label>Identificador DLC</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OTR_TXT_Num_OrdenTrabajo_HS__c</fullName>
        <description>Nº de Orden de Trabajo HomeServe. Identificador exclusivo de la Orden de Trabajo.</description>
        <externalId>true</externalId>
        <label>Nº de Servicio HS</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Rango_2_Horas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>00:00 - 02:00</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02:00 - 04:00</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>04:00 - 06:00</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>06:00 - 08:00</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>08:00 - 10:00</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>10:00 - 12:00</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>12:00 - 14:00</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>14:00 - 16:00</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>16:00 - 18:00</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>18:00 - 20:00</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>20:00 - 22:00</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>22:00 - 00:00</label>
    </customValue>
    <description>Intervalos de 2 horas pares.</description>
    <masterLabel>Rango 2 Horas</masterLabel>
</GlobalValueSet>

src/classes/Test_TRG_Orden_de_Trabajo.cls
@isTest
public without sharing class Test_TRG_Orden_de_Trabajo {
    private static Account compania {get; set;}
    private static Account cuentaPrincipal {get; set;}
    private static Account cuenta {get; set;}
    private static Account cuentaProfesional {get; set;}
    private static Tipo_Producto_CIA__c tipoProductoCIA {get; set;}
    private static Producto_CIA__c productoCIA {get; set;}
    private static Poblacion__c poblacion {get; set;}
    private static ServiceContract poliza {get; set;}
    private static Procedencia__c procedencia {get; set;}
    private static Case caso {get; set;}
    private static WorkType tipoTrabajo {get; set;}
    private static WorkType tipoTrabajo2 {get; set;}
    private static Contract contrato {get; set;}
    private static Linea_Contrato__c lineaContrato {get; set;}
    private static Linea_Contrato__c lineaContrato2 {get; set;}
    private static Direcciones_B2B_B2B2C_Lineas_de_Contrato__c direccionBB_lineas {get; set;}
    private static Direcciones_B2B_B2B2C_Lineas_de_Contrato__c direccionBB_lineas2 {get; set;}
    private static WorkOrder ordenTrabajo {get; set;}
    private static WorkOrderLineItem lineaOrdenTrabajo {get; set;}
    private static ServiceResource profesional {get; set;}
    private static User usuari {get; set;}
    private static Account cuentaProfesionalContrato {get; set;}
    private static Case casoReclamacion {get; set;}
    //private static ServiceAppointment citaDeServicio {get;set;}
   
    private static void inicializarVariables(){
      	Baipas.establecerVariableControl();
      	List<Account> listaCuentas = new List<Account>();
        cuentaPrincipal = Util_Tests.crearCuentaB2BPpal('B2BPrincipal','1019','X1134567X');
        cuentaPrincipal.type = Label.CUE_TIPO_CLIENTEFINAL;
        insert cuentaPrincipal;
      	cuentaProfesionalContrato = Util_Tests.crearCuentaProfesionalContrato('PR000001','1030','X1111567X', cuentaPrincipal.Id);
      	cuentaProfesionalContrato.CUE_LKP_CuentaPrincipalProf__c = cuentaPrincipal.id;
      	cuentaProfesionalContrato.CUE_LKP_Cuenta_principal__c = null;
      	cuentaProfesionalContrato.CUE_SEL_Tipo_de_Profesional__c = '01';
      
      	insert cuentaProfesionalContrato;
        cuentaProfesionalContrato.CUE_SEL_Estado__c = Label.CUE_ESTADO_ACTIVADO;
        update cuentaProfesionalContrato;
    	compania = Util_Tests.crearCuentaCompania('SegurCaixa','1018','X1234567X');
    	RecordType rt = [select id from RecordType Where name = 'Profesional Contrato'];
        cuentaProfesional = Util_Tests.crearCuentaB2BPpal('PR123456','1020','X1114567X');
        cuentaProfesional.CUE_SEL_Tipo_de_Profesional__c = '01';
        cuentaProfesional.RecordTypeId = rt.Id;
        cuentaProfesional.CUE_LKP_CuentaPrincipalProf__c = cuentaPrincipal.id;
        cuentaProfesional.CUE_LKP_Cuenta_principal__c = null;
    	insert cuentaProfesional;
        cuentaProfesional.CUE_CAS_Activado__c=true;
        cuentaProfesional.CUE_SEL_Estado__c= '02';
     	update cuentaProfesional;
        Profile perfil = [SELECT Id FROM Profile WHERE Name =: Label.PERFIL_ADMINISTRADOR];
        usuari = Util_Tests.nuevoUsuario('pruebas','pruebas','asdd@hotmail.com','pruebas','pruebas',perfil);
        insert usuari;


        profesional = Util_Tests.crearRecursoServicio(cuentaProfesional.CUE_TXT_Identificador__c+'21_1','Estanislao',cuentaProfesionalContrato.Id,usuari);
        profesional.RSE_LKP_Cuenta__r=cuentaProfesional;
        profesional.RSE_SEL_Gremio__c = '21';
        profesional.RSE_LKP_Cuenta__c=cuentaProfesional.Id;
        insert profesional;
    	cuenta = Util_Tests.crearCuentaB2BSec('Asegurado','1021',cuentaPrincipal.Id,'X1111567X');
    	listaCuentas.add(compania);
    	listaCuentas.add(cuenta);
    	insert listaCuentas;
    	tipoProductoCIA = Util_Tests.crearTipoProductoCIA('SegurCaixa - HOGAR','01',compania.ID);
    	insert tipoProductoCIA;
    	productoCIA = Util_Tests.crearProductoCIA('KIT 107','12345678',tipoProductoCIA.Id);
    	insert productoCIA;
    	poblacion =  Util_Tests.crearPoblacion('Madrid','28');
    	insert poblacion;
    	poliza = Util_Tests.crearPolizaContrato('2277393',compania.Id,cuenta.Id,productoCIA.Id);
    	insert poliza;
    	procedencia = Util_Tests.crearProcedencia(0,0,0,0,0,cuenta.Id,'101801','CAS_Siniestro');
    	insert procedencia;
    	caso = Util_Tests.crearCasoB2B(poliza.Id, cuenta.Id, compania.Id);
    	insert caso;
    	tipoTrabajo = Util_Tests.crearTipoTrabajo('Tipo de Trabajo por Defecto','21', 2);
    	tipoTrabajo2 = Util_Tests.crearTipoTrabajo(Label.TDT_TEXTO_MANUAL,'21', 2);
    	insert tipoTrabajo;
    	insert tipoTrabajo2;
    	contrato = Util_Tests.crearContrato(cuenta.Id,'b2b_p_1');
    	insert contrato;
    	lineaContrato = Util_Tests.crearLineaContrato(contrato.Id,3,'21',Label.RT_LIN_CON_CORRECTIVO);
    	lineaContrato2 = Util_Tests.crearLineaContrato(contrato.Id,3,'21',Label.RT_LIN_CON_CORRECTIVO);
    	insert lineaContrato;
    	insert lineaContrato2;
    	direccionBB_lineas = Util_Tests.crearDireccionesB2B_B2B2CLineasContrato(cuenta.Id,lineaContrato.Id,2);
    	direccionBB_lineas.DLC_TXT_Identificador__c = String.valueOf(cuenta.Id) + '_' + String.valueOf(lineaContrato.Id);
    	direccionBB_lineas2 = Util_Tests.crearDireccionesB2B_B2B2CLineasContrato(cuenta.Id,lineaContrato2.Id,2);
    	direccionBB_lineas2.DLC_TXT_Identificador__c = String.valueOf(cuenta.Id) + '_' + String.valueOf(lineaContrato2.Id);
    	insert direccionBB_lineas;
    	insert direccionBB_lineas2;
    	List<FSL__Scheduling_Policy__c> listaPoliticas = new List<FSL__Scheduling_Policy__c>();
    	FSL__Scheduling_Policy__c primerPoliticas = new FSL__Scheduling_Policy__c();
    	primerPoliticas.Name = 'Política de Asignación – Geolocalización - Primario';
    	listaPoliticas.add(primerPoliticas);
    	FSL__Scheduling_Policy__c segundoPoliticas = new FSL__Scheduling_Policy__c();
    	segundoPoliticas.Name = 'Política de Asignación – Geolocalización';
    	listaPoliticas.add(segundoPoliticas);
    	insert listaPoliticas;
    	casoReclamacion = Util_Tests.crearCasoReclamacion(poliza.Id, cuenta.Id, compania.Id);
    	insert casoReclamacion;
    	datetime ahora = system.now();
    //citaDeServicio = Util_tests.crearCitaServicio('Madrid', 'Spain', '28003', 'Madrid', 'Castellana', ahora, ahora);
    //insert citaDeServicio;
    
    
    Baipas.deshabilitarVariableControl();
    }

    
  
  @isTest static void segundoTestTriggerOT(){
    inicializarVariables();
    Test.startTest();
    //insertamos politcas que se utilizan en TRG_Handler Orden de trabajo
    
    Baipas.deshabilitarVariableControl();
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,caso.Id,profesional.Id);
    ordenTrabajo.AccountId = cuenta.Id;
    
    
    ordentrabajo.CaseId = caso.Id;
    ordentrabajo.WorkTypeId = tipoTrabajo.Id;
    insert ordenTrabajo;
   
    update ordenTrabajo;
        lineaOrdenTrabajo = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
        Test.stopTest();
  }
  
  @isTest static void segundoTestBISTriggerOT(){
    inicializarVariables();
    Test.startTest();
    //insertamos politcas que se utilizan en TRG_Handler Orden de trabajo
    
    Baipas.establecerVariableControl();
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,caso.Id,profesional.Id);
    ordenTrabajo.AccountId = cuenta.Id;
    
    ordentrabajo.CaseId = caso.Id;
    insert ordenTrabajo;
        lineaOrdenTrabajo = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
        insert lineaOrdenTrabajo;
        Baipas.deshabilitarVariableControl();
        
        ordenTrabajo.Status = '101';
        ordenTrabajo.OTR_LKP_Linea_Contrato__c = lineaContrato.Id;
        Boolean aux2 = Baipas.deshabilitarVariableControl();
        update ordenTrabajo;
        
        Test.stopTest();
  }
  
  @isTest static void tercerTestTriggerOT(){
    inicializarVariables();
    Test.startTest();
    system.debug('>>>>>caso.Id: ' + caso.Id);
    
    //Insertamos un nuevo caso para hacer saltar la condición: if (woOld != null && wo.caseId != woOld.caseId)
    Case casoWO = new Case();
    casoWO = Util_Tests.crearCasoB2B(poliza.Id, cuenta.Id, compania.Id);
    Baipas.establecerVariableControl();
        insert casoWO;
        Baipas.deshabilitarVariableControl();
    system.debug('>>>>>casoWO.Id: ' + casoWO.Id);
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,caso.Id,profesional.Id);
    ordentrabajo.OTR_LKP_Linea_Contrato__c = lineaContrato.Id;
    ordenTrabajo.AccountId = cuenta.Id;
    
    ordentrabajo.CaseId = caso.Id;
    insert ordenTrabajo;
    casoWO.CAS_LKP_Orden_Trabajo_Principal__c = ordenTrabajo.Id;
    /*Baipas.establecerVariableControl();
    update casoWO;
    Baipas.deshabilitarVariableControl();*/
    ordentrabajo.CaseId = casoWO.Id;
    update ordenTrabajo;
    delete ordenTrabajo;
        Test.stopTest();
  }
  
  @isTest static void cuartoTestTriggerOT(){
    inicializarVariables();
    Test.startTest();
    system.debug('>>>>>caso.Id: ' + caso.Id);
    
    //Insertamos un nuevo caso para hacer saltar la condición: if (woOld != null && wo.caseId != woOld.caseId)
    Case casoWO = new Case();
    casoWO = Util_Tests.crearCasoB2B(poliza.Id, cuenta.Id, compania.Id);
    Baipas.establecerVariableControl();
        insert casoWO;
        Baipas.deshabilitarVariableControl();
    system.debug('>>>>>casoWO.Id: ' + casoWO.Id);
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,caso.Id,profesional.Id);
    ordenTrabajo.AccountId = cuenta.Id;
    
    ordentrabajo.CaseId = caso.Id;
    insert ordenTrabajo;
    ordentrabajo.CaseId = casoWO.Id;
    ordentrabajo.OTR_SEL_Rango_Primera_Cita__c = '09';
    update ordenTrabajo;
    delete ordenTrabajo;
        Test.stopTest();
  }
  
  @isTest static void quintoTestTriggerOT(){
    inicializarVariables();
    Test.startTest();
    
    Baipas.deshabilitarVariableControl();
    
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,caso.Id,profesional.Id);
    ordenTrabajo.AccountId = cuenta.Id;
    
    ordentrabajo.CaseId = caso.Id;
    insert ordenTrabajo;
        /*lineaOrdenTrabajo = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
        Baipas.establecerVariableControl();
        insert lineaOrdenTrabajo;
        Baipas.deshabilitarVariableControl();
        ordenTrabajo.Status = '06';
        ordenTrabajo.OTR_LKP_Linea_Contrato__c = lineaContrato.Id;
        Boolean aux2 = Baipas.deshabilitarVariableControl();
        update ordenTrabajo;
        List<WorkOrder> listaWO = new List<WorkOrder>();
        listaWO.add(ordenTrabajo);
        TRG_Handler_Orden_de_Trabajo.maestroClientesTRG(listaWO);
        delete listaWO;*/
        
        //Actualizamos CP, Gremio 
        //y Tipo de trabajo de la WO
        //ordenTrabajo.PostalCode = '28300';
        //ordenTrabajo.OTR_SEL_Gremio__c = '02';
        //ordenTrabajo.Name = 'Arregla mesa';
        //update ordenTrabajo;
        Test.stopTest();
  }

  @isTest static void quintoTestBISTriggerOT(){
    inicializarVariables();
    Test.startTest();
    
    Baipas.establecerVariableControl();
    
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,caso.Id,profesional.Id);
    ordenTrabajo.AccountId = cuenta.Id;
    
    ordentrabajo.CaseId = caso.Id;
    insert ordenTrabajo;
        lineaOrdenTrabajo = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
        insert lineaOrdenTrabajo;
        ordenTrabajo.Status = '06';
        ordenTrabajo.OTR_LKP_Linea_Contrato__c = lineaContrato.Id;
        update ordenTrabajo;
      /*
        List<WorkOrder> listaWO = new List<WorkOrder>();
        listaWO.add(ordenTrabajo);
     	insert listaWO;
        //TRG_Handler_Orden_de_Trabajo.maestroClientesTRG(listaWO);
        delete listaWO;
       */ 
        //Actualizamos CP, Gremio 
        //y Tipo de trabajo de la WO
        //ordenTrabajo.PostalCode = '28300';
        //ordenTrabajo.OTR_SEL_Gremio__c = '02';
        //ordenTrabajo.Name = 'Arregla mesa';
        //update ordenTrabajo;
        Baipas.deshabilitarVariableControl();
        Test.stopTest();
  }

  /*@isTest static void sextoTestTriggerOT(){
    inicializarVariables();
    Test.startTest();
    
    Baipas.deshabilitarVariableControl();
    
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,caso.Id,profesional.Id);
    ordenTrabajo.AccountId = cuenta.Id;
    
    ordentrabajo.CaseId = caso.Id;
    insert ordenTrabajo;
        lineaOrdenTrabajo = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
        Baipas.establecerVariableControl();
        insert lineaOrdenTrabajo;
        Baipas.deshabilitarVariableControl();
        ordenTrabajo.Status = '501';
        ordenTrabajo.OTR_LKP_Linea_Contrato__c = lineaContrato.Id;
        caso.CAS_DIV_Total_Facturar_CIA_AI__c=100.0;
        update caso;
        Boolean aux2 = Baipas.deshabilitarVariableControl();
        update ordenTrabajo;
        List<WorkOrder> listaWO = new List<WorkOrder>();
        listaWO.add(ordenTrabajo);
        //TRG_Handler_Orden_de_Trabajo.maestroClientesTRG(listaWO);
        delete listaWO;
        
        //Actualizamos CP, Gremio 
        //y Tipo de trabajo de la WO
        //ordenTrabajo.PostalCode = '28300';
        //ordenTrabajo.OTR_SEL_Gremio__c = '02';
        //ordenTrabajo.Name = 'Arregla mesa';
        update ordenTrabajo;
        Test.stopTest();
  }*/
  /*@isTest static void septimoTestTriggerOT(){
    inicializarVariables();
    Test.startTest();
    
    Baipas.deshabilitarVariableControl();
    
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,caso.Id,profesional.Id);
    ordenTrabajo.AccountId = cuenta.Id;
    
    ordentrabajo.CaseId = caso.Id;
    //ordentrabajo.OTR_TXT_Num_OrdenTrabajo_HS__c=null;
    insert ordenTrabajo;
        lineaOrdenTrabajo = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
        Baipas.establecerVariableControl();
        insert lineaOrdenTrabajo;
        Baipas.deshabilitarVariableControl();
        ordentrabajo.Status = Label.OTR_ESTADO_CERRADO_ALBARAN_RECIBIDO;
        ordenTrabajo.OTR_LKP_Linea_Contrato__c = lineaContrato.Id;
        caso.CAS_DIV_Total_Facturar_CIA_AI__c=100.0;
        update caso;
        Boolean aux2 = Baipas.deshabilitarVariableControl();
        update ordenTrabajo;
        List<WorkOrder> listaWO = new List<WorkOrder>();
        listaWO.add(ordenTrabajo);
       // TRG_Handler_Orden_de_Trabajo.maestroClientesTRG(listaWO);
        delete listaWO;
        
        //Actualizamos CP, Gremio 
        //y Tipo de trabajo de la WO
        //ordenTrabajo.PostalCode = '28300';
        //ordenTrabajo.OTR_SEL_Gremio__c = '02';
        //ordenTrabajo.Name = 'Arregla mesa';
        //update ordenTrabajo;
        //Test.stopTest();
  }*/
  /*@isTest static void octavoTestTriggerOT(){
        Test.startTest();
        Boolean aux = Baipas.establecerVariableControl();
                               List<Account> listaCuentas = new List<Account>();
                               compania = Util_Tests.crearCuentaCompania('SegurCaixa','1018','X1234567X');
                               cuentaPrincipal = Util_Tests.crearCuentaB2BPpal('B2BPrincipal','1019','X1134567X');
                               insert cuentaPrincipal;
        cuentaProfesional = Util_Tests.crearCuentaB2BPpal('CuentaProf','1020','X1114567X');
                               insert cuentaProfesional;
        List<Profile> perfiles = [SELECT Id FROM Profile WHERE Name =: Label.PERFIL_ADMINISTRADOR];
        usuari = Util_Tests.nuevoUsuario('pruebas','pruebas','asdd@hotmail.com','pruebas','pruebas',perfiles.get(0));
        insert usuari;
        Account cuentaProfesionalContrato = Util_Tests.crearCuentaProfesionalContrato('PR000001','1030','X1111567X');
        cuentaProfesionalContrato.CUE_SEL_Estado__c = Label.CUE_ESTADO_ACTIVADO;
      insert cuentaProfesionalContrato;
        profesional = Util_Tests.crearRecursoServicio('Nombre','Estanislao',cuentaProfesionalContrato.Id,usuari);
    insert profesional;
       cuenta = Util_Tests.crearCuentaB2BSec('Asegurado','1021',cuentaPrincipal.Id,'X1111567X');
       listaCuentas.add(compania);
       listaCuentas.add(cuenta);
       insert listaCuentas;
       tipoProductoCIA = Util_Tests.crearTipoProductoCIA('SegurCaixa - HOGAR','01',compania.ID);
       insert tipoProductoCIA;
       productoCIA = Util_Tests.crearProductoCIA('KIT 107','12345678',tipoProductoCIA.Id);
       insert productoCIA;
       poblacion =  Util_Tests.crearPoblacion('Madrid','28');
       insert poblacion;
       poliza = Util_Tests.crearPolizaContrato('2277393',compania.Id,cuenta.Id,true,'79167066','28001','PISO',Date.newInstance(2016, 12, 31),'Madrid',productoCIA.Id,'2');
       insert poliza;
       procedencia = Util_Tests.crearProcedencia(0,0,0,0,0,cuenta.Id,'101801','CAS_Siniestro');
       insert procedencia;
       caso = Util_Tests.crearCasoB2B(poliza.Id, cuenta.Id, compania.Id);
       insert caso;
       tipoTrabajo = Util_Tests.crearTipoTrabajo('Tipo de Trabajo por Defecto','21', 2);
       insert tipoTrabajo;
       contrato = Util_Tests.crearContrato(cuenta.Id,'b2b_p_1');
       insert contrato;
       lineaContrato = Util_Tests.crearLineaContrato(contrato.Id,3,'21',Label.RT_LIN_CON_CORRECTIVO);
       insert lineaContrato;
       direccionBB_lineas = Util_Tests.crearDireccionesB2B_B2B2CLineasContrato(cuenta.Id,lineaContrato.Id,3);
       direccionBB_lineas.DLC_TXT_Identificador__c = String.valueOf(cuenta.Id) + '_' + String.valueOf(lineaContrato.Id);
       insert direccionBB_lineas;
       ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,caso.Id,profesional.Id);
       ordenTrabajo.AccountId = cuenta.Id;
       insert ordenTrabajo;
        lineaOrdenTrabajo = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
        insert lineaOrdenTrabajo;
        ordenTrabajo.Status = '501';
        Boolean aux2 = Baipas.deshabilitarVariableControl();
        upsert ordenTrabajo;
        delete ordenTrabajo;
        Test.stopTest();
  }*/

  @isTest
  public static void testUltimo(){
    Test.startTest();
    inicializarVariables();
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,caso.Id,profesional.Id);
    ordenTrabajo.OTR_LKP_Linea_Contrato__c = lineaContrato.Id;
    ordenTrabajo.OTR_TXT_Identificador_DLC__c = direccionBB_lineas.DLC_TXT_Identificador__c;
    insert ordenTrabajo;
    ordenTrabajo.OTR_LKP_Linea_Contrato__c = lineaContrato2.Id;
    ordenTrabajo.OTR_TXT_Identificador_DLC__c = direccionBB_lineas2.DLC_TXT_Identificador__c;
    update ordenTrabajo;
    Test.stopTest();
  }
  
  /*@isTest
  public static void CambioEstadoCerrado(){
    Test.startTest();
    inicializarVariables();
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',null,caso.Id,profesional.Id);
    ordenTrabajo.Status = Label.OTR_ESTADO_REVISADO;
    insert ordenTrabajo;
    ordenTrabajo.Status = Label.OTR_ESTADO_CERRADO;
    WorkOrderLineItem partidaWO = new WorkOrderLineItem();
    partidaWO = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
    insert partidaWO;
    update ordenTrabajo;
    Test.stopTest();
  }*/
  
  @isTest
  public static void woCasoReclamacion(){
    Test.startTest();
    inicializarVariables();
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,casoReclamacion.Id,profesional.Id);
    ordenTrabajo.Status = Label.OTR_ESTADO_REVISADO;
    ordenTrabajo.OTR_CAS_Orden_Trabajo_Facturada__c = false;
    insert ordenTrabajo;
    ordenTrabajo.Status = Label.OTR_ESTADO_CERRADO;
    ordenTrabajo.OTR_CAS_Orden_Trabajo_Facturada__c = true;
    update ordenTrabajo;
    WorkOrderLineItem partidaWO = new WorkOrderLineItem();
    partidaWO = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
    Test.stopTest();
  }
  
  @isTest
  public static void woCasoNoReclamacion(){
    Test.startTest();
    inicializarVariables();
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,caso.Id,profesional.Id);
    ordenTrabajo.Status = Label.OTR_ESTADO_ANULADO;
    ordenTrabajo.OTR_CAS_Orden_Trabajo_Facturada__c = false;
    insert ordenTrabajo;
    caso.CAS_LKP_Orden_Trabajo_Principal__c = ordenTrabajo.Id;
    update caso;
    ordenTrabajo.Status = Label.OTR_ESTADO_CERRADO;
    ordenTrabajo.OTR_CAS_Orden_Trabajo_Facturada__c = true;
    update ordenTrabajo;
    WorkOrderLineItem partidaWO = new WorkOrderLineItem();
    partidaWO = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
    Test.stopTest();
  }
  
  @isTest
  public static void woCambioEstado(){
    Test.startTest();
    inicializarVariables();
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,casoReclamacion.Id,profesional.Id);
    ordenTrabajo.Status = Label.OTR_ESTADO_REVISADO;
    ordenTrabajo.OTR_CAS_Orden_Trabajo_Facturada__c = false;
    insert ordenTrabajo;
    caso.CAS_LKP_Orden_Trabajo_Principal__c = ordenTrabajo.Id;
    update caso;
    ordenTrabajo.Status = Label.OTR_ESTADO_CERRADO_ALBARAN_RECIBIDO;
    ordenTrabajo.OTR_CAS_Orden_Trabajo_Facturada__c = true;
    update ordenTrabajo;
    WorkOrderLineItem partidaWO = new WorkOrderLineItem();
    partidaWO = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
    Test.stopTest();
  }
  
  @isTest
  public static void enEsperaDeConf(){
    
    inicializarVariables();
    Test.startTest();
    ordenTrabajo = Util_Tests.crearOrdenTrabajoConProfesional('18210.0','21',tipoTrabajo.Id,casoReclamacion.Id,profesional.Id);
    ordenTrabajo.Status = Label.OTR_ESTADO_REVISADO;
    ordenTrabajo.OTR_CAS_Orden_Trabajo_Facturada__c = false;
    caso.CAS_DIV_Total_Facturar_CIA_AI__c = 10.22;
    update caso;
    insert ordenTrabajo;
    caso.CAS_LKP_Orden_Trabajo_Principal__c = ordenTrabajo.Id;
    caso.CAS_DIV_Total_Facturar_CIA_AI__c = 43.34;
    update caso;
    ordenTrabajo.Status = Label.OTR_ESTADO_CERRADO_ALBARAN_RECIBIDO;
    ordenTrabajo.OTR_CAS_Orden_Trabajo_Facturada__c = true;
    ordenTrabajo.OTR_TXT_Num_OrdenTrabajo_HS__c = '';
    //ordenTrabajo.OTR_LKP_Primera_Cita__c = citaDeServicio.iD;
    update ordenTrabajo;
    WorkOrderLineItem partidaWO = new WorkOrderLineItem();
    partidaWO = Util_Tests.crearNuevaPartidaTrabajo(ordenTrabajo.Id);
    
    List<WorkOrder> listWO = new List<WorkOrder>();
    listWO.add(ordenTrabajo);
    Map<Id, WorkOrder> mapWO = new Map<Id, WorkOrder>();
    Set<Id> setIdsWO = new Set<Id>();   
    mapWO.put(ordenTrabajo.Id,ordenTrabajo);
    setIdsWO.add(ordenTrabajo.Id);
    TRG_Handler_Orden_de_Trabajo.calcularLimiteOrdenEnCurso(listWO,mapWO,setIdsWO);
    TRG_Handler_Orden_de_Trabajo.calcularLimiteOrdenMensual(listWO,mapWO,setIdsWO);
    Test.stopTest();
  }
}