src/objects/Documentos_Profesionales_Contrato__c.object
<CustomObject>
    <description>Sirve para identificar los diferentes documentos de los que se dispone asociados a cada Profesional Contrato</description>
    <fields>
        <fullName>DPC_DAT_Fecha_Entrega__c</fullName>
        <description>Fecha en la que el Profesional Contrato aportó el documento asociado al registro</description>
        <label>Fecha Entrega</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DPC_DAT_Fecha_Expiracion__c</fullName>
        <description>Indica la fecha en la que expira el documento asociado al registro</description>
        <label>Fecha Expiración</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DPC_LKP_Profesional_Contrato__c</fullName>
        <description>Indica la cuenta Profesional Contrato a la que se asocia  el documento registrado</description>
        <label>Profesional Contrato</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>La cuenta seleccionada no es válida.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Profesional Contrato</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documentos de Profesional Contrato</relationshipLabel>
        <relationshipName>Documentos_de_Profesional_Contrato</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DPC_LKP_Tipo_de_Documento__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Tipo de Documento</label>
        <referenceTo>Tipo_de_documento__c</referenceTo>
        <relationshipLabel>Documentos de Profesional Contrato</relationshipLabel>
        <relationshipName>Documentos_de_Profesional_Contrato</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Documento de Profesional Contrato</label>
    <nameField>
        <displayFormat>DPC-{000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentos de Profesional Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tipo_de_documento__c.object
<CustomObject>
    <description>Entidad necesaria para el registro de tipos de documentos</description>
    <fields>
        <fullName>DOC_CAS_Estado_Documento__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indica si el documento aplica o no</description>
        <label>Documento imprescindible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DOC_CAS_Validez__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si el Documento tiene fecha de vigencia o no</description>
        <label>Caducidad</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DOC_DAT_Fecha_Inicio_Vigencia__c</fullName>
        <description>Fecha en la que el documento comienza a ser vigente</description>
        <label>Fecha de Inicio Vigencia</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DOC_NUM_Dias_para_Baja__c</fullName>
        <description>Número de días en el que se dará de baja temporal a la cuenta de Profesional Contrato, tras haber vencido el Documento.</description>
        <label>Dias para Baja tras Vencimiento</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DOC_SEL_Tipo_de_Profesional__c</fullName>
        <description>Indica los diferentes tipos de Profesionales a los que aplica el documento</description>
        <label>Tipo de Profesional</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipos_de_Profesional</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DOC_TXT_Identificador__c</fullName>
        <description>Id externo del Documento</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOC_TXT_Texto_Email__c</fullName>
        <description>Campo tipo texto para la configuración de los e-mail de notificación del profesional 30 días antes de la fecha de vencimiento de un documento.</description>
        <label>Texto Email</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Tipo de Documento</label>
    <nameField>
        <label>Tipo de Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Documento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Tipos_de_Profesional.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>AUTÓNOMO</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>S.L. (U)</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>S.A. (U)</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>SOC.CIVIL P.</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>SOC. COOP.</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>C.B.</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>AUTÓNOMO TÉCNICO</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>S.L. (U) TÉCNICO</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>S.A. (U) TÉCNICO</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>SOC.CIVIL P. TÉCNICO</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>SOC. COOP. TÉCNICO</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>C.B. TÉCNICO</label>
    </customValue>
    <masterLabel>Tipos de Profesional</masterLabel>
</GlobalValueSet>

src/classes/Test_TRG_Handler_Documentos_Prof.cls
@isTest
public without sharing class Test_TRG_Handler_Documentos_Prof extends TestSetup{
	
	public static Documentos_Profesionales_Contrato__c crearDocumento(Id idProfesional, Id idTipoDocumento, Date fechaEntrega, Date fechaExpiracion){
		Documentos_Profesionales_Contrato__c Documento = new Documentos_Profesionales_Contrato__c();
		Documento.DPC_LKP_Profesional_Contrato__c = idProfesional;
		Documento.DPC_LKP_Tipo_de_Documento__c = idTipoDocumento;
		Documento.DPC_DAT_Fecha_Entrega__c = fechaEntrega;
		Documento.DPC_DAT_Fecha_Expiracion__c = fechaExpiracion;
		return Documento;
	}
	
	public static Tipo_de_Documento__c crearTipoDocumento(String identificador, String nombre, Boolean estado, Boolean validez, String tipoProf, Date fechaInicio, Decimal numDiasBaja, String email){
		Tipo_de_Documento__c tipoDocumento = new Tipo_de_Documento__c();
		tipoDocumento.DOC_TXT_Identificador__c = identificador;
		tipoDocumento.Name = nombre;
		tipoDocumento.DOC_CAS_Estado_Documento__c = estado;
		tipoDocumento.DOC_CAS_Validez__c = validez;
		tipoDocumento.DOC_SEL_Tipo_de_Profesional__c = tipoProf;
		tipoDocumento.DOC_DAT_Fecha_Inicio_Vigencia__c = fechaInicio;
		tipoDocumento.DOC_NUM_Dias_para_Baja__c = numDiasBaja;
		tipoDocumento.DOC_TXT_Texto_Email__c = email;
		return tipoDocumento;
	}

	private static void inicializarVariables(){
		Baipas.establecerVariableControl();
		Account profesionalEmpresa = Util_Tests.crearCuentaCompania('profesionalEmpresa1','1111','Z1585459M');
		insert profesionalEmpresa;
		Account profesional = Util_Tests.crearCuentaProfesionalContrato('PR123456', 'PR123456', 'Z1585459M', profesionalEmpresa.Id);	
     	profesional.CUE_SEL_Tipo_de_Profesional__c = '01';
     	String a = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Profesional Contrato').getRecordTypeId();
     	profesional.RecordTypeId = a;
     	profesional.CUE_CAS_Activado__c = false;
     	profesional.CUE_SEL_Estado__c = '01';
     	insert profesional;
     	Baipas.deshabilitarVariableControl();
     	List <Tipo_de_Documento__c> tiposDocumento = new List <Tipo_de_Documento__c>();
     	Tipo_de_Documento__c tipo1 = crearTipoDocumento('DOC_01','Documento01', true, false, '01', Date.today().addDays(-10), null , null);
     	tiposDocumento.add(tipo1);
     	insert tiposDocumento; 
     	List <Documentos_Profesionales_Contrato__c> Documentos = new List <Documentos_Profesionales_Contrato__c>();
     	Documentos_Profesionales_Contrato__c Documento_1 = crearDocumento(profesional.Id, tipo1.Id, Date.today().addDays(30),null);
     	Documentos.add(Documento_1);
     	insert Documentos;   	
	}
	
	static testMethod void test_Handler_Documento(){
	 	inicializarVariables();
	}

}