src/objects/ENC_Encuesta__c.object
<CustomObject>
    <description>Representa al conjunto de datos que se van a trabajar a lo largo de la Encuesta.</description>
    <fields>
        <fullName>ENC_DAT_Fecha_Hora__c</fullName>
        <description>Fecha y hora en la que se realizó la encuesta</description>
        <label>Fecha/Hora Encuesta</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ENC_LKP_Caso__c</fullName>
        <description>Intervención sobre la que se realiza la encuesta.</description>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Encuestas Realizadas</relationshipLabel>
        <relationshipName>EncuestasRealizadas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ENC_LKP_Encuesta_Tipo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Encuesta Tipo vinculada. Modelo de encuesta realizada.</description>
        <label>Encuesta Tipo</label>
        <referenceTo>ENC_Encuesta_Tipo__c</referenceTo>
        <relationshipLabel>Encuestas Realizadas</relationshipLabel>
        <relationshipName>EncuestasRealizadas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Encuesta Realizada</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encuestas Realizadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ENC_Encuesta_Tipo__c.object
<CustomObject>
    <description>Representa la conexión de las preguntas elegidas para la encuesta del tipo de encuesta elegido con la Encuesta.</description>
    <fields>
        <fullName>ENT_LKP_Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Compañía vinculada a la encuesta tipo.</description>
        <label>Compañía</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Encuestas Tipo</relationshipLabel>
        <relationshipName>EncuestasTipo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ENT_LKP_PrimeraPregunta__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primera pregunta de la encuesta tipo.</description>
        <label>Primera Pregunta</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ENC_Pregunta__c.ENP_LKP_Encuesta_Tipo__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ENC_Pregunta__c</referenceTo>
        <relationshipLabel>Encuestas Tipo</relationshipLabel>
        <relationshipName>EncuestasTipo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ENT_SEL_Long_Encuesta__c</fullName>
        <description>Clasificación de la encuesta tipo: Corta/Larga</description>
        <label>Tipo</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipos_Encuesta</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ENT_TXT_Identificador__c</fullName>
        <description>Indica el identificador de la encuesta (T-Nº encuesta_cod_CIA_Tipo encuesta)</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Encuesta Tipo</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encuestas Tipo</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ENC_Pregunta__c.object
<CustomObject>
    <description>Representa cada una de las preguntas de una Encuesta Tipo.</description>
    <fields>
        <fullName>ENP_CAS_Pregunta_Gremio__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si está marcado que la pregunta debe tener una respuesta para cada uno de los Servicios de la Intervención.</description>
        <label>Preguntar por cada Gremio</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ENP_FOR_PrimeraPregunta__c</fullName>
        <description>Indica si la pregunta es la primera de la encuesta tipo padre.</description>
        <formula>ENP_LKP_Encuesta_Tipo__r.ENT_LKP_PrimeraPregunta__c = Id</formula>
        <label>Primera Pregunta</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ENP_LKP_Encuesta_Tipo__c</fullName>
        <description>Encuesta Tipo a la que pertenece la pregunta.</description>
        <label>Encuesta Tipo</label>
        <referenceTo>ENC_Encuesta_Tipo__c</referenceTo>
        <relationshipLabel>Encuestas Tipo: Pregunta</relationshipLabel>
        <relationshipName>Preguntas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ENP_LKP_Pregunta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pregunta principal a la que pertenece la pregunta en el caso de que sea una pregunta secundaria.</description>
        <label>Pregunta Principal</label>
        <referenceTo>ENC_Pregunta__c</referenceTo>
        <relationshipLabel>Preguntas Secundarias</relationshipLabel>
        <relationshipName>PreguntasSecundarias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ENP_SEL_Tipo_Respuesta__c</fullName>
        <description>Clasificación de la respuesta para poder visualizarla: Check/RadioButton/Picklist/Multipicklist/Texto/Número/Fecha</description>
        <label>Tipo Visual Respuesta</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipo_Respuesta_Encuesta</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ENP_TXT_Identificador__c</fullName>
        <description>Identificador externo de la pregunta (valor del campo Name).</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ENP_TXT_Pregunta__c</fullName>
        <description>Texto de la pregunta.</description>
        <label>Pregunta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Encuesta Tipo: Pregunta</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encuestas Tipo: Pregunta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ENC_Respuesta__c.object
<CustomObject>
    <description>Representa el conjunto de respuestas de una pantalla de la Encuesta</description>
    <fields>
        <fullName>ENR_LKP_Encuesta_Realizada__c</fullName>
        <description>Encuesta realizada a la que pertenece la respuesta.</description>
        <label>Encuesta Realizada</label>
        <referenceTo>ENC_Encuesta__c</referenceTo>
        <relationshipLabel>Encuestas Realizadas: Respuesta</relationshipLabel>
        <relationshipName>RespuestasRealizadas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ENR_LKP_Resp_Pregunta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Pregunta vinculada a la respuesta.</description>
        <label>Pregunta</label>
        <referenceTo>ENC_Pregunta__c</referenceTo>
        <relationshipLabel>Encuestas Realizadas: Respuesta</relationshipLabel>
        <relationshipName>RespuestasRealizadas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ENR_LKP_WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Servicio (si aplica) vinculado a la respuesta.</description>
        <label>Servicio</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Encuestas Realizadas: Respuesta</relationshipLabel>
        <relationshipName>RespuestasRealizadas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ENR_TXT_Respuesta__c</fullName>
        <description>Texto de la respuesta.</description>
        <label>Respuesta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Encuesta Realizada: Respuesta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encuestas Realizadas: Respuesta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ENC_Respuesta_Tipo__c.object
<CustomObject>
    <description>Representa las posibles respuestas de cada una de las preguntas de una Encuesta Tipo, determinando para cada respuesta cuál es la pregunta siguiente.</description>
    <fields>
        <fullName>ENRT_FOR_Tipo_Respuesta__c</fullName>
        <description>Valor API del Tipo Visual de la respuesta determinado por la pregunta padre.</description>
        <formula>TEXT(ENRT_LKP_Pregunta__r.ENP_SEL_Tipo_Respuesta__c)</formula>
        <label>Tipo de Respuesta</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENRT_LKP_PreguntaDestino__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Pregunta siguiente en la encuesta tipo tras utilizar la respuesta tipo.</description>
        <label>Pregunta Destino</label>
        <referenceTo>ENC_Pregunta__c</referenceTo>
        <relationshipLabel>Respuestas Origen</relationshipLabel>
        <relationshipName>RespuestasTipoOrigen</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ENRT_LKP_Pregunta__c</fullName>
        <description>Pregunta a la que pertenece la respuesta tipo.</description>
        <label>Pregunta</label>
        <referenceTo>ENC_Pregunta__c</referenceTo>
        <relationshipLabel>Respuestas Posibles</relationshipLabel>
        <relationshipName>RespuestasTipo</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ENRT_NUM_Ordenacion__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Número de orden para visualizar la respuesta en el caso de que el tipo visual de la pregunta determine que tiene varias respuestas posibles.</description>
        <label>Ordenación</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ENRT_TXT_Valor__c</fullName>
        <description>Valor correspondiente a la respuesta:
a) Si el Tipo Visual es &quot;Check&quot;: Valor Sí o valor No
b) Si el Tipo Visual es &quot;RadioButton&quot;, &quot;Picklist&quot;, &quot;Multipicklist&quot;: Valor de la opción disponible para ser seleccionada.
c) Si el Tipo Visual es &quot;Texto&quot;, &quot;Número&quot;: Vacío ya que el valor es libre.</description>
        <label>Valor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Encuesta Tipo: Respuesta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encuestas Tipo: Respuesta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Tipo_Respuesta_Encuesta.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Sí/No</fullName>
    </customValue>
    <customValue>
        <fullName>Texto</fullName>
    </customValue>
    <customValue>
        <fullName>Número</fullName>
    </customValue>
    <customValue>
        <fullName>Lista de Opciones</fullName>
    </customValue>
    <customValue>
        <fullName>Lista de Opciones (múltiple)</fullName>
    </customValue>
    <masterLabel>Tipos de Respuesta Encuesta</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Tipos_Encuesta.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Encuesta Corta</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Encuesta Larga</label>
    </customValue>
    <masterLabel>Tipos de Encuesta</masterLabel>
</GlobalValueSet>

src/classes/Util_Encuestas.cls
/**
 * Clase de funciones auxiliares relativas a las encuestas.
 * 
 * @author EVERIS
 * 
 */
public without sharing class Util_Encuestas {
	
	public class RespuestaTipoVF {
		public Id idPregunta {get;set;}
		public String tipoRespuesta {get;set;}
		public List<SelectOption> listaOpciones {get;set;}
		public Id idPreguntaDestIndividual {get;set;}
		public Map<String, Id> mapaPreguntasDestMultiple {get;set;}
		public RespuestaTipoVF(Id idPregunta, String tipoRespuesta, List<SelectOption> listaOpciones,
							   Id idPreguntaDestIndividual, Map<String, Id> mapaPreguntasDestMultiple){
			this.idPregunta = idPregunta;
			this.tipoRespuesta = tipoRespuesta;
			this.listaOpciones = listaOpciones;
			this.idPreguntaDestIndividual = idPreguntaDestIndividual;
			this.mapaPreguntasDestMultiple = mapaPreguntasDestMultiple;
		}
	}

	/**
	 * Devuelve las encuestas de los IDs especificados.
	 *
	 * @param setIdEncuesta: IDs de las encuestas a buscar
	 * @return mapa que contiene las encuestas encontradas
	 */
	public static Map<Id,ENC_Encuesta_Tipo__c> queryMapEncuestaTipo(Set<Id> setIdEncuesta){
		Map<Id,ENC_Encuesta_Tipo__c> mapa = new Map<Id,ENC_Encuesta_Tipo__c>();
		if(setIdEncuesta != null && !setIdEncuesta.isEmpty()){
			for(List<ENC_Encuesta_Tipo__c> lista : [SELECT Id,Name,ENT_LKP_Cuenta__c,ENT_TXT_Identificador__c,ENT_SEL_Long_Encuesta__c
													FROM ENC_Encuesta_Tipo__c
													WHERE Id IN :setIdEncuesta]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}

	/**
	 * Devuelve una encuesta a partir de su ID.
	 *
	 * @param idEncuesta: ID de la encuesta a buscar
	 * @return encuesta encontrada
	 */
	/*public static ENC_Encuesta_Tipo__c queryEncuestaTipoById(Id idEncuesta){
		ENC_Encuesta_Tipo__c encuesta = null;
		List<ENC_Encuesta_Tipo__c> lista = new List<ENC_Encuesta_Tipo__c>();
		if(idEncuesta != null){
			lista = [SELECT Id,Name,ENT_LKP_Cuenta__c,ENT_TXT_Identificador__c,ENT_SEL_Long_Encuesta__c FROM ENC_Encuesta_Tipo__c WHERE Id = :idEncuesta];
		}
		if(!lista.isEmpty()){
			encuesta = lista.get(0);
		}
		return encuesta;
	}*/




	public static ENC_Encuesta__c getEncuestaRealizadaById(Id idEncuestaRealizada){
		ENC_Encuesta__c registro = null;
		if(idEncuestaRealizada != null){
			List<ENC_Encuesta__c> lista = [SELECT Id,
												  ENC_DAT_Fecha_Hora__c,
												  ENC_LKP_Caso__c,
												  ENC_LKP_Encuesta_Tipo__c,
												  (SELECT Id FROM RespuestasRealizadas__r)
										   FROM ENC_Encuesta__c
										   WHERE Id = :idEncuestaRealizada];
			if(!lista.isEmpty()){
				registro = lista.get(0);
			}
		}
		return registro;
	}


	public static ENC_Encuesta_Tipo__c getEncuestaTipo(Id idEncuestaTipo, String nameEncuestaTipo){
		ENC_Encuesta_Tipo__c registro = null;
		List<ENC_Encuesta_Tipo__c> lista = new List<ENC_Encuesta_Tipo__c>();
		if(idEncuestaTipo != null){
			lista = [SELECT Id,
							Name,
							ENT_LKP_Cuenta__c,
							ENT_LKP_PrimeraPregunta__c,
							ENT_TXT_Identificador__c,
							ENT_SEL_Long_Encuesta__c,
							(SELECT Id FROM Preguntas__r)
					FROM ENC_Encuesta_Tipo__c
					WHERE Id = :idEncuestaTipo];
		}
		else if(nameEncuestaTipo != null){
			lista = [SELECT Id,
							Name,
							ENT_LKP_Cuenta__c,
							ENT_LKP_PrimeraPregunta__c,
							ENT_TXT_Identificador__c,
							ENT_SEL_Long_Encuesta__c,
							(SELECT Id FROM Preguntas__r)
					FROM ENC_Encuesta_Tipo__c
					WHERE Name = :nameEncuestaTipo];
		}
		if(!lista.isEmpty()){
			registro = lista.get(0);
		}
		return registro;
	}


	public static Map<Id,ENC_Pregunta__c> getMapaPreguntasByEncuestaTipo(Id idEncuestaTipo){
		Map<Id,ENC_Pregunta__c> mapa = new Map<Id,ENC_Pregunta__c>();
		if(idEncuestaTipo != null){
			mapa = new Map<Id,ENC_Pregunta__c>(
				[SELECT Id,
						Name,
						ENP_CAS_Pregunta_Gremio__c,
						ENP_FOR_PrimeraPregunta__c,
						ENP_LKP_Encuesta_Tipo__c,
						ENP_LKP_Pregunta__c,
						ENP_SEL_Tipo_Respuesta__c,
						ENP_TXT_Identificador__c,
						ENP_TXT_Pregunta__c,
						(SELECT Id FROM PreguntasSecundarias__r),
						(SELECT Id FROM RespuestasTipo__r)
				 FROM ENC_Pregunta__c
				 WHERE ENP_LKP_Encuesta_Tipo__c = :idEncuestaTipo
 				 ORDER BY ENP_LKP_Pregunta__c]);
		}
		return mapa;
	}


	public static Map<Id,RespuestaTipoVF> getMapaRespuestasTipoVFByPreguntas(Set<Id> idPreguntas){
		Map<Id,RespuestaTipoVF> mapa = new Map<Id,RespuestaTipoVF>();
		if(idPreguntas != null && !idPreguntas.isEmpty()){
			List<ENC_Respuesta_Tipo__c> lista = [SELECT Id,
														Name,
														ENRT_FOR_Tipo_Respuesta__c,
														ENRT_LKP_PreguntaDestino__c,
														ENRT_LKP_Pregunta__c,
														ENRT_NUM_Ordenacion__c,
														ENRT_TXT_Valor__c
										   		 FROM ENC_Respuesta_Tipo__c
												 WHERE ENRT_LKP_Pregunta__c IN :idPreguntas
		 										 ORDER BY ENRT_LKP_Pregunta__c, ENRT_NUM_Ordenacion__c ASC];
			for(ENC_Respuesta_Tipo__c registro : lista){
				RespuestaTipoVF registroVF = mapa.get(registro.ENRT_LKP_Pregunta__c);
				if(registroVF == null){
					List<SelectOption> listaOpciones = new List<SelectOption>();
					listaOpciones.add(new SelectOption('', '--'));
					registroVF = new RespuestaTipoVF(registro.ENRT_LKP_Pregunta__c, registro.ENRT_FOR_Tipo_Respuesta__c,
													 listaOpciones, registro.ENRT_LKP_PreguntaDestino__c, new Map<String, Id>());
				}
				if(registroVF.tipoRespuesta == 'Lista de Opciones' || registroVF.tipoRespuesta == 'Lista de Opciones (múltiple)'){
					registroVF.listaOpciones.add(new SelectOption(registro.ENRT_TXT_Valor__c, registro.ENRT_TXT_Valor__c));
					registroVF.mapaPreguntasDestMultiple.put(registro.ENRT_TXT_Valor__c, registro.ENRT_LKP_PreguntaDestino__c);
				}
				mapa.put(registro.ENRT_LKP_Pregunta__c, registroVF);
			}
		}
		return mapa;
	}
	

	public static Map<Id,ENC_Respuesta__c> getMapaRespuestasRealByEncuestaReal(Id idEncuestaRealizada, Set<Id> setIdPreguntas){
		Map<Id,ENC_Respuesta__c> mapa = new Map<Id, ENC_Respuesta__c>();
		if(idEncuestaRealizada != null){
			List<ENC_Respuesta__c> lista = [SELECT Id,
												   Name,
												   ENR_LKP_Encuesta_Realizada__c,
												   ENR_LKP_Resp_Pregunta__c,
												   ENR_LKP_WorkOrder__c,
												   ENR_TXT_Respuesta__c
										    FROM ENC_Respuesta__c
											WHERE ENR_LKP_Encuesta_Realizada__c = :idEncuestaRealizada
						 					ORDER BY ENR_LKP_Resp_Pregunta__c];	
			for(ENC_Respuesta__c registro : lista){
				mapa.put(registro.ENR_LKP_Resp_Pregunta__c, registro);
			}
		}
		for(Id idPregunta : setIdPreguntas){
			if(!mapa.containsKey(idPregunta)){
				mapa.put(idPregunta, new ENC_Respuesta__c());				
			}
		}
		return mapa;
	}
}