src/objects/Factura__c.object
<CustomObject>
    <fields>
        <fullName>FAC_TXT_Numero_factura__c</fullName>
        <description>Número de factura informado por el Facturador</description>
        <label>Número de factura</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Propuesta_de_Abono__c.object
<CustomObject>
    <fields>
        <fullName>AB_CAS_Abono_Liquidado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Abono Liquidado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AB_DIV_Importe_a_Imputar__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar (Gestor)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AB_DIV_Importe_a_ingresar__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a ingresar (CIA/Cliente)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AB_FOR_Direccion_Territorial__c</fullName>
        <formula>TEXT(AB_LKP_Caso__r.CAS_SEL_Direccion_Territorial__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dirección Territorial</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Factura__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Factura</label>
        <referenceTo>Factura__c</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Ingresar_a__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ingresar a (CIA/Cliente)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Propuestas de Abonos (Ingresar a)</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Orden_de_Trabajo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Número Servicio</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_SEL_Descripcion_evento__c</fullName>
        <label>Descripción evento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>E01</fullName>
                </value>
                <value>
                    <fullName>E02</fullName>
                </value>
                <value>
                    <fullName>E03</fullName>
                </value>
                <value>
                    <fullName>E04</fullName>
                </value>
                <value>
                    <fullName>E11</fullName>
                </value>
                <value>
                    <fullName>E15</fullName>
                </value>
                <value>
                    <fullName>E16</fullName>
                </value>
                <value>
                    <fullName>E17</fullName>
                </value>
                <value>
                    <fullName>E18</fullName>
                </value>
                <value>
                    <fullName>E19</fullName>
                </value>
                <value>
                    <fullName>E20</fullName>
                </value>
                <value>
                    <fullName>E21</fullName>
                </value>
                <value>
                    <fullName>E22</fullName>
                </value>
                <value>
                    <fullName>E29</fullName>
                </value>
                <value>
                    <fullName>E37</fullName>
                </value>
                <value>
                    <fullName>E30</fullName>
                </value>
                <value>
                    <fullName>E31</fullName>
                </value>
                <value>
                    <fullName>E34</fullName>
                </value>
                <value>
                    <fullName>E32</fullName>
                </value>
                <value>
                    <fullName>E33</fullName>
                </value>
                <value>
                    <fullName>E36</fullName>
                </value>
                <value>
                    <fullName>E25</fullName>
                </value>
                <value>
                    <fullName>E26</fullName>
                </value>
                <value>
                    <fullName>E23</fullName>
                </value>
                <value>
                    <fullName>E24</fullName>
                </value>
                <value>
                    <fullName>E28</fullName>
                </value>
                <value>
                    <fullName>E35</fullName>
                </value>
                <value>
                    <fullName>E12</fullName>
                </value>
                <value>
                    <fullName>E111</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AB_SEL_Estado__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>En Curso</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Aprobado</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Rechazado</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AB_TXT_Descripcion__c</fullName>
        <label>Descripción</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AB_TXT_Observaciones__c</fullName>
        <label>Observaciones</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Propuesta de Abono</label>
    <nameField>
        <displayFormat>AB-{0000000}</displayFormat>
        <label>Abono</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propuestas de Abonos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_LKP_Recurso_Servicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Profesional (Perfil Técnico) vinculado a la Orden de Trabajo. Representa la FK al objeto ServiceResource. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto ServiceResource (ServiceResources.RSE_TXT_Codigo_Recurso__c): Código único del Profesional</description>
        <label>Profesional</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>ServiceResource.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Status</field>
                <operation>equals</operation>
                <value>Anulado, Anulado desde Inactivo, Cerrado, Cerrado Albarán Recibido, Cerrado Pdte. Albarán, Revisado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Órdenes de trabajo</relationshipLabel>
        <relationshipName>OTR_REL_Recurso_Servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Util_Propuesta_de_abono.cls
/**
 * Clase de funciones auxiliares relacionadas con el objeto personalizado Util_Propuesta_de_abono 
 * 
 * @author EVERIS
 * 
 */
public without sharing class Util_Propuesta_de_abono {



public static Map<Id,Propuesta_de_abono__c> queryMap_Propuesta_de_AbonoBy_EV_AB_LKP_Caso_Or_Orden_de_Trabajo_r_CaseId_And_PropEvEconomico_null_And_LKPAbono_null_And_EstadoNoAprobado_And_EstadoNoRechazado(set<Id> reclamacionIds){
    
        Map<Id,Propuesta_de_abono__c> mapa = new Map<Id,Propuesta_de_abono__c>();
        
        if(reclamacionIds != null && !reclamacionIds.isEmpty()){
            
            for(List<Propuesta_de_abono__c> lista : 
            [Select id from Propuesta_de_abono__c where (AB_LKP_Caso__c in :reclamacionIds
            or AB_LKP_Orden_de_Trabajo__r.CaseId in :reclamacionIds)
            and AB_SEL_Estado__c != :Label.EV_AB_ESTADO_APROBADO 
            and AB_SEL_Estado__c != :Label.EV_AB_ESTADO_RECHAZADO]) {
                
                mapa.putAll(lista);
            }
        }
        return mapa;
    }

public static Map<Id,Propuesta_de_abono__c> getPropuestaAbonoById(Set<Id> setId){
	
		Map<Id,Propuesta_de_abono__c> mapa = new Map<Id,Propuesta_de_abono__c>();
		
		if(setId != null && !setId.isEmpty()){
			for(List<Propuesta_de_abono__c> lista : 
			[SELECT Id 
				,AB_LKP_Ingresar_a__c//,AB_LKP_Cuenta__c
				,AB_DIV_Importe_a_ingresar__c//,AB_DIV_Importe_a_imputar__c
				,AB_TXT_Descripcion__c
				,AB_LKP_Caso__c
				,AB_LKP_Orden_de_Trabajo__c
				,AB_FOR_Direccion_Territorial__c
				,AB_LKP_Caso__r.CAS_LKP_Procedencia__r.PROC_SEL_Canal__c
				,AB_LKP_Caso__r.CAS_LKP_Procedencia__r.PROC_SEL_Subcanal__c
				,AB_LKP_Orden_de_Trabajo__r.WorkOrderNumber
				,AB_LKP_Caso__r.Type
				,AB_LKP_Caso__r.CAS_SEL_Grupo_Causa__c
				,AB_LKP_Caso__r.RecordTypeId
				,AB_LKP_Caso__r.CAS_LKP_Cliente_contable__c
				,AB_LKP_Orden_de_Trabajo__r.OTR_LKP_Recurso_Servicio__c
				,AB_LKP_Caso__r.CaseNumber
				,AB_LKP_Ingresar_a__r.CUE_TXT_Identificador__c//,AB_LKP_Cuenta__r.CUE_TXT_Identificador__c
				,AB_LKP_Caso__r.CAS_LKP_Compania__r.CUE_TXT_Identificador__c
				,AB_TXT_Observaciones__c
         		,AB_LKP_Factura__r.FAC_TXT_Numero_factura__c
				,AB_LKP_Cuenta__c
				,AB_DIV_Importe_a_Imputar__c
				,AB_LKP_Caso__r.CAS_LKP_Procedencia__r.PROC_TXT_Identificador__c
				FROM Propuesta_de_abono__c WHERE Id IN :setId]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}

	/**
	 * Método que te devuelve una lista con los abonos de un caso
	 *
	 * @param casoIds: set de ids de caso
	 * @return abonos por id caso
	 */
	public static Map<Id, List<Propuesta_de_abono__c>> pAbonosByCaso(Set<Id> casoIds){
		Map<Id, List<Propuesta_de_abono__c>> resultados = new Map<Id,List<Propuesta_de_abono__c>>();
		if(casoIds != null && !casoIds.isEmpty()) {
			List<Propuesta_de_abono__c> propAb = [Select Id,
													AB_CAS_Abono_Liquidado__c,
													AB_LKP_Orden_de_Trabajo__c,
													AB_LKP_Caso__c 
													from Propuesta_de_abono__c where AB_LKP_Caso__c in :casoIds];
			for(Propuesta_de_abono__c ab: propAb){
				List<Propuesta_de_abono__c> temp = resultados.get(ab.AB_LKP_Caso__c);
				if(temp == null)
					temp = new List<Propuesta_de_abono__c>();
					
				temp.add(ab);
				resultados.put(ab.AB_LKP_Caso__c,temp);
			}
		}
		return resultados;
	}

	/**
	 * Devuelve un mapa de propuestas de abono filtrado por un conjunto de ids de Ordenes de trabajo.
	 *
	 * @param setIdWos: ids de las ordenes de trabajo
	 * @return mapa de propuestas de abono filtradas
	 */
	public static Map<Id,Propuesta_de_abono__c> queryPropAbByWo(Set<Id> setIdWos){
		Map<Id,Propuesta_de_abono__c> mapa = new Map<Id,Propuesta_de_abono__c>();
		if(setIdWos != null && !setIdWos.isEmpty()){
			for (List<Propuesta_de_abono__c> lista : [SELECT Id,
													 AB_CAS_Abono_Liquidado__c,
													 AB_LKP_Orden_de_Trabajo__c 
													 FROM Propuesta_de_abono__c WHERE AB_LKP_Orden_de_Trabajo__c IN :setIdWos]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}

	/**
	 * Devuelve un mapa de propuestas de abono filtrado por un conjunto de ids de Abonos.
	 *
	 * @param setIdProp: ids de los abonos
	 * @return mapa de propuestas de abono filtradas
	 */
	public static Map<Id,Propuesta_de_abono__c> getPropAbByAbono(Set<Id> setIdProp){
		Map<Id,Propuesta_de_abono__c> mapa = new Map<Id,Propuesta_de_abono__c>();
		if(setIdProp != null && !setIdProp.isEmpty()){
			for (List<Propuesta_de_abono__c> lista : [SELECT 
                                                      Id, 
                                                      AB_CAS_Abono_Liquidado__c,
                                                      AB_SEL_Descripcion_evento__c,
                                                      AB_LKP_Caso__c,
                                                      AB_LKP_Orden_de_Trabajo__c
                                                      FROM Propuesta_de_Abono__c WHERE Id IN :setIdProp]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}
}