src/objects/Factura__c.object
<CustomObject>
    <fields>
        <fullName>FAC_CAS_Factura_de_Gestion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si la factura es en concepto de gestión si está a true</description>
        <label>Factura de Gestión</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FAC_CAS_IndicadorPagoFranquicia__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Representa si en la factura aplica Franquicia</description>
        <label>Indicador Pago Franquicia</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FAC_DAT_FechaFactura__c</fullName>
        <description>Fecha de expedición de la factura</description>
        <label>Fecha de Factura</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FAC_DIV_ImporteFactura__c</fullName>
        <description>Importe de la factura con Base imponible</description>
        <label>Importe de factura</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FAC_DIV_ImporteFranquicia__c</fullName>
        <label>Importe Franquicia</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FAC_DIV_RetencionPago__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Valor de la Retención del Pago (importe retenido) informada por el Facturador.</description>
        <label>Retencion Pago</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FAC_LKP_Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id del caso asociado a la factura</description>
        <label>Id Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Facturas</relationshipLabel>
        <relationshipName>Facturas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FAC_LKP_Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identificador de la cuenta asociada a la factura</description>
        <label>Id Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Facturas</relationshipLabel>
        <relationshipName>Facturas_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FAC_LKP_WorkOrkder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id de la orden de trabajo asociada a la factura.</description>
        <label>Id Servicio</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Facturas</relationshipLabel>
        <relationshipName>Facturas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FAC_NUM_Ano_Pago__c</fullName>
        <description>Año de emisión de la factura</description>
        <label>Año Pago</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FAC_NUM_ImporteFinal__c</fullName>
        <description>Importe de la factura con Base imponible</description>
        <label>Importe Final</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FAC_NUM_ImporteIVA__c</fullName>
        <description>Importe añadido por IVA</description>
        <label>ImporteIVA</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FAC_NUM_IndicadorQuincena__c</fullName>
        <description>Quincena de emisión de la factura</description>
        <label>Indicador Quincena</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FAC_NUM_MesPago__c</fullName>
        <description>Mes en el que se realiza el pago informado por el Facturador</description>
        <label>Mes Pago</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FAC_NUM_TotalImportes__c</fullName>
        <description>Importe del pago sin base imponible</description>
        <label>Total Importes</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FAC_POR_PorcentajeIVA__c</fullName>
        <description>Porcentaje de IVA informado por el Facturador</description>
        <label>Porcentaje IVA</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>FAC_TXT_Codigo_Capital__c</fullName>
        <label>Codigo Capital</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FAC_TXT_Numero_factura__c</fullName>
        <description>Número de factura informado por el Facturador</description>
        <label>Número de factura</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FAC_TXT_Tipo_Registro__c</fullName>
        <description>Tipo de Registro de Pagos enviado a la aseguradora.</description>
        <label>Tipo Registro</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Propuesta_de_Abono__c.object
<CustomObject>
    <fields>
        <fullName>AB_CAS_Abono_Liquidado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Abono Liquidado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AB_DAT_Fecha_Liquidacion__c</fullName>
        <label>Fecha Liquidación</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Orden_de_Trabajo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Número Servicio</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Propuesta de Abono</label>
    <nameField>
        <displayFormat>AB-{0000000}</displayFormat>
        <label>Abono</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propuestas de Abonos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Propuesta_de_Evento__c.object
<CustomObject>
    <description>Objeto utilizado para modelar el proceso de liquidación y/o facturación a profesionales, clientes y compañías aseguradoras</description>
    <fields>
        <fullName>EV_AB_CAS_Evento_Ab_Facturado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Evento Facturado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EV_AB_CAS_Evento_Ab_Liquidado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Evento Liquidado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EV_AB_DAT_Fecha_Facturacion__c</fullName>
        <label>Fecha Facturación</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EV_AB_DAT_Fecha_Liquidacion__c</fullName>
        <label>Fecha Liquidación</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EV_AB_LKP_Orden_de_Trabajo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Orden de Trabajo relacionada al Evento/Abono</description>
        <label>Número Servicio</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipName>EV_AB_REL_Orden_de_Trabajo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_AB_SEL_Descripcion__c</fullName>
        <label>Código</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GBL_SEL_Codigo_evento</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EV_AB_SEL_Tipo_de_Evento__c</fullName>
        <label>Tipo de Evento</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>EV_AB_SEL_Descripcion__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cobro</fullName>
                </value>
                <value>
                    <fullName>Pago</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Propuesta de Evento Económico</label>
    <nameField>
        <displayFormat>EV-{0000000}</displayFormat>
        <label>Evento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propuestas de Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_CAS_Orden_Trabajo_Facturada__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check que indica si la Work Order ha sido facturada</description>
        <label>Servicio Facturado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OTR_CAS_Orden_Trabajo_Liquidada__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check que indica si la Work Order ha sido liquidada</description>
        <label>Servicio Liquidado</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GBL_SEL_Codigo_evento.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>E01</fullName>
    </customValue>
    <customValue>
        <fullName>E02</fullName>
    </customValue>
    <customValue>
        <fullName>E03</fullName>
    </customValue>
    <customValue>
        <fullName>E04</fullName>
    </customValue>
    <customValue>
        <fullName>E05</fullName>
    </customValue>
    <customValue>
        <fullName>E06</fullName>
    </customValue>
    <customValue>
        <fullName>E11</fullName>
    </customValue>
    <customValue>
        <fullName>E12</fullName>
    </customValue>
    <customValue>
        <fullName>E15</fullName>
    </customValue>
    <customValue>
        <fullName>E16</fullName>
    </customValue>
    <customValue>
        <fullName>E17</fullName>
    </customValue>
    <customValue>
        <fullName>E18</fullName>
    </customValue>
    <customValue>
        <fullName>E19</fullName>
    </customValue>
    <customValue>
        <fullName>E20</fullName>
    </customValue>
    <customValue>
        <fullName>E21</fullName>
    </customValue>
    <customValue>
        <fullName>E22</fullName>
    </customValue>
    <customValue>
        <fullName>E23</fullName>
    </customValue>
    <customValue>
        <fullName>E24</fullName>
    </customValue>
    <customValue>
        <fullName>E25</fullName>
    </customValue>
    <customValue>
        <fullName>E26</fullName>
    </customValue>
    <customValue>
        <fullName>E27</fullName>
    </customValue>
    <customValue>
        <fullName>E28</fullName>
    </customValue>
    <customValue>
        <fullName>E29</fullName>
    </customValue>
    <customValue>
        <fullName>E30</fullName>
    </customValue>
    <customValue>
        <fullName>E31</fullName>
    </customValue>
    <customValue>
        <fullName>E32</fullName>
    </customValue>
    <customValue>
        <fullName>E33</fullName>
    </customValue>
    <customValue>
        <fullName>E34</fullName>
    </customValue>
    <customValue>
        <fullName>E35</fullName>
    </customValue>
    <customValue>
        <fullName>E36</fullName>
    </customValue>
    <masterLabel>Código de evento</masterLabel>
</GlobalValueSet>

src/classes/Rest_Fac_infoFacturas.cls
/**
 * Todo: Clase que se utilizará para exponer un servicio a SF para la inserción de Facturas.
 * @author everis
 * @version 1.0
 */
@RestResource(urlMapping='/facturador/factura/')
global without sharing class Rest_Fac_infoFacturas {
	private static Integer contParametros;
	public static String response ='';
	global class listaCasos{
		public String identificadorUnicoCaso;
		public listaCasos(String identificadorUnicoCaso){
			this.identificadorUnicoCaso = identificadorUnicoCaso;
			system.debug('>>>>>identificadorUnicoCaso: ' + identificadorUnicoCaso);
		}   
	}

	global class listaWO{
		public String identificadorUnicoOrdenTrabajo;
		public listaWO(String identificadorUnicoOrdenTrabajo){
			this.identificadorUnicoOrdenTrabajo = identificadorUnicoOrdenTrabajo;
			system.debug('>>>>>identificadorUnicoOrdenTrabajo: ' + identificadorUnicoOrdenTrabajo);
		}
	}
	@HttpPost
	global static void doPost(
			List<listaCasos> listaCasos,
			List<listaWO> listaWO,
			String identificadorUnicoCuentaProf,
			String identificadorUnicoCuentaClie,
			String identificadorUnicoEvento,
			String identificadorUnicoAbono,
			Integer anioFactura,
			Double importePago,
			Integer mesPago,
			Double retencionPago,
			String numeroFactura,
			Date fechaFactura,
			String codigoCapital,
			Double importeFranquicia,
			Double importeFinal, 
			Double importeIva,
			Integer porcentajeIva,
			Boolean indicadorFranquicia,
			String tipoRegistro,
			Integer indicadorQuincena,
			Double totalImporte,
			Boolean facturaGestion
			) {

		system.debug('>>>>>listaCasos: ' + listaCasos);
		system.debug('>>>>>listaWO: ' + listaWO);
		system.debug('>>>>>identificadorUnicoCuentaProf: ' + identificadorUnicoCuentaProf);
		system.debug('>>>>>identificadorUnicoCuentaClie: ' + identificadorUnicoCuentaClie);
		system.debug('>>>>>identificadorUnicoEvento: ' + identificadorUnicoEvento);
		system.debug('>>>>>identificadorUnicoAbono: ' + identificadorUnicoAbono);
		system.debug('>>>>>anioFactura: ' + anioFactura);
		system.debug('>>>>>importePago: ' + importePago);
		system.debug('>>>>>mesPago: ' + mesPago);
		system.debug('>>>>>retencionPago: ' + retencionPago);
		system.debug('>>>>>numeroFactura: ' + numeroFactura);
		system.debug('>>>>>fechaFactura: ' + fechaFactura);
		system.debug('>>>>>codigoCapital: ' + codigoCapital);
		system.debug('>>>>>importeFranquicia: ' + importeFranquicia);
		system.debug('>>>>>importeFinal: ' + importeFinal);
		system.debug('>>>>>importeIva: ' + importeIva);
		system.debug('>>>>>porcentajeIva: ' + porcentajeIva);
		system.debug('>>>>>indicadorFranquicia: ' + indicadorFranquicia);
		system.debug('>>>>>tipoRegistro: ' + tipoRegistro);
		system.debug('>>>>>indicadorQuincena: ' + indicadorQuincena);
		system.debug('>>>>>totalImporte: ' + totalImporte);
		system.debug('>>>>>facturaGestion: ' + facturaGestion);

		Rest_Fac_infoFacturas_RP respuesta = new Rest_Fac_infoFacturas_RP();
		Factura__c fac = new Factura__c();
		List<Factura__c> listFac = new List<Factura__c>();
		List<String> casosIds = new List<String>();
		List<String> wOIds = new List<String>();
		List<Case> casosToUpdate = new List<Case>();
		//List<WorkOrder> woToUpdate = new List<WorkOrder>();
		List<Propuesta_de_Abono__c> listaAbonos = new List<Propuesta_de_Abono__c>();
		List<Propuesta_de_Evento__c> listaEventos = new List<Propuesta_de_Evento__c>();
		Map<Id,WorkOrder> woToUpdate = new Map<Id,WorkOrder>();
		Set<Id> setIds = new Set<Id>();
		for(listaCasos casoId : listaCasos){
			if(casoId.identificadorUnicoCaso!= null && casoId.identificadorUnicoCaso != '')
				setIds.add((Id) casoId.identificadorUnicoCaso);
		}
		for(listaWO woId:listaWO){setIds.add((Id) woId.identificadorUnicoOrdenTrabajo);}
		Map<Id,Case> mapaCasos = Util_Caso.getCaseById(setIds);
		Map<Id,WorkOrder> mapaOTs = new Map<Id,WorkOrder>([SELECT Id,OTR_CAS_Orden_Trabajo_Facturada__c,CaseId,Case.RecordTypeId,Case.CAS_LKP_Compania__r.CUE_TXT_Identificador__c, RecordTypeId FROM WorkOrder WHERE Id IN : setIds AND RecordTypeId !=: Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_OTR_EN_REVISION)]);
		WorkOrder woAbono = new WorkOrder();
		WorkOrder woEvento = new WorkOrder();
		system.debug('>>>>>setIds: ' + setIds);
		system.debug('>>>>>verMapaOTs: ' + mapaOTs);
		Account cuentaClient = new Account();
		if(identificadorUnicoCuentaClie != null && identificadorUnicoCuentaClie!= ''){
			cuentaClient = ([SELECT RecordTypeId FROM Account WHERE Id =: identificadorUnicoCuentaClie]);
		}
		Propuesta_de_Evento__c evento = new Propuesta_de_Evento__c();
		Propuesta_de_Abono__c abono = new Propuesta_de_Abono__c();
		if(identificadorUnicoAbono != null && identificadorUnicoAbono != ''){
			abono = [SELECT Id, AB_LKP_Orden_de_Trabajo__r.Case.RecordTypeId FROM Propuesta_de_Abono__c WHERE id =: identificadorUnicoAbono];
		}


		//try{
			system.debug('>>>>>identificadorUnicoEventoTry: ' + identificadorUnicoEvento);
			system.debug('>>>>>EV_AB_SEL_Tipo_de_Evento__c: ' + evento.EV_AB_SEL_Tipo_de_Evento__c);
			if(identificadorUnicoEvento != null && identificadorUnicoEvento != '' && !facturaGestion){
				evento = ([SELECT EV_AB_SEL_Tipo_de_Evento__c
									,EV_AB_CAS_Evento_Ab_Facturado__c
									,EV_AB_CAS_Evento_Ab_Liquidado__c
									,EV_AB_DAT_Fecha_Facturacion__c
									,EV_AB_DAT_Fecha_Liquidacion__c
									,EV_AB_LKP_Orden_de_Trabajo__c FROM Propuesta_de_Evento__c WHERE Id =: identificadorUnicoEvento]);

				system.debug('>>>>>TipoDeEvento: ' + evento.EV_AB_SEL_Tipo_de_Evento__c);
				if(evento.EV_AB_SEL_Tipo_de_Evento__c == Label.TIPO_EVENTO_COBRO){
					evento.EV_AB_CAS_Evento_Ab_Facturado__c = true;
					evento.EV_AB_DAT_Fecha_Facturacion__c = system.now();
					update evento;
					woEvento = facturarServicioEvento(evento);
					woToUpdate.put(woEvento.Id,woEvento);
				} else if (evento.EV_AB_SEL_Tipo_de_Evento__c == Label.TIPO_EVENTO_PAGO){
					evento.EV_AB_CAS_Evento_Ab_Liquidado__c = true;
					evento.EV_AB_DAT_Fecha_Liquidacion__c = system.now();
					update evento;
					woEvento = liquidarServicioEvento(evento);
					woToUpdate.put(woEvento.Id,woEvento);
				}
				/*update evento;

				if(evento.EV_AB_SEL_Tipo_de_Evento__c == Label.TIPO_EVENTO_COBRO){
					woEvento = facturarServicioEvento(evento);
					woToUpdate.put(woEvento.Id,woEvento);
				} else if (evento.EV_AB_SEL_Tipo_de_Evento__c == Label.TIPO_EVENTO_PAGO){
					woEvento = liquidarServicioEvento(evento);
					woToUpdate.put(woEvento.Id,woEvento);
				}*/
			}

			system.debug('>>>>>identificadorUnicoAbono: ' + identificadorUnicoAbono);
			if(identificadorUnicoAbono != null && identificadorUnicoAbono != '' && !facturaGestion){
				abono.Id = identificadorUnicoAbono;
				abono.AB_CAS_Abono_Liquidado__c = true;
				abono.AB_DAT_Fecha_Liquidacion__c = system.today();
				update abono;
				if(abono.AB_LKP_Orden_de_Trabajo__c != null)
					woAbono = liquidarServicioAbono(abono);
					woToUpdate.put(woAbono.Id, woAbono);
					system.debug('>>>>>verMapaWoToUpdate: ' + woToUpdate);
			}

			List<WorkOrder> listaCaseId = new List<WorkOrder>();
			List<WorkOrder> listaOTByCaseId = new List<WorkOrder>();

			if(setIds != null && (!setIds.isEmpty())){
				listaCaseId = ([SELECT CaseId FROM WorkOrder WHERE Id IN :setIds]);
				List<Id> listaID = new List<Id>();
				for(WorkOrder cs:listaCaseId){
					listaID.add(cs.CaseId);
				}
				listaOTByCaseId = ([SELECT Id, OTR_CAS_Orden_Trabajo_Facturada__c, OTR_CAS_Orden_Trabajo_Liquidada__c, CaseId, Case.RecordTypeId
							FROM WorkOrder WHERE CaseId IN :listaID AND RecordTypeId = :Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CAS_B2C)]);	
			}

			List<WorkOrder> lista = new List<WorkOrder>();
			Map<Id, List<WorkOrder>> mapaOT = new Map<Id, List<WorkOrder>>();
	        if(setIds != null && (!setIds.isEmpty())){
	            lista = ([SELECT Id,
	                        CaseId,
	                        OTR_CAS_Orden_Trabajo_Facturada__c,
	                        OTR_CAS_Orden_Trabajo_Liquidada__c,
	                        Case.CAS_CAS_Liquidado__c,
	                        Case.CAS_CAS_Siniestro_Facturado__c
	                 FROM WorkOrder WHERE CaseId IN :setIds
	                 AND RecordTypeId = :Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CAS_B2C)]);
	            for(WorkOrder registro : lista){
	                List<WorkOrder> listaAux = mapaOT.get(registro.CaseId);
	                if(listaAux == null){
	                    listaAux = new List<WorkOrder>();
	                }
	                listaAux.add(registro);
	                mapaOT.put(registro.CaseId, listaAux);
	            }
	        }

			List<Id> idCaso = new List<Id>();
			for(WorkOrder ls:lista){
				idCaso.add(ls.CaseId);
				system.debug('>>>>>ls.CaseId: ' + ls.CaseId);
			}

			List<Case> siniestros = new List<Case>([SELECT Id, CAS_CAS_Siniestro_Facturado__c, CAS_CAS_Liquidado__c FROM Case WHERE Id IN :idCaso]);

			for(Case caso:siniestros){
				if(mapaOT != null && !mapaOT.isEmpty()){
					List<WorkOrder> ListWO = mapaOT.get(caso.Id);
					caso.CAS_CAS_Siniestro_Facturado__c = true;
					caso.CAS_CAS_Liquidado__c = true;
					for(WorkOrder wo:ListWO){
						system.debug('>>>>>verWoId: ' + wo.Id);
						if(wo.OTR_CAS_Orden_Trabajo_Facturada__c == false){
							caso.CAS_CAS_Siniestro_Facturado__c = false;
						}
						if(wo.OTR_CAS_Orden_Trabajo_Liquidada__c == false){
							caso.CAS_CAS_Liquidado__c = false;
						}
					}
					casosToUpdate.add(caso);
				}
			}

			for(listaCasos casoId:listaCasos){
				fac = new Factura__c();
				//marco check facturado //Pendiente ver si borrar el if de aquí y marcar check de facturado en otro sitio
				if(mapaCasos.get(casoId.identificadorUnicoCaso)!=null && (identificadorUnicoCuentaClie != null && identificadorUnicoCuentaClie != '') && !facturaGestion){
					system.debug('>>>>>DentroFacturarSiniestro');
					mapaCasos.get(casoId.identificadorUnicoCaso).CAS_CAS_Siniestro_Facturado__c = true;
					if(!casosToUpdate.contains(mapaCasos.get(casoId.identificadorUnicoCaso))){
						casosToUpdate.add(mapaCasos.get(casoId.identificadorUnicoCaso));
					}
				}
				fac.FAC_LKP_Caso__c = casoId.identificadorUnicoCaso;
				if(identificadorUnicoCuentaClie != '')
					fac.FAC_LKP_Cuenta__c = identificadorUnicoCuentaClie;
				if(identificadorUnicoCuentaProf != '')
					fac.FAC_LKP_Cuenta__c = identificadorUnicoCuentaProf; 
				fac.FAC_NUM_Ano_Pago__c = anioFactura; 
				fac.FAC_DIV_ImporteFactura__c = importePago;
				fac.FAC_NUM_MesPago__c = mesPago;
				fac.FAC_DIV_RetencionPago__c = retencionPago;
				fac.FAC_TXT_Numero_Factura__c = numeroFactura;
				fac.FAC_DAT_FechaFactura__c = fechaFactura;
				fac.FAC_TXT_Codigo_Capital__c = codigoCapital;
				fac.FAC_DIV_ImporteFranquicia__c = importeFranquicia;
				fac.FAC_NUM_ImporteFinal__c = importeFinal;
				fac.FAC_NUM_ImporteIVA__c = importeIva;
				fac.FAC_POR_PorcentajeIVA__c = porcentajeIva;
				fac.FAC_CAS_IndicadorPagoFranquicia__c = indicadorFranquicia;
				fac.FAC_TXT_Tipo_Registro__c = tipoRegistro;
				fac.FAC_NUM_IndicadorQuincena__c = indicadorQuincena;
				fac.FAC_NUM_TotalImportes__c = totalImporte;
				fac.FAC_CAS_Factura_de_Gestion__c = facturaGestion;
				listFac.add(fac);
			}

			List<Id> casosFacturados = new List<Id>();
			for(listaCasos csId:listaCasos){
				if((csId.identificadorUnicoCaso != null) && (identificadorUnicoCuentaClie != null) && (
				cuentaClient.RecordTypeId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CUE_CLIENTEB2B_2) ||
				cuentaClient.RecordTypeId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CUE_CLIENTE_ASEGURADO) ||
				cuentaClient.RecordTypeId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CUE_CLIENTE_PARTICULAR)) && !facturaGestion){
					system.debug('>>>>>DentroFacturarCaso');
					mapaCasos.get(csId.identificadorUnicoCaso).CAS_CAS_Siniestro_Facturado__c = true;
					if(!casosToUpdate.contains(mapaCasos.get(csId.identificadorUnicoCaso)))
						casosToUpdate.add(mapaCasos.get(csId.identificadorUnicoCaso));
				}

				if((csId.identificadorUnicoCaso != null) && (identificadorUnicoCuentaProf != null && identificadorUnicoCuentaProf != '') && !facturaGestion){
					mapaCasos.get(csId.identificadorUnicoCaso).CAS_CAS_Liquidado__c= true;
					if(!casosToUpdate.contains(mapaCasos.get(csId.identificadorUnicoCaso)))
						casosToUpdate.add(mapaCasos.get(csId.identificadorUnicoCaso));
				}
			}

			if(!facturaGestion){
				update woToUpdate.values();
				system.debug('>>>>>woToUpdate: ' + woToUpdate);
				update casosToUpdate;
				system.debug('>>>>>casosToUpdate: ' + casosToUpdate);
			}


			List<WorkOrder> WOcasoFacLiq = new List<WorkOrder>([SELECT Id, OTR_CAS_Orden_Trabajo_Facturada__c, Case.CAS_CAS_Siniestro_Facturado__c , OTR_CAS_Orden_Trabajo_Liquidada__c, Case.CAS_CAS_Liquidado__c, Case.RecordTypeId
																	FROM WorkOrder 
																	WHERE (Case.CAS_CAS_Siniestro_Facturado__c = true AND OTR_CAS_Orden_Trabajo_Facturada__c = false)
																	OR (Case.CAS_CAS_Liquidado__c = true AND OTR_CAS_Orden_Trabajo_Liquidada__c = false)]);

			system.debug('>>>>>WOcasoFacLiq: ' + WOcasoFacLiq);
			for(WorkOrder wo:WOcasoFacLiq){
				system.debug('>>>>>wo.Id: ' + wo.Id);
				if(wo.Case.CAS_CAS_Siniestro_Facturado__c){
					wo.OTR_CAS_Orden_Trabajo_Facturada__c = true;
				}
				if(wo.Case.CAS_CAS_Liquidado__c){
					wo.OTR_CAS_Orden_Trabajo_Liquidada__c = true;
				}
				woToUpdate.put(wo.Id,wo);
			}

			for(listaWO woId:listaWO){

				fac = new Factura__c();
				fac.FAC_LKP_WorkOrkder__c = woId.identificadorUnicoOrdenTrabajo;
				if(identificadorUnicoCuentaClie != '')
					fac.FAC_LKP_Cuenta__c = identificadorUnicoCuentaClie;
				if(identificadorUnicoCuentaProf != '')
					fac.FAC_LKP_Cuenta__c = identificadorUnicoCuentaProf;   
				if(identificadorUnicoEvento != '')
				fac.FAC_NUM_Ano_Pago__c = anioFactura; 
				fac.FAC_DIV_ImporteFactura__c = importePago;
				fac.FAC_NUM_MesPago__c = mesPago;
				fac.FAC_DIV_RetencionPago__c = retencionPago;
				fac.FAC_TXT_Numero_Factura__c = numeroFactura;
				fac.FAC_DAT_FechaFactura__c = fechaFactura;
				fac.FAC_TXT_Codigo_Capital__c = codigoCapital;
				fac.FAC_DIV_ImporteFranquicia__c = importeFranquicia;
				fac.FAC_NUM_ImporteFinal__c = importeFinal;
				fac.FAC_NUM_ImporteIVA__c = importeIva;
				fac.FAC_POR_PorcentajeIVA__c = porcentajeIva;
				fac.FAC_CAS_IndicadorPagoFranquicia__c = indicadorFranquicia;
				fac.FAC_TXT_Tipo_Registro__c = tipoRegistro;
				fac.FAC_NUM_IndicadorQuincena__c = indicadorQuincena;
				fac.FAC_NUM_TotalImportes__c = totalImporte;
				fac.FAC_CAS_Factura_de_Gestion__c = facturaGestion;
				listFac.add(fac);

				WorkOrder woFACT = mapaOTs.get(fac.FAC_LKP_WorkOrkder__c);
				system.debug('>>>>>woFACT: ' + woFACT);
				system.debug('>>>>>cuentaClient.RecordTypeId: ' + cuentaClient.RecordTypeId);
				system.debug('>>>>>cuentaClient: ' + cuentaClient.Id);


				/*Cuando se recibe una factura de una Orden de Trabajo dirigida a una cuenta con RecordType Cliente B2B Secundario, Cliente Asegurado o Cliente
				Particular, con el campo Factura de Gestión sin marcar (FAC_CAS_Factura_de_Gestion__c = false), se registra el Servicio como Facturado*/
				if((cuentaClient.RecordTypeId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CUE_CLIENTEB2B_2) ||
				cuentaClient.RecordTypeId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CUE_CLIENTE_ASEGURADO) ||
				cuentaClient.RecordTypeId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CUE_CLIENTE_PARTICULAR)) && !facturaGestion){
					woFACT.OTR_CAS_Orden_Trabajo_Facturada__c = true;
					woToUpdate.put(woFACT.Id,woFACT);
				}

				/*Cuando se recibe una factura de una Orden de Trabajo dirigida a un profesional, se registra el Servicio como Liquidado */
				if(identificadorUnicoCuentaProf != null && identificadorUnicoCuentaProf != ''){
					woFACT.OTR_CAS_Orden_Trabajo_Liquidada__c = true;
					woToUpdate.put(woFACT.Id,woFACT);
				}
			}           

			system.debug('>>>>>facturaInsertada preUpsert: '+listFac);
			upsert listFac;
			system.debug('>>>>>facturaInsertada postUpsert: '+listFac);
			List<String> idFact = new List<String>();
			for(Factura__c aux:listFac){
				idFact.add(aux.id);
			}

			respuesta.listaFacturas = idFact;

			//Actualizo casos y WO
			update casosToUpdate;
			system.debug('>>>>>casosToUpdate: ' + casosToUpdate);
			//update woToUpdate;
			system.debug('>>>>>woToUpdate: ' + woToUpdate);
			system.debug('>>>>>woToUpdate.size(): ' + woToUpdate.size());

			system.debug('@@@Contiene nulos: ' + woToUpdate.containsKey(null));
			for (Id key : woToUpdate.keySet()) {
				system.debug('>>>>>verWO: ' + woToUpdate.get(key).Id);
			}

			if(!facturaGestion)
				update woToUpdate.values();
				system.debug('>>>>>woToUpdate: ' + woToUpdate);

			//Genero movimientos
			system.debug('response: '+response);
			for(Case c : casosToUpdate){
				if(Util_Siniestro.esSiniestro(c)){
					Util_Movimientos.compruebaEnviable(c.Id,c.CAS_LKP_Compania__r.CUE_TXT_Identificador__c,'99');
					Util_Movimientos.compruebaEnviable(c.Id,c.CAS_LKP_Compania__r.CUE_TXT_Identificador__c,'98');
				}
			}

			system.debug('>>>>>verMapaWoToUpdate: ' + woToUpdate);

			for(Id key : woToUpdate.keySet()){
				WorkOrder woUtilMov = woToUpdate.get(key);
				system.debug('>>>>>woUtilMovId: ' + woUtilMov);
				system.debug('>>>>>woUtilMov.CaseId: ' + woUtilMov.CaseId);
				system.debug('>>>>>woUtilMov.Case.RecordTypeId: ' + woUtilMov.Case.RecordTypeId);
				Case caso = new Case(RecordTypeId = woUtilMov.Case.RecordTypeId);
				if(Util_Siniestro.esSiniestro(caso)){
					Util_Movimientos.compruebaEnviable(woUtilMov.CaseId,woUtilMov.Case.CAS_LKP_Compania__r.CUE_TXT_Identificador__c,'99',woUtilMov.Id);
					Util_Movimientos.compruebaEnviable(woUtilMov.CaseId,woUtilMov.Case.CAS_LKP_Compania__r.CUE_TXT_Identificador__c,'98',woUtilMov.Id);
				}
			}

			//respuesta.listaFacturas = idFact;
			respuesta.success = 'true';
			respuesta.errors = '';
			respuesta.listaFacturas = idFact;   
			response += '{"code":"FAC-001", "message":"Operación ejecutada correctamente","listaFacturas":[';
			contParametros = 0;
			for(String aux:idFact){
				if(contParametros != 0){response += '}';}
				concatenarParametroJSON('id',aux);
			}
			response += '}]}';
			system.debug(respuesta);
			system.debug('Factura Insertada: '+idFact); 
			system.debug('response: '+response);

		if (!test.isRunningTest()) {
			RestContext.response.addHeader('Content-Type', 'application/json');
			RestContext.response.responseBody = Blob.valueOf(response);
		}
	}

	private static void concatenarParametroJSON(String nombreParametro, String valorParametro)
	{
		if (valorParametro != null)
		{
			if (contParametros > 0) {response += ',';}
			response += '{"' + nombreParametro + '" : "' + valorParametro + '"';
			contParametros++;
		}else{
			if (contParametros > 0) {response += ',';}
			response += '{"' + nombreParametro + '" : ""';
			contParametros++;        	
		}
	}


	/*Cuando se recibe una factura de una Abono dirigida a una cuenta con RecordType Cliente B2B Secundario, Cliente Asegurado o Cliente Particular, 
	se registra el Abono como Liquidado (AB_CAS_Abono_Liquidado__c= true).*/
	public static WorkOrder liquidarServicioAbono(Propuesta_de_Abono__c abono){
		List<Propuesta_de_Abono__c> listaAbonos = new List<Propuesta_de_Abono__c>();
		listaAbonos = ([SELECT Id, AB_CAS_Abono_Liquidado__c FROM Propuesta_de_Abono__c WHERE AB_LKP_Orden_de_Trabajo__c =: abono.AB_LKP_Orden_de_Trabajo__c]);
		system.debug('>>>>>verListaAbonos: ' + listaAbonos);
		WorkOrder woAbono = new WorkOrder();
		woAbono = ([SELECT Id, CaseId, Case.RecordTypeId FROM WorkOrder WHERE Id =: abono.AB_LKP_Orden_de_Trabajo__c]);
		system.debug('>>>>>verWoAbono: ' + woAbono);
		if(woAbono.Case.RecordTypeId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CAS_RECLAMACION)){
			woAbono.OTR_CAS_Orden_Trabajo_Liquidada__c = true;
			for(Propuesta_de_Abono__c ab:listaAbonos){
				if(!ab.AB_CAS_Abono_Liquidado__c){
					woAbono.OTR_CAS_Orden_Trabajo_Liquidada__c = false;
				}
			}
		}
		system.debug('>>>>>verWoAbonoBeforeUpdate: ' + woAbono);
		//Devolvemos la WO para añadirla al mapa para su posterior actualización;
		return woAbono;
	}


	/*Cuando un Servicio que pertenece a una reclamación, tenga todos sus Eventos facturados a excepción del E111, se registrará el Servicio como
	facturado (OTR_CAS_Orden_Trabajo_Facturada__c = true)*/
	public static WorkOrder facturarServicioEvento(Propuesta_de_Evento__c evento){
		WorkOrder woEvento = new WorkOrder();

		List<Propuesta_de_Evento__c> listaEventos = new List<Propuesta_de_Evento__c>();
		listaEventos = ([SELECT Id,
								EV_AB_CAS_Evento_Ab_Facturado__c,
								EV_AB_DAT_Fecha_Facturacion__c,
								EV_AB_LKP_Orden_de_Trabajo__c,
								EV_AB_SEL_Descripcion__c,
								EV_AB_SEL_Tipo_de_Evento__c
								FROM Propuesta_de_Evento__c WHERE EV_AB_LKP_Orden_de_Trabajo__c =: evento.EV_AB_LKP_Orden_de_Trabajo__c]);

		system.debug('>>>>>verListaEventos: ' + listaEventos);
		woEvento = ([SELECT Id, CaseId, Case.RecordTypeId FROM WorkOrder WHERE Id =: evento.EV_AB_LKP_Orden_de_Trabajo__c]);
		system.debug('>>>>>verWoEventoFacturar: ' + woEvento);
		if(woEvento.Case.RecordTypeId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CAS_RECLAMACION)){
			woEvento.OTR_CAS_Orden_Trabajo_Facturada__c = true;
			for(Propuesta_de_Evento__c ev:listaEventos){
				system.debug('>>>>>DentroFor');
				system.debug('>>>>>verEvento: ' + ev);
				if(!ev.EV_AB_CAS_Evento_Ab_Facturado__c && ev.EV_AB_SEL_Descripcion__c  != Label.AB_DESCRIPCION_IMP_GESTOR && ev.EV_AB_SEL_Tipo_de_Evento__c == Label.TIPO_EVENTO_COBRO){
					system.debug('>>>>>DentroIF');
					woEvento.OTR_CAS_Orden_Trabajo_Facturada__c = false;
				}
			}
		}

		system.debug('>>>>>verWOEvento: ' + woEvento);
		return woEvento;
	}


	/*Cuando un Servicio que pertenece a una reclamación, tenga todos sus Eventos liquidados a excepción del E111, se registrará el Servicio como
	liquidado (OTR_CAS_Orden_Trabajo_Liquidada__c= true)*/
	public static WorkOrder liquidarServicioEvento(Propuesta_de_Evento__c evento){
		WorkOrder woEvento = new WorkOrder();
		
		List<Propuesta_de_Evento__c> listaEventos = new List<Propuesta_de_Evento__c>();
		listaEventos = ([SELECT Id,
								EV_AB_CAS_Evento_Ab_Liquidado__c,
								EV_AB_DAT_Fecha_Liquidacion__c,
								EV_AB_LKP_Orden_de_Trabajo__c,
								EV_AB_SEL_Descripcion__c,
								EV_AB_SEL_Tipo_de_Evento__c
								FROM Propuesta_de_Evento__c WHERE EV_AB_LKP_Orden_de_Trabajo__c =: evento.EV_AB_LKP_Orden_de_Trabajo__c]);

		system.debug('>>>>>verListaEventos: ' + listaEventos);
		woEvento = ([SELECT Id, CaseId, Case.RecordTypeId FROM WorkOrder WHERE Id =: evento.EV_AB_LKP_Orden_de_Trabajo__c]);
		system.debug('>>>>>verWoEventoLiquidar: ' + woEvento);
		if(woEvento.Case.RecordTypeId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CAS_RECLAMACION)){
			system.debug('>>>>>EsReclamacion');
			woEvento.OTR_CAS_Orden_Trabajo_Liquidada__c = true;
			for(Propuesta_de_Evento__c ev:listaEventos){
				system.debug('>>>>>evento: ' + ev);
				if(!ev.EV_AB_CAS_Evento_Ab_Liquidado__c && ev.EV_AB_SEL_Descripcion__c != Label.AB_DESCRIPCION_IMP_GESTOR && ev.EV_AB_SEL_Tipo_de_Evento__c == Label.TIPO_EVENTO_PAGO){
					system.debug('>>>>>DentroIf');
					woEvento.OTR_CAS_Orden_Trabajo_Liquidada__c = false;
				}
			}
		}
		system.debug('>>>>>Label.AB_DESCRIPCION_IMP_GESTOR: ' + Label.AB_DESCRIPCION_IMP_GESTOR);
		system.debug('>>>>>woEvento: ' + woEvento);
		system.debug('>>>>>listaEventos: ' + listaEventos);
		return woEvento;
	}

}