src/objects/Factura__c.object
<CustomObject>
    <fields>
        <fullName>FAC_TXT_Numero_factura__c</fullName>
        <description>Número de factura informado por el Facturador</description>
        <label>Número de factura</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_TRG_ContentDocumentLink.cls
@isTest
public without sharing class Test_TRG_ContentDocumentLink extends TestSetup{
	@isTest static void testTRG(){
		ContentVersion cv = new ContentVersion();
		cv.Title = 'CV';
		cv.PathOnClient = 'Home_1430x650.jpg';
		cv.VersionData = EncodingUtil.base64Decode('YQ==');
		insert cv;
		List<ContentVersion> listaCV = [SELECT ContentDocumentId FROM ContentVersion LIMIT 1];
		Factura__c factura = new Factura__c();
		factura.FAC_TXT_Numero_factura__c = '2';
		insert factura;
		ContentDocumentLink cdl = new ContentDocumentLink();
		cdl.ContentDocumentId = listaCV.get(0).ContentDocumentId;
		cdl.LinkedEntityId = factura.Id;
		cdl.ShareType = 'V';
		insert cdl;
	}
}