src/objects/Festivos__c.object
<CustomObject>
    <label>Festivo</label>
    <nameField>
        <label>Festivo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Festivos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FSL__Scheduling_Policy__c.object
<CustomObject>
    <label>Scheduling Policy</label>
    <nameField>
        <label>Scheduling Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduling Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>CSE_CAS_Asignada__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asignada</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Asignar_Como_Franquiciado__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campos casilla para identificar si en la cita de servicio se tiene que asignar como franquiciado</description>
        <label>Asignar como franquiciado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Asignar_Mizad__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asignar como Mizad</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Asignar_como_Urgencias__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asignar como Red Urgencias</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Asignar_territorio_prim_no_franq__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campos casilla para identificar si en la cita de servicio se tiene que asignar como territorio no franquiciado</description>
        <label>Asignar territorio prim no franquiciado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Comprobado_Horario__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Comprobado Horario</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Crear_cita_app__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Crear cita app</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Urgente__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check que indica si la cita es urgente o no</description>
        <label>Urgente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_DAT_Fecha_Proxima_Programacion__c</fullName>
        <label>Fecha Próxima Programación</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSE_DAT_Fecha_Ultima_Programacion__c</fullName>
        <label>Fecha Última Programación</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSE_NUM_Numero_de_Ofrecimientos__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Numero de Ofrecimientos</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FSL__Auto_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Schedule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Emergency__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Emergency</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__InJeopardy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Jeopardy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__IsFillInCandidate__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Fill In Candidate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__IsMultiDay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is MultiDay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Pinned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pinned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Prevent_Geocoding_For_Chatter_Actions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prevent Geocoding For Chatter Actions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Same_Day__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same Day</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Same_Resource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same Resource</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Schedule_Mode__c</fullName>
        <label>Schedule Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Automatic</fullName>
                </value>
                <value>
                    <fullName>Optimization</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FSL__Scheduling_Policy_Used__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scheduling Policy Used</label>
        <referenceTo>FSL__Scheduling_Policy__c</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FSL__UpdatedByOptimization__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UpdatedByOptimization</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Virtual_Service_For_Chatter_Action__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Virtual Service For Chatter Action (SLR)</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>FSL__IsFillInCandidate__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Fill In Candidate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FSL__Prevent_Geocoding_For_Chatter_Actions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prevent Geocoding For Chatter Actions</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_CaptureSignature.cls
@isTest
public without sharing class Test_CaptureSignature {
	public static FSL__Scheduling_Policy__c scheduling{get; set;}
	public static ServiceAppointment serviceApp{get; set;}
	private static Account compania {get; set;}
	private static Account cuentaPrincipal {get; set;}
	private static Account asegurada {get; set;}
	private static Account cuenta {get; set;}
	private static Tipo_Producto_CIA__c tipoProductoCIA {get; set;}
    private static Producto_CIA__c productoCIA {get; set;}
	private static ServiceContract poliza {get; set;}
	private static Case caso {get; set;}
	private static WorkType tipoTrabajo {get; set;}
	private static WorkOrder ordenTrabajo {get;set;}
	private static Festivos__c festivo {get; set;}
	private static OperatingHours horaFuncionamiento {get; set;}
	private static ServiceTerritory territorioServicio {get; set;}
	private static String tipoFirma {get;set;}
	
    private static void inicializarVariables(){
    	Baipas.establecerVariableControl();
    	scheduling = Util_Tests.crearPolitica('Política de Asignación – Geolocalización');
		insert scheduling;
		compania = Util_Tests.crearCuentaCompania('SegurCaixa','1018','X1234567X');
    	insert compania;
    	cuentaPrincipal = Util_Tests.crearCuentaB2BPpal('B2BPrincipal','1019','X1134567X');
    	insert cuentaPrincipal;
    	asegurada = Util_Tests.crearCuentaB2BSec('Asegurado','1020',cuentaPrincipal.Id,'X1114567X');
    	cuenta = Util_Tests.crearCuentaB2BSec('SegurCaixa1','1021',cuentaPrincipal.Id,'X1111567X');
    	tipoProductoCIA = Util_Tests.crearTipoProductoCIA('SegurCaixa - HOGAR','01',compania.ID);
        insert tipoProductoCIA;
        productoCIA = Util_Tests.crearProductoCIA('KIT 107','12345678',tipoProductoCIA.Id);
        insert productoCIA;
		ServiceContract poliza = Util_Tests.crearPolizaContrato('Alberto', asegurada.Id, cuentaPrincipal.Id, productoCIA.Id);
        insert poliza;
        caso = Util_Tests.crearCasoB2B(poliza.Id, cuenta.Id, compania.Id);
        insert caso;
        tipoTrabajo = Util_Tests.crearTipoTrabajo('Tipo de Trabajo por Defecto', '51', 5.30);
        insert tipoTrabajo;
        ordenTrabajo = Util_Tests.crearOrdenTrabajo('0000000739','01',tipoTrabajo.Id,caso.Id);
        insert ordenTrabajo;
    	
    	List<ServiceAppointment> listCit = [SELECT Id,ParentRecordId FROM ServiceAppointment WHERE ParentRecordId = :ordenTrabajo.Id];
		system.debug('cita creada automaticamente al crear un workorder '+listCit);
		delete listCit;
		
		datetime mydate = system.today() + 1;
        datetime newDate = mydate.addHours(2);
        //Datetime myDateTime = Datetime.newInstance(2018, 02, 19);
        Datetime myDateTime = Datetime.newInstance(2018, 03,06,12,10,10);
		Datetime dueDate = myDateTime.addDays(2);
        //Datetime arrivalDate = myDateTime.addDays(-2);
        Datetime arrivalDate = myDateTime;
        Datetime arrivalStartDate = arrivalDate.addDays(-15);
	   	serviceApp = Util_Tests.crearCitaServicio('Madrid','España','','','',myDateTime,dueDate);
	   
        
        serviceApp.CreatedById = system.UserInfo.getUserId();
        serviceApp.ArrivalWindowEndTime = arrivalDate;
        serviceApp.ArrivalWindowStartTime = arrivalDate;
        serviceApp.CSE_CAS_Asignada__c = false;
        serviceApp.CSE_CAS_Asignar_como_Urgencias__c = false;
        serviceApp.CSE_CAS_Asignar_territorio_prim_no_franq__c = false;
        serviceApp.CSE_CAS_Asignar_Como_Franquiciado__c = false;
        serviceApp.CSE_CAS_Asignar_Mizad__c = false;
        serviceApp.CSE_CAS_Comprobado_Horario__c = false;
        serviceApp.CSE_CAS_Crear_cita_app__c = false;
        serviceApp.CSE_CAS_Urgente__c = false;
        serviceApp.CSE_NUM_Numero_de_Ofrecimientos__c = 1.0;
        serviceApp.Duration = 2;
        serviceApp.DurationType = 'Hours';
        serviceApp.FSL__Auto_Schedule__c = false;
        serviceApp.FSL__Emergency__c = false;
        serviceApp.FSL__InJeopardy__c = false;
        serviceApp.FSL__InternalSLRGeolocation__Latitude__s = 40.381038;
        serviceApp.FSL__InternalSLRGeolocation__Longitude__s = 	-3.734841;
        serviceApp.FSL__IsFillInCandidate__c = true;
        serviceApp.FSL__IsMultiDay__c = false;
        serviceApp.FSL__Pinned__c = false;
        serviceApp.FSL__Prevent_Geocoding_For_Chatter_Actions__c = false;
        serviceApp.FSL__Same_Day__c = false;
        serviceApp.FSL__Same_Resource__c = false;
        serviceApp.FSL__Schedule_Mode__c = 'Automatic';
        serviceApp.FSL__Scheduling_Policy_Used__c = scheduling.Id;
        serviceApp.FSL__UpdatedByOptimization__c = false;
        serviceApp.FSL__Virtual_Service_For_Chatter_Action__c = false;
        serviceApp.GeocodeAccuracy = 'Zip';
        serviceApp.Latitude = 40.38096;
        serviceApp.Longitude = -3.73376;
        serviceApp.CSE_DAT_Fecha_Proxima_Programacion__c = system.today() +2;
        serviceApp.CSE_DAT_Fecha_Ultima_Programacion__c = system.today() +1;
        serviceApp.status = 'Pte. de asignar';
        serviceApp.ParentRecordId = ordenTrabajo.Id;
    	
    	horaFuncionamiento = Util_Tests.crearHoraFuncionamiento('Horario','Europe/Paris');
        insert horaFuncionamiento;
        territorioServicio = Util_Tests.crearTerritorioServicio('28001 MADRID',horaFuncionamiento.Id,'28001');
        territorioServicio.IsActive=true;
        insert territorioServicio;
        serviceApp.ServiceTerritoryId=territorioServicio.Id;
        festivo = Util_Tests.crearFestivo('Nacional',territorioServicio.Id,Date.newInstance(2018, 3, 08));
        insert festivo;
    	insert serviceApp;
    	tipoFirma = 'Firma';
    	Baipas.deshabilitarVariableControl();
    }
    @isTest static void test1(){
		inicializarVariables();
		Test.startTest();
		PageReference pageRef = Page.CaptureSignature;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('idCita',serviceApp.Id);
        ApexPages.currentPage().getParameters().put('idOrdenTrabajo',ordenTrabajo.Id);
        ApexPages.currentPage().getParameters().put('tipoFirma',tipoFirma);
        CaptureSignature pagina = new CaptureSignature();
		
		Test.stopTest();
    }
    @isTest static void test2(){
		inicializarVariables();
		Test.startTest();
		CaptureSignature.saveSignature('cuerpo',serviceApp.Id,'nombreArchivo');
		
		Test.stopTest();
    }
}