src/objects/Festivos__c.object
<CustomObject>
    <fields>
        <fullName>FES_TXT_Identificador__c</fullName>
        <description>Identificador único del Festivo</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Festivo</label>
    <nameField>
        <label>Festivo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Festivos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TRG_Handler_Festivo.cls
/**
  * Clase handler del trigger del Trigger TRG_Festivo.
  * 
  * @author EVERIS
  */
public without sharing class TRG_Handler_Festivo {
    
	public static void tratamientoBefore(Map<Id, Festivos__c> triggerNewMap, List<Festivos__c> triggerNew, 
			Map<Id, Festivos__c> triggerOldMap, List<Festivos__c> triggerOld){
				if(trigger.isInsert){
					
					for(Festivos__c festivo : triggerNew){
						if(festivo.FES_TXT_Identificador__c == null){
							Long timestamp = datetime.now().getTime();
							festivo.FES_TXT_Identificador__c = String.valueOf(timestamp);
						}
					}
				}
			}
	
}