src/objects/FSL__Scheduling_Policy__c.object
<CustomObject>
    <label>Scheduling Policy</label>
    <nameField>
        <label>Scheduling Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduling Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Procedencia__c.object
<CustomObject>
    <description>Representa cada una de las procedencias de una Compañía/Cliente B2B.</description>
    <fields>
        <fullName>PROC_SEL_Motivos_rechazo_presupuesto__c</fullName>
        <label>Motivos rechazo presupuesto</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Motivo_rechazo_presupuesto</valueSetName>
        </valueSet>
    </fields>
    <label>Procedencia</label>
    <nameField>
        <label>Código de Procedencia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>CSE_CAS_Asignar_Mizad__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asignar como Mizad</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_CAS_Urgente__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check que indica si la Orden de Trabajo es urgente.</description>
        <label>Urgente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OTR_DAT_Fecha_Primera_Cita__c</fullName>
        <description>Fecha de la primera visita del profesional a la situación de riesgo del asegurado.</description>
        <label>Fecha de Primera Cita</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OTR_SEL_Rango_Primera_Cita__c</fullName>
        <label>Hora de Primera Cita</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Rango_2_Horas</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Rango_2_Horas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>00:00 - 02:00</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02:00 - 04:00</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>04:00 - 06:00</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>06:00 - 08:00</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>08:00 - 10:00</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>10:00 - 12:00</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>12:00 - 14:00</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>14:00 - 16:00</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>16:00 - 18:00</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>18:00 - 20:00</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>20:00 - 22:00</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>22:00 - 00:00</label>
    </customValue>
    <description>Intervalos de 2 horas pares.</description>
    <masterLabel>Rango 2 Horas</masterLabel>
</GlobalValueSet>

src/globalValueSets/Motivo_rechazo_presupuesto.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Rechazo por precio alto</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>No disponible gremio</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Otros</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Avería de un tercero</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>No hay averia</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Atencion al cliente</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Seguimiento de asistencia</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Telefono erroneo</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Error en tramitacion</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>No se puede reparar</label>
    </customValue>
    <masterLabel>Motivo rechazo presupuesto</masterLabel>
</GlobalValueSet>

src/classes/Test_ReservarCitaUrgente.cls
@isTest
public without sharing class Test_ReservarCitaUrgente {

    private static Account compania;
    private static Account cuenta;
    private static Tipo_Producto_CIA__c tipoProducto;
    private static Producto_CIA__c producto;
    private static ServiceContract sv;
    private static Case caso;
    private static Procedencia__c procedencia;
    private static WorkOrder wo;
    private static WorkType tipoTrabajo;
    
    @isTest static void ReservarCitaUrgente(){
        Test.startTest();
    	compania = Util_Tests.crearCuentaCompania('compania', '1018','X1234567X');
        compania.Type = '01';
        
        //compania.CUE_TXT_Numero_Documento__c = 'A1234567';
		insert compania;
        
		cuenta = Util_Tests.crearCuentaB2BPpal('cuenta', '1458','X1134567X');
        cuenta.CUE_LKP_Cuenta_principal__c = compania.Id;
        cuenta.Type = '01';
		insert cuenta;

        
		tipoProducto = Util_Tests.crearTipoProductoCIA('tipo', '01', compania.Id);
		insert tipoProducto;
        
		producto = Util_Tests.crearProductoCIA('producto', '292', tipoProducto.Id);
		insert producto;
        
		sv = Util_Tests.crearPolizaContrato('poliza', compania.Id, cuenta.Id, producto.Id);
        insert sv;
        procedencia = Util_Tests.crearProcedencia(0.0, 0.0, 0.0, 0.0, 0.0, cuenta.Id, '545687', 'CAS_Solicitud_de_Servicio_B2B_B2B2C;CAS_Servicio_B2B_B2B2C');
        procedencia.PROC_SEL_Motivos_rechazo_presupuesto__c = '09;07;02;08;06;21;03;01';
        insert procedencia;
        
            caso = Util_Tests.crearCasoB2B(sv.Id, cuenta.Id, compania.Id);
            caso.CAS_SEL_Encuestador__c = 'Servitelco';
            caso.CAS_LKP_Compania__c = compania.Id;
            caso.CAS_EMA_Solicitud_Email__c = 'sera@sera.com';        
            caso.CAS_LKP_Procedencia__c = procedencia.Id;
            caso.CreatedDate = system.now();
        	caso.CAS_TXT_DirRiesgo_CP__c = '28001';
            caso.Status = '993';
            insert caso;
            
            caso.Status = '001';
            update caso;
            
            tipoTrabajo = Util_Tests.crearTipoTrabajo('Tipo de Trabajo por Defecto', '01', 120.0);
            insert tipoTrabajo;
        
         FSL__Scheduling_Policy__c sched = new FSL__Scheduling_Policy__c();
        sched.Name = 'Política de Asignación – Geolocalización';
        insert sched;
        
        
        User newUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        system.runAs(newUser){
            wo = Util_Tests.crearOrdenTrabajo('0000000545','01',tipoTrabajo.Id,caso.Id);
        	wo.OTR_DAT_Fecha_Primera_Cita__c = system.today();
        	wo.OTR_SEL_Rango_Primera_Cita__c = '07';
        	wo.OTR_CAS_Urgente__c = true;
            wo.PostalCode = '28001';
        	insert wo;
            system.debug(wo.status + ' Workorder nada mas insertada en el test');
           List<ServiceAppointment> listaSAs = [SELECT ArrivalWindowStartTime, ArrivalWindowEndTime, CSE_CAS_Asignar_Mizad__c, postalCode FROM ServiceAppointment WHERE ParentRecordId =: wo.Id AND Status = 'Pte. de asignar'];
            ServiceAppointment sa = listaSAs.get(0);
            sa.CSE_CAS_Asignar_Mizad__c = true;
            sa.PostalCode = '28001';
            update sa;
            system.debug(sa + ' Workorder despues de updatear el serviceAppoinment');
            

            ReservarCitaUrgente.reservaCita(wo.Id);
        }
        Test.stopTest();
    }
}