src/objects/Garantia_Poliza__c.object
<CustomObject>
    <fields>
        <fullName>GPOL_LKP_Garantia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Garantía</label>
        <referenceTo>Garantia__c</referenceTo>
        <relationshipLabel>Garantías Póliza</relationshipLabel>
        <relationshipName>Garantias_Poliza</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Garantía Póliza</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantías Póliza</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <fields>
        <fullName>PRD_LKP_Tipo_Producto_CIA__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Tipo de Producto CIA al que pertenece el producto. Representa la FK al objeto Tipo_Producto_CIA_c. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External Id del objeto Tipo_Producto_CIA_c (Tipo_Producto_CIA_c .TPR_TXT_Identificador__c): Código único del Tipo de Producto</description>
        <label>Tipo de Producto CIA</label>
        <referenceTo>Tipo_Producto_CIA__c</referenceTo>
        <relationshipLabel>Compañía: Productos</relationshipLabel>
        <relationshipName>Compania_Productos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRD_TXT_Cod_Producto__c</fullName>
        <description>Código del producto para la cía</description>
        <label>Codigo Producto</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>POL_LKP_Compania__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Compañía asociada a la póliza</description>
        <label>Compañía</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>POL_REL_Compania</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POL_LKP_Producto_Cia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Producto asociado a la póliza</description>
        <label>Producto</label>
        <referenceTo>Producto_CIA__c</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>POL_REL_Producto</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POL_LKP_Version_Actual__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versión Actual</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Version_ContratoServicio__c.POLV_LKP_PolizaContrato__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Version_ContratoServicio__c</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>Contratos_de_servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POL_TXT_Cliente_Ensura__c</fullName>
        <description>Código del cliente en Ensura. Es necesario almacenarlo a nivel de póliza pues el valor nos llega a CRM desde la integración con VESTA de Consulta de Pólizas. Se utiliza para una integración de información posterior con Ensura para informarle de los clientes no Robinson.</description>
        <label>Cliente Ensura</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Version_ContratoServicio__c.object
<CustomObject>
    <description>Representa cada una de las versiones de una Póliza o Contrato.</description>
    <fields>
        <fullName>POLV_CAS_Activa__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Activa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>POLV_CAS_Corresponde_a_HomeServe__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campo que representa si la gestión de la póliza/contrato de un cliente asegurado corresponde a HomeServe</description>
        <label>Corresponde a HomeServe</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>POLV_CAS_IsGold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>VESTA nos indica si la póliza de RGA es o no Oro con este campo</description>
        <label>Póliza Oro RGA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>POLV_DAT_FechaFin__c</fullName>
        <description>Fecha de finalización</description>
        <label>Fecha de finalización</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POLV_DAT_FechaInicio__c</fullName>
        <description>Fecha de inicio</description>
        <label>Fecha de inicio</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POLV_DAT_Fecha_Alta_CIA__c</fullName>
        <description>Fecha/hora de alta para CIA</description>
        <label>Fecha de alta para CIA</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>POLV_DIV_Capital_Contenido__c</fullName>
        <description>Capital contenido</description>
        <label>Capital Contenido</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>POLV_DIV_Capital_Continente__c</fullName>
        <description>Capital continente</description>
        <label>Capital Continente</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>POLV_DIV_Capital_Objetos__c</fullName>
        <description>Capital objetos</description>
        <label>Capital Objetos</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>POLV_DIV_Importe_Franquicia__c</fullName>
        <description>Importe franquicia</description>
        <label>Importe Franquicia</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>POLV_FOR_Activo__c</fullName>
        <formula>POLV_LKP_PolizaContrato__r.POL_LKP_Version_Actual__c = Id</formula>
        <label>Versión Activa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>POLV_FOR_Cod_Segmentacion__c</fullName>
        <formula>IF( POLV_LKP_PolizaContrato__r.POL_LKP_Compania__r.CUE_TXT_Identificador__c == $Label.IDE_SEGURCAIXA , 
IF( POLV_TXT_VIPCompany__c == &apos;A&apos; || POLV_TXT_VIPCompany__c == &apos;P&apos;|| POLV_TXT_VIPCompany__c == &apos;S&apos;,&apos;03&apos;, 
IF ( POLV_TXT_VIPCompany__c == &apos;B&apos; || POLV_TXT_VIPCompany__c == &apos;F&apos;,&apos;02&apos;, 
IF ( POLV_TXT_VIPCompany__c == &apos;N&apos;,&apos;01&apos;,&apos;01&apos;) 
) 
), 

IF( POLV_LKP_PolizaContrato__r.POL_LKP_Compania__r.CUE_TXT_Identificador__c == $Label.IDE_RGA, 
IF( POLV_CAS_IsGold__c == true , 
&apos;04&apos;, 
IF( POLV_LKP_PolizaContrato__r.POL_LKP_Compania__r.CUE_TXT_Identificador__c == $Label.IDE_NATIONALE_NETHERLANDEN, 
IF( POLV_LKP_PolizaContrato__r.POL_LKP_Producto_Cia__r.PRD_TXT_Cod_Producto__c == &apos;PH6&apos;, 
&apos;05&apos;, 
&apos;01&apos;) 
,&apos;01&apos;) 
) 
,&apos;01&apos;))</formula>
        <label>Segmentación (Código)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLV_LKP_PolizaContrato__c</fullName>
        <label>Póliza/Contrato</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Versiones Póliza/Contrato</relationshipLabel>
        <relationshipName>Versiones_Poliza_Contrato</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>POLV_NUM_Control_SegurCaixa__c</fullName>
        <description>Número que identifica si la póliza debe ser atendida por HomeServe u por otra compañía</description>
        <label>Control SegurCaixa</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>POLV_NUM_Superficie_Garaje__c</fullName>
        <description>Superficie garaje</description>
        <label>Superficie garaje</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>POLV_NUM_Superficie_Trastero__c</fullName>
        <description>Superficie trastero</description>
        <label>Superficie trastero</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>POLV_NUM_Superficie_Vivienda__c</fullName>
        <description>Superficie vivienda</description>
        <label>Superficie vivienda</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>POLV_NUM_Tipo_Transferencia__c</fullName>
        <description>Tipo de transferencia</description>
        <label>Tipo de transferencia</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>POLV_SEL_Estado_Provincia__c</fullName>
        <description>Provincia</description>
        <label>Provincia</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Provincias</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>POLV_SEL_Idioma__c</fullName>
        <description>Idioma</description>
        <label>Idioma</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Idiomas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>POLV_SEL_Pais__c</fullName>
        <description>País</description>
        <label>País</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Paises</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>POLV_SEL_Tipo_Riesgo__c</fullName>
        <description>Representa la tipología de Dirección de Riesgo dónde la póliza ampara al asegurado. El tipo de Riesgo influye en el árbol de decisión de apertura.</description>
        <label>Tipo de riesgo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipos_de_Riesgo</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>POLV_TXT_Calle__c</fullName>
        <description>Vía/Domicilio</description>
        <label>Vía/Domicilio</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>POLV_TXT_Certificado__c</fullName>
        <description>Certificado</description>
        <label>Certificado</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLV_TXT_Cod_Delegacion__c</fullName>
        <description>Código de Delegación</description>
        <label>Código de Delegación</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLV_TXT_Cod_Sucursal__c</fullName>
        <description>Código de Sucursal</description>
        <label>Código de Sucursal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLV_TXT_Codigo_Cliente_ING__c</fullName>
        <description>Código Cliente ING</description>
        <label>Código Cliente ING</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLV_TXT_Codigo_Gestor_CIA__c</fullName>
        <description>Código Gestor</description>
        <label>Código Gestor</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLV_TXT_Codigo_Postal__c</fullName>
        <description>Código  Postal</description>
        <label>Código  Postal</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLV_TXT_Datos_Vivienda__c</fullName>
        <description>Datos de la vivienda</description>
        <label>Datos de la vivienda</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLV_TXT_Poblacion__c</fullName>
        <description>Población</description>
        <label>Población</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLV_TXT_Suplemento_Poliza__c</fullName>
        <description>Suplemento en la póliza</description>
        <label>Suplemento en la póliza</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLV_TXT_Tipo_Divisa__c</fullName>
        <description>Tipo de divisa</description>
        <label>Tipo de divisa</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLV_TXT_Tipo_Reg_Vivienda__c</fullName>
        <description>Tipo de régimen de vivienda</description>
        <label>Tipo de régimen de vivienda</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POLV_TXT_VIPCompany__c</fullName>
        <description>Código Segmentación SegurCaixa</description>
        <label>Código Segmentación SegurCaixa</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Versión Póliza/Contrato</label>
    <nameField>
        <label>Versión Póliza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versiones Póliza/Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Idiomas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <default>true</default>
        <label>Castellano</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Catalán</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Desconocido</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Euskera</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Gallego</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Francés</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Alemán</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Italiano</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Resto</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Portugués</label>
    </customValue>
    <masterLabel>Idiomas</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Paises.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ES</fullName>
        <default>true</default>
        <label>España</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
        <label>Bélgica</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croacia</label>
    </customValue>
    <customValue>
        <fullName>CY</fullName>
        <label>Chipre</label>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
        <label>República Checa</label>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
        <label>Dinamarca</label>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
        <label>Estonia</label>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
        <label>Finlandia</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>Francia</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Alemania</label>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
        <label>Grecia</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungría</label>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
        <label>Irlanda</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italia</label>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
        <label>Letonia</label>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
        <label>Lituania</label>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
        <label>Luxemburgo</label>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
        <label>Malta</label>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
        <label>Países Bajos</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Polonia</label>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
        <label>Portugal</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Rumanía</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Eslovaquia</label>
    </customValue>
    <customValue>
        <fullName>SI</fullName>
        <label>Eslovenia</label>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
        <label>Suecia</label>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
        <label>Reino Unido</label>
    </customValue>
    <description>Listados de países de Europa</description>
    <masterLabel>Países</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Tipos_de_Riesgo.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>COMERCIO</fullName>
    </customValue>
    <customValue>
        <fullName>COMUNIDAD</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAL ALQUILADO</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAL EN PROPIEDAD</fullName>
    </customValue>
    <customValue>
        <fullName>OFICINAS Y DESPACHOS</fullName>
    </customValue>
    <customValue>
        <fullName>PISO</fullName>
    </customValue>
    <customValue>
        <fullName>PYMES</fullName>
    </customValue>
    <customValue>
        <fullName>VIVIENDA UNIFAMILIAR</fullName>
    </customValue>
    <masterLabel>Tipos de Riesgo</masterLabel>
</GlobalValueSet>

src/classes/Util_Poliza_Contrato.cls
/**
 * Clase de funciones auxiliares relativas a las Pólizas.
 * 
 * @author EVERIS
 * 
 */
public without sharing class Util_Poliza_Contrato {

	/**
	 * Devuelve las polizas filtrando por las Cuentas y las Compañías.
	 *
	 * @param setCuenta: conjunto de IDs de Cuentas
	 * @param setName: conjunto de nombres de Compañías
	 *
	 * @return mapa que contiene las polizas encontradas
	 */
	public static Map<Id, ServiceContract> queryPolizaByAccountIdAndCompania(Set<Id> setCuenta, Set<String> setName) {
		Map<Id, ServiceContract> mapa=new Map<Id, ServiceContract>();
		if(!setName.isEmpty() && !setCuenta.isEmpty()) {
			mapa = new Map<Id, ServiceContract>(
				[SELECT Id,
						AccountId,
						Name,
						POL_LKP_Compania__c,
						POL_LKP_Compania__r.CUE_TXT_Identificador__c,
						POL_LKP_Compania__r.CUE_CAS_No_Permite_Servicio_B2C__c,
						POL_LKP_Compania__r.Name,
						POL_LKP_Producto_Cia__r.PRD_TXT_Cod_Producto__c,
						POL_LKP_Version_Actual__r.Name
				 FROM ServiceContract
				 WHERE AccountId IN :setCuenta
				 AND POL_LKP_Compania__r.CUE_TXT_Identificador__c IN :setName]);
		}
		return mapa;
	}

	/**
	 * Devuelve las polizas filtrando por el nombre y las Compañías.
	 *
	 * @param setName: conjunto de nombres de Polizas
	 * @param setCompania: conjunto de nombres de Compañías
	 *
	 * @return mapa que contiene las polizas encontradas
	 */
	public static Map<Id, ServiceContract> queryPolizaByNameAndCompania(Set<String> setName, Set<Id> setCompania) {
		Map<Id, ServiceContract> mapa = new Map<Id, ServiceContract>();
		if(!setName.isEmpty() && !setCompania.isEmpty()){
			mapa = new Map<Id, ServiceContract>(
				[SELECT Id, 
						AccountId,
						Name,
						POL_LKP_Compania__c,
						POL_LKP_Compania__r.CUE_TXT_Identificador__c,
						POL_LKP_Compania__r.CUE_CAS_No_Permite_Servicio_B2C__c,
						POL_LKP_Compania__r.Name,
						POL_LKP_Producto_Cia__c,
						POL_LKP_Producto_Cia__r.Name,
						POL_LKP_Producto_Cia__r.PRD_LKP_Tipo_Producto_CIA__r.TPR_SEL_TiposRiesgo_Seleccionables__c,
						POL_LKP_Producto_Cia__r.PRD_TXT_Cod_Producto__c,
						POL_LKP_Version_Actual__c,
						POL_LKP_Version_Actual__r.name
				 FROM ServiceContract
				 WHERE Name IN :setName
				 AND POL_LKP_Compania__c IN :setCompania]);
		}
		return mapa;
	}
	
	/**
	* Obtiene un mapa de las polizas por el accountID que tienen cliente ensura informado
	*
	* @param setAccountId
	*
	* @return mapa de polizas coincidentes
   **/
	public static Map<Id, ServiceContract> queryPolizaByAccountAndEnsuraNotNull(Set<Id> setAccountId){
		Map<Id, ServiceContract> mapa = new Map<Id, ServiceContract>();
		if(setAccountId != null && !setAccountId.isEmpty()){
			mapa = new Map<Id, ServiceContract>(
				[SELECT Id, 
						AccountId,
						Name,
						POL_LKP_Compania__c,
						POL_LKP_Compania__r.CUE_TXT_Identificador__c,
						POL_LKP_Compania__r.CUE_CAS_No_Permite_Servicio_B2C__c,
						POL_LKP_Compania__r.Name,
						POL_LKP_Producto_Cia__c,
						POL_LKP_Producto_Cia__r.Name,
						POL_LKP_Producto_Cia__r.PRD_LKP_Tipo_Producto_CIA__r.TPR_SEL_TiposRiesgo_Seleccionables__c,
						POL_LKP_Producto_Cia__r.PRD_TXT_Cod_Producto__c,
                 		POL_TXT_Cliente_Ensura__c
				 FROM ServiceContract
				 WHERE AccountId IN :setAccountId
				 AND POL_TXT_Cliente_Ensura__c != null]);
		}
		return mapa;
	}
	
		/**
	* Obtiene un mapa de las polizas por el campo Name
	* 
	* @param setNames
	*
	* @return mapa de polizas coincidentes
   **/
	public static Map<Id, ServiceContract> queryPolizaByName(Set<String> setNames) {
		Map<Id, ServiceContract> mapa = new Map<Id, ServiceContract>();
		if(setNames != null && !setNames.isEmpty()) {
			mapa = new Map<Id, ServiceContract>(
				[SELECT Id,
						POL_LKP_Compania__r.Name,
						POL_LKP_Compania__r.CUE_EMA_Email__c,
						POL_LKP_Version_Actual__r.POLV_TXT_Calle__c,
						POL_LKP_Version_Actual__r.POLV_TXT_Codigo_Postal__c,
						POL_LKP_Version_Actual__r.POLV_SEL_Estado_Provincia__c,
						POL_LKP_Version_Actual__r.POLV_TXT_Poblacion__c,
						AccountId,
						Account.Name,
						POL_LKP_Version_Actual__r.POLV_CAS_Corresponde_a_HomeServe__c,
						POL_LKP_Version_Actual__r.Name,
						POL_LKP_Version_Actual__r.POLV_SEL_Tipo_Riesgo__c,
						startDate,
						POL_LKP_Producto_Cia__r.PRD_LKP_Tipo_Producto_CIA__r.TPR_SEL_Interlocutores_Autorizados__c,
						Name
				 FROM ServiceContract
				 WHERE Name IN :setNames]);
		}
		return mapa;
	}
	

	public static Map<Id, ServiceContract> queryPolizaById(Set<Id> setId) {
		Map<Id, ServiceContract> mapa = new Map<Id, ServiceContract>();
		if(setId != null && !setId.isEmpty()) {
			mapa = new Map<Id, ServiceContract>(
				[SELECT Id, 
						AccountId,
						Account.Name,
						Account.CUE_EMA_Email__c,
						Account.CUE_TXT_Numero_Documento__c,
						ContactId,
						Name,
						POL_LKP_Compania__c,
						POL_LKP_Compania__r.CUE_TXT_Identificador__c,
						POL_LKP_Compania__r.CUE_CAS_No_Permite_Servicio_B2C__c,
						POL_LKP_Compania__r.Name,
						POL_LKP_Producto_Cia__c,
						POL_LKP_Producto_Cia__r.Name,
						POL_LKP_Producto_Cia__r.PRD_LKP_Tipo_Producto_CIA__r.TPR_SEL_TiposRiesgo_Seleccionables__c,
						POL_LKP_Producto_Cia__r.PRD_LKP_Tipo_Producto_CIA__r.TPR_SEL_Interlocutores_Autorizados__c,
						POL_LKP_Producto_Cia__r.PRD_LKP_Tipo_Producto_CIA__r.TPR_SEL_Interlocutores_Seleccionables__c,				 
						POL_LKP_Producto_Cia__r.PRD_TXT_Cod_Producto__c,
						POL_LKP_Version_Actual__r.Name,
						POL_LKP_Version_Actual__r.POLV_SEL_Estado_Provincia__c,
						POL_LKP_Version_Actual__r.POLV_CAS_Corresponde_a_HomeServe__c,
						POL_LKP_Version_Actual__r.POLV_SEL_Idioma__c,
						POL_LKP_Version_Actual__r.POLV_SEL_Pais__c,
						POL_LKP_Version_Actual__r.POLV_SEL_Tipo_Riesgo__c,
						POL_LKP_Version_Actual__r.POLV_TXT_Calle__c,
						POL_LKP_Version_Actual__r.POLV_TXT_Codigo_Postal__c,
						POL_LKP_Version_Actual__r.POLV_TXT_Poblacion__c,
						POL_LKP_Version_Actual__r.POLV_CAS_IsGold__c
				 FROM ServiceContract
				 WHERE Id IN :setId]);
		}
		return mapa;
	}

	
	public static Map<Id, Version_ContratoServicio__c> queryVersionPoliza(Set<Id> setId) {
		Map<Id, Version_ContratoServicio__c> mapa = new Map<Id, Version_ContratoServicio__c>();
		if(setId != null && !setId.isEmpty()) {
			mapa = new Map<Id, Version_ContratoServicio__c>(
				[SELECT Id,
						Name,
						POLV_CAS_Activa__c,
						POLV_CAS_Corresponde_a_HomeServe__c,
						POLV_CAS_IsGold__c,
						POLV_DAT_Fecha_Alta_CIA__c,
						POLV_DAT_FechaFin__c,
						POLV_DAT_FechaInicio__c,
						POLV_DIV_Capital_Contenido__c,
						POLV_DIV_Capital_Continente__c,
						POLV_DIV_Capital_Objetos__c,
						POLV_DIV_Importe_Franquicia__c,
						POLV_FOR_Activo__c,
						POLV_LKP_PolizaContrato__c,
						POLV_NUM_Control_SegurCaixa__c,
						POLV_NUM_Superficie_Garaje__c,
						POLV_NUM_Superficie_Trastero__c,
						POLV_NUM_Superficie_Vivienda__c,
						POLV_NUM_Tipo_Transferencia__c,
						POLV_SEL_Estado_Provincia__c,
						POLV_SEL_Idioma__c,
						POLV_SEL_Pais__c,
						POLV_FOR_Cod_Segmentacion__c,
						POLV_SEL_Tipo_Riesgo__c,
						POLV_TXT_Calle__c,
						POLV_TXT_Certificado__c,
						POLV_TXT_Cod_Delegacion__c,
						POLV_TXT_Cod_Sucursal__c,
						POLV_TXT_Codigo_Cliente_ING__c,
						POLV_TXT_Codigo_Gestor_CIA__c,
						POLV_TXT_Codigo_Postal__c,
						POLV_TXT_Datos_Vivienda__c,
						POLV_TXT_Poblacion__c,
						POLV_TXT_Suplemento_Poliza__c,
						POLV_TXT_Tipo_Divisa__c,
						POLV_TXT_Tipo_Reg_Vivienda__c,
						POLV_TXT_VIPCompany__c
				 FROM Version_ContratoServicio__c
				 WHERE Id  IN :setId]);
		}
		return mapa;
	}
	

	/**
	 * Asocia una nueva póliza a un cliente
	 * 
	 * @param polizaSeleccionada póliza a crear
	 * @param idCliente cliente a asociar con la póliza
	 * @return objeto de tipo póliza
	 */ 
	public static ServiceContract nuevaPoliza(Callout_ConsultaPolizaVesta_RP polizaSeleccionada, Id idCliente){
		ServiceContract poliza = new ServiceContract();
		poliza.AccountId = idCliente;
		poliza.Name = polizaSeleccionada.numeroPoliza;		
		poliza.POL_LKP_Producto_Cia__c = polizaSeleccionada.idSFProducto;
		poliza.POL_LKP_Compania__c = polizaSeleccionada.idSFCompania;
		poliza.EndDate = Date.valueOf(polizaSeleccionada.fechaFinCobertura);
		poliza.StartDate = Date.valueOf(polizaSeleccionada.fechaInicioCobertura);
		return poliza;
	}
 
	/**
	 * Obtiene a partir de una póliza, un listado de opciones con los interlocutores seleccionables
	 * para el tipo de producto de la misma.
	 * 
	 * @param poliza
	 * @return lista de opciones del selector
	 */
	public static List<SelectOption> cargarSelectorTipoInterlocutor(ServiceContract poliza){
		List<SelectOption> listaSelOpt = new List<SelectOption>();
		listaSelOpt.add(new SelectOption('', '--Ninguno--'));
		DescribeSObjectResult obj = Schema.getGlobalDescribe().get('Case').getDescribe();
		DescribeFieldResult campo = obj.fields.getMap().get('CAS_SEL_Tipo_Interlocutor__c').getDescribe();
		if(poliza.POL_LKP_Producto_Cia__c != null && poliza.POL_LKP_Producto_Cia__r.PRD_LKP_Tipo_Producto_CIA__r.TPR_SEL_Interlocutores_Seleccionables__c != null){
			String seleccionables = poliza.POL_LKP_Producto_Cia__r.PRD_LKP_Tipo_Producto_CIA__r.TPR_SEL_Interlocutores_Seleccionables__c;
			if(seleccionables != null){
				seleccionables = ';' + seleccionables + ';';
				for(Schema.PicklistEntry valorPCK : campo.getPicklistValues()){
					if(seleccionables.contains(';' + valorPCK.getValue() + ';')){
						listaSelOpt.add(new SelectOption(valorPCK.getValue(), valorPCK.getLabel()));
					}
				}
			}
		}
		return listaSelOpt;
	} // FIN cargarSelectorTipoInterlocutor

	/**
	 * Obtiene a partir de una póliza, un listado de opciones con los tipos de riesgo seleccionables
	 * para el tipo de producto de la misma.
	 * 
	 * @param poliza
	 * @return lista de opciones del selector
	 */
	public static List<SelectOption> cargarSelectorTipoRiesgo(ServiceContract poliza, String seleccionables){
		List<SelectOption> listaSelOpt = new List<SelectOption>();
		listaSelOpt.add(new SelectOption('', '--Ninguno--'));
		DescribeSObjectResult obj = Schema.getGlobalDescribe().get('Version_ContratoServicio__c').getDescribe();
		DescribeFieldResult campo = obj.fields.getMap().get('POLV_SEL_Tipo_Riesgo__c').getDescribe();
		if(poliza.POL_LKP_Producto_Cia__c != null && poliza.POL_LKP_Producto_Cia__r.PRD_LKP_Tipo_Producto_CIA__r.TPR_SEL_TiposRiesgo_Seleccionables__c != null){
			seleccionables = poliza.POL_LKP_Producto_Cia__r.PRD_LKP_Tipo_Producto_CIA__r.TPR_SEL_TiposRiesgo_Seleccionables__c;
		}
		if(seleccionables != null){
			seleccionables = ';' + seleccionables + ';';
			for(Schema.PicklistEntry valorPCK : campo.getPicklistValues()){
				if(seleccionables.contains(';' + valorPCK.getValue() + ';')){
					listaSelOpt.add(new SelectOption(valorPCK.getValue(), valorPCK.getLabel()));
				}
			}
		}
		return listaSelOpt;
	} // FIN cargarSelectorTipoInterlocutor
	
	/**
	 * Obtiene a partir de una versión de una póliza, el listado de garantías asociadas
	 *
	 * @param setIdVersionPolizas
	 * @return mapa de garantias asociadas a pólizas
	 */
	public static Map<Id, Garantia_Poliza__c> queryGarantiasPolizaByPoliza(Set<Id> setIdVersionPolizas) {
		Map<Id, Garantia_Poliza__c> mapa = new Map<Id, Garantia_Poliza__c>();
		if(setIdVersionPolizas != null && !setIdVersionPolizas.isEmpty()) {
			mapa = new Map<Id, Garantia_Poliza__c>(
				[SELECT GPOL_LKP_Garantia__r.GAR_TXT_Codigo_Garantia__c
				 FROM Garantia_Poliza__c
				 WHERE GPOL_LKP_VersionPolizaContrato__r.POLV_LKP_PolizaContrato__c IN :setIdVersionPolizas]);
		}
		return mapa;
	}
	
	
	/**
	 * Obtiene a partir de un set de AccountIds, una lista de Contracts
	 *
	 *
	 * @param setAccountIds
	 * @return mapa de Contract asociadas a cuentas
	 */
	public static Map<Id, Contract> getContractByAccountId(Set<Id> setAccountIds) {
		Map<Id, Contract> mapa = new Map<Id, Contract>();
		if(!setAccountIds.isEmpty()) {
			for(List<Contract> listaContratosAux:
			[Select Id,
			  Status,
			  AccountId,
			  ContractNumber
			  FROM Contract WHERE AccountId IN :setAccountIds
			  ]) {
		 	   mapa.putAll(listaContratosAux);
	   		}
		}
		return mapa;
	}


	public static Version_ContratoServicio__c nuevaVersion(Callout_ConsultaPolizaVesta_RP polizaSeleccionada) {
		Version_ContratoServicio__c nuevaVersion = new Version_ContratoServicio__c(
			Name=polizaSeleccionada.identificadorVersion,
			POLV_DAT_FechaInicio__c = Date.valueOf(polizaSeleccionada.fechaInicioCobertura),
			POLV_DAT_FechaFin__c = Date.valueOf(polizaSeleccionada.fechaFinCobertura),		
			POLV_TXT_VIPCompany__c=polizaSeleccionada.VIPCompany,
			POLV_TXT_Calle__c = polizaSeleccionada.direccionRiesgoDomicilio,
			POLV_TXT_Poblacion__c = polizaSeleccionada.direccionRiesgoPoblacion,
			POLV_SEL_Estado_Provincia__c = polizaSeleccionada.direccionRiesgoCodProvincia,
			POLV_TXT_Codigo_Postal__c = polizaSeleccionada.direccionRiesgoCp,
			POLV_SEL_Pais__c = Label.PAIS_ESPANA,
			POLV_SEL_Idioma__c = polizaSeleccionada.idioma,
			POLV_DIV_Capital_Contenido__c = polizaSeleccionada.capitalContenido,
			POLV_DIV_Capital_Continente__c = polizaSeleccionada.capitalContinente,
			POLV_DIV_Capital_Objetos__c = polizaSeleccionada.capitalObjetos,
			POLV_TXT_Certificado__c = polizaSeleccionada.certificado,
			POLV_TXT_Cod_Delegacion__c = polizaSeleccionada.codigoDelegacion,
			POLV_TXT_Cod_Sucursal__c = polizaSeleccionada.codigoSucursal,
			POLV_TXT_Datos_Vivienda__c = polizaSeleccionada.datosVivienda,
			POLV_DAT_Fecha_Alta_CIA__c = polizaSeleccionada.fechaAltaCompania,
			POLV_CAS_IsGold__c = polizaSeleccionada.isGold,
			POLV_NUM_Superficie_Garaje__c = polizaSeleccionada.superficieGaraje,
			POLV_NUM_Superficie_Trastero__c = polizaSeleccionada.superficieTrastero,
			POLV_NUM_Superficie_Vivienda__c = polizaSeleccionada.superficieVivienda,
			POLV_TXT_Suplemento_Poliza__c = polizaSeleccionada.suplemento,
			POLV_TXT_Tipo_Divisa__c = polizaSeleccionada.tipoDivisa,
			POLV_TXT_Tipo_Reg_Vivienda__c = polizaSeleccionada.tipoRegimenVivienda,
			POLV_NUM_Tipo_Transferencia__c = polizaSeleccionada.tipoTransferencia,
			POLV_TXT_Codigo_Gestor_CIA__c = polizaSeleccionada.codigoGestor,
			POLV_TXT_Codigo_Cliente_ING__c = polizaSeleccionada.codigocliente,
			POLV_NUM_Control_SegurCaixa__c = polizaSeleccionada.controlDigitoSegurcaixa,
			POLV_CAS_Corresponde_a_HomeServe__c = polizaSeleccionada.perteneceHS
			);
		return nuevaVersion;
	} 
}