src/objects/Indemnizable_Documento__c.object
<CustomObject>
    <fields>
        <fullName>IND_LKP_Caso__c</fullName>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Documentos Indemnizable</relationshipLabel>
        <relationshipName>Documentos_Indemnizable</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IND_SEL_Estado__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Estados_Documento_Indemnizable</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IND_SEL_Tipo_Documento__c</fullName>
        <description>Tipo de Documento Indemnizable</description>
        <label>Tipo de Documento</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipos_de_Documento_Indeminizable</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IND_TXT_Descripcion__c</fullName>
        <label>Descripción</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Indemnizable: Documento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indemnizable: Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Indemnizable_Partida__c.object
<CustomObject>
    <fields>
        <fullName>INDP_DIV_Importe__c</fullName>
        <label>Importe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>INDP_LKP_Documento_Indemnizable__c</fullName>
        <label>Documento Indemnizable</label>
        <referenceTo>Indemnizable_Documento__c</referenceTo>
        <relationshipLabel>Partidas Indemnizable</relationshipLabel>
        <relationshipName>Indemnizable_Partidas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>INDP_SEL_Estado__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Estados_Partida_Indemnizable</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>INDP_TXT_Descripcion__c</fullName>
        <label>Descripción</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Indemnizable: Partida</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indemnizable: Partidas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <fields>
        <fullName>PRD_LKP_Tipo_Producto_CIA__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Tipo de Producto CIA al que pertenece el producto. Representa la FK al objeto Tipo_Producto_CIA_c. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External Id del objeto Tipo_Producto_CIA_c (Tipo_Producto_CIA_c .TPR_TXT_Identificador__c): Código único del Tipo de Producto</description>
        <label>Tipo de Producto CIA</label>
        <referenceTo>Tipo_Producto_CIA__c</referenceTo>
        <relationshipLabel>Compañía: Productos</relationshipLabel>
        <relationshipName>Compania_Productos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Profesional_Gremio__c.object
<CustomObject>
    <fields>
        <fullName>PRG_LKP_Cuenta_Profesional__c</fullName>
        <description>Cuenta del Profesional Contrato</description>
        <label>Cuenta del Profesional</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>La cuenta debe ser del Tipo de Registro: Profesional Contrato</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>CUE_Profesional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Profesional Gremios</relationshipLabel>
        <relationshipName>Gremios_Profesionales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PRG_NUM_Lim_OT_en_Curso__c</fullName>
        <description>Límite de Servicios en curso para el PR_GREMIO</description>
        <label>Límite de Servicios en curso</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRG_SEL_Gremio__c</fullName>
        <description>Gremio al que pertenece el profesional</description>
        <label>Gremio</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Gremios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PRG_TXT_Identificador__c</fullName>
        <description>Identificador del Profesional Gremio</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Profesional Gremio</label>
    <nameField>
        <label>Profesional Gremio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profesionales Gremio</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>POL_LKP_Compania__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Compañía asociada a la póliza</description>
        <label>Compañía</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>POL_REL_Compania</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POL_LKP_Producto_Cia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Producto asociado a la póliza</description>
        <label>Producto</label>
        <referenceTo>Producto_CIA__c</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>POL_REL_Producto</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceResource.object
<CustomObject>
    <fields>
        <fullName>RSE_LKP_Profesional_Gremio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relación con el objeto Profesional_Gremio</description>
        <label>Profesional Gremio</label>
        <referenceTo>Profesional_Gremio__c</referenceTo>
        <relationshipLabel>Recursos de servicios</relationshipLabel>
        <relationshipName>Recursos_de_servicios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSE_SEL_Gremio__c</fullName>
        <description>Gremio al que pertenece el profesional</description>
        <label>Gremio</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Gremios</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <fields>
        <fullName>TPR_SEL_Interlocutores_Autorizados__c</fullName>
        <description>Listado de Interlocutores Autorizados por la Compañía para ese tipo de producto</description>
        <label>Interlocutores Autorizados</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipos_Interlocutor</valueSetName>
        </valueSet>
    </fields>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_DAT_Fecha_cambio_estado__c</fullName>
        <description>Campo fecha que debe almacenar el último cambio de estado para controlar el semáforo visual. A completar en el trigger de creación/actualización (before) con el cambio de estado de la orden de trabajo.</description>
        <label>Fecha cambio estado</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OTR_LKP_Recurso_Servicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Profesional (Perfil Técnico) vinculado a la Orden de Trabajo. Representa la FK al objeto ServiceResource. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto ServiceResource (ServiceResources.RSE_TXT_Codigo_Recurso__c): Código único del Profesional</description>
        <label>Profesional</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>ServiceResource.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Status</field>
                <operation>equals</operation>
                <value>Anulado, Anulado desde Inactivo, Cerrado, Cerrado Albarán Recibido, Cerrado Pdte. Albarán, Revisado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Órdenes de trabajo</relationshipLabel>
        <relationshipName>OTR_REL_Recurso_Servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OTR_NUM_Horas_amarillo__c</fullName>
        <description>Campo numérico que almacena el número de horas que una orden de trabajo se considera en estado de semáforo “amarillo”. A completar en el trigger de creación/actualización (before) con el cambio de estado de la orden de trabajo en función de los datos almacenado en el custom metadata anterior</description>
        <label>Dias Amarillo</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OTR_NUM_Horas_verde__c</fullName>
        <description>Campo numérico que almacena el número de horas que una orden de trabajo se considera en estado de semáforo “verde”. A completar en el trigger de creación/actualización (before) con el cambio de estado de la orden de trabajo en función de los datos almacenado en el custom metadata anterior</description>
        <label>Dias Verde</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OTR_TXT_Num_OrdenTrabajo_HS__c</fullName>
        <description>Nº de Orden de Trabajo HomeServe. Identificador exclusivo de la Orden de Trabajo.</description>
        <externalId>true</externalId>
        <label>Nº de Servicio HS</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Estados_Documento_Indemnizable.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <default>true</default>
        <label>Pendiente</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>Recibido</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>Rechazado</label>
    </customValue>
    <masterLabel>Estados Documento Indemnizable</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Estados_Partida_Indemnizable.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <default>true</default>
        <label>Pendiente</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Aceptada</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Rechazada</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Tramitada</label>
    </customValue>
    <masterLabel>Estados Partida Indemnizable</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Tipos_Interlocutor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administrador de la Finca</fullName>
    </customValue>
    <customValue>
        <fullName>Agente</fullName>
    </customValue>
    <customValue>
        <fullName>Asegurado/a</fullName>
    </customValue>
    <customValue>
        <fullName>Empleado/a del negocio</fullName>
    </customValue>
    <customValue>
        <fullName>Hijo/a</fullName>
    </customValue>
    <customValue>
        <fullName>Inquilino</fullName>
    </customValue>
    <customValue>
        <fullName>Marido</fullName>
    </customValue>
    <customValue>
        <fullName>Padre</fullName>
    </customValue>
    <customValue>
        <fullName>Perito</fullName>
    </customValue>
    <customValue>
        <fullName>Portero</fullName>
    </customValue>
    <customValue>
        <fullName>Presidente</fullName>
    </customValue>
    <customValue>
        <fullName>Propietario</fullName>
    </customValue>
    <customValue>
        <fullName>Empleado de la sucursal</fullName>
    </customValue>
    <customValue>
        <fullName>Compañía</fullName>
    </customValue>
    <customValue>
        <fullName>Madre</fullName>
    </customValue>
    <customValue>
        <fullName>Mujer</fullName>
    </customValue>
    <customValue>
        <fullName>Pareja</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>Otros familiares</fullName>
    </customValue>
    <customValue>
        <fullName>Vecino/a</fullName>
    </customValue>
    <masterLabel>Tipos de Interlocutor</masterLabel>
</GlobalValueSet>

src/classes/Test_Sini_Indemn_Partidas.cls
/**
 * Clase de Test de la Clase controladora Sini_Sondeo
 * 
*/
@isTest
public without sharing class Test_Sini_Indemn_Partidas/* extends TestSetup*/{ 
	private static ServiceContract NuevaPoliza{get; set;}
	private static Case Nuevocaso {get; set;}
	public static SiniIndemnDocumentosController siniDocumentos  {get; set;}
	private static Account compania {get; set;}
	private static Account cuenta {get; set;}
	private static Account cuentaPrincipal {get; set;}
	private static Tipo_Producto_CIA__c  tipoProductoCIA {get; set;}
	private static Producto_CIA__c productoCIA {get; set;}
	private static WorkOrder OrdenTrabajo {get; set;}
	private static WorkType tipoTrabajo {get; set;}
	private static Indemnizable_Documento__c documentoIndem {get; set;}
	
	
	/**
	* Este metodo se encarga de realizar la carga de datos de static resources
	* 
	*/
	
	/*
	@testSetup
	public static void test(){
		TestSetup loadData = new Test_Sini_Indemn_Partidas();
		loadData.setTestData();
	}
	*/

	public static void InicializarVariables(){
		Baipas.establecerVariableControl();
		compania = Util_Tests.crearCuentaCompania('compania', '1018','X1234567X');
		compania.CUE_DIV_Limite_Actuacion__c = 2000.00;
		insert compania;
		cuentaPrincipal = Util_Tests.crearCuentaB2BPpal('B2BPrincipal','111019','X1134567X');
		cuentaPrincipal.Type = '01';
		insert cuentaPrincipal;
		cuenta = Util_Tests.crearCuentaB2BSec('Asegurado','101120',cuentaPrincipal.Id,'X1114567X');
		cuenta.CUE_LKP_Cliente_contable__c = cuentaPrincipal.Id;
		cuenta.Type = '01';
		insert cuenta;
		tipoProductoCIA = Util_Tests.crearTipoProductoCIA('SegurCaixa - HOGAR','01',compania.Id);
		system.debug('@@@@@@@@@@@ '+tipoProductoCIA);
		insert tipoProductoCIA;
		productoCIA = Util_Tests.crearProductoCIA('KIT 107','12345678',tipoProductoCIA.Id);
		insert productoCIA;
		NuevaPoliza = Util_Tests.crearPolizaContrato('4523814',cuentaPrincipal.Id,cuenta.Id,productoCIA.Id);
		insert NuevaPoliza;
		Nuevocaso = Util_Tests.crearCasoB2B(NuevaPoliza.Id, cuenta.id, cuentaPrincipal.Id);
		insert Nuevocaso;
		Account cuentaProfesional = Util_Tests.crearCuentaProfesionalContrato('PR123456','1020','X1114567X',cuenta.Id);
		//cuentaProfesional.CUE_SEL_Estado__c = '02';
		cuentaProfesional.CUE_LKP_Cuenta_principal__c = Null;
		cuentaProfesional.CUE_SEL_Tipo_de_Profesional__c = '01';
		insert cuentaProfesional;
		cuentaProfesional.CUE_SEL_Estado__c = '02';
		update cuentaProfesional;
		Profile perfil = [SELECT Id FROM Profile WHERE Name =: Label.PERFIL_ADMINISTRADOR];
		User usuario = Util_Tests.nuevoUsuario('pruebas','pruebas','asdd@hotmail.com','pruebas','pruebas',perfil);
		insert usuario;
		Account cuentaProfUp = [SELECT Id, Name, CUE_TXT_Identificador__c FROM Account WHERE Id=: cuentaProfesional.Id];
		Profesional_Gremio__c profGrem = new Profesional_Gremio__c();
		profGrem.PRG_LKP_Cuenta_Profesional__c = cuentaProfUp.Id;
		profGrem.PRG_TXT_Identificador__c='j40dg49alnf194j';
		profGrem.PRG_NUM_Lim_OT_en_Curso__c=2;
		profGrem.PRG_SEL_Gremio__c = '01';
		profGrem.Name = cuentaProfUp.CUE_TXT_Identificador__c+'_'+profGrem.PRG_SEL_Gremio__c;
		insert profGrem;
		ServiceResource sr = Util_Tests.crearRecursoServicio('David','Estanislao',cuentaProfUp.Id,usuario);
		sr.RSE_SEL_Gremio__c = '01';
		sr.Name = cuentaProfUp.CUE_TXT_Identificador__c + '_01_1';
		sr.RSE_LKP_Profesional_Gremio__c = profGrem.Id;
		insert sr;
								//Crear Worktype
		tipoTrabajo = Util_Tests.crearTipoTrabajo('Tipo de Trabajo por Defecto','21', 2);
		insert tipoTrabajo;
		 						//Crear WorkOrder//
		ordenTrabajo = Util_Tests.crearOrdenTrabajo('18210.0','21',tipoTrabajo.Id,Nuevocaso.Id);
		ordenTrabajo.OTR_TXT_Num_OrdenTrabajo_HS__c = '1516201877423';
		ordenTrabajo.OTR_DAT_Fecha_cambio_estado__c = system.now();
		ordenTrabajo.OTR_NUM_Horas_verde__c = 0;
		ordenTrabajo.OTR_NUM_Horas_amarillo__c = 0;
		ordenTrabajo.AccountId = cuenta.Id;
		//ordenTrabajo.Status = '999';
		ordenTrabajo.OTR_LKP_Recurso_Servicio__c = sr.Id;
		insert ordenTrabajo;
		
		documentoIndem = new Indemnizable_Documento__c();
		documentoIndem.IND_SEL_Estado__c = 	'001';
		documentoIndem.IND_LKP_Caso__c = Nuevocaso.Id;
		documentoIndem.IND_SEL_Tipo_Documento__c = '02';
		documentoIndem.IND_TXT_Descripcion__c = ' Indemnizacion de IronHackers ';
		insert documentoIndem;
		Baipas.deshabilitarVariableControl();
	}
	
	
	@isTest static void testSini_Indemn_Partidas(){
		InicializarVariables();
		PageReference pageRef = Page.Sini_TipoInterlocutor;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('retorno','1018');
		ApexPages.currentPage().getParameters().put('VDN','1018');
		ApexPages.currentPage().getParameters().put('idTabBusqClientes','01r9E0000000');
		ApexPages.currentPage().getParameters().put('fase','1018');
		ServiceContract poliza = getServiceContractByName(NuevaPoliza.Name);
		Case caso = getCaseById(poliza.Id);
		ApexPages.currentPage().getParameters().put('id',caso.id);
		ApexPages.currentPage().getParameters().put('idPoliza',poliza.Id);
		WorkOrder workOrder = getWorkOrderByPolidaId(caso.Id); 
		ApexPages.currentPage().getParameters().put('idOrdenTrabajo',workOrder.Id);
		ApexPages.currentPage().getParameters().put('idDocIndemnizable',documentoIndem.Id);
		ApexPages.StandardController stdc = new ApexPages.StandardController(caso);
		Test.startTest();
		SiniIndemnPartidasController siniIndemnPartidas = new SiniIndemnPartidasController(stdc);
		siniIndemnPartidas.indiceListaItems = 0;
		// siniIndemnPartidas.nuevoItem = new Indemnizable_Partida__c();
		
		/*
		Indemnizable_Partida__c indemen= new Indemnizable_Partida__c();
		indemen.INDP_SEL_Estado__c = '01';
		indemen.INDP_DIV_Importe__c = 100;
		indemen.INDP_LKP_Documento_Indemnizable__c = documentoIndem.Id;
		indemen.INDP_TXT_Descripcion__c = ' Indemnizacion de IronHackers ';  
		insert indemen;
		*/
		//siniIndemnPartidas.listaItems.add(indemen);

		siniIndemnPartidas.crearItem();
		siniIndemnPartidas.nuevoItem.INDP_TXT_Descripcion__c = 'IronHackers';
		siniIndemnPartidas.guardarItem();
		siniIndemnPartidas.cancelarCreacionItem();
		siniIndemnPartidas.volver();
		siniIndemnPartidas.indiceListaItems=0;
		siniIndemnPartidas.seleccionarItem();
		siniIndemnPartidas.actualizarItem();
		//siniIndemnPartidas.indiceListaItems=1;  
		//siniIndemnPartidas.eliminarItem();
	Test.stopTest();
	}

	private static WorkOrder getWorkOrderByPolidaId(Id idPoliza){
		 WorkOrder workOrder;
		
		List<WorkOrder> listaWorkOrder = new List<WorkOrder>([Select Id,
								OTR_TXT_Num_OrdenTrabajo_HS__c,
								CaseId
								FROM WorkOrder Where CaseId = :idPoliza LIMIT 1]);
								
		if(!listaWorkOrder.isEmpty()){
			workOrder = listaWorkOrder.get(0);
		}else{
			throw new TestException('No existen WorkOrders con la id de poliza especificado');
		}

		return workOrder;
	}

	private static ServiceContract getServiceContractByName(String name){
		ServiceContract poliza;
		
		List<ServiceContract> listaPolizas = new List<ServiceContract>([Select Id,
								POL_LKP_Compania__r.Name,
								POL_LKP_Compania__r.CUE_EMA_Email__c,
								AccountId,
								Account.Name,
								POL_LKP_Producto_Cia__r.PRD_LKP_Tipo_Producto_CIA__r.TPR_SEL_Interlocutores_Autorizados__c
								FROM ServiceContract Where Name = :name LIMIT 1]);
								
		if(!listaPolizas.isEmpty()){
			poliza = listaPolizas.get(0);
		}else{
			throw new TestException('No existen polizas/contratos con el nombre especificado');
		}

		return poliza;
	}

  private static Case getCaseById(Id id){
		Case caso;
		
		List<Case> listaCasos = new List<Case>([Select Id,			
								CAS_LKP_PolizaContrato__c,
								AccountId,
								CAS_LKP_Compania__c,
								Origin,
								CAS_TXT_Persona_que_llama__c,
								RecordTypeId,
								status,
								CAS_SEL_Motivo_No_Apertura__c,
								CAS_SEL_Tipo_Interlocutor__c
								FROM Case Where CAS_LKP_PolizaContrato__c = :id LIMIT 1]);
								
		if(!listaCasos.isEmpty()){
			caso = listaCasos.get(0);
		}else{
			throw new TestException('No existen casos con el nombre especificado');
		}

		return caso;
	}
}