src/objects/INT_Bitacora__c.object
<CustomObject>
    <description>Representa el registro histórico de integraciones entre Salesforce y otros sistemas de forma que se puedan monitorizar los estados de los envíos y los errores obtenidos.</description>
    <fields>
        <fullName>BIT_FOR_Id_Fichero__c</fullName>
        <formula>BIT_LKP_Envio_Programado_CIA__r.ENV_LKP_Fichero__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id Fichero</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BIT_LKP_Compania__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Compañía</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Integraciones: Bitácora</relationshipLabel>
        <relationshipName>Integraciones_Bitacora</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BIT_LKP_Envio_Programado_CIA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Envío Programado CIA</label>
        <referenceTo>INT_Envio_Programado__c</referenceTo>
        <relationshipLabel>Integraciones: Bitácora</relationshipLabel>
        <relationshipName>Integraciones_Bit_cora</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BIT_NUM_Lote__c</fullName>
        <description>Indica el número de lote de envío</description>
        <label>Lote</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BIT_NUM_Reintentos__c</fullName>
        <description>Contador de reintentos realizados tras la integración errónea contra un sistema tercero.</description>
        <label>Reintentos</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BIT_SEL_Estado__c</fullName>
        <description>Indica el estado del movimiento</description>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Estados_Bitacora</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BIT_SEL_Tipo_Integracion__c</fullName>
        <description>Tipo de integración para el registro en la bitácora</description>
        <label>Tipo de Integración</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipos_de_Integracion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BIT_TXT_Error__c</fullName>
        <description>Indica los errores en el envío del movimiento</description>
        <label>Error</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BIT_TXT_Json__c</fullName>
        <description>Campo que almacena el Json con la información de la petición que se le va a enviar al sistema tercero. Con este campo tendremos la posibilidad de revisar la información de salida y poder depurar.</description>
        <label>Json</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BIT_TXT_Nombre_Fichero__c</fullName>
        <description>Nombre del fichero enviado</description>
        <label>Nombre del Fichero</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BIT_TXT_Nombre_Integracion__c</fullName>
        <description>Será necesario introducir el código de la integración de negocio que ha fallado</description>
        <label>Nombre Integración Web</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Integraciones: Bitácora</label>
    <nameField>
        <displayFormat>BIT{000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones: Bitácora</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/INT_Config_Fichero_CIA__c.object
<CustomObject>
    <description>Representa la configuración de cada uno de los ficheros enviados a las Compañías Aseguradoras.</description>
    <label>Integraciones: Configuración Fichero CIA</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integraciones: Configuración Fichero CIA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/INT_Envio_Programado__c.object
<CustomObject>
    <description>Representa la tabla de parametrización correspondiente a los diferentes eventos/movimientos de siniestros/asistencias/reclamaciones que se deben informar a cada una de las aseguradoras.</description>
    <fields>
        <fullName>ENV_LKP_Fichero__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Id Fichero</label>
        <referenceTo>INT_Config_Fichero_CIA__c</referenceTo>
        <relationshipName>Integraciones_Envios_Programados_CIA</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Integraciones: Envío Programado CIA</label>
    <nameField>
        <displayFormat>ENV{000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones: Envío Programado CIA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Estados_Bitacora.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <default>true</default>
        <label>No Enviado</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Enviado</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Error</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Recibido</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>En espera</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Resuelto</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Recibiendo</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>En espera de apertura</label>
    </customValue>
    <masterLabel>Estados Bitacora</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Tipos_de_Integracion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Envío de Fichero</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Servicio Web</label>
    </customValue>
    <masterLabel>Tipos de Integración</masterLabel>
</GlobalValueSet>

src/classes/Util_Bitacora.cls
/**
 * Clase de funciones auxiliares relativas a las bitácoras.
 * 
 * @author EVERIS
 * 
 */
public without sharing class Util_Bitacora {

	/**
	 * Método que busca bitácoras por query.
	 *
	 * @param setIdBitacora: IDs de las bitácoras a buscar
	 * @param setNameBitacora: nombres de las bitácoras a buscar
	 * @param filtro: otras condiciones del Where
	 *
	 * @return lista con bitácoras resultantes de la query
	 */
	/*public static List<INT_Bitacora__c> queryBitacora(Set<Id> setIdBitacora, Set<String> setNameBitacora, String filtro){
        system.debug('<<<<<<<sera arg1, 1rg2, arg3>>>>>>>>>>' + setIdBitacora + ' / ' + setNameBitacora + ' / ' + filtro);
		Boolean arg1 = setIdBitacora != null && !setIdBitacora.isEmpty();
		Boolean arg2 = setNameBitacora != null && !setNameBitacora.isEmpty();
		Boolean arg3 = filtro != null;
        system.debug('<<<<<<<sera arg1, 1rg2, arg3>>>>>>>>>>' + arg1 + arg2 + arg3);
		List<INT_Bitacora__c> bitacoras = new List<INT_Bitacora__c>();
		if(arg1 || arg2 || arg3){
			String sentenciaOT = 'SELECT Id,';
			sentenciaOT += ' Name,';
			sentenciaOT += ' RecordTypeId,';
			sentenciaOT += ' BIT_SEL_Tipo_Integracion__c,';
			sentenciaOT += ' BIT_SEL_Estado__c,';
			sentenciaOT += ' BIT_FOR_Id_Fichero__c,';
			sentenciaOT += ' BIT_NUM_Lote__c,';
			sentenciaOT += ' BIT_NUM_Reintentos__c,';
			sentenciaOT += ' BIT_TXT_Error__c,';
			sentenciaOT += ' BIT_TXT_Nombre_Integracion__c,';
			sentenciaOT += ' BIT_TXT_Json__c,';
			sentenciaOT += ' BIT_LKP_Envio_Programado_CIA__r.ENV_LKP_Fichero__r.FIC_TXT_Query__c';
			sentenciaOT += ' FROM INT_Bitacora__c';
			String sentenciaOT_where = ' WHERE ';
			if(arg1 && !arg2){
				sentenciaOT_where += 'Id IN :setIdBitacora';
			}
			else if(!arg1 && arg2){
				sentenciaOT_where += 'Name IN :setNameBitacora';
			}
			else if(arg1 && arg2){
				sentenciaOT_where += '(Id IN :setIdBitacora OR Name IN :setNameBitacora)';
			}
			if(arg3){
				if(sentenciaOT_where != ' WHERE '){
					sentenciaOT_where += ' AND ';
				}
				sentenciaOT_where += '('+filtro+')';
			}
			sentenciaOT += sentenciaOT_where;
			system.debug('>>>>>>>>>>>>>>>>>>Util_Bitacora.queryBitacora.sentenciaOT: ' + sentenciaOT);
			bitacoras = database.query(sentenciaOT);
		}
		return bitacoras;
	}*/

	/**
	 * Método que devuelve mapa de bitácoras a partir del Set<ID>.
	 *
	 * @param setIdBitacora: Set<ID> de la bitácora a buscar
	 *
	 * @return mapa de bitácoras encontradas
	 */
	public static Map<Id,INT_Bitacora__c> queryBitacora(Set<ID> setIdBitacora){
		Map<Id,INT_Bitacora__c> mapa = new Map<Id,INT_Bitacora__c>();
		if(setIdBitacora != null && !setIdBitacora.isEmpty()){
			for(List<INT_Bitacora__c> lb:[SELECT Id,
													RecordTypeId,
													BIT_LKP_Compania__c,
													BIT_SEL_Estado__c,
													BIT_NUM_Lote__c,
													BIT_TXT_Nombre_Fichero__c,
													BIT_LKP_Envio_Programado_CIA__c,
													BIT_LKP_Envio_Programado_CIA__r.ENV_LKP_Fichero__r.Name
			                              FROM INT_Bitacora__c 
			                              WHERE Id IN: setIdBitacora ]){
				mapa.putAll(lb);
			}
		}
		return mapa;
	}

	public static Map<String, INT_Bitacora__C> queryBitacoraByEstadoYLote(Set<String> setEstados,Set<Decimal> setLotes) {
		Map<String, INT_Bitacora__c> mapBitacora=new Map<String, INT_Bitacora__c>();
		if(!setEstados.isEmpty() && !setLotes.isEmpty()) {
			for(List<INT_Bitacora__c> listBitacoras:[SELECT Id,RecordTypeId, BIT_SEL_Tipo_Integracion__c
														FROM INT_Bitacora__c WHERE BIT_SEL_Estado__c IN :setEstados AND BIT_NUM_Lote__c IN: setLotes]) {
				mapBitacora.putAll(listBitacoras);
			}
		}
		return mapBitacora;
	}
	
	public static Map<String, INT_Bitacora__C> queryBitacoraByFechaRecordTypeAndEstado(Set<Date> setFecha,Set<Id> setRecordType,Set<String> setEstado) {
		Map<String, INT_Bitacora__c> mapBitacora=new Map<String, INT_Bitacora__c>();
		if(!setFecha.isEmpty() && !setRecordType.isEmpty() && setEstado.isEmpty()) {
			for(List<INT_Bitacora__c> listBitacoras:[SELECT Id FROM INT_Bitacora__c
														WHERE LastModifiedDate <: setFecha AND RecordTypeId  =: setRecordType AND BIT_SEL_Estado__c =: setEstado]) {
				mapBitacora.putAll(listBitacoras);
			}
		}
		return mapBitacora;
	}
}