src/objects/INT_Bitacora__c.object
<CustomObject>
    <description>Representa el registro histórico de integraciones entre Salesforce y otros sistemas de forma que se puedan monitorizar los estados de los envíos y los errores obtenidos.</description>
    <fields>
        <fullName>BIT_SEL_Tipo_Integracion__c</fullName>
        <description>Tipo de integración para el registro en la bitácora</description>
        <label>Tipo de Integración</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipos_de_Integracion</valueSetName>
        </valueSet>
    </fields>
    <label>Integraciones: Bitácora</label>
    <nameField>
        <displayFormat>BIT{000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones: Bitácora</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Tipos_de_Integracion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Envío de Fichero</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Servicio Web</label>
    </customValue>
    <masterLabel>Tipos de Integración</masterLabel>
</GlobalValueSet>

src/classes/Test_Callout_Fac_MaestroProfesionales.cls
@isTest
public without sharing class Test_Callout_Fac_MaestroProfesionales {

	@isTest
	public static void Testing(){
		Callout_Fac_MaestroProfesionales_RQ datos = new Callout_Fac_MaestroProfesionales_RQ();
		datos.origenDatos = 'Siniestro';
		datos.accionRealizada = 'Reparado';
		datos.nombreProfesional = 'Lucas';
		datos.identificadorUnicoProfesional = '01h76134Htl1747';
		datos.numeroProfesional = 'h76134Ht023g743';
		datos.tipoDocumento = 'DNI';
		datos.tomadorNumeroDocumentoCliente = '003a';
		datos.nombreContacto = 'Ildefonso';
		datos.mailContacto = 'idelfonso.prueba@reparado.com';
		Address direccion = new Address();
		datos.direccionContacto = direccion;//'C/De la pampa 78';
		datos.telefonoContacto = '+92 632 432 129';
		datos.direccionDelProfesional = 'Avda. Principal, 9';
		datos.codigoPostalProfesional = '15443';
		datos.ciudadProfesional = 'Cordoba';
		datos.paisProfesional = 'España';
		datos.importeFianzaMaxima = 128;
		datos.condicionPago = 'Reparacion';
		datos.codigoRetencionFiscal = '782sd3891d';
		datos.profesionaFianza = true;
		datos.porcentajeFianza = 21;
		datos.importeTotalFianza = 450;
		datos.importeFianzadevuelta = 395;
		//datos.profesionalFranquicia = ';
		datos.importeFranquicia = 322;
		//datos.fechaFranquicia = 13112017;
		datos.tipoProfesional = '';
		datos.metodoPago = 'Prueba';
		datos.codigoEntidadBanco = '2345';
		datos.codigoSucursal = '7685';
		datos.profesionalRappel = true;
		datos.tipologiaRappel = 'Desconocido';
		datos.digitosControl = '3455';
		datos.numeroCuenta = '2207';
		datos.numeroIban = '2345707';
		datos.paisCuentaBancaria = 'Argentina';
		datos.embargado = false;
		datos.vetado = true;
		//datos.profesionalPerito = true;

		String datosSerializados = JSON.serialize(datos);
		
		INT_Bitacora__c bitacora = new INT_Bitacora__c();
		bitacora.BIT_SEL_Tipo_Integracion__c = '01';
		insert bitacora;
		String idBitacora = bitacora.Id;
		
		test.startTest();
		String body = Callout_Fac_MaestroProfesionales.construirBody(datos);
		Callout_Fac_MaestroProfesionales.updateDatos(body, '',idBitacora,'','');
		test.stopTest();
	}
}