src/objects/INT_Bitacora__c.object
<CustomObject>
    <description>Representa el registro histórico de integraciones entre Salesforce y otros sistemas de forma que se puedan monitorizar los estados de los envíos y los errores obtenidos.</description>
    <fields>
        <fullName>BIT_SEL_Estado__c</fullName>
        <description>Indica el estado del movimiento</description>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Estados_Bitacora</valueSetName>
        </valueSet>
    </fields>
    <label>Integraciones: Bitácora</label>
    <nameField>
        <displayFormat>BIT{000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones: Bitácora</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Estados_Bitacora.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <default>true</default>
        <label>No Enviado</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Enviado</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Error</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Recibido</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>En espera</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Resuelto</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Recibiendo</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>En espera de apertura</label>
    </customValue>
    <masterLabel>Estados Bitacora</masterLabel>
</GlobalValueSet>

src/classes/Batch_Elim_Bitacora.cls
/** 
*   Clase que implementa un proceso batch que encargado de eliminar borrado de bitácoras que será ejecutado el el primer día de cada mes:
*   Una entrada de bitácora se eliminará en caso de que esta tenga una antigüedad mayor a X MESES (BATCH_BORRADO_BITACORA_MESES) y su estado sea '06' ; es decir, que ya se envió la información al sistema tercero.
*   @author everis
*   @version 1.0
*
 */
global without sharing class Batch_Elim_Bitacora implements Schedulable {

    global String status;
    global date fechaLimite ;
    global String tipo ;
    global String query;

    global Batch_Elim_Bitacora() {

        RecordType rt = Util_mapasTiposDeRegistro.getRTByName(new Set<String>{'Servicio Web'}).values()[0];
        //RecordType rt =[SELECT Id,Name FROM RecordType WHERE Name = 'Servicio Web'][0] ;
        this.tipo = rt.Id;
        this.status = '06' ;
        date hoy = date.today();
        this.fechaLimite = hoy.addMonths(-integer.valueOf(Label.BATCH_BORRADO_BITACORA_MESES));
        
    }

    global void execute(SchedulableContext ctx) {
        system.debug(tipo);
        List<INT_Bitacora__c > bitacora_a_eliminar = Util_Bitacora.queryBitacoraByFechaRecordTypeAndEstado(new Set<Date>{this.fechaLimite}, new Set<Id>{this.tipo}, new Set<String>{this.status}).values();
        //List<INT_Bitacora__c > bitacora_a_eliminar = [SELECT Id FROM INT_Bitacora__c WHERE LastModifiedDate <: this.fechaLimite AND RecordTypeId  =: tipo AND BIT_SEL_Estado__c =: this.status];
         for (INT_Bitacora__c b : bitacora_a_eliminar) {
            delete b;
         }
    }

}