src/objects/INT_Bitacora__c.object
<CustomObject>
    <description>Representa el registro histórico de integraciones entre Salesforce y otros sistemas de forma que se puedan monitorizar los estados de los envíos y los errores obtenidos.</description>
    <fields>
        <fullName>BIT_SEL_Estado__c</fullName>
        <description>Indica el estado del movimiento</description>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Estados_Bitacora</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BIT_SEL_Tipo_Integracion__c</fullName>
        <description>Tipo de integración para el registro en la bitácora</description>
        <label>Tipo de Integración</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipos_de_Integracion</valueSetName>
        </valueSet>
    </fields>
    <label>Integraciones: Bitácora</label>
    <nameField>
        <displayFormat>BIT{000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones: Bitácora</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Estados_Bitacora.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <default>true</default>
        <label>No Enviado</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Enviado</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Error</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Recibido</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>En espera</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Resuelto</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Recibiendo</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>En espera de apertura</label>
    </customValue>
    <masterLabel>Estados Bitacora</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Tipos_de_Integracion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Envío de Fichero</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Servicio Web</label>
    </customValue>
    <masterLabel>Tipos de Integración</masterLabel>
</GlobalValueSet>

src/classes/Test_Batch_Elim_Bitacora.cls
@isTest
public without sharing class Test_Batch_Elim_Bitacora {
    @isTest static void test_Elim_Bitacora(){
        //[Insert into RecordType (Id, Name) Values (Id.valueOf('123'), 'Servicio Web')];
        Account compania = Util_tests.crearCuentaCompania('compania','2000', 'X1234567X');
        Insert compania;
        Account acc=new Account();
        acc.CUE_TXT_Numero_Documento__c='12345678Z';
        acc.CUE_SEL_Tipo_Documento__c='P';
        acc.Name='Manolo';
        acc.CUE_LKP_CUENTA_PRINCIPAL__c = compania.id;
        insert acc;
        
        Batch_Elim_Bitacora bitacora=new Batch_Elim_Bitacora();
        Date hoy=Date.today().toStartOfMonth();
        bitacora.fechaLimite=hoy.addDays(10);
        bitacora.status='02';
       	bitacora.tipo= '0129E0000006EJyQAM';
        
        INT_Bitacora__c test=new INT_Bitacora__c();
        test.LastModifiedDate=hoy.addDays(2);//.addDays(29);
        test.CreatedDate=hoy;
        //test.
        test.RecordTypeId=bitacora.tipo;
        test.BIT_SEL_Estado__c=bitacora.status;
        
        test.BIT_SEL_Tipo_Integracion__c='02';
        
        insert test;
        
        bitacora.execute(null);
    }
}