src/objects/INT_Bitacora__c.object
<CustomObject>
    <description>Representa el registro histórico de integraciones entre Salesforce y otros sistemas de forma que se puedan monitorizar los estados de los envíos y los errores obtenidos.</description>
    <fields>
        <fullName>BIT_LKP_Envio_Programado_CIA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Envío Programado CIA</label>
        <referenceTo>INT_Envio_Programado__c</referenceTo>
        <relationshipLabel>Integraciones: Bitácora</relationshipLabel>
        <relationshipName>Integraciones_Bit_cora</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BIT_SEL_Estado__c</fullName>
        <description>Indica el estado del movimiento</description>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Estados_Bitacora</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BIT_TXT_Error__c</fullName>
        <description>Indica los errores en el envío del movimiento</description>
        <label>Error</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Integraciones: Bitácora</label>
    <nameField>
        <displayFormat>BIT{000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones: Bitácora</pluralLabel>
    <recordTypes>
        <fullName>Fichero</fullName>
        <active>true</active>
        <description>Registros de integraciones por fichero</description>
        <label>Fichero</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/INT_Config_Fichero_CIA__c.object
<CustomObject>
    <description>Representa la configuración de cada uno de los ficheros enviados a las Compañías Aseguradoras.</description>
    <label>Integraciones: Configuración Fichero CIA</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integraciones: Configuración Fichero CIA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/INT_Envio_Programado__c.object
<CustomObject>
    <description>Representa la tabla de parametrización correspondiente a los diferentes eventos/movimientos de siniestros/asistencias/reclamaciones que se deben informar a cada una de las aseguradoras.</description>
    <fields>
        <fullName>ENV_LKP_Fichero__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Id Fichero</label>
        <referenceTo>INT_Config_Fichero_CIA__c</referenceTo>
        <relationshipName>Integraciones_Envios_Programados_CIA</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Integraciones: Envío Programado CIA</label>
    <nameField>
        <displayFormat>ENV{000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones: Envío Programado CIA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Estados_Bitacora.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <default>true</default>
        <label>No Enviado</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Enviado</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Error</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Recibido</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>En espera</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Resuelto</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Recibiendo</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>En espera de apertura</label>
    </customValue>
    <masterLabel>Estados Bitacora</masterLabel>
</GlobalValueSet>

src/classes/Reenvio_Bitacora.cls
public without sharing class Reenvio_Bitacora {
	private INT_Bitacora__c bitacora;
	public String mensajeError {get; set;}
	public Reenvio_Bitacora(ApexPages.StandardController stdController) {
		bitacora = (INT_Bitacora__c)stdController.getRecord();
	}

	public PageReference autoRun() {
		Id theId = ApexPages.currentPage().getParameters().get('id');

		//LLM
		Callout_Centinela_Generacion callout = new Callout_Centinela_Generacion();
		//FLLM
		
		if (theId == null) {
			return null;
		}
		List<INT_Bitacora__c> bitList = new List<INT_Bitacora__c>();
		INT_Bitacora__c bitacoraQuery = Util_Bitacora.queryBitacora(new Set<Id>{theId}).get(theId);
		system.debug('CONDICIONES: '+bitacoraQuery != null);
		system.debug(Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_BIT_FICHERO));
		system.debug(bitacoraQuery.RecordTypeId); //NULL POINTER EXCEPTION
		system.debug(bitacoraQuery.RecordTypeId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_BIT_FICHERO));
		
		//LLM
		//if(callout.updateDatos(bitacoraQuery.BIT_LKP_Envio_Programado_CIA__r.ENV_LKP_Fichero__r.Name)){
		//FLLM
			if(bitacoraQuery != null && bitacoraQuery.RecordTypeId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_BIT_FICHERO)){//Compruebo que me ha traído algo y es de tipo fichero
				bitacoraQuery.BIT_SEL_Estado__c=label.BIT_ESTADO_NO_ENVIADO;
				bitacoraQuery.BIT_TXT_Error__c = '';
				update bitacoraQuery;
				bitList.add(bitacoraQuery);
				Batch_Envio_Mov myBatchObject = new Batch_Envio_Mov(null,bitList);
				Id batchId = Database.executeBatch(myBatchObject);
				PageReference pageRef = new PageReference('/' + theId);
				pageRef.setRedirect(true);
				return pageRef;
			}
		//LLM
		/*}else{
			mensajeError = 'Fichero de envío duplicado en destino.';
		}*/
		//FLLM
		return null;
	}
}