src/objects/OperatingHours.object
<CustomObject>
    <fields>
        <fullName>OPH_TXT_Identificador__c</fullName>
        <description>Identificador único y externo</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Procedencia__c.object
<CustomObject>
    <description>Representa cada una de las procedencias de una Compañía/Cliente B2B.</description>
    <label>Procedencia</label>
    <nameField>
        <label>Código de Procedencia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceTerritory.object
<CustomObject>
    <fields>
        <fullName>TDS_TXT_Identificador__c</fullName>
        <description>Identificador externo y exclusivo que se informará con el nombre del territorio</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_DAT_Fecha_Primera_Cita__c</fullName>
        <description>Fecha de la primera visita del profesional a la situación de riesgo del asegurado.</description>
        <label>Fecha de Primera Cita</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OTR_SEL_Motivos_de_Rechazo_de_Albaran__c</fullName>
        <description>Se indican los motivos por los que se puede rechazar un albarán</description>
        <label>Motivos de Rechazo de Albarán</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>Aporte factura de compra de materiales.</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Indique marca y/o modelo de material/es.</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Describa los trabajos realizados.</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>Albarán ilegible (formato jpg).</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>Aporte fotografías.</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>Valore la reparación con códigos de baremo.</label>
                </value>
                <value>
                    <fullName>07</fullName>
                    <label>Envíe albarán de servicio/asistencia según corresponda (el enviado no es correcto).</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>Indique quien aportó el material, el importe y %iva cobrado al asegurado.</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <label>Otros</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OTR_SEL_Rango_Primera_Cita__c</fullName>
        <label>Hora de Primera Cita</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Rango_2_Horas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OTR_TXT_Num_OrdenTrabajo_HS__c</fullName>
        <description>Nº de Orden de Trabajo HomeServe. Identificador exclusivo de la Orden de Trabajo.</description>
        <externalId>true</externalId>
        <label>Nº de Servicio HS</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkType.object
<CustomObject>
    <fields>
        <fullName>TDT_SEL_Categoria__c</fullName>
        <description>Clasificación del Tipo de Trabajo (Siniestro, Servicio B2B/B2B2C).</description>
        <label>Categorías</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Categoria_TDT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TDT_SEL_Gremio__c</fullName>
        <description>Gremio asociado al tipo de trabajo.</description>
        <label>Gremio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Gremios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TDT_TXT_Identificador__c</fullName>
        <description>Identificador exclusivo del Tipo de Trabajo.</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Categoria_TDT.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Siniestro</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>B2B/B2B2C</label>
    </customValue>
    <masterLabel>Categorías Tipo de Trabajo</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Rango_2_Horas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>00:00 - 02:00</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02:00 - 04:00</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>04:00 - 06:00</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>06:00 - 08:00</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>08:00 - 10:00</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>10:00 - 12:00</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>12:00 - 14:00</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>14:00 - 16:00</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>16:00 - 18:00</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>18:00 - 20:00</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>20:00 - 22:00</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>22:00 - 00:00</label>
    </customValue>
    <description>Intervalos de 2 horas pares.</description>
    <masterLabel>Rango 2 Horas</masterLabel>
</GlobalValueSet>

src/classes/Test_Util_Caso.cls
@isTest
public without sharing class Test_Util_Caso {

    @isTest static void Util_Caso(){
        Account compania = Util_Tests.crearCuentaCompania('compania', Label.IDE_MEMBERSHIP,'X1234567X');
        compania.type = '01';
		insert compania;
        Account compania2 = Util_Tests.crearCuentaCompania('compania', '1018','X1134567X');
		insert compania2;
        Account cuenta = Util_Tests.crearCuentaB2BPpal('cuenta', '1458','X1334567X');
        cuenta.type = '01';
        cuenta.CUE_LKP_Cuenta_principal__c = compania.Id;
		insert cuenta;
        
        Tipo_Producto_CIA__c tipoProducto = Util_Tests.crearTipoProductoCIA('tipo', '01', compania.Id);
		insert tipoProducto;
        
		Producto_CIA__c producto = Util_Tests.crearProductoCIA('producto', '292', tipoProducto.Id);
		insert producto;
        
        Procedencia__c procedencia = Util_Tests.crearProcedencia(0.0, 0.0, 0.0, 0.0, 0.0, cuenta.Id, '545687', 'CAS_Solicitud_de_Servicio_B2B_B2B2C;CAS_Servicio_B2B_B2B2C');
        insert procedencia;
        
       	ServiceContract sv = Util_Tests.crearPolizaContrato('poliza', compania.Id, cuenta.Id, producto.Id);
        insert sv;
        
        Case caso = new Case();
        caso = Util_Tests.crearCasoB2B(sv.Id, cuenta.Id, compania.Id);
        caso.CAS_SEL_Encuestador__c = 'Servitelco';
        caso.CAS_LKP_Compania__c = compania.Id;
        caso.CAS_EMA_Solicitud_Email__c = 'sera@sera.com';        
        caso.CAS_LKP_Procedencia__c = procedencia.Id;
        caso.CreatedDate = system.now();
        caso.Status = '993';
        caso.OwnerId = system.UserInfo.getUserId();
        caso.CAS_SEL_DirRiesgo_Estado_Provincia__c = '43';
        insert caso;
        
        
        WorkType wt = new WorkType();
		wt.Name = 'Tipo de Trabajo por Defecto';
		wt.EstimatedDuration = 120.0;
		wt.DurationType = 'Minutes';
		wt.TDT_SEL_Categoria__c = '01;02';
		wt.TDT_SEL_Gremio__c = '07';
		wt.ShouldAutoCreateSvcAppt = true;
		wt.TDT_TXT_Identificador__c = '701';

		insert wt;
        
        OperatingHours oh = new OperatingHours();
		oh.name = 'Horario por defecto';
		oh.OPH_TXT_Identificador__c = '0001';

		insert oh;
        
        
		ServiceTerritory st = new ServiceTerritory();
		st.IsActive = true;
		st.Name = '28015 MADRID';
		st.PostalCode = '28015';
		st.TDS_TXT_Identificador__c = '28015#MADRID';
		st.OperatingHoursId = oh.Id;
		//st.TDS_LKP_Poblacion__c = poblacion.Id; 

		insert st;
        
        WorkOrder wo = new WorkOrder();
		wo.AccountId = cuenta.Id;
        wo.CaseId = caso.Id;
		wo.City = 'Madrid';
		wo.StartDate = system.now();
		wo.Duration = 2.0;
		wo.DurationType = 'Hours';
		wo.Latitude = 40.48023673004623;
		wo.Longitude = -3.6690412312805356;
		wo.WorkTypeId = wt.Id;
		wo.OTR_TXT_Num_OrdenTrabajo_HS__c = '1516809815917';
		wo.ServiceTerritoryId = st.Id;
		Datetime posibleFechaReserva = Datetime.now().addDays(Util_Cita_Servicio.sumarDias(Datetime.now()));
		wo.OTR_DAT_Fecha_Primera_Cita__c = posibleFechaReserva.date();
		//wo.CreatedDate = system.now();
		//wo.OTR_DAT_Fecha_Primera_Cita__c = Date.today();
		wo.OTR_SEL_Rango_Primera_Cita__c = '07';
        wo.OwnerId = System.UserInfo.getUserId();
        wo.OTR_SEL_Motivos_de_Rechazo_de_Albaran__c = '09';

		insert wo;
        
        Util_Caso.getIdTipoDeRegistro(Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get('Siniestro'), Label.CAS_TIPO_ASISTENCIA_COBERTURA, compania, Label.SINI_ESTADO_NO_ABIERTO);
        Util_Caso.getIdTipoDeRegistro(Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get('Siniestro'), Label.CAS_TIPO_ASISTENCIA_COBERTURA, compania, 'Otro');
        Util_Caso.getIdTipoDeRegistro(Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get('Siniestro'), Label.CAS_TIPO_ASISTENCIA_COBERTURA, compania2, 'Otro');
        Util_Caso.devolverDireccionTerritorial(caso);
        
        List<WorkOrder> listaOT = new List<WorkOrder>();
        Util_Caso.casosDeOT(listaOT);
        listaOT.add(wo);
        Util_Caso.calcularTotalFacturarCIA(listaOT);
        Util_caso.calcularTotalFacturarCliente(listaOT);
        Util_Caso.calcularTotalFacturarProfesional(listaOT);
        Util_Caso.getListaOTsCaso(caso.Id);
        Util_Caso.getListaPartidasCaso(caso.Id);
        Util_Caso.guardarCaso(caso);
        Util_Caso.crearComentarioCaso(caso.Id, 'comentario');
        Set<Id> setIds = new Set<Id>();
        setIds.add(caso.Id);
        Util_Tarea.getMapaTareasCaso(setIds);
        Util_Presupuesto.getMapaUltPresupCasos(setIds);
        Util_Caso.getMapaSharesCaso(setIds);
        Util_Caso.getMapaPartidasCasos(setIds);
        Util_Orden_Trabajo.getMapaOTsCasosFull(setIds);
        
        
        Map<Id, Case> mapaCasos = new Map<Id, Case>();
        mapaCasos.put(caso.Id, caso);
        Map<Id, WorkOrder> mapaOTs = new Map<Id, WorkOrder>();
        mapaOTs.put(wo.Id, wo);
        Map<Id, WorkOrder> mapaActualizado = new Map<Id, WorkOrder>();
        mapaActualizado.put(wo.Id, wo);
        Util_Caso.heredarDatosCaseOT(mapaCasos, mapaOTs, mapaActualizado);
        
        Test.startTest();
        /*
        Case caso2 = new Case();
        caso2 = Util_Tests.crearCasoB2B(sv.Id, cuenta.Id, compania.Id);
        caso2.CAS_SEL_Encuestador__c = 'Servitelco';
        caso2.CAS_LKP_Compania__c = compania.Id;
        caso2.CAS_EMA_Solicitud_Email__c = 'sera@sera.com';        
        caso2.CAS_LKP_Procedencia__c = procedencia.Id;
        caso2.CreatedDate = system.now();
        caso2.Status = LABEL.CAS_ESTADO_EN_CURSO;
        caso2.CAS_SEL_DirRiesgo_Estado_Provincia__c = '43';
        insert caso2;
        */
        /*
         Case caso3 = new Case();
        caso3 = Util_Tests.crearCasoB2B(sv.Id, cuenta.Id, compania.Id);
        caso3.CAS_SEL_Encuestador__c = 'Servitelco';
        caso3.CAS_LKP_Compania__c = compania.Id;
        caso3.CAS_EMA_Solicitud_Email__c = 'sera@sera.com';        
        caso3.CAS_LKP_Procedencia__c = procedencia.Id;
        caso3.CreatedDate = system.now();
        caso3.Status = LABEL.CAS_ESTADO_EN_CURSO;
        caso3.CAS_SEL_DirRiesgo_Estado_Provincia__c = '43';
        insert caso3;
*/
        Util_Caso.actualizarFechasParo(caso, caso);
        //Util_Caso.actualizarFechasParo(caso3, caso2);
       
        Test.stopTest();
        
        
    }
    
    @isTest public static void util_caso2(){
        Test.startTest();
        Account compania = Util_Tests.crearCuentaCompania('compania', Label.IDE_MEMBERSHIP,'X1234567X');
        compania.type = '01';
		insert compania;
        Account compania2 = Util_Tests.crearCuentaCompania('compania', '1018','X1134567X');
		insert compania2;
        Account cuenta = Util_Tests.crearCuentaB2BPpal('cuenta', '1458','X1334567X');
        cuenta.type = '01';
        cuenta.CUE_LKP_Cuenta_principal__c = compania.Id;
		insert cuenta;
        
        Tipo_Producto_CIA__c tipoProducto = Util_Tests.crearTipoProductoCIA('tipo', '01', compania.Id);
		insert tipoProducto;
        
		Producto_CIA__c producto = Util_Tests.crearProductoCIA('producto', '292', tipoProducto.Id);
		insert producto;
        
        Procedencia__c procedencia = Util_Tests.crearProcedencia(0.0, 0.0, 0.0, 0.0, 0.0, cuenta.Id, '545687', 'CAS_Solicitud_de_Servicio_B2B_B2B2C;CAS_Servicio_B2B_B2B2C');
        insert procedencia;
        
        ServiceContract sv = Util_Tests.crearPolizaContrato('poliza', compania.Id, cuenta.Id,producto.Id);
        insert sv;
        
        Case caso = new Case();
        caso = Util_Tests.crearCasoB2B(sv.Id, cuenta.Id, compania.Id);
        caso.CAS_SEL_Encuestador__c = 'Servitelco';
        caso.CAS_LKP_Compania__c = compania.Id;
        caso.CAS_EMA_Solicitud_Email__c = 'sera@sera.com';        
        caso.CAS_LKP_Procedencia__c = procedencia.Id;
        caso.CreatedDate = system.now();
        caso.Status = '993';
        caso.CAS_SEL_DirRiesgo_Estado_Provincia__c = '43';
        insert caso;
        caso.CAS_SEL_DirRiesgo_Estado_Provincia__c = '46';
        update caso;
        Util_Caso.devolverDireccionTerritorial(caso);
        caso.CAS_SEL_DirRiesgo_Estado_Provincia__c = '52';
        update caso;
        Util_Caso.devolverDireccionTerritorial(caso);
        caso.CAS_SEL_DirRiesgo_Estado_Provincia__c = '45';
        update caso;
        Util_Caso.devolverDireccionTerritorial(caso);
        caso.CAS_SEL_DirRiesgo_Estado_Provincia__c = '49';
        update caso;
        Util_Caso.devolverDireccionTerritorial(caso);
        caso.CAS_SEL_DirRiesgo_Estado_Provincia__c = '50';
        update caso;
        Util_Caso.devolverDireccionTerritorial(caso);
        caso.CAS_SEL_DirRiesgo_Estado_Provincia__c = '38';
        update caso;
        Util_Caso.devolverDireccionTerritorial(caso);
        Test.stopTest();
    }
        
}