src/objects/OperatingHours.object
<CustomObject>
    <fields>
        <fullName>OPH_TXT_Identificador__c</fullName>
        <description>Identificador único y externo</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Presupuesto__c.object
<CustomObject>
    <description>Representa cada uno de los presupuestos generados para un caso.</description>
    <fields>
        <fullName>PRE_LKP_Caso__c</fullName>
        <description>Caso al que se vincula el Comentario. Representa la FK al objeto Case. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto Case (Case.CAS_TXT_Identificador__c).</description>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Presupuestos</relationshipLabel>
        <relationshipName>Presupuestos_Valoraciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PRE_NUM_Version__c</fullName>
        <description>Versión.</description>
        <label>Versión</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRE_SEL_Estado_Anterior__c</fullName>
        <description>Guarda el estado anterior.</description>
        <label>Estado Anterior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Estados_Presupuesto</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PRE_SEL_Estado__c</fullName>
        <description>Estado del presupuesto.</description>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Estados_Presupuesto</valueSetName>
        </valueSet>
    </fields>
    <label>Presupuesto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nº de Presupuesto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Presupuestos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Procedencia__c.object
<CustomObject>
    <description>Representa cada una de las procedencias de una Compañía/Cliente B2B.</description>
    <fields>
        <fullName>PROC_SEL_Motivos_rechazo_presupuesto__c</fullName>
        <label>Motivos rechazo presupuesto</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Motivo_rechazo_presupuesto</valueSetName>
        </valueSet>
    </fields>
    <label>Procedencia</label>
    <nameField>
        <label>Código de Procedencia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceTerritory.object
<CustomObject>
    <fields>
        <fullName>TDS_TXT_Identificador__c</fullName>
        <description>Identificador externo y exclusivo que se informará con el nombre del territorio</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_TXT_Num_OrdenTrabajo_HS__c</fullName>
        <description>Nº de Orden de Trabajo HomeServe. Identificador exclusivo de la Orden de Trabajo.</description>
        <externalId>true</externalId>
        <label>Nº de Servicio HS</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkType.object
<CustomObject>
    <fields>
        <fullName>TDT_SEL_Categoria__c</fullName>
        <description>Clasificación del Tipo de Trabajo (Siniestro, Servicio B2B/B2B2C).</description>
        <label>Categorías</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Categoria_TDT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TDT_SEL_Gremio__c</fullName>
        <description>Gremio asociado al tipo de trabajo.</description>
        <label>Gremio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Gremios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TDT_TXT_Identificador__c</fullName>
        <description>Identificador exclusivo del Tipo de Trabajo.</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Categoria_TDT.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Siniestro</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>B2B/B2B2C</label>
    </customValue>
    <masterLabel>Categorías Tipo de Trabajo</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Estados_Presupuesto.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>300</fullName>
        <label>Aceptado</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <default>true</default>
        <label>Borrador</label>
    </customValue>
    <customValue>
        <fullName>200</fullName>
        <label>Pendiente respuesta cliente</label>
    </customValue>
    <customValue>
        <fullName>400</fullName>
        <label>Rechazo Total</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>Pendiente Aprobación CIA</label>
    </customValue>
    <customValue>
        <fullName>006</fullName>
        <label>Rechazo Parcial</label>
    </customValue>
    <customValue>
        <fullName>007</fullName>
        <label>Aprobado CIA</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
        <label>Estado inicial Membership</label>
    </customValue>
    <customValue>
        <fullName>500</fullName>
        <label>Rechaza antes de presupuesto</label>
    </customValue>
    <customValue>
        <fullName>600</fullName>
        <label>Cliente no contactado</label>
    </customValue>
    <customValue>
        <fullName>700</fullName>
        <label>Instant Cover</label>
    </customValue>
    <customValue>
        <fullName>800</fullName>
        <label>Limpieza Sass</label>
    </customValue>
    <customValue>
        <fullName>900</fullName>
        <label>Enviado a Perito</label>
    </customValue>
    <masterLabel>Estados Presupuesto</masterLabel>
</GlobalValueSet>

src/globalValueSets/Motivo_rechazo_presupuesto.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Rechazo por precio alto</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>No disponible gremio</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Otros</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Avería de un tercero</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>No hay averia</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Atencion al cliente</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Seguimiento de asistencia</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Telefono erroneo</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Error en tramitacion</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>No se puede reparar</label>
    </customValue>
    <masterLabel>Motivo rechazo presupuesto</masterLabel>
</GlobalValueSet>

src/classes/Test_TRG_Handler_Presupuesto.cls
@isTest
public without sharing class Test_TRG_Handler_Presupuesto {

    private static Account compania;
    private static Account cuentaPrincipal;
    private static Account cuentaSec;
    private static Tipo_Producto_CIA__c tipoProductoCIA;
    private static Producto_CIA__c productoCia;
    private static ServiceContract poliza;
    private static Case casoB2B;
    private static Procedencia__c procedencia;
    private static WorkOrder wo;
    private static WorkType wt;
    private static Presupuesto__c pre;

    static void inicializarVariables(boolean generarPresupuesto, String estado, boolean pendienteCita){

        compania = Util_Tests.crearCuentaCompania('SegurCaixa','1018','X1234567X');
        insert compania;

        cuentaPrincipal = Util_Tests.crearCuentaB2BPpal('B2BPrincipal','1245678','X1134567X');
        cuentaPrincipal.Type='01';
        insert cuentaPrincipal;

        cuentaSec=Util_Tests.crearCuentaB2BSec('Name','13132', cuentaPrincipal.Id, 'X5544663X');
        cuentaSec.Type='01';
        cuentaSec.CUE_LKP_Cliente_contable__c=cuentaPrincipal.Id;
        insert cuentaSec;

        tipoProductoCIA = Util_Tests.crearTipoProductoCIA('SegurCaixa - HOGAR','01',compania.Id);
        insert tipoProductoCIA;

        productoCia=Util_Tests.crearProductoCIA('nombre','01', tipoProductoCIA.Id);
        insert productoCia;


        poliza=Util_Tests.crearPolizaContrato('4523814',compania.Id, cuentaPrincipal.Id, productoCIA.Id);
        insert poliza;

        procedencia = Util_Tests.crearProcedencia(0.0, 0.0, 0.0, 0.0, 0.0, cuentaPrincipal.Id, '545687', 'CAS_Solicitud_de_Servicio_B2B_B2B2C;CAS_Servicio_B2B_B2B2C');
        procedencia.PROC_SEL_Motivos_rechazo_presupuesto__c = '09;07;02;08;06;21;03;01';
        insert procedencia;

        casoB2B = Util_Tests.crearCasoB2B(poliza.Id, cuentaSec.Id, compania.Id);
        casoB2B.CAS_SEL_Encuestador__c = 'Servitelco';
        casoB2B.CAS_EMA_Solicitud_Email__c = 'sera@sera.com';        
        casoB2B.CAS_LKP_Procedencia__c = procedencia.Id;
        casoB2B.OwnerId = System.UserInfo.getUserId();
        casoB2B.Status = '993';
        if (generarPresupuesto) {
            casoB2B.CAS_CAS_Generar_Presupuesto__c = true;
        }
        insert casoB2B;

        wt = new WorkType();
        wt.Name = 'Tipo de Trabajo por Defecto';
        wt.EstimatedDuration = 120.0;
        wt.DurationType = 'Minutes';
        wt.TDT_SEL_Categoria__c = '01;02';
        wt.TDT_SEL_Gremio__c = '07';
        wt.ShouldAutoCreateSvcAppt = true;
        wt.TDT_TXT_Identificador__c = '701';
        insert wt;

        OperatingHours oh = new OperatingHours();
        oh.name = 'Horario por defecto';
        oh.OPH_TXT_Identificador__c = '0001';
        insert oh;

        ServiceTerritory st = new ServiceTerritory();
        st.IsActive = true;
        st.Name = '28015 MADRID';
        st.PostalCode = '28015';
        st.TDS_TXT_Identificador__c = '28015#MADRID';
        st.OperatingHoursId = oh.Id;
        //st.TDS_LKP_Poblacion__c = poblacion.Id; 
        insert st;

        wo = new WorkOrder();
        wo.CaseId = casoB2B.Id;
        wo.AccountId = cuentaPrincipal.Id;
        wo.City = 'Madrid';
        wo.StartDate = system.now();
        wo.Duration = 2.0;
        wo.DurationType = 'Hours';
        wo.Latitude = 40.48023673004623;
        wo.Longitude = -3.6690412312805356;
        wo.WorkTypeId = wt.Id;
        wo.OTR_TXT_Num_OrdenTrabajo_HS__c = '1516809815917';
        wo.ServiceTerritoryId = st.Id;
        wo.CreatedDate = system.now();
        insert wo;

        WorkOrderLineItem lineaOrdenTrabajo = Util_Tests.crearNuevaPartidaTrabajo(wo.Id);
        if (pendienteCita) {
            lineaOrdenTrabajo.status = Label.PAR_ESTADO_PDTE_CIA;
        }
        test.startTest();
        insert lineaOrdenTrabajo;

        pre = new Presupuesto__c();
        pre.PRE_LKP_Caso__c = casoB2B.Id;
        pre.PRE_NUM_Version__c = 1.0;
        pre.PRE_SEL_Estado_Anterior__c = Label.PRESUPUESTO_PENDIENTE_CIA;
        if (estado == 'pendienteCIA') {
            pre.PRE_SEL_Estado__c = Label.PRESUPUESTO_PENDIENTE_CIA;
        }else if(estado == 'rechazadoParcial'){
            pre.PRE_SEL_Estado__c = Label.PRESU_RECHAZADO_PARCIAL;
        }
        
        insert pre;
        
    }
    static testMethod void Handler_Presupuesto(){
        inicializarVariables(false,'pendienteCIA',true);
    }

    static testMethod void Handler_Presupuesto1(){
        inicializarVariables(false,'',false);
        pre.PRE_SEL_Estado__c = Label.PRESU_RECHAZADO_PARCIAL;
        update pre;
        test.stoptest();
    }

    static testMethod void Handler_Presupuesto2(){
        inicializarVariables(true,'rechazadoParcial',true);
    }
}