src/objects/OperatingHours.object
<CustomObject>
    <fields>
        <fullName>OPH_TXT_Identificador__c</fullName>
        <description>Identificador único y externo</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Poblacion__c.object
<CustomObject>
    <description>Municipios de España.</description>
    <fields>
        <fullName>POB_SEL_Provincia__c</fullName>
        <description>Provincia.</description>
        <label>Provincia</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Provincias</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>POB_TXT_Identificador__c</fullName>
        <description>Campo externo y exclusivo</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Población</label>
    <nameField>
        <label>Población</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poblaciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <fields>
        <fullName>PRD_TXT_Identificador__c</fullName>
        <description>Identificador externo para los productos. Será la concatenación de la compañía, el código del tipo de producto y el Código del Prdocuto.</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>CSE_CAS_Asignada__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asignada</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Asignar_Como_Franquiciado__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campos casilla para identificar si en la cita de servicio se tiene que asignar como franquiciado</description>
        <label>Asignar como franquiciado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Asignar_Mizad__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asignar como Mizad</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Asignar_como_Urgencias__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asignar como Red Urgencias</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Asignar_territorio_prim_no_franq__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campos casilla para identificar si en la cita de servicio se tiene que asignar como territorio no franquiciado</description>
        <label>Asignar territorio prim no franquiciado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Comprobado_Horario__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Comprobado Horario</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Crear_cita_app__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Crear cita app</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_CAS_Urgente__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check que indica si la cita es urgente o no</description>
        <label>Urgente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_DAT_Fecha_Hora_Fin_Nueva_Cita__c</fullName>
        <label>Fecha/Hora Fin Nueva Cita</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSE_DAT_Fecha_Hora_Inicio_Nueva_Cita__c</fullName>
        <label>Fecha/Hora Inicio Nueva Cita</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSE_DAT_Fecha_Proxima_Programacion__c</fullName>
        <label>Fecha Próxima Programación</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSE_DAT_Fecha_Ultima_Programacion__c</fullName>
        <label>Fecha Última Programación</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSE_DAT_Fecha_para_nueva_cita__c</fullName>
        <label>Fecha para nueva cita</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSE_FOR_Calculo_de_Segmentacion__c</fullName>
        <formula>IF(CSE_TXT_Segmentacion_Cliente__c  = &quot;Normal&quot;,50,
IF(CSE_TXT_Segmentacion_Cliente__c  = &quot;Vip&quot;,70,
IF(CSE_TXT_Segmentacion_Cliente__c  = &quot;Valor&quot;,90,
IF(CSE_TXT_Segmentacion_Cliente__c  = &quot;Oro&quot;,90,
IF(CSE_TXT_Segmentacion_Cliente__c  = &quot;Vip&quot;,90,0
)
)
)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calculo de Segmentación</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSE_FOR_Num_Asociado_Mizad__c</fullName>
        <formula>IF (CSE_CAS_Asignar_Mizad__c , 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Num Asociado Mizad</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSE_FOR_Num_Asociado_Urgencias__c</fullName>
        <formula>IF ( CSE_CAS_Asignar_como_Urgencias__c , 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Num Asociado Urgencias</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSE_NUM_Numero_de_Ofrecimientos__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Numero de Ofrecimientos</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSE_SEL_Gremio__c</fullName>
        <label>Gremio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Gremios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSE_SEL_Hora_para_nueva_cita__c</fullName>
        <label>Hora para nueva cita</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Rango_2_Horas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSE_SEL_Motivo_Desasignacion__c</fullName>
        <description>Motivo el cual el profesional se desasigna una cita de servicio que se le había asignado previamente.</description>
        <label>Motivo de desasignación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Motivo_Desasignacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSE_SEL_Motivo_Retraso__c</fullName>
        <description>Motivo del retraso del profesional a la cita de servicio con el cliente.</description>
        <label>Motivo de retraso</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Motivo_Retraso</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSE_SEL_Tipo_Red__c</fullName>
        <label>Tipo de Servicio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipo_de_Servicio</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSE_TXT_Comentario_Estado__c</fullName>
        <label>Comentario</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSE_TXT_Identificador__c</fullName>
        <description>Identificador exclusivo de Cita de servicio</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CSE_TXT_Segmentacion_Cliente__c</fullName>
        <description>Indica la segmentación del cliente asociado a la cita</description>
        <label>Segmentación Cliente</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FSL__Appointment_Grade__c</fullName>
        <label>Appointment Grade</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceResource.object
<CustomObject>
    <fields>
        <fullName>RSE_LKP_Cuenta__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Cuenta del Profesional Contrato</description>
        <label>Cuenta de Profesional</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Profesional Contrato</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recursos de servicios</relationshipLabel>
        <relationshipName>Recursos_de_servicios</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSE_TXT_Codigo_Recurso__c</fullName>
        <description>Campo externo y exclusivo para identificar cada uno de los recursos de un profesional.</description>
        <externalId>true</externalId>
        <label>Código de Recurso</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceTerritory.object
<CustomObject>
    <fields>
        <fullName>TDS_TXT_Identificador__c</fullName>
        <description>Identificador externo y exclusivo que se informará con el nombre del territorio</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceTerritoryMember.object
<CustomObject>
    <fields>
        <fullName>MTS_CAS_Creado_para_guardia__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Creado para guardia</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MTS_CAS_Procesado_Festivo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Procesado Festivo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MTS_TXT_Identificador__c</fullName>
        <description>Campo externo y exclusivo para identificar que concatena el Id del Recurso de Servicio (RSE_TXT_Codigo_Recurso__c) y el Id Territorio de Servicio (TDS_TXT_Identificador)</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <fields>
        <fullName>TPR_LKP_Compania__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Compañía a la que pertenece el tipo de producto. Representa la FK al objeto Account para la compañía. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External Id (Account.CUE_TXT_Identificador__c):Código de compañía HomeServe</description>
        <label>Compañía</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Compañía</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Compañía: Tipos de Producto</relationshipLabel>
        <relationshipName>Tipos_de_Producto_CIA</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TPR_SEL_Interlocutores_Autorizados__c</fullName>
        <description>Listado de Interlocutores Autorizados por la Compañía para ese tipo de producto</description>
        <label>Interlocutores Autorizados</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipos_Interlocutor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TPR_SEL_Tipo_Producto__c</fullName>
        <description>Tipología del Producto</description>
        <label>Tipo de Producto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipos_Producto_CIA</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TPR_TXT_Identificador__c</fullName>
        <description>Es la concatenación de Compañía y Tipo de Producto</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkType.object
<CustomObject>
    <fields>
        <fullName>TDT_SEL_Categoria__c</fullName>
        <description>Clasificación del Tipo de Trabajo (Siniestro, Servicio B2B/B2B2C).</description>
        <label>Categorías</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Categoria_TDT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TDT_SEL_Gremio__c</fullName>
        <description>Gremio asociado al tipo de trabajo.</description>
        <label>Gremio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Gremios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TDT_TXT_Identificador__c</fullName>
        <description>Identificador exclusivo del Tipo de Trabajo.</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Categoria_TDT.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Siniestro</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>B2B/B2B2C</label>
    </customValue>
    <masterLabel>Categorías Tipo de Trabajo</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Motivo_Desasignacion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>No disponer de herramientas</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Conflicto con cliente</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Conflicto con Homeserve</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Falta de capacitación</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Servicio desatendido</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Prof. Rechaza la Reclamación</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Control de gestión por precio elevado</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Motivos personales</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Icompatibilidad horaria</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Vehículo averiado</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>Falta de colaboración en presupuestar asistencias</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>No se ajusta a valoración/baremo en asistencias</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Sin causa justificada</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>El trabajo descrito no es el que hay que realizar</label>
    </customValue>
    <description>Motivo de desasignación de la cita de servicio</description>
    <masterLabel>Motivo de Desasignación</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Motivo_Retraso.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Retraso del profesional</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Accidente / Baja médica</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Pendiente gremio anterior</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Falta de material / herramientas</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>Cliente ausente</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Cambio de hora petición del Cliente / perjudicado</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Error apertura</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>No localizo vivienda</label>
    </customValue>
    <customValue>
        <fullName>99</fullName>
        <label>Otros</label>
    </customValue>
    <description>Motivo de retraso del profesional en la cita de servicio</description>
    <masterLabel>Motivo de retraso</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Rango_2_Horas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>00:00 - 02:00</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02:00 - 04:00</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>04:00 - 06:00</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>06:00 - 08:00</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>08:00 - 10:00</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>10:00 - 12:00</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>12:00 - 14:00</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>14:00 - 16:00</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>16:00 - 18:00</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>18:00 - 20:00</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>20:00 - 22:00</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>22:00 - 00:00</label>
    </customValue>
    <description>Intervalos de 2 horas pares.</description>
    <masterLabel>Rango 2 Horas</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Tipo_de_Servicio.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Mizad</fullName>
    </customValue>
    <description>Representa las tipologías de servicios a las que puede pertenecer una orden de trabajo o una cita de servicio.</description>
    <masterLabel>Tipos de Servicio</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Tipos_Interlocutor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administrador de la Finca</fullName>
    </customValue>
    <customValue>
        <fullName>Agente</fullName>
    </customValue>
    <customValue>
        <fullName>Asegurado/a</fullName>
    </customValue>
    <customValue>
        <fullName>Empleado/a del negocio</fullName>
    </customValue>
    <customValue>
        <fullName>Hijo/a</fullName>
    </customValue>
    <customValue>
        <fullName>Inquilino</fullName>
    </customValue>
    <customValue>
        <fullName>Marido</fullName>
    </customValue>
    <customValue>
        <fullName>Padre</fullName>
    </customValue>
    <customValue>
        <fullName>Perito</fullName>
    </customValue>
    <customValue>
        <fullName>Portero</fullName>
    </customValue>
    <customValue>
        <fullName>Presidente</fullName>
    </customValue>
    <customValue>
        <fullName>Propietario</fullName>
    </customValue>
    <customValue>
        <fullName>Empleado de la sucursal</fullName>
    </customValue>
    <customValue>
        <fullName>Compañía</fullName>
    </customValue>
    <customValue>
        <fullName>Madre</fullName>
    </customValue>
    <customValue>
        <fullName>Mujer</fullName>
    </customValue>
    <customValue>
        <fullName>Pareja</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>Otros familiares</fullName>
    </customValue>
    <customValue>
        <fullName>Vecino/a</fullName>
    </customValue>
    <masterLabel>Tipos de Interlocutor</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Tipos_Producto_CIA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>HOGAR</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>COMERCIO</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>COMUNIDAD DE PROPIETARIOS</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>INMUEBLES</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>PYMES</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>MANTENIMIENTO</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>PREMIUM</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>SEGMENTADO</label>
    </customValue>
    <masterLabel>Tipos de Producto CIA</masterLabel>
</GlobalValueSet>

src/classes/Test_TRG_Handler_Recurso_Asignado.cls
@isTest(seeAllData = true)
public without sharing class Test_TRG_Handler_Recurso_Asignado{
	private static Account compania {get; set;}
	private static Account cuentaPrincipal {get; set;}
	private static Account cuenta {get; set;}
    private static Account cuentaProfesional {get; set;}
	private static Tipo_Producto_CIA__c tipoProductoCIA {get; set;}
	private static Producto_CIA__c productoCIA {get; set;}
	private static Poblacion__c poblacion {get; set;}
	private static ServiceContract poliza {get; set;}
	private static Procedencia__c procedencia {get; set;}
	private static Case caso {get; set;} 
    private static WorkType tipoTrabajo;

    static testMethod void actualizarCitaServicioAsignacionDirectaTest(){
       
        Baipas.establecerVariableControl();
        List<Account> listaCuentas = new List<Account>();
        Account compania = Util_Tests.crearCuentaCompania('compania', '111018','X1234567X');
        listaCuentas.add(compania);
        //compania.CUE_TXT_Numero_Documento__c='2153523646';
		cuentaPrincipal = Util_Tests.crearCuentaB2BPpal('B2BPrincipal','111019','X1134567X');
		listaCuentas.add(cuentaPrincipal);
		insert listaCuentas;
        Profile perfil = [SELECT Id FROM Profile WHERE Name =: Label.PERFIL_ADMINISTRADOR];
        User usuario = Util_Tests.nuevoUsuario('pruebas','pruebas','asdd@hotmail.com','pruebas','pruebas',perfil);
        insert usuario;
		cuenta = Util_Tests.crearCuentaB2BSec('Asegurado','101120',cuentaPrincipal.Id,'X1114567X');
		insert cuenta;

		cuentaProfesional = Util_Tests.crearCuentaProfesionalContrato('PR123486','PR155586','E1234567E',compania.id);
        cuentaProfesional.CUE_SEL_Tipo_de_Profesional__c = '01'; //Autonomo
        insert cuentaProfesional;
		cuentaProfesional.CUE_SEL_Estado__c = '02';
        update cuentaProfesional;

		tipoProductoCIA = Util_Tests.crearTipoProductoCIA('SegurCaixa - HOGAR','01',compania.ID);
		insert tipoProductoCIA;

		productoCIA = Util_Tests.crearProductoCIA('KIT 107','12345678',tipoProductoCIA.Id);
        productoCIA.PRD_TXT_Identificador__c = '58765657';
		insert productoCIA;
		//poblacion =  Util_Tests.crearPoblacion('Madrid','28');
		poblacion = new Poblacion__c();
		poblacion.Name = 'Madrid_Test';
		poblacion.POB_SEL_Provincia__c = '28';
		poblacion.POB_TXT_Identificador__c = '28#Madrid_Test';
		insert poblacion;
		poliza = Util_Tests.crearPolizaContrato('2277393',compania.Id,cuenta.Id,productoCIA.Id);
		insert poliza;
		caso = Util_Tests.crearCasoB2B(poliza.Id, cuenta.Id, compania.Id);
        caso.CAS_TXT_Identificador__c = '678576897';
		insert caso;
        ServiceResource sr = new ServiceResource();
        sr.RSE_LKP_Cuenta__c = cuentaProfesional.Id;
        sr.Name = cuentaProfesional.CUE_TXT_Identificador__c+'_01_1';
        sr.RelatedRecordId = usuario.id;
        sr.RSE_TXT_Codigo_Recurso__c = cuentaProfesional.Name+'_01_1';
        sr.IsCapacityBased = true;
        sr.IsActive = true;
        
        insert sr;
        
        Tipo_Producto_CIA__c tipoProd = new Tipo_Producto_CIA__c();
        tipoProd.Name = 'SegurCaixa333';
        tipoProd.TPR_SEL_Tipo_Producto__c = '01';
        tipoProd.TPR_LKP_Compania__c = compania.Id;
        tipoProd.TPR_SEL_Interlocutores_Autorizados__c = 'Padre';
        tipoProd.TPR_TXT_Identificador__c = '435345_Test';
        
        insert tipoProd;
        
        WorkType wt = new WorkType();
        wt.Name = 'Tipo de Trabajo por Defecto';
        wt.EstimatedDuration = 120.0;
        wt.DurationType = 'Minutes';
        wt.TDT_SEL_Categoria__c = '01;02';
        wt.TDT_SEL_Gremio__c = '07';
        wt.ShouldAutoCreateSvcAppt = true;
        wt.TDT_TXT_Identificador__c = '701_Test';
        
        insert wt;
        
        OperatingHours oh = new OperatingHours();
        oh.name = 'Horario por defecto';
        oh.OPH_TXT_Identificador__c = 'Test';
        
        insert oh;
        
        Poblacion__c poblacion = new Poblacion__c();
        poblacion.Name = 'MADRID_Test';
        poblacion.POB_SEL_Provincia__c = '28';
        poblacion.POB_TXT_Identificador__c = '28#MADRID_Test';
        
        //insert poblacion;
        
        ServiceTerritory st = new ServiceTerritory();
        st.IsActive = true;
        st.Name = '69096 Ochitoria';
        st.PostalCode = '69096';
        st.TDS_TXT_Identificador__c = '69096#Ochitoria_Test';
        st.OperatingHoursId = oh.Id;
        //st.TDS_LKP_Poblacion__c = poblacion.Id; 
        
        insert st;
        
        ServiceTerritoryMember stm = new ServiceTerritoryMember();
        stm.EffectiveStartDate = DateTime.newInstance(2018, 3, 13, 12, 0, 0);
        stm.MTS_CAS_Creado_para_guardia__c = false;
        stm.MTS_CAS_Procesado_Festivo__c = false;
        stm.ServiceTerritoryId = st.Id;
        stm.TerritoryType = 'P';
        stm.OperatingHoursId = oh.Id;
        stm.MTS_TXT_Identificador__c = 'STM-0012_69096#Ochitoria_Test';
        stm.PostalCode = '69096';
        stm.ServiceResourceId = sr.Id;
        /*stm.FSL__Internal_SLR_HomeAddress_Geolocation__Longitude__s = 98989.89;
        stm.Street = 'jkdhfalshflkjas';
        stm.City = 'Madrid';
        stm.Country = 'España';
        stm.PostalCode = '28001';*/
        
        insert stm;
        tipoTrabajo = Util_Tests.crearTipoTrabajo('Siniestro', '21', 2.5);
        insert tipoTrabajo;
        
        WorkOrder wo = Util_Tests.crearOrdenTrabajo('26032018', '75', tipoTrabajo.id, caso.Id);

        insert wo;
        
        List<ServiceAppointment> serviceApp = new List<ServiceAppointment>([SELECT AccountId
                                                                    ,ActualDuration,ActualEndTime,ActualStartTime,Address,AppointmentNumber,ArrivalWindowEndTime
                                                                    ,ArrivalWindowStartTime,City,ContactId,Country,CreatedById,CreatedDate,CSE_CAS_Asignada__c
                                                                    ,CSE_CAS_Asignar_Como_Franquiciado__c,CSE_CAS_Asignar_como_Urgencias__c,CSE_CAS_Asignar_Mizad__c
                                                                    ,CSE_CAS_Asignar_territorio_prim_no_franq__c,CSE_CAS_Comprobado_Horario__c
                                                                    ,CSE_CAS_Crear_cita_app__c,CSE_CAS_Urgente__c,CSE_DAT_Fecha_Hora_Fin_Nueva_Cita__c
                                                                    ,CSE_DAT_Fecha_Hora_Inicio_Nueva_Cita__c,CSE_DAT_Fecha_para_nueva_cita__c
                                                                    ,CSE_DAT_Fecha_Proxima_Programacion__c,CSE_DAT_Fecha_Ultima_Programacion__c
                                                                    ,CSE_FOR_Calculo_de_Segmentacion__c,CSE_FOR_Num_Asociado_Mizad__c,CSE_FOR_Num_Asociado_Urgencias__c
                                                                    ,CSE_NUM_Numero_de_Ofrecimientos__c,CSE_SEL_Gremio__c,CSE_SEL_Hora_para_nueva_cita__c
                                                                    ,CSE_SEL_Motivo_Desasignacion__c,CSE_SEL_Motivo_Retraso__c,CSE_SEL_Tipo_Red__c
                                                                    ,CSE_TXT_Comentario_Estado__c,CSE_TXT_Identificador__c,CSE_TXT_Segmentacion_Cliente__c
                                                                    ,Description,DueDate,Duration,DurationInMinutes,DurationType,EarliestStartTime
                                                                    ,FSL__Appointment_Grade__c,FSL__Auto_Schedule__c,FSL__Emergency__c,FSL__GanttColor__c
                                                                    ,FSL__GanttLabel__c,FSL__InJeopardyReason__c,FSL__InJeopardy__c,FSL__InternalSLRGeolocation__c
                                                                    ,FSL__InternalSLRGeolocation__Latitude__s,FSL__InternalSLRGeolocation__Longitude__s
                                                                    ,FSL__IsFillInCandidate__c,FSL__IsMultiDay__c,FSL__Pinned__c
                                                                    ,FSL__Prevent_Geocoding_For_Chatter_Actions__c,FSL__Related_Service__c,FSL__Same_Day__c
                                                                    ,FSL__Same_Resource__c,FSL__Schedule_Mode__c,FSL__Scheduling_Policy_Used__c,FSL__Time_Dependency__c
                                                                    ,FSL__UpdatedByOptimization__c,FSL__Virtual_Service_For_Chatter_Action__c,GeocodeAccuracy,Id,IsDeleted
                                                                    ,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Latitude,Longitude,OwnerId
                                                                    ,ParentRecordId,ParentRecordStatusCategory,ParentRecordType,PostalCode,RecordTypeId,SchedEndTime
                                                                    ,SchedStartTime,ServiceNote,ServiceTerritoryId,State,Status,StatusCategory,Street,Subject
                                                                    ,SystemModstamp,WorkTypeId 
                                                                    FROM ServiceAppointment where ParentRecordId = :wo.Id]);

        ServiceAppointment sa = serviceApp.get(0);
        //ServiceAppointment sa = new ServiceAppointment();
        sa.EarliestStartTime = DateTime.newInstance(2018,3,15,14,0,0);
        sa.DueDate = sa.EarliestStartTime.addDays(1);
        //sa.EarliestStartTime = wo.CreatedDate.addDays(2);
        //sa.DueDate = wo.CreatedDate.addDays(4);
        sa.Duration = 2.0;
        //sa.SchedEndTime = wo.CreatedDate.addDays(2).addHours(1);
        //sa.SchedStartTime = wo.CreatedDate.addDays(2);
        sa.SchedEndTime = sa.EarliestStartTime.addDays(1).addHours(1);
        sa.SchedStartTime = sa.EarliestStartTime.addDays(1);
        //sa.ArrivalWindowStartTime = wo.CreatedDate.addDays(2);
        //sa.ArrivalWindowEndTime = wo.CreatedDate.addDays(2).addHours(1);
        sa.ArrivalWindowStartTime = sa.EarliestStartTime.addDays(1);
        sa.ArrivalWindowEndTime = sa.EarliestStartTime.addDays(1).addHours(1);
        sa.ServiceTerritoryId = st.Id;
        sa.City = 'MADRID';
        sa.CSE_CAS_Asignar_como_Urgencias__c = true;
        //sa.ParentRecordId = wo.Id;
        //sa.Status = 'Anulada por el cambio de cita';
        update sa;
        Baipas.deshabilitarVariableControl();
        
        AssignedResource assign = new AssignedResource();
        assign.ServiceAppointmentId = sa.Id;
        assign.ServiceResourceId = sr.Id;
        insert assign;
        List<AssignedResource> ListaRecursosAsignados = new List<AssignedResource>();
        ListaRecursosAsignados.add(assign);
        TRG_Handler_Recurso_Asignado.sharePartner(ListaRecursosAsignados);   
    }
}