src/objects/Perito_Provincia__c.object
<CustomObject>
    <description>Tabla donde se relacionan a los peritos con las provincias asociadas y su porcentaje de asignación</description>
    <fields>
        <fullName>PERP_FOR_Compania__c</fullName>
        <formula>PERP_LKP_Perito__r.PER_LKP_Compania__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Compañía</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PERP_NUM_Siniestros_Asignados__c</fullName>
        <description>Numero de Siniestros Asignados para el perito en la provincia seleccionada</description>
        <label>Siniestros Asignados</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PERP_SEL_Provincia__c</fullName>
        <description>Provincia asociada al Perito</description>
        <label>Provincia</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Provincias</valueSetName>
        </valueSet>
    </fields>
    <label>Perito: Provincia</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Nombre de Perito: Provincia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Perito: Provincias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRG_Handler_Perito_Provincia.cls
/**
  * Handler del Trigger TRG_Perito_Provincia.
  * 
  * @author EVERIS
  * 
  */
public without sharing class TRG_Handler_Perito_Provincia {
	
	public static void tratamientoAfter(Map<Id, Perito_Provincia__c> triggerNewMap, List<Perito_Provincia__c> triggerNew, 
			Map<Id, Perito_Provincia__c> triggerOldMap, List<Perito_Provincia__c> triggerOld){
		Set<Id> idCompanias = new Set<Id>();
		List<Perito_Provincia__c> peritosAct = new List<Perito_Provincia__c>();
		Set<String> idProvincias = new Set<String>();
		
		if(Trigger.isInsert) {
			for(Perito_Provincia__c per :triggerNew) {
				idCompanias.add(per.PERP_FOR_Compania__c);
				idProvincias.add(per.PERP_SEL_Provincia__c);
			}
			List<Perito_Provincia__c> listPeritos = Util_Perito.peritoByIdCompaniaAndProvincia(idCompanias, idProvincias).values();
			for(Perito_Provincia__c perAct :listPeritos) {
				perAct.PERP_NUM_Siniestros_Asignados__c = 0;
				peritosAct.add(perAct);
			}
			if(!peritosAct.isEmpty()) {
				update peritosAct;
			}
		}
		
	}
}