src/objects/Poblacion__c.object
<CustomObject>
    <description>Municipios de España.</description>
    <fields>
        <fullName>POB_SEL_Provincia__c</fullName>
        <description>Provincia.</description>
        <label>Provincia</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Provincias</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>POB_TXT_Identificador__c</fullName>
        <description>Campo externo y exclusivo</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Población</label>
    <nameField>
        <label>Población</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poblaciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Poblacion_CP__c.object
<CustomObject>
    <description>Objeto intermedio para relacionar los Territorios de Servicio con las Poblaciones.</description>
    <fields>
        <fullName>PCP_LKP_Poblacion__c</fullName>
        <description>Población relacionada</description>
        <label>Población</label>
        <referenceTo>Poblacion__c</referenceTo>
        <relationshipName>Poblaciones_CP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PCP_LKP_TerritorioServicio__c</fullName>
        <description>Territorio de Servicio relacionado</description>
        <label>Territorio de servicio</label>
        <referenceTo>ServiceTerritory</referenceTo>
        <relationshipName>Poblaciones_CP</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PCP_TXT_Identificador__c</fullName>
        <description>Identificador externo y exclusivo que se informará con el código postal y el nombre del territorio (CP#Población).</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Población con el Código Postal</label>
    <nameField>
        <label>Población con el Código Postal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poblaciones con los Códigos Postales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceTerritory.object
<CustomObject>
    <fields>
        <fullName>TDS_TXT_Identificador__c</fullName>
        <description>Identificador externo y exclusivo que se informará con el nombre del territorio</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Util_Poblacion.cls
/**
 * Clase de funciones auxiliares relativas a los campos Poblacion y Provincia.
 * 
 * @author EVERIS
 * 
 */
public without sharing class Util_Poblacion {
	/**
	 * Inicialización de la lista de provincias
	 * 
	 * @return la lista de provincias inicializada
	 */
	public static List<SelectOption> inicializarListaProvincias(){
		List<SelectOption> listaProvincias = new List<SelectOption>();
		listaProvincias.add(new SelectOption('', '-- Ninguno --'));
		Map <String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
		Map <String, Schema.SObjectField> poblacionFieldMap = schemaMap.get('Poblacion__c').getDescribe().fields.getMap();
		DescribeFieldResult provincia = poblacionFieldMap.get('POB_SEL_Provincia__c').getDescribe();
		for(Schema.PicklistEntry prov : provincia.getPicklistValues()){
			listaProvincias.add(new SelectOption(prov.getValue(), prov.getLabel()));
		}
		return listaProvincias;
	}
	/**
	 * Se inicializa la lista de poblaciones, insertando la opcion "Ninguno"
	 * 
	 * @return la lista de poblaciones inicializada
	 */
	public static List<SelectOption> inicializarListaPoblaciones(){
		List<SelectOption> listaPoblaciones = new List<SelectOption>();
		listaPoblaciones.add(new SelectOption('', '-- Ninguno --'));
		return listaPoblaciones;
	}
	/**
	 * Se busca la poblacion por codigo postal
	 * 
	 * @param valorCodigoPostal Código Postal a usar para la búsqueda
	 * @return una lista con las poblaciones que coinciden con el código postal
	 */
	/*public static List<SelectOption> buscarPorCP(String valorCodigoPostal){
        List<SelectOption> listaPoblaciones;
        if(valorCodigoPostal != null 
         && valorCodigoPostal.isNumeric()
         && valorCodigoPostal.length() <= 5){
            List<Poblacion__c> listaPobsBusq = new List<Poblacion__c>([SELECT Name
             FROM Poblacion__c 
             WHERE POB_NUM_Codigo_Postal_Inicio__c <= :Integer.valueOf(valorCodigoPostal) 
                 AND (POB_NUM_Codigo_Postal_Fin__c = null
                    OR POB_NUM_Codigo_Postal_Fin__c >= :Integer.valueOf(valorCodigoPostal))]);
            if(!listaPobsBusq.isEmpty()){
                listaPoblaciones = new List<SelectOption>();
                listaPoblaciones.add(new SelectOption(listaPobsBusq.get(0).Id, listaPobsBusq.get(0).Name));

            }else{
                listaPoblaciones = inicializarListaPoblaciones();
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.ERROR_MUNICIPIOS_NO_CP));
            }

        }else{
            listaPoblaciones = inicializarListaPoblaciones();
            if(valorCodigoPostal != null && valorCodigoPostal != ''){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.ERROR_CAMPO_CP));
            }
        }
        return listaPoblaciones;
    }*/

	/**
	 * Se busca la poblacion por provincia
	 * 
	 * @param valorCodigoPostal Código Postal a usar para la búsqueda
	 * @param valorProvincia Provincia a usar para la búsqueda
	 * @return una lista con las poblaciones que coinciden con el código postal
	 */
	//	NO SE INVOCA NUNCA
	/*public static List<SelectOption> buscarPorProvincia(String valorCodigoPostal, String valorProvincia){
        List<SelectOption> listaPoblaciones;
        if(valorCodigoPostal == null || valorCodigoPostal == ''){
            List<Poblacion__c> listaPobsBusq = new List<Poblacion__c>([SELECT Name 
             FROM Poblacion__c 
             WHERE POB_SEL_Provincia__c = :valorProvincia]);
            if(!listaPobsBusq.isEmpty()){
                listaPoblaciones = new List<SelectOption>();
                for(Poblacion__c pob : listaPobsBusq){
                    listaPoblaciones.add(new SelectOption(pob.Id, pob.Name));
                }
            }else{
                listaPoblaciones = inicializarListaPoblaciones();
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.ERROR_MUNICIPIOS_NO_PROVINCIA));
            }
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.ERROR_BUSQUEDA_CP));
        }
        return listaPoblaciones;
    }*/

	//NO SE LLAMA DESDE NINGUNA PARTE
	/*public static List<Poblacion__c> recogerProvinciaPoblacion(Id poblacion){
    //public static String recogerProvinciaPoblacion(Id poblacion){ 
        List<Poblacion__c> listaProvs = new List<Poblacion__c>(
                                [SELECT POB_SEL_Provincia__c
                                 FROM Poblacion__c
                                 WHERE Id = :poblacion]);

        return listaProvs.get(0).POB_SEL_Provincia__c;

        List<Poblacion__c> listaProvs = new List<Poblacion__c>(
                                [SELECT Name,
                                        POB_SEL_Provincia__c
                                 FROM Poblacion__c
                                 WHERE Id = :poblacion]);

        return listaProvs;
    }*/

	/**
	* Devuelve un objeto Poblacion__c desde la búsqueda de identificador por provincia
	*
	* @param provincia: String de una provincia
	*
	* @return mapa que contiene los objetos Poblacion__c
	*/
	public static Map<Id,Poblacion__c> getPoblacionProv(String provincia){
		Map<Id,Poblacion__c> mapa = new Map<Id,Poblacion__c>();
		if(provincia != null){
			for(List<Poblacion__c> lista:[SELECT Id,POB_TXT_Identificador__c FROM Poblacion__c  WHERE POB_TXT_Identificador__c Like :provincia+'%']){
				mapa.putAll(lista);
			}
		} 
		return mapa;
	}

	/**
	* Devuelve un objeto Poblacion_CP__c desde su LKP a Poblacion__c
	*
	* @param setPoblacion: id de la poblacion asociada
	*
	* @return mapa que contiene los objetos Poblacion_CP__c
	*/
	public static Map<Id,Poblacion_CP__c> getCpPoblacion(set<String> setPoblacion){
		Map<Id,Poblacion_CP__c> mapa = new Map<Id,Poblacion_CP__c>();
		if(setPoblacion != null && !setPoblacion.isEmpty()){
	        for(List<Poblacion_CP__c> lista:[SELECT PCP_LKP_TerritorioServicio__c, PCP_LKP_Poblacion__c, PCP_TXT_Identificador__c
	         FROM Poblacion_CP__c WHERE PCP_LKP_Poblacion__c IN :setPoblacion LIMIT 1]){
	            mapa.putAll(lista);
	        }               
	    } 
	    return mapa;
	}

	/**
	 * Query que obtiene un mapa de poblaciones asociadas a un conjunto de códigos postales que se especifican como parámetro
	 *
	 * @param codigoPostal: Set de códigos postales sobre los que se quiere buscar la población
	 *
	 * @return mapa que <Id,Poblacion_CP__c>
	 */
    public static Map <Id,Poblacion_CP__c> queryPoblacion_CPByPCP_LKP_TerritorioServicio_r_TDS_TXT_Identificador (Set<String> codigoPostal){
        Map<Id,Poblacion_CP__c> mapa = new Map<Id,Poblacion_CP__c>();
	    if(!codigoPostal.isEmpty()){
	        for(List<Poblacion_CP__c> lista:[SELECT PCP_LKP_Poblacion__r.POB_SEL_Provincia__c,
								PCP_LKP_Poblacion__r.Name
						 FROM Poblacion_CP__c 
						 WHERE PCP_LKP_TerritorioServicio__r.TDS_TXT_Identificador__c in :codigoPostal]){
	            mapa.putAll(lista);
	        }               
	    }
		return mapa;
    }
}