src/objects/Procedencia_TipoTrabajo__c.object
<CustomObject>
    <description>Representa el conjunto de Tipos de Trabajo disponibles en una Procedencia.</description>
    <fields>
        <fullName>PRTT_LKP_Procedencia__c</fullName>
        <label>Procedencia</label>
        <referenceTo>Procedencia__c</referenceTo>
        <relationshipLabel>Tipos de Trabajo</relationshipLabel>
        <relationshipName>Procedencia_Tipos_de_Trabajo</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PRTT_LKP_TipoTrabajo__c</fullName>
        <label>Tipo de trabajo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>WorkType.TDT_SEL_Gremio__c</field>
                <operation>equals</operation>
                <valueField>$Source.PRTT_SEL_Gremio__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>WorkType</referenceTo>
        <relationshipLabel>Procedencias</relationshipLabel>
        <relationshipName>Procedencia_Tipos_de_Trabajo</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Procedencia: Tipo de Trabajo</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procedencia: Tipos de Trabajo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkType.object
<CustomObject>
    <fields>
        <fullName>TDT_SEL_Categoria__c</fullName>
        <description>Clasificación del Tipo de Trabajo (Siniestro, Servicio B2B/B2B2C).</description>
        <label>Categorías</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Categoria_TDT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TDT_SEL_Gremio__c</fullName>
        <description>Gremio asociado al tipo de trabajo.</description>
        <label>Gremio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Gremios</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Categoria_TDT.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Siniestro</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>B2B/B2B2C</label>
    </customValue>
    <masterLabel>Categorías Tipo de Trabajo</masterLabel>
</GlobalValueSet>

src/classes/Util_TipoTrabajo.cls
/**

 * Clase de funciones auxiliares relativas a las Tipos de Trabajo.
 * 
 * @author EVERIS
 * 
 */
public without sharing class Util_TipoTrabajo {

	/**
	 * Devuelve los Tipos de Trabajo filtrados por Gremios y valor de Categoría.
	 *
	 * @param setStringGremios: conjunto de Gremios
	 * @param selectValueCategoria: valor contenido en las Categorías
	 *
	 * @return mapa que contiene los Tipos de Trabajos encontrados
	 */
	public static Map<Id,WorkType> getWorkTypeByGremioAndCategoria(Set<String> setStringGremios, String selectValueCategoria){
		Map<Id,WorkType> mapa = new Map<Id,WorkType>();
		if(setStringGremios != null && !setStringGremios.isEmpty() && selectValueCategoria != null){
			for(List<WorkType> lista:[SELECT Id,Name FROM WorkType WHERE TDT_SEL_Categoria__c INCLUDES (:selectValueCategoria) AND TDT_SEL_Gremio__c IN :setStringGremios]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}

	/**
	 * Devuelve los Tipos de Trabajo filtrados por los IDs.
	 *
	 * @param setId: conjunto de IDs de Tipo de Trabajo
	 *
	 * @return mapa que contiene los Tipos de Trabajos encontrados
	 */
	public static Map<Id,WorkType> getWorkTypeById(Set<Id> setId){
		Map<Id,WorkType> mapa = new Map<Id,WorkType>();
		if(setId != null && !setId.isEmpty()){
			for(List<WorkType> lista:[SELECT Id,Name FROM WorkType WHERE Id IN :setId]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}

	/**
	 * Devuelve los Tipos de Trabajo filtrados por los nombres.
	 *
	 * @param setName: conjunto de nombres de Tipo de Trabajo
	 *
	 * @return mapa que contiene los Tipos de Trabajos encontrados
	 */
	public static Map<Id,WorkType> getWorkTypeByName(Set<String> setName){
		Map<Id,WorkType> mapa = new Map<Id,WorkType>();
		if(setName != null && !setName.isEmpty()){
			for(List<WorkType> lista:[SELECT Id,Name FROM WorkType WHERE Name IN :setName]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}

	/**
	 * Devuelve los Tipos de Trabajo filtrados por Procedencias, Gremios y valor de Categoría.
	 *
	 * @param setIdProcedencia: conjunto de IDs de Procedencia
	 * @param setStringGremios: conjunto de Gremios
	 * @param selectValueCategoria: valor contenido en las Categorías
	 *
	 * @return mapa que contiene los Tipos de Trabajos encontrados
	 */
	public static Map<Id,WorkType> getWorkTypeByProcedenciaAndGremioAndCategoria(Set<Id> setIdProcedencia, Set<String> setStringGremios, String selectValueCategoria){
		Map<Id,WorkType> mapa = new Map<Id,WorkType>();
		if(setIdProcedencia != null && !setIdProcedencia.isEmpty() && setStringGremios != null && !setStringGremios.isEmpty() && selectValueCategoria != null){
			for(List<WorkType> lista:[SELECT Id,Name FROM WorkType WHERE TDT_SEL_Categoria__c INCLUDES (:selectValueCategoria) AND TDT_SEL_Gremio__c IN :setStringGremios AND Id IN (SELECT PRTT_LKP_TipoTrabajo__c FROM Procedencia_TipoTrabajo__c WHERE PRTT_LKP_Procedencia__c IN :setIdProcedencia)]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}

    /*public static List<WorkType> queryTipoTrabajo(String categoria, String gremio) {
        List<WorkType> listWorkType=new List<WorkType>();
        if(!String.isEmpty(categoria)) {
            for(WorkType tipoTrabajoAux:[SELECT Id,Name FROM WorkType WHERE TDT_SEL_Categoria__c INCLUDES (:categoria) AND TDT_SEL_Gremio__c = :gremio]) {
                listWorkType.add(tipoTrabajoAux);
            }
        }
        return listWorkType;
    }

    public static List<WorkType> queryTipoTrabajo(String categoria, String gremio, Id procedencia) {
        List<WorkType> listWorkType=new List<WorkType>();
        if(!String.isEmpty(categoria)) {
            for(WorkType tipoTrabajoAux: [SELECT Id,Name FROM WorkType WHERE TDT_SEL_Categoria__c INCLUDES (:categoria) AND TDT_SEL_Gremio__c = :gremio AND Id IN (SELECT PRTT_LKP_TipoTrabajo__c FROM Procedencia_TipoTrabajo__c WHERE PRTT_LKP_Procedencia__c = :procedencia)]) {
                listWorkType.add(tipoTrabajoAux);
            }
        }
        return listWorkType;
    }*/
}