src/objects/Procedencia__c.object
<CustomObject>
    <description>Representa cada una de las procedencias de una Compañía/Cliente B2B.</description>
    <fields>
        <fullName>PROC_CAS_No_Requiere_Albaran__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Si está marcado indica que no se requiere que haya albarán en el cierre de una Orden de Trabajo.</description>
        <label>Cierre Servicio No Requiere Albarán</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PROC_CAS_Requiere_Declaracion_Resp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica que se requiere que el profesional presente un documento de Declaración de Responsable antes de iniciar los trabajos.</description>
        <label>Requiere Declaración Responsable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PROC_LKP_Cuenta__c</fullName>
        <description>Identificador único de la compañia</description>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Procedencias</relationshipLabel>
        <relationshipName>Procedencias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PROC_NUM_Contador_Rechazos__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Campo utilizado para contabilizar el número de siniestros con tipo de actuación rechazo que lleva la Compañía Aseguradora</description>
        <label>Contador Rechazos</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PROC_NUM_Contador__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Contador secuencial de Siniestros y Cuentas</description>
        <label>Contador Siniestros</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PROC_NUM_Tiempo_Atencion_Urgencias__c</fullName>
        <description>Tiempo en horas establecido por la Compañía para atender Urgencias.</description>
        <label>Tiempo de atención de urgencias (hrs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PROC_SEL_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Canales_Procedencia</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROC_SEL_Gremios_Disp__c</fullName>
        <description>Listado de gremios disponibles para cada CIA</description>
        <label>Gremios Disponibles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Gremios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROC_SEL_Motivos_Anulacion__c</fullName>
        <label>Motivos de Anulación</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Motivos_Anulacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROC_SEL_Motivos_rechazo_presupuesto__c</fullName>
        <label>Motivos rechazo presupuesto</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Motivo_rechazo_presupuesto</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROC_SEL_Subcanal__c</fullName>
        <label>Subcanal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Subcanales_Procedencia</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROC_SEL_Tipos_Caso__c</fullName>
        <label>Tipos de Registro de Intervención</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipo_Caso_Procedencia</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROC_TXT_Identificador__c</fullName>
        <description>Identificador único (External ID) del Código de Procedencia</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Procedencia</label>
    <nameField>
        <label>Código de Procedencia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Canales_Procedencia.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>100</fullName>
        <label>BAU</label>
    </customValue>
    <customValue>
        <fullName>110</fullName>
        <label>REAL ESTATE</label>
    </customValue>
    <customValue>
        <fullName>120</fullName>
        <label>SME&apos;S</label>
    </customValue>
    <customValue>
        <fullName>130</fullName>
        <label>B2C/DIGITAL</label>
    </customValue>
    <customValue>
        <fullName>140</fullName>
        <label>B2B2C</label>
    </customValue>
    <customValue>
        <fullName>150</fullName>
        <label>ON DEMAND</label>
    </customValue>
    <customValue>
        <fullName>160</fullName>
        <label>B2B</label>
    </customValue>
    <masterLabel>Canales Procedencia</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Subcanales_Procedencia.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1001</fullName>
        <label>INSURERS</label>
    </customValue>
    <customValue>
        <fullName>1002</fullName>
        <label>NEW INSURERS</label>
    </customValue>
    <customValue>
        <fullName>1003</fullName>
        <label>ASISTENCIAS</label>
    </customValue>
    <customValue>
        <fullName>1011</fullName>
        <label>REAL ESTATE</label>
    </customValue>
    <customValue>
        <fullName>1021</fullName>
        <label>SME&apos;S</label>
    </customValue>
    <customValue>
        <fullName>1031</fullName>
        <label>COLECTIVO</label>
    </customValue>
    <customValue>
        <fullName>1032</fullName>
        <label>DIGITAL</label>
    </customValue>
    <customValue>
        <fullName>1033</fullName>
        <label>MEMBER</label>
    </customValue>
    <customValue>
        <fullName>1041</fullName>
        <label>WEB</label>
    </customValue>
    <customValue>
        <fullName>1042</fullName>
        <label>RETAIL</label>
    </customValue>
    <customValue>
        <fullName>1043</fullName>
        <label>COMUNIDADES</label>
    </customValue>
    <customValue>
        <fullName>1044</fullName>
        <label>Prescriptor</label>
    </customValue>
    <customValue>
        <fullName>1045</fullName>
        <label>B2C</label>
    </customValue>
    <customValue>
        <fullName>1061</fullName>
        <label>B2B</label>
    </customValue>
    <customValue>
        <fullName>1062</fullName>
        <label>PARTNER</label>
    </customValue>
    <masterLabel>Subcanales Procedencia</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Tipo_Caso_Procedencia.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CAS_Solicitud_de_Siniestro</fullName>
        <label>Solicitud de Siniestro</label>
    </customValue>
    <customValue>
        <fullName>CAS_Siniestro</fullName>
        <label>Siniestro</label>
    </customValue>
    <customValue>
        <fullName>CAS_Siniestro_Membership</fullName>
        <label>Siniestro Membership</label>
    </customValue>
    <customValue>
        <fullName>CAS_Solicitud_de_Servicio_B2C</fullName>
        <label>Solicitud de Asistencia</label>
    </customValue>
    <customValue>
        <fullName>CAS_Servicio_B2C</fullName>
        <label>Asistencia</label>
    </customValue>
    <customValue>
        <fullName>CAS_Solicitud_de_Servicio_B2B_B2B2C</fullName>
        <label>Solicitud de Servicio B2B/B2B2C</label>
    </customValue>
    <customValue>
        <fullName>CAS_Servicio_B2B_B2B2C</fullName>
        <label>Servicio B2B/B2B2C</label>
    </customValue>
    <masterLabel>Tipos de Intervención (Procedencias)</masterLabel>
</GlobalValueSet>

src/globalValueSets/Motivo_rechazo_presupuesto.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>Rechazo por precio alto</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>No disponible gremio</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>Otros</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>Avería de un tercero</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>No hay averia</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>Atencion al cliente</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>Seguimiento de asistencia</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>Telefono erroneo</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>Error en tramitacion</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>No se puede reparar</label>
    </customValue>
    <masterLabel>Motivo rechazo presupuesto</masterLabel>
</GlobalValueSet>

src/classes/Util_Procedencia.cls
/**
 * Clase de funciones auxiliares relativas a las procedencias.
 * 
 * @author EVERIS
 * 
 */
public without sharing class Util_Procedencia {

	public static Id getProcedencia(Id	recordTypeCaseId, Id companiaCaseId, Map<Id, Procedencia__c> mapaProcedencias){
		Id idProcedencia = null;
		//Boolean esB2C = (recordTypeCaseId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CAS_B2C) ||
		//				   recordTypeCaseId == Util_mapasTiposDeRegistro.RTIDBYDEVNAME.get(Label.RT_CAS_SOLIC_B2C));

		for(Procedencia__c proc : mapaProcedencias.values()) {
			String tiposDeCaso = '';
			if(proc.PROC_SEL_Tipos_Caso__c != null){
				tiposDeCaso = ';' + proc.PROC_SEL_Tipos_Caso__c + ';';
			}

			//system.debug('>>>>>>>>>>>> getProcedencia: recordTypeCaseId (caso.RecordTypeId): ' + recordTypeCaseId);
			//system.debug('>>>>>>>>>>>> getProcedencia: companiaCaseId (caso.CAS_LKP_Compania__c): ' + companiaCaseId);
			//system.debug('>>>>>>>>>>>> getProcedencia: proc: ' + proc);
			//system.debug('>>>>>>>>>>>> getProcedencia: esB2C: ' + esB2C);
			//system.debug('>>>>>>>>>>>> getProcedencia: companiaCaseId: ' + companiaCaseId);
			//system.debug('>>>>>>>>>>>> getProcedencia: proc.PROC_LKP_Cuenta__c: ' + proc.PROC_LKP_Cuenta__c);
			//system.debug('>>>>>>>>>>>> getProcedencia: tiposDeCaso: ' + tiposDeCaso);

			/*
			// Si es B2C y no hay Poliza: la procedencia es Canal Digital, código 0000
			if (esB2C && companiaCaseId == null) {
				if (proc.PROC_LKP_Cuenta__r.CUE_TXT_Identificador__c == Label.IDE_HOMESERVE &&
					tiposDeCaso.contains(';' + Label.PROCEDENCIA_SERVICIO_B2C + ';')){
					idProcedencia = proc.Id;
					break;
				}
			}
			// Si es Siniestro o Servicio B2C de Asegurado: la procedencia es la correspondiente de las de la CIA
			else {
			 */
			if(proc.PROC_LKP_Cuenta__c == companiaCaseId &&
					tiposDeCaso.contains(';' + Util_mapasTiposDeRegistro.RTDEVNAMEBYID.get(recordTypeCaseId) + ';')){
				idProcedencia = proc.Id;
				break;
			}
			//}
		}

		return idProcedencia;
	}

	public static List<Procedencia__c> queryProcedencia(Id idProcedencia){
		return queryProcedencia(idProcedencia, false);
	}

	/**
	 * Devuelve las procedencias filtrando por los IDs.
	 *
	 * @param setIdProcedencia: conjunto de IDs de procedencia
	 *
	 * @return mapa que contiene las procedencias encontradas
	 */
	public static Map<Id,Procedencia__c> queryProcedencia(Set<Id> setIdProcedencia){
		Map<Id,Procedencia__c> mapa = new Map<Id,Procedencia__c>();
		if(setIdProcedencia != null && !setIdProcedencia.isEmpty()){
			for(List<Procedencia__c> lista:[SELECT Id,Name,PROC_CAS_No_Requiere_Albaran__c,PROC_CAS_Requiere_Declaracion_Resp__c,PROC_NUM_Contador__c,PROC_NUM_Contador_Rechazos__c,PROC_NUM_Tiempo_Atencion_Urgencias__c,PROC_SEL_Motivos_rechazo_presupuesto__c,PROC_SEL_Motivos_Anulacion__c,PROC_SEL_Canal__c,PROC_SEL_Gremios_Disp__c,PROC_SEL_Subcanal__c FROM Procedencia__c WHERE Id IN :setIdProcedencia]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}

	/**
	 * Obtiene una procedencia a partir del ID de procedencia
	 * 
	 * @param idProcedencia ID de Procedencia a buscar
	 * @return lista de Procedencias que coinciden con el ID
	 */
	public static List<Procedencia__c> queryProcedencia(Id idProcedencia, Boolean forUpdate){
		List<Procedencia__c> listaProcedencias = new List<Procedencia__c>();
		if(idProcedencia != null){
			/*listaProcedencias.add([SELECT Name
										,PROC_CAS_No_Requiere_Albaran__c
										,PROC_CAS_Requiere_Declaracion_Resp__c
										,PROC_NUM_Contador__c
										,PROC_NUM_Contador_Rechazos__c
										,PROC_NUM_Tiempo_Atencion_Urgencias__c
										,PROC_SEL_Canal__c
										,PROC_SEL_Gremios_Disp__c
										,PROC_SEL_Subcanal__c
									FROM Procedencia__c 
									WHERE ID = :idProcedencia FOR UPDATE]);*/
			
			String sentenciaProcedencia = 'SELECT Id,';
			sentenciaProcedencia += ' Name,';
			sentenciaProcedencia += ' PROC_CAS_No_Requiere_Albaran__c,';
			sentenciaProcedencia += ' PROC_CAS_Requiere_Declaracion_Resp__c,';
			sentenciaProcedencia += ' PROC_NUM_Contador__c,';
			sentenciaProcedencia += ' PROC_NUM_Contador_Rechazos__c,';
			sentenciaProcedencia += ' PROC_NUM_Tiempo_Atencion_Urgencias__c,';
			sentenciaProcedencia += ' PROC_SEL_Motivos_rechazo_presupuesto__c,';
			sentenciaProcedencia += ' PROC_SEL_Motivos_Anulacion__c,';
			sentenciaProcedencia += ' PROC_SEL_Canal__c,';
			sentenciaProcedencia += ' PROC_SEL_Gremios_Disp__c,';
			sentenciaProcedencia += ' PROC_SEL_Subcanal__c';	
			sentenciaProcedencia += ' FROM Procedencia__c';
			sentenciaProcedencia += ' WHERE Id = \'' + idProcedencia + '\'';
			if(forUpdate)
				sentenciaProcedencia += ' FOR UPDATE';
			listaProcedencias = database.query(sentenciaProcedencia);
		}
		return listaProcedencias;
	}

	/**
	 * Devuelve las procedencias filtradas por IDs de Cuentas y por un valor de PROC_SEL_Tipos_Caso__c.
	 *
	 * @param setIdAccount: conjunto de IDs de Cuentas
	 * @param selValTiposCaso: valor contenido en PROC_SEL_Tipos_Caso__c
	 *
	 * @return mapa que contiene las Cuentas encontradas
	 */
	public static Map<Id,Procedencia__c> getProcedenciaByAccountTiposCaso(Set<Id> setIdAccount, String selValTiposCaso){
		Map<Id,Procedencia__c> mapa = new Map<Id,Procedencia__c>();
		if(setIdAccount != null && !setIdAccount.isEmpty() && selValTiposCaso != null){
			for(List<Procedencia__c> lista:[SELECT Id,PROC_SEL_Gremios_Disp__c, PROC_SEL_Canal__c FROM Procedencia__c WHERE PROC_SEL_Tipos_Caso__c includes (:selValTiposCaso) AND PROC_LKP_Cuenta__c IN :setIdAccount]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}
	
	/**
	 * Devuelve las procedencias filtradas por IDs de Cuentas
	 *
	 * @param setIdAccount: conjunto de IDs de Cuentas
	 *
	 * @return mapa que contiene las Cuentas encontradas
	 */
	public static Map<Id,Procedencia__c> getProcedenciaByAccount(Set<Id> setIdAccount){
		Map<Id,Procedencia__c> mapa = new Map<Id,Procedencia__c>();
		if(setIdAccount != null && !setIdAccount.isEmpty()){
			for(List<Procedencia__c> lista:[SELECT Id,PROC_SEL_Gremios_Disp__c, PROC_SEL_Canal__c FROM Procedencia__c WHERE PROC_LKP_Cuenta__c IN :setIdAccount]){
				mapa.putAll(lista);
			}
		}
		return mapa;
	}

	/**
	 * Obtiene una procedencia a partir del ID de su cuenta.
	 *
	 * @param idCuenta ID de cuenta de la procedencia a buscar
	 * @return lista de Procedencias que coinciden con el ID de su cuenta
	 */
	public static List<Procedencia__c> queryProcedenciaPorCuenta(Id idCuenta){
		if(idCuenta != null){
			return [SELECT Id,
							Name,
							PROC_CAS_No_Requiere_Albaran__c,
							PROC_CAS_Requiere_Declaracion_Resp__c,
							PROC_NUM_Contador__c,
							PROC_NUM_Contador_Rechazos__c,
							PROC_NUM_Tiempo_Atencion_Urgencias__c,
							PROC_SEL_Canal__c,
							PROC_SEL_Gremios_Disp__c,
							PROC_SEL_Subcanal__c
					FROM Procedencia__c
					WHERE PROC_LKP_Cuenta__c = :idCuenta];
		}
		return new List<Procedencia__c>();
	}

	/**
	 * Obtiene una procedencia a partir del ID de su cuenta y de su tipo de registro.
	 *
	 * @param idCuenta ID de cuenta de la procedencia a buscar
	 * @return lista de Procedencias con el tipo de registro especificado que coinciden con el ID de su cuenta
	 */
	public static List<Procedencia__c> queryProcedenciaPorCuenta(Id idCuenta, String tipoReg){
		if(idCuenta != null){
			return [SELECT Id,
							Name,
							PROC_CAS_No_Requiere_Albaran__c,
							PROC_CAS_Requiere_Declaracion_Resp__c,
							PROC_NUM_Contador__c,
							PROC_NUM_Contador_Rechazos__c,
							PROC_NUM_Tiempo_Atencion_Urgencias__c,
							PROC_SEL_Canal__c,
							PROC_SEL_Gremios_Disp__c,
							PROC_SEL_Subcanal__c
					FROM Procedencia__c
					WHERE PROC_LKP_Cuenta__c = :idCuenta
					AND PROC_SEL_Tipos_Caso__c includes (:tipoReg)];
		}
		return new List<Procedencia__c>();
	}
	
/**
 * Query sobre procedencias con bloqueo
 *
 * @return mapa de Procedencias 
 */
	public static Map<Id,Procedencia__c> queryProcedenciasForUpdate(){
		Map<Id,Procedencia__c> mapa = new Map<Id,Procedencia__c> ();
		for(List<Procedencia__c> lista:[SELECT Name,
								PROC_SEL_Tipos_Caso__c,
								PROC_LKP_Cuenta__c,
								PROC_LKP_Cuenta__r.CUE_TXT_Identificador__c,
								PROC_TXT_Identificador__c
						 FROM Procedencia__c
						 FOR UPDATE] ){
						 	mapa.putAll(lista);
						 }
		return mapa;
	}
	
/**
 * Query sobre procedencias sin condición
 *
 * @return mapa de Procedencias 
 */
	public static Map<Id,Procedencia__c> queryProcedenciasNoWhere(){
		Map<Id,Procedencia__c> mapa = new Map<Id,Procedencia__c> ();
		for(List<Procedencia__c> lista:[SELECT Name,
						PROC_SEL_Tipos_Caso__c,
						PROC_LKP_Cuenta__c,
						PROC_LKP_Cuenta__r.CUE_TXT_Identificador__c,
						PROC_TXT_Identificador__c
						 FROM Procedencia__c
						 ] ){
						 	mapa.putAll(lista);
						 }
		return mapa;
	}





	
	
}