src/objects/Procedencia__c.object
<CustomObject>
    <description>Representa cada una de las procedencias de una Compañía/Cliente B2B.</description>
    <fields>
        <fullName>PROC_CAS_No_Requiere_Albaran__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Si está marcado indica que no se requiere que haya albarán en el cierre de una Orden de Trabajo.</description>
        <label>Cierre Servicio No Requiere Albarán</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PROC_SEL_Motivos_Anulacion__c</fullName>
        <label>Motivos de Anulación</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Motivos_Anulacion</valueSetName>
        </valueSet>
    </fields>
    <label>Procedencia</label>
    <nameField>
        <label>Código de Procedencia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedencias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Propuesta_de_Abono__c.object
<CustomObject>
    <label>Propuesta de Abono</label>
    <nameField>
        <displayFormat>AB-{0000000}</displayFormat>
        <label>Abono</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propuestas de Abonos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Propuesta_de_Evento__c.object
<CustomObject>
    <description>Objeto utilizado para modelar el proceso de liquidación y/o facturación a profesionales, clientes y compañías aseguradoras</description>
    <fields>
        <fullName>EV_AB_LKP_Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Caso relacionado al Evento/Abono</description>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Propuestas de Eventos</relationshipLabel>
        <relationshipName>EV_AB_REL_Caso</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_AB_LKP_Imputar_a_profesional__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a (Prof)</label>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Propuestas de Eventos (Imputar a)</relationshipLabel>
        <relationshipName>Propuestas_de_Eventos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_AB_LKP_Orden_de_Trabajo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Orden de Trabajo relacionada al Evento/Abono</description>
        <label>Número Servicio</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipName>EV_AB_REL_Orden_de_Trabajo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_AB_SEL_Departamento_Solicitante__c</fullName>
        <label>Departamento Solicitante</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Departamento_Solicitante</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EV_AB_SEL_Descripcion__c</fullName>
        <label>Código</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GBL_SEL_Codigo_evento</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EV_AB_SEL_Estado__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>02</fullName>
                    <label>Aprobado</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Rechazado</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>Anulado</label>
                </value>
                <value>
                    <fullName>01</fullName>
                    <isActive>false</isActive>
                    <label>En Curso</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EV_AB_SEL_Tipo_de_Evento__c</fullName>
        <label>Tipo de Evento</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>EV_AB_SEL_Descripcion__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cobro</fullName>
                </value>
                <value>
                    <fullName>Pago</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EV_DIV_Importe_a_imputar_Departamento__c</fullName>
        <label>Importe a imputar (Departamento)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Propuesta de Evento Económico</label>
    <nameField>
        <displayFormat>EV-{0000000}</displayFormat>
        <label>Evento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propuestas de Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_LKP_Recurso_Servicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Profesional (Perfil Técnico) vinculado a la Orden de Trabajo. Representa la FK al objeto ServiceResource. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto ServiceResource (ServiceResources.RSE_TXT_Codigo_Recurso__c): Código único del Profesional</description>
        <label>Profesional</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>ServiceResource.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Status</field>
                <operation>equals</operation>
                <value>Anulado, Anulado desde Inactivo, Cerrado, Cerrado Albarán Recibido, Cerrado Pdte. Albarán, Revisado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Órdenes de trabajo</relationshipLabel>
        <relationshipName>OTR_REL_Recurso_Servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OTR_TXT_Estado_Anterior__c</fullName>
        <description>Almacena el estado anterior de la Orden de Trabajo tras un cambio de estado.</description>
        <label>Estado Anterior</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GBL_SEL_Codigo_evento.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>E01</fullName>
    </customValue>
    <customValue>
        <fullName>E02</fullName>
    </customValue>
    <customValue>
        <fullName>E03</fullName>
    </customValue>
    <customValue>
        <fullName>E04</fullName>
    </customValue>
    <customValue>
        <fullName>E05</fullName>
    </customValue>
    <customValue>
        <fullName>E06</fullName>
    </customValue>
    <customValue>
        <fullName>E11</fullName>
    </customValue>
    <customValue>
        <fullName>E12</fullName>
    </customValue>
    <customValue>
        <fullName>E15</fullName>
    </customValue>
    <customValue>
        <fullName>E16</fullName>
    </customValue>
    <customValue>
        <fullName>E17</fullName>
    </customValue>
    <customValue>
        <fullName>E18</fullName>
    </customValue>
    <customValue>
        <fullName>E19</fullName>
    </customValue>
    <customValue>
        <fullName>E20</fullName>
    </customValue>
    <customValue>
        <fullName>E21</fullName>
    </customValue>
    <customValue>
        <fullName>E22</fullName>
    </customValue>
    <customValue>
        <fullName>E23</fullName>
    </customValue>
    <customValue>
        <fullName>E24</fullName>
    </customValue>
    <customValue>
        <fullName>E25</fullName>
    </customValue>
    <customValue>
        <fullName>E26</fullName>
    </customValue>
    <customValue>
        <fullName>E27</fullName>
    </customValue>
    <customValue>
        <fullName>E28</fullName>
    </customValue>
    <customValue>
        <fullName>E29</fullName>
    </customValue>
    <customValue>
        <fullName>E30</fullName>
    </customValue>
    <customValue>
        <fullName>E31</fullName>
    </customValue>
    <customValue>
        <fullName>E32</fullName>
    </customValue>
    <customValue>
        <fullName>E33</fullName>
    </customValue>
    <customValue>
        <fullName>E34</fullName>
    </customValue>
    <customValue>
        <fullName>E35</fullName>
    </customValue>
    <customValue>
        <fullName>E36</fullName>
    </customValue>
    <masterLabel>Código de evento</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Departamento_Solicitante.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Reclamaciones</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Auditoría de Gestión</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Coordinadores de cuentas</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Financiero</label>
    </customValue>
    <description>Listado de Departamento Solicitantes</description>
    <masterLabel>Departamento Solicitante</masterLabel>
</GlobalValueSet>

src/classes/Test_CierreReclamaciones.cls
@isTest
private class Test_CierreReclamaciones {
    
    private static Case reclamacion;
	private static Case reclCampos;
    private static Account compania;
    private static ServiceContract poliza;
	private static WorkOrder ordTbj;
    private static Propuesta_de_evento__c evento;
    private static Case reclamacionFake;
    private static Propuesta_de_abono__c propAbono;
    private static User usuari;

	
	private static void inicializarVariables(){
		Baipas.establecerVariableControl();
        Profile perfil = [SELECT Id FROM Profile WHERE Name = 'Administrador del sistema'];
        usuari = Util_Tests.nuevoUsuario('pruebas','pruebas','asdd@hotmail.com','pruebas','pruebas',perfil);
        insert usuari;
		compania = Util_Tests.crearCuentaCompania('SegurCaixa', '1018','X1234567X');
		insert compania;
        Account cuentaSecundaria = Util_Tests.crearCuentaB2BSec('Alberto2','1080', compania.Id);
        cuentaSecundaria.CUE_TXT_Numero_Documento__c = '89074907R';
        cuentaSecundaria.CUE_SEL_Tipo_Documento__c = 'N';
        insert cuentaSecundaria;
		Tipo_Producto_CIA__c tipoProducto = Util_Tests.crearTipoProductoCIA('SEGURCAIXA - Hogar', '01', compania.Id);
		insert tipoProducto;
		Producto_CIA__c producto = Util_Tests.crearProductoCIA('Segurcaixa - HOGAR', '01', tipoProducto.Id);
		insert producto;
		
		ServiceContract poliza = Util_Tests.crearPolizaContrato('Alberto', cuentaSecundaria.Id, compania.Id, producto.Id);
		insert poliza;
		Procedencia__c procedencia = Util_Tests.crearProcedencia(0.00, 0, 1, 0, 0, compania.Id, '1620334609050', 'CAS_Solicitud_de_Servicio_B2B_B2B2C;CAS_Servicio_B2B_B2B2C');
		procedencia.PROC_SEL_Motivos_Anulacion__c = '02;03';
		procedencia.PROC_CAS_No_Requiere_Albaran__c = true;
		insert procedencia;
		reclamacion = Util_Tests.crearCasoReclamacion(poliza.Id, compania.Id, compania.Id);
		reclamacion.CAS_LKP_Procedencia__c = procedencia.Id;
		insert reclamacion;

        
		
	}
	

	static testMethod void testCierreReclamaciones(){
		inicializarVariables();
		Test.startTest();
		PageReference pageRef = Page.CierreReclamaciones;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('id',reclamacion.Id);
		ApexPages.StandardController stdc = new ApexPages.StandardController(reclamacion);
		CierreReclamaciones clase = new CierreReclamaciones(stdc);
		List<SelectOption> estados = clase.getOpcionesEstado();
		reclamacion.Status = Label.CAS_ESTADO_CERRADO_FACTURADO;
        clase.reclCampos.CAS_SEL_Padre_reclamacion__c = '1';
		clase.reclCampos.CAS_SEL_Reclamacion__c = '002';
        clase.reclCampos.CAS_SEL_Comunicador_Recl__c = '003';
		clase.reclCampos.CAS_SEL_Naturaleza__c = '001';
		List<SelectOption> motivos = clase.getOpcionesCierre();
		reclamacion.CAS_SEL_Motivo_de_Cierre__c = '';
		clase.guardar();
		Test.stopTest();

	}
    
    	static testMethod void partidasLLenas(){
		inicializarVariables();
        reclamacion.status = Label.PAR_ESTADO_PENDIENTE;
        update reclamacion;
		Test.startTest();
		PageReference pageRef = Page.CierreReclamaciones;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('id',reclamacion.Id);
		ApexPages.StandardController stdc = new ApexPages.StandardController(reclamacion);
		CierreReclamaciones clase = new CierreReclamaciones(stdc);
		List<SelectOption> estados = clase.getOpcionesEstado();
		clase.reclCampos.CAS_SEL_Padre_reclamacion__c = '1';
		clase.reclCampos.CAS_SEL_Reclamacion__c = '001';
		clase.reclCampos.CAS_SEL_Naturaleza__c = '001';
       	system.debug(clase.reclamacion  + ' claseeeeeee');
        WorkType tipoTrabajo = Util_Tests.crearTipoTrabajo('Aplicación de estetica', '02', 120.00);
		insert tipoTrabajo;
		ordTbj = Util_Tests.crearOrdenTrabajo('0010100244', '02', tipoTrabajo.Id,reclamacion.Id);
		ordTbj.Status = Label.OTR_ESTADO_EN_ESPERA_GESTOR_INDICACIONES;
		ordTbj.OTR_TXT_Estado_Anterior__c = Label.OTR_ESTADO_ESPERA_PROF_PEND_TERMINAR;
		insert ordTbj;
        WorkOrderLineItem partidaWO = new WorkOrderLineItem();
		partidaWO = Util_Tests.crearNuevaPartidaTrabajo(ordTbj.Id);
        insert partidaWO;
        evento = new Propuesta_de_Evento__c();
		evento.EV_AB_SEL_Tipo_de_Evento__c = 'Cobro';
        evento.EV_AB_LKP_Imputar_a_profesional__c = ordTbj.OTR_LKP_Recurso_Servicio__c;
        evento.EV_DIV_Importe_a_imputar_Departamento__c = 100;
		evento.EV_AB_SEL_Descripcion__c = 'E19';
		evento.EV_AB_LKP_Orden_de_Trabajo__c = ordTbj.Id;
		evento.EV_AB_SEL_Departamento_Solicitante__c = '2';
		evento.EV_AB_SEL_Estado__c = '04'; //Diferente a Label.EV_AB_ESTADO_APROBADO and Label.EV_AB_ESTADO_RECHAZADO
		evento.EV_AB_LKP_Caso__c = reclamacion.Id;
            
		insert evento;
		clase.guardar();
		Test.stopTest();
	}
      
      	static testMethod void CamposReclamacion(){
        
     	inicializarVariables();
        reclamacion.status = Label.PAR_ESTADO_PENDIENTE;
        update reclamacion;
        reclamacionFake = new Case();
        reclamacionFake.AccountId = compania.Id;
        reclamacionFake.CAS_LKP_Compania__c = compania.Id;
        insert reclamacionFake;
		Test.startTest();
		PageReference pageRef = Page.CierreReclamaciones;
		Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('id',reclamacion.Id);
		ApexPages.StandardController stdc = new ApexPages.StandardController(reclamacion);
		CierreReclamaciones clase = new CierreReclamaciones(stdc);
		List<SelectOption> estados = clase.getOpcionesEstado();
		clase.reclCampos.CAS_SEL_Padre_reclamacion__c = '1';
        clase.reclCampos.CAS_SEL_Conformidad_del_Cliente__c = '';
        clase.reclCampos.CAS_SEL_Conformidad_del_Cliente_2__c = '';
        clase.reclCampos.CAS_SEL_Conformidad_del_Cliente_3__c = '';  
		clase.reclCampos.CAS_SEL_Reclamacion__c = '001';
		clase.reclCampos.CAS_SEL_Naturaleza__c = '001';
       	system.debug(clase.reclamacion  + ' claseeeeeee');
        WorkType tipoTrabajo = Util_Tests.crearTipoTrabajo('Aplicación de estetica', '02', 120.00);
		insert tipoTrabajo;
		ordTbj = Util_Tests.crearOrdenTrabajo('0010100244', '02', tipoTrabajo.Id,reclamacionFake.Id);
		ordTbj.Status = Label.OTR_ESTADO_EN_ESPERA_GESTOR_INDICACIONES;
		ordTbj.OTR_TXT_Estado_Anterior__c = Label.OTR_ESTADO_ESPERA_PROF_PEND_TERMINAR;
		insert ordTbj;
        WorkOrderLineItem partidaWO = new WorkOrderLineItem();
		partidaWO = Util_Tests.crearNuevaPartidaTrabajo(ordTbj.Id);
        insert partidaWO;
		clase.guardar();
            
        clase.reclCampos.CAS_SEL_Padre_reclamacion__c = '1';
        clase.reclCampos.CAS_SEL_Conformidad_del_Cliente__c = '1';
        clase.reclCampos.CAS_SEL_Conformidad_del_Cliente_2__c = '1';
        clase.reclCampos.CAS_SEL_Conformidad_del_Cliente_3__c = '1';  
		clase.reclCampos.CAS_SEL_Reclamacion__c = '001';
		clase.reclCampos.CAS_SEL_Naturaleza__c = '001'; 
        clase.reclCampos.CAS_LKP_Responsable_Reclamacion__c = usuari.Id ;      	
        clase.comentario = 'TEST OK Espero que con estos caracteres sea suficiente' ;
 
         clase.guardar();   
            
		Test.stopTest();
        
    }
    
    
    
    
}