src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_SEL_Gremio__c</fullName>
        <description>Gremio vinculado a la orden de trabajo.</description>
        <label>Gremio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Gremios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OTR_TXT_Num_OrdenTrabajo_HS__c</fullName>
        <description>Nº de Orden de Trabajo HomeServe. Identificador exclusivo de la Orden de Trabajo.</description>
        <externalId>true</externalId>
        <label>Nº de Servicio HS</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_Rest_Query_WorkOrder.cls
@isTest
public without sharing class Test_Rest_Query_WorkOrder {
	@isTest
	public static void testUtil(){
        baipas.establecerVariableControl();
        Account compania = Util_Tests.crearCuentaCompania('SegurCaixa','1018','X1234567X');
		insert compania;
        Account cuentaPrincipal = Util_Tests.crearCuentaB2BPpal('B2BPrincipal','111019','X1134567X');
        cuentaPrincipal.Type = '01';
        insert cuentaPrincipal;
        Account cuenta = Util_Tests.crearCuentaB2BSec('Asegurado','101120',cuentaPrincipal.Id,'X1114567X');
        cuenta.CUE_LKP_Cliente_contable__c = cuentaPrincipal.Id;
        cuenta.Type = '01';
        insert cuenta;
        
		Tipo_Producto_CIA__c tipoProductoCIA = Util_Tests.crearTipoProductoCIA('SegurCaixa - HOGAR','01',compania.ID);
		system.debug('@@@@@@@@@@@ '+tipoProductoCIA);
		insert tipoProductoCIA;
		Producto_CIA__c productoCIA = Util_Tests.crearProductoCIA('KIT 107','12345678',tipoProductoCIA.Id);
		insert productoCIA;
		ServiceContract poliza = Util_Tests.crearPolizaContrato('2277393',compania.Id,cuenta.Id,productoCIA.Id);
		Case caso = Util_Tests.crearCasoB2B(poliza.Id, cuenta.id, cuentaPrincipal.Id);
		caso.CAS_TXT_Identificador__c = '678576897';
		insert caso;
        
		WorkOrder w = new WorkOrder();

		w.Description = 'Cambio tubería';
		//w.DurationType = '120';
		//w.OTR_CAS_Foto_Requerida__c = true;
		//w.OTR_SEL_Gremio__c = 'Carpinteria';
		w.OTR_TXT_Num_OrdenTrabajo_HS__c = '122';
		w.Priority ='Low';
		w.Status = 'ok';
		w.Case = caso;
		w.Account = cuenta;

		insert w;
		baipas.deshabilitarVariableControl();
		Rest_Query_WorkOrder.doGet();
	}
}