src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Propuesta_de_Abono__c.object
<CustomObject>
    <fields>
        <fullName>AB_DIV_Importe_a_Imputar4__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar (Prof)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AB_DIV_Importe_a_Imputar__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar (Gestor)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AB_DIV_Importe_a_ingresar__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a ingresar (CIA/Cliente)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Imputar_a4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a (Prof)</label>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Imputar_a__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a (Gestor)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Ingresar_a__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ingresar a (CIA/Cliente)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Propuestas de Abonos (Ingresar a)</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_SEL_Descripcion_evento__c</fullName>
        <label>Descripción evento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>E01</fullName>
                </value>
                <value>
                    <fullName>E02</fullName>
                </value>
                <value>
                    <fullName>E03</fullName>
                </value>
                <value>
                    <fullName>E04</fullName>
                </value>
                <value>
                    <fullName>E11</fullName>
                </value>
                <value>
                    <fullName>E15</fullName>
                </value>
                <value>
                    <fullName>E16</fullName>
                </value>
                <value>
                    <fullName>E17</fullName>
                </value>
                <value>
                    <fullName>E18</fullName>
                </value>
                <value>
                    <fullName>E19</fullName>
                </value>
                <value>
                    <fullName>E20</fullName>
                </value>
                <value>
                    <fullName>E21</fullName>
                </value>
                <value>
                    <fullName>E22</fullName>
                </value>
                <value>
                    <fullName>E29</fullName>
                </value>
                <value>
                    <fullName>E37</fullName>
                </value>
                <value>
                    <fullName>E30</fullName>
                </value>
                <value>
                    <fullName>E31</fullName>
                </value>
                <value>
                    <fullName>E34</fullName>
                </value>
                <value>
                    <fullName>E32</fullName>
                </value>
                <value>
                    <fullName>E33</fullName>
                </value>
                <value>
                    <fullName>E36</fullName>
                </value>
                <value>
                    <fullName>E25</fullName>
                </value>
                <value>
                    <fullName>E26</fullName>
                </value>
                <value>
                    <fullName>E23</fullName>
                </value>
                <value>
                    <fullName>E24</fullName>
                </value>
                <value>
                    <fullName>E28</fullName>
                </value>
                <value>
                    <fullName>E35</fullName>
                </value>
                <value>
                    <fullName>E12</fullName>
                </value>
                <value>
                    <fullName>E111</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AB_SEL_Estado__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>En Curso</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Aprobado</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Rechazado</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Propuesta de Abono</label>
    <nameField>
        <displayFormat>AB-{0000000}</displayFormat>
        <label>Abono</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propuestas de Abonos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Propuesta_de_Evento__c.object
<CustomObject>
    <description>Objeto utilizado para modelar el proceso de liquidación y/o facturación a profesionales, clientes y compañías aseguradoras</description>
    <fields>
        <fullName>EV_AB_CAS_Evento_Ab_Facturado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Evento Facturado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EV_AB_DIV_Importe_a_liquidar_prof__c</fullName>
        <label>Importe a liquidar (Prof)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EV_AB_DIV_Importe_profesional__c</fullName>
        <label>Importe a Imputar (Prof)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EV_AB_LKP_Abono__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Abono padre</label>
        <referenceTo>Propuesta_de_Abono__c</referenceTo>
        <relationshipLabel>Propuestas de Eventos</relationshipLabel>
        <relationshipName>Propuestas_de_Eventos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_AB_LKP_Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Caso relacionado al Evento/Abono</description>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Propuestas de Eventos</relationshipLabel>
        <relationshipName>EV_AB_REL_Caso</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_AB_LKP_Orden_de_Trabajo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Orden de Trabajo relacionada al Evento/Abono</description>
        <label>Número Servicio</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipName>EV_AB_REL_Orden_de_Trabajo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_AB_LKP_Propuesta_de_Evento_Economico__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evento padre</label>
        <referenceTo>Propuesta_de_Evento__c</referenceTo>
        <relationshipLabel>Propuestas de Eventos</relationshipLabel>
        <relationshipName>Propuestas_de_Eventos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_AB_SEL_Descripcion__c</fullName>
        <label>Código</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GBL_SEL_Codigo_evento</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EV_AB_SEL_Estado__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>02</fullName>
                    <label>Aprobado</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Rechazado</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>Anulado</label>
                </value>
                <value>
                    <fullName>01</fullName>
                    <isActive>false</isActive>
                    <label>En Curso</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EV_AB_TXT_Identificador__c</fullName>
        <description>Identificador externo para la carga de eventos</description>
        <externalId>true</externalId>
        <label>Identificador</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Propuesta de Evento Económico</label>
    <nameField>
        <displayFormat>EV-{0000000}</displayFormat>
        <label>Evento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propuestas de Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceResource.object
<CustomObject>
    <fields>
        <fullName>RSE_LKP_Cuenta__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Cuenta del Profesional Contrato</description>
        <label>Cuenta de Profesional</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Profesional Contrato</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recursos de servicios</relationshipLabel>
        <relationshipName>Recursos_de_servicios</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_LKP_Recurso_Servicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Profesional (Perfil Técnico) vinculado a la Orden de Trabajo. Representa la FK al objeto ServiceResource. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto ServiceResource (ServiceResources.RSE_TXT_Codigo_Recurso__c): Código único del Profesional</description>
        <label>Profesional</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>ServiceResource.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Status</field>
                <operation>equals</operation>
                <value>Anulado, Anulado desde Inactivo, Cerrado, Cerrado Albarán Recibido, Cerrado Pdte. Albarán, Revisado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Órdenes de trabajo</relationshipLabel>
        <relationshipName>OTR_REL_Recurso_Servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GBL_SEL_Codigo_evento.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>E01</fullName>
    </customValue>
    <customValue>
        <fullName>E02</fullName>
    </customValue>
    <customValue>
        <fullName>E03</fullName>
    </customValue>
    <customValue>
        <fullName>E04</fullName>
    </customValue>
    <customValue>
        <fullName>E05</fullName>
    </customValue>
    <customValue>
        <fullName>E06</fullName>
    </customValue>
    <customValue>
        <fullName>E11</fullName>
    </customValue>
    <customValue>
        <fullName>E12</fullName>
    </customValue>
    <customValue>
        <fullName>E15</fullName>
    </customValue>
    <customValue>
        <fullName>E16</fullName>
    </customValue>
    <customValue>
        <fullName>E17</fullName>
    </customValue>
    <customValue>
        <fullName>E18</fullName>
    </customValue>
    <customValue>
        <fullName>E19</fullName>
    </customValue>
    <customValue>
        <fullName>E20</fullName>
    </customValue>
    <customValue>
        <fullName>E21</fullName>
    </customValue>
    <customValue>
        <fullName>E22</fullName>
    </customValue>
    <customValue>
        <fullName>E23</fullName>
    </customValue>
    <customValue>
        <fullName>E24</fullName>
    </customValue>
    <customValue>
        <fullName>E25</fullName>
    </customValue>
    <customValue>
        <fullName>E26</fullName>
    </customValue>
    <customValue>
        <fullName>E27</fullName>
    </customValue>
    <customValue>
        <fullName>E28</fullName>
    </customValue>
    <customValue>
        <fullName>E29</fullName>
    </customValue>
    <customValue>
        <fullName>E30</fullName>
    </customValue>
    <customValue>
        <fullName>E31</fullName>
    </customValue>
    <customValue>
        <fullName>E32</fullName>
    </customValue>
    <customValue>
        <fullName>E33</fullName>
    </customValue>
    <customValue>
        <fullName>E34</fullName>
    </customValue>
    <customValue>
        <fullName>E35</fullName>
    </customValue>
    <customValue>
        <fullName>E36</fullName>
    </customValue>
    <customValue>
        <fullName>E39</fullName>
    </customValue>
    <masterLabel>Código de evento</masterLabel>
</GlobalValueSet>

src/classes/Test_TRG_Handler_Propuesta_de_Evento.cls
@isTest
public without sharing class Test_TRG_Handler_Propuesta_de_Evento {
	
	private static Profile perfil;
	private static User usuario;
	private static Account compania;
	private static Account cuentaPrincipal;
	private static Account cuentaProfesionalPrincipal;
	private static Account cuentaProfesional;
	private static ServiceResource recursoServ;
	private static Account cuentaSec;
	private static Account cuentaAsegurado;
	private static Tipo_Producto_CIA__c tipoProductoCIA;
	private static Producto_CIA__c productoCia;
	private static ServiceContract poliza;
	private static Case casoSini;
	private static WorkType tipoTrabajo;
	private static WorkOrder ordenTrabajo;
	private static Propuesta_de_Abono__c propAbono;

	private static void inicializarVariables(){
		List<Account> listaCuentas = new List<Account>();
		perfil = [SELECT Id FROM Profile WHERE Name =: Label.PERFIL_GESTOR_FRONT_TRAMITACION];
		
		usuario = Util_Tests.nuevoUsuario('pruebas','pruebas','asdd@hotmail.com','pruebas','pruebas',perfil);
		insert usuario;

		compania = Util_Tests.crearCuentaCompania('SegurCaixa','1018','X1234567X');
		cuentaPrincipal = Util_Tests.crearCuentaB2BPpal('B2BPrincipal','1245678','X1134567X');
		cuentaProfesionalPrincipal = Util_Tests.crearCuentaB2C('PR123456','PR123456','X1234568X');

		listaCuentas.add(compania);
		listaCuentas.add(cuentaPrincipal);
		listaCuentas.add(cuentaProfesionalPrincipal);
		insert listaCuentas;

		cuentaProfesional = Util_Tests.crearCuentaProfesionalContrato('PR636325','PR636325','X1234567X',cuentaProfesionalPrincipal.id);
		cuentaProfesional.CUE_SEL_Tipo_de_Profesional__c = '01'; //AUTONOMO
		listaCuentas.add(cuentaProfesional);
		upsert listaCuentas;
		cuentaProfesional.CUE_SEL_Estado__c = '02';
		upsert listaCuentas;

		recursoServ = Util_Tests.crearRecursoServicio('PR636325_01_1', '00000', cuentaProfesional.Id, usuario);
		recursoServ.RSE_LKP_Cuenta__r = cuentaProfesional;
		insert recursoServ;

		cuentaSec=Util_Tests.crearCuentaB2BSec('Name','13132', cuentaPrincipal.Id, 'X5544663X');
		listaCuentas.add(cuentaSec);

		cuentaAsegurado = Util_Tests.crearCuentaAsegurado('Asegurado','1021','email@gmail.es','03629033R','nombre','apellido1','apellido2');
		cuentaAsegurado.CUE_LKP_CUENTA_Principal__c = cuentaPrincipal.id;
		listaCuentas.add(cuentaAsegurado);
		upsert listaCuentas;

		tipoProductoCIA = Util_Tests.crearTipoProductoCIA('SegurCaixa - HOGAR','01',compania.Id);
		insert tipoProductoCIA;

		productoCia=Util_Tests.crearProductoCIA('nombre','01', tipoProductoCIA.Id);
		insert productoCia;

		poliza=Util_Tests.crearPolizaContrato('4523814',compania.Id, cuentaPrincipal.Id, productoCia.Id);
		insert poliza;

		createCaseSini();

		tipoTrabajo = Util_Tests.crearTipoTrabajo('Siniestro', '21', 2.5);
		insert tipoTrabajo;

		ordenTrabajo = Util_Tests.crearOrdenTrabajo('26032018', '75', tipoTrabajo.id, casoSini.Id);
		ordenTrabajo.OTR_LKP_Recurso_Servicio__c = recursoServ.id;
		Test.startTest();
		insert ordenTrabajo;
		
		propAbono = new Propuesta_de_Abono__c();
		propAbono.AB_SEL_Estado__c = '04';
		propAbono.AB_LKP_CASO__c = casoSini.id;
        propAbono.AB_LKP_Imputar_a__c = usuario.id;
        propAbono.AB_LKP_Ingresar_a__c  = casoSini.AccountId;
        propAbono.AB_DIV_Importe_a_Imputar__c = 50;
        propAbono.AB_SEL_Descripcion_evento__c = 'E11';
        propAbono.AB_DIV_Importe_a_ingresar__c = 50;
        propAbono.AB_LKP_Imputar_a4__c = ordenTrabajo.OTR_LKP_Recurso_Servicio__c;
        propAbono.AB_DIV_Importe_a_Imputar4__c = 1;
        insert propAbono;
	}

	private static void createCaseSini(){
		poliza.AccountId = cuentaAsegurado.id;
		update poliza;

		casoSini = Util_Tests.crearCasoSini(poliza.Id,cuentaAsegurado.Id,cuentaPrincipal.Id);
		casoSini.CAS_TXT_Nombre__c = 'casoEvento';
		casoSini.CAS_DIV_Total_Facturar_Cliente_AI__c = 101.00;
		casoSini.CAS_DIV_Total_Facturar_Profesional__c = 101.00;
		insert casoSini;
		
	}

	@isTest static void insertarEvento(){

		
		inicializarVariables();

		List<Propuesta_de_Evento__c> listaEventos = new List<Propuesta_de_Evento__c>();

		Propuesta_de_Evento__c propEvent1 = Util_Tests.crearPropuestaDeEvento('04', casoSini.id, ordenTrabajo.id);
		listaEventos.add(propEvent1);
		
		Propuesta_de_Evento__c propEvento = new Propuesta_de_Evento__c(EV_AB_SEL_Estado__c = '04', EV_AB_LKP_Caso__c = casoSini.Id);
		propEvento.EV_AB_SEL_Descripcion__c = 'E01';
		propEvento.EV_AB_LKP_Orden_de_Trabajo__c = ordenTrabajo.Id;
		listaEventos.add(propEvento);

		Propuesta_de_Evento__c propEvento4 = new Propuesta_de_Evento__c(EV_AB_SEL_Estado__c = '04', EV_AB_LKP_Caso__c = casoSini.Id);
		propEvento4.EV_AB_SEL_Descripcion__c = 'E23';
		propEvento4.EV_AB_LKP_Orden_de_Trabajo__c = ordenTrabajo.Id;
		listaEventos.add(propEvento4);

        insert listaEventos;
        Propuesta_de_Evento__c propEvento3 = new Propuesta_de_Evento__c(EV_AB_SEL_Estado__c = '04', EV_AB_LKP_Caso__c = casoSini.Id);
        propEvento3.EV_AB_SEL_Descripcion__c = 'E39';
        propEvento3.EV_AB_LKP_Orden_de_Trabajo__c = ordenTrabajo.Id;
        propEvento3.EV_AB_LKP_Propuesta_de_Evento_Economico__c = propEvento4.Id;
        propEvento3.EV_AB_DIV_Importe_a_liquidar_prof__c = 50;
        listaEventos.add(propEvento3);

        Propuesta_de_Evento__c propEvento28 = new Propuesta_de_Evento__c(EV_AB_SEL_Estado__c = '04', EV_AB_LKP_Caso__c = casoSini.Id);
        propEvento28.EV_AB_SEL_Descripcion__c = 'E28';
        propEvento28.EV_AB_DIV_Importe_profesional__c = 50;
        propEvento28.CreatedDate = system.now();
        propEvento28.EV_AB_LKP_Propuesta_de_Evento_Economico__c = propEvento4.Id;
        listaEventos.add(propEvento28);
        
        Propuesta_de_Evento__c propEvento35 = new Propuesta_de_Evento__c(EV_AB_SEL_Estado__c = '04', EV_AB_LKP_Caso__c = casoSini.Id);
        propEvento35.EV_AB_SEL_Descripcion__c = 'E35';
        propEvento35.EV_AB_LKP_Propuesta_de_Evento_Economico__c = propEvento4.Id;
        propEvento35.EV_AB_DIV_Importe_a_liquidar_prof__c = 50;
        listaEventos.add(propEvento35);

        upsert listaEventos;

        Test.stopTest();
    }
    
    @isTest static void updateEvento(){

    	inicializarVariables();

    	Propuesta_de_Evento__c propEvento = new Propuesta_de_Evento__c(EV_AB_SEL_Estado__c = '04', EV_AB_LKP_Caso__c = casoSini.Id);
        propEvento.EV_AB_SEL_Descripcion__c = 'E01';
        propEvento.EV_AB_LKP_Orden_de_Trabajo__c = ordenTrabajo.Id;
		propEvento.EV_AB_TXT_Identificador__c = '13042018';
		insert propEvento;
		
		propEvento.EV_AB_SEL_Estado__c = '02';
		propEvento.EV_AB_CAS_Evento_Ab_Facturado__c = true;
		propEvento.EV_AB_LKP_Orden_de_Trabajo__c = ordenTrabajo.Id;
		propEvento.EV_AB_LKP_Abono__c = propAbono.Id;
		
		update propEvento;
        Test.stopTest();
	}
	
}