src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>CSE_CAS_Cambio_de_cita__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cambio de cita</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSE_SEL_Gremio__c</fullName>
        <label>Gremio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Gremios</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>POL_LKP_Version_Actual__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versión Actual</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Version_ContratoServicio__c.POLV_LKP_PolizaContrato__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Version_ContratoServicio__c</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>Contratos_de_servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Version_ContratoServicio__c.object
<CustomObject>
    <description>Representa cada una de las versiones de una Póliza o Contrato.</description>
    <label>Versión Póliza/Contrato</label>
    <nameField>
        <label>Versión Póliza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versiones Póliza/Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_LKP_Primera_Cita__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primera Cita de Servicio vinculada a la Orden de Trabajo. Representa la FK al objeto ServiceAppoinment. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto ServiceAppoinment</description>
        <label>Primera Cita de Servicio</label>
        <referenceTo>ServiceAppointment</referenceTo>
        <relationshipLabel>Órdenes de trabajo</relationshipLabel>
        <relationshipName>Ordenes_de_trabajo</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_Rest_B2B2C_CambioCita.cls
/**
 * Clase de Test de la Clase Rest_B2B2C_CambioCita
 *
 * @author EVERIS
 *
 */
@isTest(SeeAllData=true)
public without sharing class Test_Rest_B2B2C_CambioCita {
	
	private static Account cuentaPrincipal {get; set;}
	private static Account cuentaSecundaria {get; set;}
	private static Account compania {get; set;}
	private static Tipo_Producto_CIA__c tipoProductoCIA {get; set;}
	private static Producto_CIA__c productoCIA {get; set;}
	private static ServiceContract poliza {get; set;}
	private static Version_ContratoServicio__c versionPoliza {get; set;}
	private static Case caso {get; set;}
	private static WorkType tipoTrabajo {get; set;}
	private static WorkOrder ordenTrabajo {get; set;}
	private static ServiceAppointment citaServicio {get; set;}
	
	@isTest static void inicializarVariables(){
		Baipas.establecerVariableControl();
		cuentaPrincipal = Util_Tests.crearCuentaB2BPpal('B2BPrincipal', '2224', 'G69746881');
		cuentaPrincipal.ShippingPostalCode = '28028';
		insert cuentaPrincipal;
		cuentaSecundaria = Util_Tests.crearCuentaB2BSec('B2BSecundaria','22242', cuentaPrincipal.Id, 'R7553064B');
		insert cuentaSecundaria;
		compania = Util_Tests.crearCuentaCompania('Worten','50751322','S5735385F');
		insert compania;
		tipoProductoCIA = Util_Tests.crearTipoProductoCIA('Worten - TV','01',compania.ID);
		insert tipoProductoCIA;
		productoCIA = Util_Tests.crearProductoCIA('KIT 107','12345678',tipoProductoCIA.Id);
		insert productoCIA;
		poliza = Util_Tests.crearPolizaContrato('2277393',compania.Id,cuentaPrincipal.Id,productoCIA.Id);
		insert poliza;
		versionPoliza = Util_Tests.crearVersionPoliza(poliza.Id, Date.newInstance(2018, 06, 12));
		insert versionPoliza;
		poliza.POL_LKP_Version_Actual__c = versionPoliza.Id;
		update poliza;
		
		caso = Util_Tests.crearCasoB2B(poliza.Id, cuentaPrincipal.Id, compania.Id);
		insert caso;
		tipoTrabajo = Util_Tests.crearTipoTrabajo('Tipo de Trabajo por Defecto','21', 2);
		insert tipoTrabajo;
		ordenTrabajo = Util_Tests.crearOrdenTrabajo('19210.0','21',tipoTrabajo.Id,caso.Id);
		ordenTrabajo.AccountId = cuentaPrincipal.Id;
		ordenTrabajo.Status = '002';
		insert ordenTrabajo;
        
        caso.CAS_LKP_Orden_Trabajo_Principal__c = ordenTrabajo.Id;
        update caso;
		/*datetime fechaInicio = datetime.newInstance(2018, 05, 22);
		datetime fechaVencimiento = datetime.newInstance(2018, 05, 31);
		citaServicio = Util_Tests.crearCitaServicio('MADRID', 'España', '28025','Madrid', 'CALLE Chimbo 22 2 B', fechaInicio, fechaVencimiento);
		citaServicio.Status = 'Pte. de asignar';
		citaServicio.ParentRecordId = ordenTrabajo.Id;
		citaServicio.CSE_SEL_Gremio__c = '21';
        citaServicio.CSE_CAS_Cambio_de_cita__c  = true;
		insert citaServicio;
		ordenTrabajo.OTR_LKP_Primera_Cita__c = citaServicio.Id;
		update ordenTrabajo;*/
        Baipas.deshabilitarVariableControl();
	}
	
	/*Test*/
	@isTest
    static void Test(){
		inicializarVariables();
		test.startTest();
		
		Rest_B2B2C_CambioCita.Resultado respuesta = new Rest_B2B2C_CambioCita.Resultado();
		List<ServiceAppointment> sa = [SELECT AppointmentNumber, CSE_SEL_Gremio__c, Id FROM ServiceAppointment WHERE ParentRecordId =: ordenTrabajo.Id];
		List<Case> casoList = [SELECT CAS_CAS_Urgente__c, Id FROM Case WHERE Id =: caso.Id];
		List<Account> cuentaList = [SELECT CUE_CAS_Ola_calor__c, Id FROM Account WHERE Id =: cuentaPrincipal.Id];
		
		//Caso KO. Formato de datos no correcto
		respuesta = Rest_B2B2C_CambioCita.setAppointment('', '07', sa[0].AppointmentNumber, 'test cambio cita', Date.newInstance(2018,05,20));
		//Caso KO. No existe la cita
		respuesta = Rest_B2B2C_CambioCita.setAppointment('2018-05-28', '07', 'SA-2222', 'test cambio cita', Date.newInstance(2018,05,20));
		//Caso OK.
		respuesta = Rest_B2B2C_CambioCita.setAppointment('2018-05-28', '07', sa[0].AppointmentNumber, 'test cambio cita', Date.newInstance(2018,05,20));
		
		test.stopTest();
	}
}