src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>POL_LKP_Producto_Cia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Producto asociado a la póliza</description>
        <label>Producto</label>
        <referenceTo>Producto_CIA__c</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>POL_REL_Producto</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <fields>
        <fullName>TPR_SEL_Interlocutores_Seleccionables__c</fullName>
        <description>Listado de Interlocutores que el gestor puede seleccionar</description>
        <label>Interlocutores Seleccionables</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Tipos_Interlocutor</valueSetName>
        </valueSet>
    </fields>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Tipos_Interlocutor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administrador de la Finca</fullName>
    </customValue>
    <customValue>
        <fullName>Agente</fullName>
    </customValue>
    <customValue>
        <fullName>Asegurado/a</fullName>
    </customValue>
    <customValue>
        <fullName>Empleado/a del negocio</fullName>
    </customValue>
    <customValue>
        <fullName>Hijo/a</fullName>
    </customValue>
    <customValue>
        <fullName>Inquilino</fullName>
    </customValue>
    <customValue>
        <fullName>Marido</fullName>
    </customValue>
    <customValue>
        <fullName>Padre</fullName>
    </customValue>
    <customValue>
        <fullName>Perito</fullName>
    </customValue>
    <customValue>
        <fullName>Portero</fullName>
    </customValue>
    <customValue>
        <fullName>Presidente</fullName>
    </customValue>
    <customValue>
        <fullName>Propietario</fullName>
    </customValue>
    <customValue>
        <fullName>Empleado de la sucursal</fullName>
    </customValue>
    <customValue>
        <fullName>Compañía</fullName>
    </customValue>
    <customValue>
        <fullName>Madre</fullName>
    </customValue>
    <customValue>
        <fullName>Mujer</fullName>
    </customValue>
    <customValue>
        <fullName>Pareja</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>Otros familiares</fullName>
    </customValue>
    <customValue>
        <fullName>Vecino/a</fullName>
    </customValue>
    <masterLabel>Tipos de Interlocutor</masterLabel>
</GlobalValueSet>

src/classes/Test_Util_Poliza_Contrato.cls
@isTest
public without sharing class Test_Util_Poliza_Contrato {

    static testMethod void util_Poliza_Contrato(){
        Account compania = Util_Tests.crearCuentaCompania('SegurCaixa', '1018','X1234567X');
		insert compania;
		Account asegurado = Util_Tests.crearCuentaAsegurado('Miguel', '2018','miguel@gmail.es', '46745581G','Miguel', 'Sagrado', 'Velasco');
		asegurado.CUE_SEL_Tipo_Documento__c = 'N';
        asegurado.CUE_TXT_Numero_Documento__c='03522374Q';
        asegurado.CUE_LKP_Cuenta_principal__c = compania.Id;
		insert asegurado;
		Date startDate = Date.newInstance(2016, 12, 31);
        Tipo_Producto_CIA__c tipoProductoCIA = Util_Tests.crearTipoProductoCIA('SegurCaixa - HOGAR','01',compania.id);
        tipoProductoCIA.TPR_SEL_Interlocutores_Seleccionables__c = 'Administrador de la Finca';
        insert tipoProductoCIA;
        Producto_Cia__c productoCIA = Util_Tests.crearProductoCIA('KIT 107','12345678',tipoProductoCIA.Id);
        insert productoCIA;
		ServiceContract poliza = Util_Tests.crearPolizaContrato('poliza', compania.Id, asegurado.Id, productoCIA.Id);
    	poliza.POL_LKP_Producto_Cia__c = productoCIA.Id;
        insert poliza;
        Callout_ConsultaPolizaVesta_RP resError =new Callout_ConsultaPolizaVesta_RP();
        List<ServiceContract> scList = Util_Poliza_Contrato.queryPolizaById(new Set<Id>{poliza.Id}).values();
        //List<ServiceContract> scList = Util_Poliza_Contrato.queryMapPoliza('Id = \''+poliza.Id+'\'').values();
        //List<ServiceContract> scList = Util_Poliza_Contrato.queryPoliza(poliza.Id);
        ServiceContract nuevaPoliza = Util_Poliza_Contrato.nuevaPoliza(resError, asegurado.Id);
        List<SelectOption> so = Util_Poliza_Contrato.cargarSelectorTipoInterlocutor(poliza);
        List<SelectOption> so1 = Util_Poliza_Contrato.cargarSelectorTipoRiesgo(poliza, null);
    }
}