src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Propuesta_de_Abono__c.object
<CustomObject>
    <fields>
        <fullName>AB_CAS_Abono_Automatico__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Representa si el abono es generado de forma automática</description>
        <label>Abono Automático</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AB_CAS_Abono_Liquidado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Abono Liquidado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AB_DIV_Importe_a_Imputar2__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar (Gestor)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AB_DIV_Importe_a_Imputar3__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar (Gestor)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AB_DIV_Importe_a_Imputar4__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar (Prof)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AB_DIV_Importe_a_Imputar5__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar (Prof)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AB_DIV_Importe_a_Imputar6__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar (Prof)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AB_DIV_Importe_a_Imputar__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a Imputar (Gestor)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AB_DIV_Importe_a_ingresar__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Importe a ingresar (CIA/Cliente)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intervención</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Imputar_a2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a (Gestor)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Propuestas_de_Abonos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Imputar_a3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a (Gestor)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Propuestas_de_Abonos2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Imputar_a4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a (Prof)</label>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Imputar_a5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a (Prof)</label>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Propuestas de Abonos (Imputar a)</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Imputar_a6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a (Prof)</label>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Propuestas de Abonos (Imputar a)</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Imputar_a__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Imputar a (Gestor)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Ingresar_a__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ingresar a (CIA/Cliente)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Propuestas de Abonos (Ingresar a)</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_LKP_Orden_de_Trabajo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Número Servicio</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Propuestas de Abonos</relationshipLabel>
        <relationshipName>Propuestas_de_Abonos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AB_SEL_Descripcion_evento__c</fullName>
        <label>Descripción evento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>E01</fullName>
                </value>
                <value>
                    <fullName>E02</fullName>
                </value>
                <value>
                    <fullName>E03</fullName>
                </value>
                <value>
                    <fullName>E04</fullName>
                </value>
                <value>
                    <fullName>E11</fullName>
                </value>
                <value>
                    <fullName>E15</fullName>
                </value>
                <value>
                    <fullName>E16</fullName>
                </value>
                <value>
                    <fullName>E17</fullName>
                </value>
                <value>
                    <fullName>E18</fullName>
                </value>
                <value>
                    <fullName>E19</fullName>
                </value>
                <value>
                    <fullName>E20</fullName>
                </value>
                <value>
                    <fullName>E21</fullName>
                </value>
                <value>
                    <fullName>E22</fullName>
                </value>
                <value>
                    <fullName>E29</fullName>
                </value>
                <value>
                    <fullName>E37</fullName>
                </value>
                <value>
                    <fullName>E30</fullName>
                </value>
                <value>
                    <fullName>E31</fullName>
                </value>
                <value>
                    <fullName>E34</fullName>
                </value>
                <value>
                    <fullName>E32</fullName>
                </value>
                <value>
                    <fullName>E33</fullName>
                </value>
                <value>
                    <fullName>E36</fullName>
                </value>
                <value>
                    <fullName>E25</fullName>
                </value>
                <value>
                    <fullName>E26</fullName>
                </value>
                <value>
                    <fullName>E23</fullName>
                </value>
                <value>
                    <fullName>E24</fullName>
                </value>
                <value>
                    <fullName>E28</fullName>
                </value>
                <value>
                    <fullName>E35</fullName>
                </value>
                <value>
                    <fullName>E12</fullName>
                </value>
                <value>
                    <fullName>E111</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AB_SEL_Estado__c</fullName>
        <label>Estado</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>En Curso</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Aprobado</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Rechazado</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Propuesta de Abono</label>
    <nameField>
        <displayFormat>AB-{0000000}</displayFormat>
        <label>Abono</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propuestas de Abonos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceResource.object
<CustomObject>
    <fields>
        <fullName>RSE_LKP_Cuenta__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Cuenta del Profesional Contrato</description>
        <label>Cuenta de Profesional</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Profesional Contrato</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recursos de servicios</relationshipLabel>
        <relationshipName>Recursos_de_servicios</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_LKP_Recurso_Servicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Profesional (Perfil Técnico) vinculado a la Orden de Trabajo. Representa la FK al objeto ServiceResource. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto ServiceResource (ServiceResources.RSE_TXT_Codigo_Recurso__c): Código único del Profesional</description>
        <label>Profesional</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>ServiceResource.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Status</field>
                <operation>equals</operation>
                <value>Anulado, Anulado desde Inactivo, Cerrado, Cerrado Albarán Recibido, Cerrado Pdte. Albarán, Revisado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Órdenes de trabajo</relationshipLabel>
        <relationshipName>OTR_REL_Recurso_Servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_TRG_Handler_Propuesta_de_Abono.cls
@isTest
public without sharing class Test_TRG_Handler_Propuesta_de_Abono {

	private static Profile perfil;
	private static User usuario;
	private static User usuario2;
	private static Account compania;
	private static Account cuentaPrincipal;
	private static Account cuentaProfesionalPrincipal;
	private static Account cuentaProfesional;
	private static ServiceResource recursoServ;
	private static ServiceResource recursoServ2;
	private static Account cuentaSec;
	private static Account cuentaAsegurado;
	private static Tipo_Producto_CIA__c tipoProductoCIA;
	private static Producto_CIA__c productoCia;
	private static ServiceContract poliza;
	private static Case casoB2B;
	private static Case casoSini;
	private static WorkType tipoTrabajo;
	private static WorkOrder ordenTrabajo;
	private static Propuesta_de_Abono__c propAbono;

	private static void inicializarVariables(){
		List<Account> listaCuentas = new List<Account>();
		perfil = [SELECT Id FROM Profile WHERE Name =: Label.PERFIL_GESTOR_FRONT_TRAMITACION];
		Profile perfil2 = [SELECT Id FROM Profile WHERE Name =: Label.PERFIL_GESTOR_FRONT_TRAMITACION];

		usuario = Util_Tests.nuevoUsuario('pruebas','pruebas','asdd@hotmail.com','pruebas','pruebas',perfil);
		insert usuario;
		usuario2 = Util_Tests.nuevoUsuario('pruebas2','pruebas2','asdd2@hotmail.com','pruebas2','pruebas2',perfil2);
		insert usuario2;

		compania = Util_Tests.crearCuentaCompania('SegurCaixa','1018','X1234567X');
		cuentaPrincipal = Util_Tests.crearCuentaB2BPpal('B2BPrincipal','1245678','X1134567X');
		cuentaProfesionalPrincipal = Util_Tests.crearCuentaB2C('PR123456','PR123456','X1234568X');

		listaCuentas.add(compania);
		listaCuentas.add(cuentaPrincipal);
		listaCuentas.add(cuentaProfesionalPrincipal);
		insert listaCuentas;

		cuentaProfesional = Util_Tests.crearCuentaProfesionalContrato('PR636325','PR636325','X1234567X',cuentaProfesionalPrincipal.id);
		cuentaProfesional.CUE_SEL_Tipo_de_Profesional__c = '01'; //AUTONOMO
		listaCuentas.add(cuentaProfesional);
		upsert listaCuentas;
		cuentaProfesional.CUE_SEL_Estado__c = '02';
		upsert listaCuentas;

		recursoServ = Util_Tests.crearRecursoServicio('PR636325_01_1', '00000', cuentaProfesional.Id, usuario);
		recursoServ.RSE_LKP_Cuenta__r = cuentaProfesional;
		insert recursoServ;

		recursoServ2 = Util_Tests.crearRecursoServicio('PR636325_01_2', '00001', cuentaProfesional.Id, usuario2);
		recursoServ2.isActive = true;
		insert recursoServ2;

		cuentaSec=Util_Tests.crearCuentaB2BSec('Name','13132', cuentaPrincipal.Id, 'X5544663X');
		listaCuentas.add(cuentaSec);

		cuentaAsegurado = Util_Tests.crearCuentaAsegurado('Asegurado','1021','email@gmail.es','03629033R','nombre','apellido1','apellido2');
		cuentaAsegurado.CUE_LKP_CUENTA_Principal__c = cuentaPrincipal.id;
		listaCuentas.add(cuentaAsegurado);
		upsert listaCuentas;

		tipoProductoCIA = Util_Tests.crearTipoProductoCIA('SegurCaixa - HOGAR','01',compania.Id);
		insert tipoProductoCIA;

		productoCia=Util_Tests.crearProductoCIA('nombre','01', tipoProductoCIA.Id);
		insert productoCia;

		poliza=Util_Tests.crearPolizaContrato('4523814',compania.Id, cuentaPrincipal.Id, productoCia.Id);
		insert poliza;

		createCaseSini();

		tipoTrabajo = Util_Tests.crearTipoTrabajo('Siniestro', '21', 2.5);
		insert tipoTrabajo;

		ordenTrabajo = Util_Tests.crearOrdenTrabajo('26032018', '75', tipoTrabajo.id, casoSini.Id);
		ordenTrabajo.OTR_LKP_Recurso_Servicio__c = recursoServ.id;
		Test.startTest();
		insert ordenTrabajo;

	}

	private static void createCaseSini(){
		poliza.AccountId = cuentaAsegurado.id;
		update poliza;

		casoSini = Util_Tests.crearCasoSini(poliza.Id,cuentaAsegurado.Id,cuentaPrincipal.Id);
		casoSini.CAS_TXT_Nombre__c = 'casoEvento';
		casoSini.CAS_DIV_Total_Facturar_Cliente_AI__c = 101.00;
		casoSini.CAS_DIV_Total_Facturar_Profesional__c = 101.00;
		insert casoSini;
		
	}

	@isTest static void insertarAbono(){		
		inicializarVariables();		
																				
		Propuesta_de_Abono__c propAbono = new Propuesta_de_Abono__c(AB_SEL_Estado__c = '04', AB_SEL_Descripcion_evento__c = 'E12');
		propAbono.AB_LKP_Caso__c = casoSini.Id;
		propAbono.AB_LKP_Cuenta__c = cuentaAsegurado.Id;
		propAbono.AB_LKP_Imputar_a__c = usuario.Id;
		propAbono.AB_DIV_Importe_a_Imputar__c = 1;
		propAbono.AB_LKP_Imputar_a2__c = usuario.Id;
		propAbono.AB_DIV_Importe_a_Imputar2__c = 1;
		propAbono.AB_LKP_Imputar_a3__c = usuario.Id;
		propAbono.AB_DIV_Importe_a_Imputar3__c = 1;
		propAbono.AB_LKP_Imputar_a4__c = recursoServ.Id;
		propAbono.AB_DIV_Importe_a_Imputar4__c = 1;
		propAbono.AB_LKP_Imputar_a5__c = recursoServ.Id;
		propAbono.AB_DIV_Importe_a_Imputar5__c = 1;
		propAbono.AB_LKP_Imputar_a6__c = recursoServ.Id;
		propAbono.AB_DIV_Importe_a_Imputar6__c = 1;
		propAbono.AB_DIV_Importe_a_ingresar__c = 1;
		propAbono.AB_LKP_Ingresar_a__c = casoSini.AccountId;
		insert propAbono;

		propAbono.AB_SEL_Estado__c = '02';
		propAbono.AB_LKP_Caso__c = casoSini.Id;
		propAbono.AB_LKP_Cuenta__c = cuentaAsegurado.Id;
		propAbono.AB_CAS_Abono_Liquidado__c = true;
		propAbono.AB_LKP_Imputar_a2__c = usuario2.Id;
		propAbono.AB_LKP_Imputar_a3__c = usuario2.Id;
		propAbono.AB_LKP_Imputar_a5__c = recursoServ2.Id;
		propAbono.AB_LKP_Imputar_a6__c = recursoServ2.Id;
		update propAbono;

		Test.stopTest();
	}
	@isTest static void insertarAbono2(){

		inicializarVariables();

		Propuesta_de_Abono__c propAbono2 = new Propuesta_de_Abono__c(AB_SEL_Estado__c = '01', AB_SEL_Descripcion_evento__c = 'E12');
		propAbono2.AB_LKP_Caso__c = casoSini.Id;
		propAbono2.AB_CAS_Abono_Liquidado__c = false;
		propAbono2.AB_SEL_Estado__c = Label.EV_AB_ESTADO_APROBADO;
		propAbono2.AB_LKP_Imputar_a2__c = usuario.Id;
		propAbono2.AB_DIV_Importe_a_Imputar2__c = 1;
		propAbono2.AB_LKP_Imputar_a4__c = recursoServ.Id;
		propAbono2.AB_DIV_Importe_a_Imputar4__c = 1;
		propAbono2.AB_DIV_Importe_a_ingresar__c = 1;
		propAbono2.AB_LKP_Ingresar_a__c = casoSini.AccountId;

		insert propAbono2;
		
		propAbono2.AB_CAS_Abono_Automatico__c = false;
		propAbono2.AB_CAS_Abono_Liquidado__c = true;
		propAbono2.AB_SEL_Estado__c = Label.EV_AB_ESTADO_NUEVO;
		update propAbono2;
		
		Test.stopTest();
	}
	//El método de facturarAbono sólo se utiliza en la clase TRG_Handler_Propuesta_de_Abono, y no es invocada desde ninguna clase
	@isTest static void facturarAbono(){
		
		Case casoEvento = new Case();
		WorkOrder ordenTrabajoEvento = new WorkOrder();
		Account cuentaAbono = new Account();
		
		inicializarVariables();
		
		Propuesta_de_Abono__c propAbono = new Propuesta_de_Abono__c(AB_SEL_Estado__c = '02', AB_SEL_Descripcion_evento__c = 'E12');
		
		propAbono.AB_LKP_Orden_de_Trabajo__c = ordenTrabajoEvento.Id;
		propAbono.AB_LKP_Caso__c = casoEvento.Id;
		propAbono.AB_LKP_Cuenta__c = cuentaAbono.Id;
		propAbono.AB_CAS_Abono_Liquidado__c = true;
		propAbono.AB_LKP_Imputar_a__c = usuario.Id;
		propAbono.AB_DIV_Importe_a_Imputar__c = 50;
		propAbono.AB_LKP_Imputar_a2__c = usuario.Id;
		propAbono.AB_DIV_Importe_a_Imputar2__c = 50;
		propAbono.AB_LKP_Imputar_a3__c = usuario.Id;
		propAbono.AB_DIV_Importe_a_Imputar3__c = 50;
		propAbono.AB_LKP_Imputar_a4__c = recursoServ.Id;
		propAbono.AB_DIV_Importe_a_Imputar4__c = 50;
		propAbono.AB_LKP_Imputar_a5__c = recursoServ.Id;
		propAbono.AB_DIV_Importe_a_Imputar5__c = 50;
		propAbono.AB_LKP_Imputar_a6__c = recursoServ.Id;
		propAbono.AB_DIV_Importe_a_Imputar6__c = 50;
		propAbono.AB_DIV_Importe_a_ingresar__c = 300;		
		Baipas.establecerVariableControl();
		insert propAbono;
		Baipas.deshabilitarVariableControl();
		
		List<Propuesta_de_Abono__c> ListaAbonos = new List<Propuesta_de_Abono__c>();
		ListaAbonos.add(propAbono);
		
		List<String> listaRespuesta = new List<String>(TRG_Handler_Propuesta_de_Abono.facturarAbono(ListaAbonos));
		Test.stopTest();
	}
	
}