src/objects/Producto_CIA__c.object
<CustomObject>
    <description>Representa las diferentes tipologías de póliza y/o de contratos que ofrece cada compañía aseguradora. Cada producto determina un conjunto de garantías.</description>
    <label>Compañía: Producto</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Productos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceContract.object
<CustomObject>
    <fields>
        <fullName>POL_LKP_Compania__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Compañía asociada a la póliza</description>
        <label>Compañía</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>POL_REL_Compania</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POL_LKP_Producto_Cia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Producto asociado a la póliza</description>
        <label>Producto</label>
        <referenceTo>Producto_CIA__c</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>POL_REL_Producto</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POL_LKP_Version_Actual__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Versión Actual</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Version_ContratoServicio__c.POLV_LKP_PolizaContrato__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Version_ContratoServicio__c</referenceTo>
        <relationshipLabel>Contratos de servicio</relationshipLabel>
        <relationshipName>Contratos_de_servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Tipo_Producto_CIA__c.object
<CustomObject>
    <label>Compañía: Tipo de Producto</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañía: Tipos de Producto</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Version_ContratoServicio__c.object
<CustomObject>
    <description>Representa cada una de las versiones de una Póliza o Contrato.</description>
    <fields>
        <fullName>POLV_DAT_FechaFin__c</fullName>
        <description>Fecha de finalización</description>
        <label>Fecha de finalización</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POLV_DAT_FechaInicio__c</fullName>
        <description>Fecha de inicio</description>
        <label>Fecha de inicio</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POLV_LKP_PolizaContrato__c</fullName>
        <label>Póliza/Contrato</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Versiones Póliza/Contrato</relationshipLabel>
        <relationshipName>Versiones_Poliza_Contrato</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>POLV_SEL_Idioma__c</fullName>
        <description>Idioma</description>
        <label>Idioma</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Idiomas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>POLV_SEL_Pais__c</fullName>
        <description>País</description>
        <label>País</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GLB_SEL_Paises</valueSetName>
        </valueSet>
    </fields>
    <label>Versión Póliza/Contrato</label>
    <nameField>
        <label>Versión Póliza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versiones Póliza/Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/GLB_SEL_Idiomas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <default>true</default>
        <label>Castellano</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Catalán</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Desconocido</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Euskera</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Gallego</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Francés</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Alemán</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Italiano</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Resto</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Portugués</label>
    </customValue>
    <masterLabel>Idiomas</masterLabel>
</GlobalValueSet>

src/globalValueSets/GLB_SEL_Paises.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ES</fullName>
        <default>true</default>
        <label>España</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
        <label>Bélgica</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croacia</label>
    </customValue>
    <customValue>
        <fullName>CY</fullName>
        <label>Chipre</label>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
        <label>República Checa</label>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
        <label>Dinamarca</label>
    </customValue>
    <customValue>
        <fullName>EE</fullName>
        <label>Estonia</label>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
        <label>Finlandia</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>Francia</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Alemania</label>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
        <label>Grecia</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungría</label>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
        <label>Irlanda</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italia</label>
    </customValue>
    <customValue>
        <fullName>LV</fullName>
        <label>Letonia</label>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
        <label>Lituania</label>
    </customValue>
    <customValue>
        <fullName>LU</fullName>
        <label>Luxemburgo</label>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
        <label>Malta</label>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
        <label>Países Bajos</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Polonia</label>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
        <label>Portugal</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Rumanía</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Eslovaquia</label>
    </customValue>
    <customValue>
        <fullName>SI</fullName>
        <label>Eslovenia</label>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
        <label>Suecia</label>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
        <label>Reino Unido</label>
    </customValue>
    <description>Listados de países de Europa</description>
    <masterLabel>Países</masterLabel>
</GlobalValueSet>

src/classes/TEST_Handler_Comentario_CasoComunidad.cls
@isTest
public class TEST_Handler_Comentario_CasoComunidad {
    
    	public static ServiceContract crearPolizaContrato2(String nombre, Id compania, Id asegurado, Id productoCIA){
		ServiceContract poliza=new ServiceContract();
        poliza.Name=nombre;
        poliza.POL_LKP_Compania__c = compania;
        poliza.AccountId = asegurado;
        poliza.POL_LKP_Producto_Cia__c = productoCIA;
        insert poliza;

        Version_ContratoServicio__c nuevaVersion = new Version_ContratoServicio__c();
        nuevaVersion.POLV_LKP_PolizaContrato__c = poliza.Id;
        nuevaVersion.POLV_SEL_Pais__c = 'ES';
        nuevaVersion.POLV_SEL_Idioma__c = '2';
        nuevaVersion.POLV_DAT_FechaFin__c = Date.newInstance(2018, 5, 6);
        nuevaVersion.POLV_DAT_FechaInicio__c = Date.newInstance(2018, 5, 6).addDays(2);
        Insert nuevaVersion;


        poliza.POL_LKP_Version_Actual__c= nuevaVersion.id; 
        update poliza;

        return poliza;
	} 
    
    @isTest static void ComentarioCasoComunidad(){
 		
		
		Id ProfileID = [ Select id from Profile where Name =: Label.PERFIL_ADMINISTRADOR].id;
	
     
        User newUser = new User();
		newUser.FirstName = 'Manolo';
		newUser.LastName = 'tena';
		newUser.Email = 'manolo@manolo.com';
		newUser.Alias = 'Manolo';
		newUser.ProfileId = ProfileID;
		newUser.Username = ' john784poi@acme7.com';
		newUser.CommunityNickname = 'pepe';
		newUser.TimeZoneSidKey = 'Europe/Paris';
		newUser.LocaleSidKey = system.UserInfo.getLocale();
		newUser.EmailEncodingKey = 'ISO-8859-1';
		newUser.LanguageLocaleKey = 'es';
        newUser.ContactId = '0039E00000V1Xn7QAF';
        

		insert newUser;
        
      
        

        System.RunAs(newUser){
        Test.startTest();

      
       	Account cuentaPrincipal = new Account();
        cuentaPrincipal = Util_Tests.crearCuentaB2BPpal('B2BPrincipal', '1021', 'X1234567X');
        insert cuentaPrincipal;
  

		Account compania = Util_Tests.crearCuentaCompania('Pepito','1020','X1224567X');
        compania.type = '01';
		insert compania;
            
        Account asegurado = Util_Tests.crearCuentaAsegurado('Miguel','2018', 'miguel@gmail.es', '73661110E','Miguel', 'Sagrado', 'Velasco');
		asegurado.CUE_LKP_Cuenta_principal__c = compania.id;
        asegurado.type  = '01';
		insert asegurado; 
            
        Contact contactoPrincipal = new Contact();
		contactoPrincipal = new Contact(AccountId = asegurado.id, lastname = 'lastname');
		insert contactoPrincipal;
		Tipo_Producto_CIA__c tipoProductoCIA = Util_Tests.crearTipoProductoCIA('SegurCaixa - HOGAR','01',compania.ID);
		insert tipoProductoCIA;
		Producto_CIA__c productoCIA = Util_Tests.crearProductoCIA('KIT 107','12345678',tipoProductoCIA.Id);
		insert productoCIA;
            

        ServiceContract poliza = crearPolizaContrato2('alberto', compania.id,asegurado.Id,productoCIA.Id);


        
		Case casoTest1= new Case();
        casoTest1 = Util_Tests.crearCasoB2B(poliza.Id, asegurado.Id, compania.Id);
        casoTest1.CAS_LKP_Compania__c = compania.Id;
        casoTest1.ContactId  =contactoPrincipal.Id;
		//casoTest1.Status = '999';
		insert casoTest1;

            
        CaseComment comentarioCaso =  new CaseComment();
		comentarioCaso.CommentBody = 'Comentario del caso' ;   
		comentarioCaso.ParentId = casoTest1.Id;
        insert comentarioCaso;
           
        Test.stopTest();
                
        }
            
            
            
            
            
            

	}
}