src/objects/ServiceResource.object
<CustomObject>
    <fields>
        <fullName>RSE_LKP_Cuenta__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Cuenta del Profesional Contrato</description>
        <label>Cuenta de Profesional</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Profesional Contrato</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recursos de servicios</relationshipLabel>
        <relationshipName>Recursos_de_servicios</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_LKP_Recurso_Servicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Profesional (Perfil Técnico) vinculado a la Orden de Trabajo. Representa la FK al objeto ServiceResource. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto ServiceResource (ServiceResources.RSE_TXT_Codigo_Recurso__c): Código único del Profesional</description>
        <label>Profesional</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>ServiceResource.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Status</field>
                <operation>equals</operation>
                <value>Anulado, Anulado desde Inactivo, Cerrado, Cerrado Albarán Recibido, Cerrado Pdte. Albarán, Revisado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Órdenes de trabajo</relationshipLabel>
        <relationshipName>OTR_REL_Recurso_Servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PDF_RechazoAlbaran.cls
public without sharing class PDF_RechazoAlbaran {
    
    
    public List<RechazoAlbaran.Resultado> resultados {get;set;}
    public WorkOrder wo {get;set;}
    public String prof {get; set;}
    public String nombreCuenta {get; set;}
    public String dirEnvio {get; set;}
    /**
    * 
 	* Constructor de la clase
 	* 
 	*/  
	public PDF_RechazoAlbaran(){
		
		resultados = new List<RechazoAlbaran.Resultado>();
		
		PageReference paginaActual = ApexPages.currentPage();
		
		Id woId = paginaActual.getParameters().get('id');
		
		if(woId != null){
			List<Workorder> lAux = Util_Orden_Trabajo.queryMapOTById(new Set<Id>{woId}).values();
			/*List<Workorder> lAux = [Select Id, 	OTR_LKP_Recurso_Servicio__r.Name, WorkOrderNumber,
			OTR_LKP_Recurso_Servicio__r.RSE_LKP_Cuenta__r.name,OTR_LKP_Recurso_Servicio__r.RSE_LKP_Cuenta__r.ShippingAddress from WorkOrder where id = :woId];*/
			if(!lAux.isEmpty()){
				wo = lAux.get(0);
				prof = wo.OTR_LKP_Recurso_Servicio__r.Name;
				nombreCuenta = wo.OTR_LKP_Recurso_Servicio__r.RSE_LKP_Cuenta__r.name;
				System.Address direccion = wo.OTR_LKP_Recurso_Servicio__r.RSE_LKP_Cuenta__r.ShippingAddress;
				//dirEnvio = String.valueOf(wo.OTR_LKP_Recurso_Servicio__r.RSE_LKP_Cuenta__r.ShippingAddress);
				if(direccion != null){
					dirEnvio = direccion.Street+'<BR/>'+direccion.getPostalCode()+ ' ' + direccion.getCity() + ' ' + direccion.getState() ;
				}
			}
		}
		
		String resultadosSerializados = paginaActual.getParameters().get('resultados');
		
		if(resultadosSerializados != null){
			resultados = (List<RechazoAlbaran.Resultado>)JSON.deserialize(resultadosSerializados, List<RechazoAlbaran.Resultado>.class);
		}
	}
}