src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_CAS_Servicio_Revisado__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Orden de trabajo revisada.</description>
        <label>Servicio Revisado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OTR_DAT_Fecha_revision__c</fullName>
        <description>fecha que recoge el día y la hora de cuando se ha revisado la orden de trabajo</description>
        <label>Fecha revisión</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OTR_HOR_Hora_de_revision__c</fullName>
        <label>Hora de revisión</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>OTR_LKP_Gestor_revision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gestor revisión</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Ordenes_de_trabajo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OTR_SEL_Subestado__c</fullName>
        <label>Subestado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>Revisado manualmente</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Revisado sin albarán</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Revisado como PER</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>Revisado pendiente de recibir albarán que se ha devuelto al profesional</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>Pendiente de revisión en espera de Homeserve por resolución</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>Revisado E16</label>
                </value>
                <value>
                    <fullName>07</fullName>
                    <label>En Revisión</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>Revisado Automáticamente sin intervención gestor</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <label>Revisado Automáticamente con intervención gestor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OTR_TXT_Estado_Anterior__c</fullName>
        <description>Almacena el estado anterior de la Orden de Trabajo tras un cambio de estado.</description>
        <label>Estado Anterior</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Cambiar_Estado_WorkOrder_al_pulsar_boton.cls
public without sharing class Cambiar_Estado_WorkOrder_al_pulsar_boton {

	private ApexPages.StandardSetController standardController;
	
	public transient List<Workorder> selectedWO{get;set;}
	
	public boolean puedeRevisar {get; set;}
	private boolean paginaActual = false;
	private String currentURL = '';
	private Integer numPageUpdate = 0;
	public boolean isOver {get;set;}

	public Cambiar_Estado_WorkOrder_al_pulsar_boton(ApexPages.StandardSetController standardController)
	{
		this.standardController = standardController;
		
		if(Apexpages.currentPage().getUrl().contains('cambiar_estado_workorder_al_pulsar_boton')){
			paginaActual = true;
		} else {
			currentURL = Apexpages.currentPage().getUrl();
		}
		
		system.debug(Apexpages.currentPage().getUrl());
		/*puedeRevisar = (Util_Perfiles_Usuario.PROFILEBYID.get(UserInfo.getProfileId()).Name == Label.PERFIL_SUPERVISOR_AUDITORIA_GESTION);
		if(!puedeRevisar){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No tiene permiso para realizar esta operación'));
		}*/
	}

	public PageReference revisionAutoWorkOrders()
	{
		system.debug(paginaActual);
		system.debug(currentURL);
		system.debug(Apexpages.currentPage().getUrl());
		if(paginaActual){
			List<String> fields = new List<String> {'Status','OTR_SEL_Subestado__c'};
			if(!Test.isRunningTest()){
				standardController.addFields(fields);
			}
		}
		
				
		puedeRevisar = (Util_Perfiles_Usuario.PROFILEBYID.get(UserInfo.getProfileId()).Name == Label.PERFIL_SUPERVISOR_AUDITORIA_GESTION);
		puedeRevisar = true;
		if(!puedeRevisar){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No tiene permiso para realizar esta operación'));
		}
		
		numPageUpdate = 0;
		isOver = false;
		// Get the selected records
		List<Workorder> temp = (List<WorkOrder>) standardController.getSelected();
		
		selectedWO = new List<Workorder>();
		if(temp.size() > 200){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Se están revisando un número elevado de elementos. Se muestran los 200 primeros'));
		}
		
		for(Workorder wo: temp){
			if(selectedWO.size()>199)
				break;
			selectedWO.add(wo);
		}
		

		return null;
	}
	public void updateWorkOrders()
	{
		// Call StandardSetController 'save' method to update (optional, you can use your own DML)
		/*PageReference pag = standardController.save();
		system.debug(pag);
		system.debug(pag==null);*/
		
		try{
			
			List<WorkOrder> selectedWorkOrders = (List<WorkOrder>) standardController.getSelected();
				
			system.debug('--------enUpdate: ' + numPageUpdate + ',' + selectedWorkOrders.size());
				
			List<Workorder> selWoUpd = new List<Workorder>();


			// Update records
			//for(WorkOrder selectedWorkOrder : selectedWorkOrders)
			for(Integer i = 1000*numPageUpdate; (i<1000*(numPageUpdate+1) && i<selectedWorkOrders.size());i++)
			{	
				Workorder selectedWorkOrder = selectedWorkOrders[i];
				if(selectedWorkOrder.Status == Label.OTR_ESTADO_CERRADO_ALBARAN_RECIBIDO) {
					selectedWorkOrder.Status = Label.OTR_ESTADO_REVISADO;
					selectedWorkOrder.OTR_SEL_Subestado__c = Label.OTR_SUBESTADO_REVISADO_AUT_CON_INTER_GESTOR;
					selectedWorkOrder.OTR_CAS_Servicio_Revisado__c = true;
					selectedWorkOrder.OTR_DAT_Fecha_revision__c = Datetime.Now().date();
					selectedWorkOrder.OTR_HOR_Hora_de_revision__c = Datetime.Now().time();
					selectedWorkOrder.OTR_TXT_Estado_Anterior__c = selectedWorkOrder.Status;
					selectedWorkOrder.OTR_LKP_Gestor_revision__c = UserInfo.getUserId();
					
					selWoUpd.add(selectedWorkOrder);
				}else{
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, label.OTR_ERROR_Orden_Revisada_Autom));	
				}
			}
			
			if(1000*(numPageUpdate+1) > selectedWorkOrders.size()){
				isOver = true;
			}
			
			numPageUpdate++;
			
			system.debug('----------------'+numPageUpdate);
			system.debug('----------------'+isOver);
			
			Baipas.establecerVariableControl();
			update selWoUpd;
			Baipas.deshabilitarVariableControl();
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Servicios revisados correctamente'));
		} catch(Exception e){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
				system.debug('****** EXCEPTION : ' + e);
			isOver = true;
		}
		
		/*if(paginaActual)
			return pag;
		else
			return volver();*/
		//return volver();
	}

	public PageReference volver(){
		//PageReference paginaRedireccion = new PageReference('/0WO');
		//return paginaRedireccion;
		if(paginaActual){
			return standardController.cancel();
		} else {
			PageReference page = new PageReference(currentUrl);
			page.setRedirect(false);
			return page;
		}
	}
}