src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>OTR_DIV_Importe_diferencia__c</fullName>
        <label>Importe diferencia</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OTR_DIV_Importe_nuevo__c</fullName>
        <description>Campo para auditoria de gestión, guarda el importe del servicio a prof antes de impuestos después de la revisión</description>
        <label>Importe nuevo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OTR_DIV_Importe_original__c</fullName>
        <description>Campo para auditoria de gestión, guarda el importe del servicio a prof antes de impuestos antes de la revisión</description>
        <label>Importe original</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OTR_FOR_Codigo_Profesional__c</fullName>
        <formula>OTR_LKP_Recurso_Servicio__r.RSE_TXT_Codigo_Recurso__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código Profesional</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OTR_FOR_DT__c</fullName>
        <formula>(CASE(Case.CAS_SEL_Direccion_Territorial__c, 
&quot;a1&quot;, &quot;A1&quot;, 
&quot;a2&quot;, &quot;A2&quot;, 
&quot;a3&quot;, &quot;A3&quot;, 
&quot;a4&quot;, &quot;A4&quot;, 
&quot;a5&quot;, &quot;A5&quot;, 
&quot;a6&quot;, &quot;A6&quot;, 
&quot;a7&quot;, &quot;A7&quot;, 
&quot;&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dirección Territorial</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OTR_LKP_Recurso_Servicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Profesional (Perfil Técnico) vinculado a la Orden de Trabajo. Representa la FK al objeto ServiceResource. Para resolver esta FK en integración (servicios web) y migración (plantillas DataLoader) se debe informar el valor del campo External ID del objeto ServiceResource (ServiceResources.RSE_TXT_Codigo_Recurso__c): Código único del Profesional</description>
        <label>Profesional</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>ServiceResource.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Status</field>
                <operation>equals</operation>
                <value>Anulado, Anulado desde Inactivo, Cerrado, Cerrado Albarán Recibido, Cerrado Pdte. Albarán, Revisado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ServiceResource</referenceTo>
        <relationshipLabel>Órdenes de trabajo</relationshipLabel>
        <relationshipName>OTR_REL_Recurso_Servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OTR_RES_Liquidar_prof_AI__c</fullName>
        <label>Importe Total Liquidar a Prof antes Imp</label>
        <summarizedField>WorkOrderLineItem.PAR_DIV_Liquidar_Prof_AI__c</summarizedField>
        <summaryFilterItems>
            <field>WorkOrderLineItem.Status</field>
            <operation>notEqual</operation>
            <value>Rechazada, Rechazada por Cliente, Rechazada por Perito, Rechazada por Gestor, Rechazada por CIA</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>WorkOrderLineItem.PAR_CAS_Orden_Trabajo_Anulada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>OTR_SEL_Motivo_de_rectificacion__c</fullName>
        <label>Motivo de rectificación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exceso horas M.O.</fullName>
                </value>
                <value>
                    <fullName>Exceso Importe Material</fullName>
                </value>
                <value>
                    <fullName>Trabajos No realizados</fullName>
                </value>
                <value>
                    <fullName>No aceptado por perito/compañía</fullName>
                </value>
                <value>
                    <fullName>Exceso metros realizados</fullName>
                </value>
                <value>
                    <fullName>Mala interpretación del baremo</fullName>
                </value>
                <value>
                    <fullName>Exceso M.O. y Material</fullName>
                </value>
                <value>
                    <fullName>Trabajos no acreditados</fullName>
                </value>
                <value>
                    <fullName>No procede incremento</fullName>
                </value>
                <value>
                    <fullName>Avería no cubierta</fullName>
                </value>
                <value>
                    <fullName>No procede abrir 2 siniestros/servicios</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OTR_SEL_Penalizacion__c</fullName>
        <label>Penalización</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No procede</fullName>
                </value>
                <value>
                    <fullName>10,00€</fullName>
                </value>
                <value>
                    <fullName>40,00€</fullName>
                </value>
                <value>
                    <fullName>90,00€</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OTR_TXT_Comentario_Auditoria__c</fullName>
        <label>Comentario Auditoria</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OTR_TXT_rectificacion__c</fullName>
        <label>Texto ampliado de la rectificación</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Rectificacion_Albaranes.cls
/**
 * Clase controladora de la Visualforce "Rectificacion_Albaranes" encargada de gestionar los gremios de un Servicio B2B/B2B2C.
 * 
 * @author EVERIS
 */
public without sharing class Rectificacion_Albaranes {

	public WorkOrder ot {get; set;}
	public List<SelectOption> listaMotivos {get; set;}
	public List<SelectOption> listaPenalizaciones {get; set;}
	public String motivo {get; set;}
	public String penalizacion {get; set;}
	public String comentario {get; set;}
	public String comentarioAuditoria {get; set;}
	
	public Rectificacion_Albaranes(ApexPages.standardController stdCtr){
		PageReference paginaActual = ApexPages.currentPage();
		if(!paginaActual.getParameters().containsKey('id')){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, label.SINI_ERROR_USUARIO));
		}
		else {
			List<WorkOrder> listaOts = new List<WorkOrder>(Util_Orden_Trabajo.queryMapOTById(new Set<Id>{stdCtr.getRecord().Id}).values());
			//List<WorkOrder> listaOts = new List<WorkOrder>(Util_Orden_Trabajo.queryOT(stdCtr.getRecord().Id,null,null));
			/*List<WorkOrder> listaOts = new List<WorkOrder>([SELECT Id,
			                                                	OTR_LKP_Recurso_Servicio__c,
			                                                	ParentWorkOrderId,
			                                                	CaseId,
			                                                	ParentWorkOrder.WorkOrderNumber, 
																ParentWorkOrder.OTR_FOR_DT__c,
																OTR_FOR_Codigo_Profesional__c,
																OTR_LKP_Recurso_Servicio__r.Name,
																ParentWorkOrder.OTR_RES_Liquidar_prof_AI__c,
																OTR_RES_Liquidar_prof_AI__c,
																OTR_SEL_Motivo_de_rectificacion__c,
																OTR_SEL_Penalizacion__c,
																OTR_TXT_rectificacion__c
																FROM WorkOrder
																WHERE id = :stdCtr.getRecord().Id]);*/
			if(!listaOts.isEmpty()){
				ot = listaOts.get(0);
                system.debug(ot + ' ot');
				listaMotivos = getPicklistData ('OTR_SEL_Motivo_de_rectificacion__c');
				listaPenalizaciones = getPicklistData('OTR_SEL_Penalizacion__c');
				motivo = ot.OTR_SEL_Motivo_de_rectificacion__c;
				penalizacion = ot.OTR_SEL_Penalizacion__c;
				comentario = ot.OTR_TXT_rectificacion__c;
				comentarioAuditoria = ot.OTR_TXT_Comentario_Auditoria__c;
				
				ot.OTR_DIV_Importe_nuevo__c = ot.OTR_RES_Liquidar_prof_AI__c;
				ot.OTR_DIV_Importe_original__c = ot.ParentWorkorder.OTR_RES_Liquidar_prof_AI__c;
				
				ot.OTR_DIV_Importe_diferencia__c =  ot.ParentWorkorder.OTR_RES_Liquidar_prof_AI__c -ot.OTR_RES_Liquidar_prof_AI__c; 
				
				if(ot.OTR_DIV_Importe_diferencia__c < 10){
					penalizacion = 'No procede';
				} else if(ot.OTR_DIV_Importe_diferencia__c < 30){
					penalizacion = '10,00€';
				} else if(ot.OTR_DIV_Importe_diferencia__c < 90){
					penalizacion = '40,00€';
				} else{
					penalizacion = '90,00€';
				}
				
			}
		}
	}
	
	/** 
	 * Metodo Para recuperar los valores de una pickList de WO
	 * @param nombreCampo:nombre API del campo
	 * @return devuelve una lista de tipo SelectOption que contiene los valores de la pickList
	 */
	public List<SelectOption> getPicklistData(String nombreCampo){
	  List<SelectOption> options = new List<SelectOption>();
	  options.add(new SelectOption('', '--Ninguno--'));
	  DescribeSObjectResult obj = Schema.getGlobalDescribe().get('WorkOrder').getDescribe();
	  DescribeFieldResult campo = obj.fields.getMap().get(nombreCampo).getDescribe();    
	  for(Schema.PicklistEntry valor : campo.getPicklistValues()){
		  options.add(new SelectOption(valor.getLabel(), valor.getValue()));
	  }
	  return options;
	}
	
	/** 
	 * Metodo para redirigir a la OT principal y actualizar los campos relacionados con la rectificación
	 * @return devuelve un PageReference para volver al padre
	 */
	public PageReference aceptar(){
		List<WorkOrder> actualizar = new List<WorkOrder>();
		PageReference redireccion = null;
		if(motivo == null || penalizacion == null || comentario == ''){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.ERROR_FALTAN_CAMPOS_OBLIGATORIOS));
		}
		else {
			ot.OTR_SEL_Motivo_de_rectificacion__c = motivo;
			ot.OTR_SEL_Penalizacion__c = penalizacion;
			ot.OTR_TXT_rectificacion__c = comentario;
			ot.OTR_TXT_Comentario_Auditoria__c = comentarioAuditoria;
			actualizar.add(ot);
			if(!actualizar.isEmpty()) {
			//	Baipas.establecerVariableControl();
				update actualizar;
				//Baipas.deshabilitarVariableControl();
			}
			
			redireccion = new PageReference('/' +ot.Id);
			redireccion.setRedirect(true);
		}
		return redireccion;
	}
	
	/** 
	 * Metodo para volver a CPQ
	 * @return devuelve un PageReference para volver a CPQ
	 */
	public PageReference volver(){
		PageReference redireccion = new PageReference('/apex/'+Label.VF_QUOTE_COPY);
		redireccion.getParameters().put('idWorkO',ot.Id);
		redireccion.getParameters().put('id',ot.CaseId);
		redireccion.getParameters().put('retorno','/'+ot.Id);
		redireccion.getParameters().put('inline','1');
		redireccion.setRedirect(true);
		return redireccion;
	}
}